class RH_FLAGS(object):
    """ Flag values for the DT_MIPS_FLAGS dynamic table entries
    """
    RHF_NONE = 0
    RHF_QUICKSTART = 1
    RHF_NOTPOT = 2
    RHF_NO_LIBRARY_REPLACEMENT = 4
    RHF_NO_MOVE = 8
    RHF_SGI_ONLY = 16
    RHF_GUARANTEE_INIT = 32
    RHF_DELTA_C_PLUS_PLUS = 64
    RHF_GUARANTEE_START_INIT = 128
    RHF_PIXIE = 256
    RHF_DEFAULT_DELAY_LOAD = 512
    RHF_REQUICKSTART = 1024
    RHF_REQUICKSTARTED = 2048
    RHF_CORD = 4096
    RHF_NO_UNRES_UNDEF = 8192
    RHF_RLD_ORDER_SAFE = 16384