from ipywidgets import (
from ipywidgets.widgets.trait_types import TypedTuple
from traitlets import (
from .._base.Three import ThreeWidget
from .._base.uniforms import uniforms_serialization
from ..enums import *
from ..traits import *
from .._base.Three import ThreeWidget
import inspect
@register
class BaseBufferGeometry(ThreeWidget):
    """BaseBufferGeometry

    Autogenerated by generate-wrappers.js
    This class is a custom class for pythreejs, with no
    direct corresponding class in three.js.
    """

    def __init__(self, **kwargs):
        super(BaseBufferGeometry, self).__init__(**kwargs)
    _model_name = Unicode('BaseBufferGeometryModel').tag(sync=True)
    name = Unicode('', allow_none=False).tag(sync=True)
    type = Unicode('BaseBufferGeometry', allow_none=False).tag(sync=True)