from .basestemmer import BaseStemmer
from .among import Among
class YiddishStemmer(BaseStemmer):
    """
    This class implements the stemming algorithm defined by a snowball script.
    Generated by Snowball 2.2.0 - https://snowballstem.org/
    """
    a_0 = [Among(u'וו', -1, 1), Among(u'וי', -1, 2), Among(u'יי', -1, 3), Among(u'ך', -1, 4), Among(u'ם', -1, 5), Among(u'ן', -1, 6), Among(u'ף', -1, 7), Among(u'ץ', -1, 8)]
    a_1 = [Among(u'אדורכ', -1, 1), Among(u'אהינ', -1, 1), Among(u'אהער', -1, 1), Among(u'אהײמ', -1, 1), Among(u'אומ', -1, 1), Among(u'אונטער', -1, 1), Among(u'איבער', -1, 1), Among(u'אנ', -1, 1), Among(u'אנט', 7, 1), Among(u'אנטקעגנ', 8, 1), Among(u'אנידער', 7, 1), Among(u'אפ', -1, 1), Among(u'אפיר', 11, 1), Among(u'אקעגנ', -1, 1), Among(u'אראפ', -1, 1), Among(u'ארומ', -1, 1), Among(u'ארונטער', -1, 1), Among(u'אריבער', -1, 1), Among(u'ארױס', -1, 1), Among(u'ארױפ', -1, 1), Among(u'ארײנ', -1, 1), Among(u'אװעק', -1, 1), Among(u'אױס', -1, 1), Among(u'אױפ', -1, 1), Among(u'אײנ', -1, 1), Among(u'בא', -1, 1), Among(u'בײ', -1, 1), Among(u'דורכ', -1, 1), Among(u'דער', -1, 1), Among(u'מיט', -1, 1), Among(u'נאכ', -1, 1), Among(u'פאר', -1, 1), Among(u'פארבײ', 31, 1), Among(u'פארױס', 31, 1), Among(u'פונאנדער', -1, 1), Among(u'צו', -1, 1), Among(u'צוזאמענ', 35, 1), Among(u'צונױפ', 35, 1), Among(u'צוריק', 35, 1), Among(u'צע', -1, 1)]
    a_2 = [Among(u'דזש', -1, -1), Among(u'שטר', -1, -1), Among(u'שטש', -1, -1), Among(u'שפר', -1, -1)]
    a_3 = [Among(u'קליב', -1, 9), Among(u'ריב', -1, 10), Among(u'טריב', 1, 7), Among(u'שריב', 1, 15), Among(u'הױב', -1, 23), Among(u'שװיג', -1, 12), Among(u'גאנג', -1, 1), Among(u'זונג', -1, 18), Among(u'שלונג', -1, 21), Among(u'צװונג', -1, 20), Among(u'בױג', -1, 22), Among(u'בונד', -1, 16), Among(u'װיז', -1, 6), Among(u'ביט', -1, 4), Among(u'ליט', -1, 8), Among(u'מיט', -1, 3), Among(u'שניט', -1, 14), Among(u'נומ', -1, 2), Among(u'שטאנ', -1, 25), Among(u'ביס', -1, 5), Among(u'שמיס', -1, 13), Among(u'ריס', -1, 11), Among(u'טרונק', -1, 19), Among(u'פארלױר', -1, 24), Among(u'שװױר', -1, 26), Among(u'װוטש', -1, 17)]
    a_4 = [Among(u'ונג', -1, 1), Among(u'סטו', -1, 1), Among(u'ט', -1, 1), Among(u'בראכט', 2, 31), Among(u'סט', 2, 1), Among(u'יסט', 4, 33), Among(u'עט', 2, 1), Among(u'שאפט', 2, 1), Among(u'הײט', 2, 1), Among(u'קײט', 2, 1), Among(u'יקײט', 9, 1), Among(u'לעכ', -1, 1), Among(u'עלעכ', 11, 1), Among(u'יזמ', -1, 1), Among(u'ימ', -1, 1), Among(u'עמ', -1, 1), Among(u'ענעמ', 15, 3), Among(u'טענעמ', 16, 4), Among(u'נ', -1, 1), Among(u'קליבנ', 18, 14), Among(u'ריבנ', 18, 15), Among(u'טריבנ', 20, 12), Among(u'שריבנ', 20, 7), Among(u'הױבנ', 18, 27), Among(u'שװיגנ', 18, 17), Among(u'זונגנ', 18, 22), Among(u'שלונגנ', 18, 25), Among(u'צװונגנ', 18, 24), Among(u'בױגנ', 18, 26), Among(u'בונדנ', 18, 20), Among(u'װיזנ', 18, 11), Among(u'טנ', 18, 4), Among(u'GEביטנ', 31, 9), Among(u'GEליטנ', 31, 13), Among(u'GEמיטנ', 31, 8), Among(u'שניטנ', 31, 19), Among(u'סטנ', 31, 1), Among(u'יסטנ', 36, 1), Among(u'עטנ', 31, 1), Among(u'GEביסנ', 18, 10), Among(u'שמיסנ', 18, 18), Among(u'GEריסנ', 18, 16), Among(u'ענ', 18, 1), Among(u'גאנגענ', 42, 5), Among(u'עלענ', 42, 1), Among(u'נומענ', 42, 6), Among(u'יזמענ', 42, 1), Among(u'שטאנענ', 42, 29), Among(u'טרונקנ', 18, 23), Among(u'פארלױרנ', 18, 28), Among(u'שװױרנ', 18, 30), Among(u'װוטשנ', 18, 21), Among(u'גײנ', 18, 5), Among(u'ס', -1, 1), Among(u'טס', 53, 4), Among(u'עטס', 54, 1), Among(u'נס', 53, 1), Among(u'טנס', 56, 4), Among(u'ענס', 56, 3), Among(u'עס', 53, 1), Among(u'יעס', 59, 2), Among(u'עלעס', 59, 1), Among(u'ערס', 53, 1), Among(u'ענערס', 62, 1), Among(u'ע', -1, 1), Among(u'טע', 64, 4), Among(u'סטע', 65, 1), Among(u'עטע', 65, 1), Among(u'יע', 64, -1), Among(u'עלע', 64, 1), Among(u'ענע', 64, 3), Among(u'טענע', 70, 4), Among(u'ער', -1, 1), Among(u'טער', 72, 4), Among(u'סטער', 73, 1), Among(u'עטער', 73, 1), Among(u'ענער', 72, 3), Among(u'טענער', 76, 4), Among(u'ות', -1, 32)]
    a_5 = [Among(u'ונג', -1, 1), Among(u'שאפט', -1, 1), Among(u'הײט', -1, 1), Among(u'קײט', -1, 1), Among(u'יקײט', 3, 1), Among(u'ל', -1, 2)]
    a_6 = [Among(u'יג', -1, 1), Among(u'יק', -1, 1), Among(u'דיק', 1, 1), Among(u'נדיק', 2, 1), Among(u'ענדיק', 3, 1), Among(u'בליק', 1, -1), Among(u'גליק', 1, -1), Among(u'ניק', 1, 1), Among(u'יש', -1, 1)]
    g_niked = [255, 155, 6]
    g_vowel = [33, 2, 4, 0, 6]
    g_consonant = [239, 254, 253, 131]
    I_x = 0
    I_p1 = 0

    def __r_prelude(self):
        v_1 = self.cursor
        try:
            while True:
                v_2 = self.cursor
                try:
                    try:
                        while True:
                            v_3 = self.cursor
                            try:
                                self.bra = self.cursor
                                among_var = self.find_among(YiddishStemmer.a_0)
                                if among_var == 0:
                                    raise lab3()
                                self.ket = self.cursor
                                if among_var == 1:
                                    v_4 = self.cursor
                                    try:
                                        if not self.eq_s(u'ּ'):
                                            raise lab4()
                                        raise lab3()
                                    except lab4:
                                        pass
                                    self.cursor = v_4
                                    if not self.slice_from(u'װ'):
                                        return False
                                elif among_var == 2:
                                    v_5 = self.cursor
                                    try:
                                        if not self.eq_s(u'ִ'):
                                            raise lab5()
                                        raise lab3()
                                    except lab5:
                                        pass
                                    self.cursor = v_5
                                    if not self.slice_from(u'ױ'):
                                        return False
                                elif among_var == 3:
                                    v_6 = self.cursor
                                    try:
                                        if not self.eq_s(u'ִ'):
                                            raise lab6()
                                        raise lab3()
                                    except lab6:
                                        pass
                                    self.cursor = v_6
                                    if not self.slice_from(u'ײ'):
                                        return False
                                elif among_var == 4:
                                    if not self.slice_from(u'כ'):
                                        return False
                                elif among_var == 5:
                                    if not self.slice_from(u'מ'):
                                        return False
                                elif among_var == 6:
                                    if not self.slice_from(u'נ'):
                                        return False
                                elif among_var == 7:
                                    if not self.slice_from(u'פ'):
                                        return False
                                elif not self.slice_from(u'צ'):
                                    return False
                                self.cursor = v_3
                                raise lab2()
                            except lab3:
                                pass
                            self.cursor = v_3
                            if self.cursor >= self.limit:
                                raise lab1()
                            self.cursor += 1
                    except lab2:
                        pass
                    continue
                except lab1:
                    pass
                self.cursor = v_2
                break
        except lab0:
            pass
        self.cursor = v_1
        v_7 = self.cursor
        try:
            while True:
                v_8 = self.cursor
                try:
                    try:
                        while True:
                            v_9 = self.cursor
                            try:
                                self.bra = self.cursor
                                if not self.in_grouping(YiddishStemmer.g_niked, 1456, 1474):
                                    raise lab10()
                                self.ket = self.cursor
                                if not self.slice_del():
                                    return False
                                self.cursor = v_9
                                raise lab9()
                            except lab10:
                                pass
                            self.cursor = v_9
                            if self.cursor >= self.limit:
                                raise lab8()
                            self.cursor += 1
                    except lab9:
                        pass
                    continue
                except lab8:
                    pass
                self.cursor = v_8
                break
        except lab7:
            pass
        self.cursor = v_7
        return True

    def __r_mark_regions(self):
        self.I_p1 = self.limit
        v_1 = self.cursor
        try:
            self.bra = self.cursor
            if not self.eq_s(u'גע'):
                self.cursor = v_1
                raise lab0()
            self.ket = self.cursor
            v_2 = self.cursor
            try:
                try:
                    v_3 = self.cursor
                    try:
                        if not self.eq_s(u'לט'):
                            raise lab3()
                        raise lab2()
                    except lab3:
                        pass
                    self.cursor = v_3
                    if not self.eq_s(u'בנ'):
                        raise lab1()
                except lab2:
                    pass
                self.cursor = v_1
                raise lab0()
            except lab1:
                pass
            self.cursor = v_2
            if not self.slice_from(u'GE'):
                return False
        except lab0:
            pass
        v_4 = self.cursor
        try:
            if self.find_among(YiddishStemmer.a_1) == 0:
                self.cursor = v_4
                raise lab4()
            try:
                v_5 = self.cursor
                try:
                    v_6 = self.cursor
                    try:
                        v_7 = self.cursor
                        try:
                            if not self.eq_s(u'צוגנ'):
                                raise lab8()
                            raise lab7()
                        except lab8:
                            pass
                        self.cursor = v_7
                        try:
                            if not self.eq_s(u'צוקט'):
                                raise lab9()
                            raise lab7()
                        except lab9:
                            pass
                        self.cursor = v_7
                        if not self.eq_s(u'צוקנ'):
                            raise lab6()
                    except lab7:
                        pass
                    if self.cursor < self.limit:
                        raise lab6()
                    self.cursor = v_6
                    raise lab5()
                except lab6:
                    pass
                self.cursor = v_5
                try:
                    v_8 = self.cursor
                    if not self.eq_s(u'געבנ'):
                        raise lab10()
                    self.cursor = v_8
                    raise lab5()
                except lab10:
                    pass
                self.cursor = v_5
                try:
                    self.bra = self.cursor
                    if not self.eq_s(u'גע'):
                        raise lab11()
                    self.ket = self.cursor
                    if not self.slice_from(u'GE'):
                        return False
                    raise lab5()
                except lab11:
                    pass
                self.cursor = v_5
                self.bra = self.cursor
                if not self.eq_s(u'צו'):
                    self.cursor = v_4
                    raise lab4()
                self.ket = self.cursor
                if not self.slice_from(u'TSU'):
                    return False
            except lab5:
                pass
        except lab4:
            pass
        v_9 = self.cursor
        c = self.cursor + 3
        if c > self.limit:
            return False
        self.cursor = c
        self.I_x = self.cursor
        self.cursor = v_9
        v_10 = self.cursor
        try:
            if self.find_among(YiddishStemmer.a_2) == 0:
                self.cursor = v_10
                raise lab12()
        except lab12:
            pass
        v_11 = self.cursor
        try:
            if not self.in_grouping(YiddishStemmer.g_consonant, 1489, 1520):
                raise lab13()
            if not self.in_grouping(YiddishStemmer.g_consonant, 1489, 1520):
                raise lab13()
            if not self.in_grouping(YiddishStemmer.g_consonant, 1489, 1520):
                raise lab13()
            self.I_p1 = self.cursor
            return False
        except lab13:
            pass
        self.cursor = v_11
        if not self.go_out_grouping(YiddishStemmer.g_vowel, 1488, 1522):
            return False
        while True:
            try:
                if not self.in_grouping(YiddishStemmer.g_vowel, 1488, 1522):
                    raise lab14()
                continue
            except lab14:
                pass
            break
        self.I_p1 = self.cursor
        try:
            if not self.I_p1 < self.I_x:
                raise lab15()
            self.I_p1 = self.I_x
        except lab15:
            pass
        return True

    def __r_R1(self):
        if not self.I_p1 <= self.cursor:
            return False
        return True

    def __r_R1plus3(self):
        if not self.I_p1 <= self.cursor + 3:
            return False
        return True

    def __r_standard_suffix(self):
        v_1 = self.limit - self.cursor
        try:
            self.ket = self.cursor
            among_var = self.find_among_b(YiddishStemmer.a_4)
            if among_var == 0:
                raise lab0()
            self.bra = self.cursor
            if among_var == 1:
                if not self.__r_R1():
                    raise lab0()
                if not self.slice_del():
                    return False
            elif among_var == 2:
                if not self.__r_R1():
                    raise lab0()
                if not self.slice_from(u'יע'):
                    return False
            elif among_var == 3:
                if not self.__r_R1():
                    raise lab0()
                if not self.slice_del():
                    return False
                self.ket = self.cursor
                among_var = self.find_among_b(YiddishStemmer.a_3)
                if among_var == 0:
                    raise lab0()
                self.bra = self.cursor
                if among_var == 1:
                    if not self.slice_from(u'גײ'):
                        return False
                elif among_var == 2:
                    if not self.slice_from(u'נעמ'):
                        return False
                elif among_var == 3:
                    if not self.slice_from(u'מײד'):
                        return False
                elif among_var == 4:
                    if not self.slice_from(u'בײט'):
                        return False
                elif among_var == 5:
                    if not self.slice_from(u'בײס'):
                        return False
                elif among_var == 6:
                    if not self.slice_from(u'װײז'):
                        return False
                elif among_var == 7:
                    if not self.slice_from(u'טרײב'):
                        return False
                elif among_var == 8:
                    if not self.slice_from(u'לײט'):
                        return False
                elif among_var == 9:
                    if not self.slice_from(u'קלײב'):
                        return False
                elif among_var == 10:
                    if not self.slice_from(u'רײב'):
                        return False
                elif among_var == 11:
                    if not self.slice_from(u'רײס'):
                        return False
                elif among_var == 12:
                    if not self.slice_from(u'שװײג'):
                        return False
                elif among_var == 13:
                    if not self.slice_from(u'שמײס'):
                        return False
                elif among_var == 14:
                    if not self.slice_from(u'שנײד'):
                        return False
                elif among_var == 15:
                    if not self.slice_from(u'שרײב'):
                        return False
                elif among_var == 16:
                    if not self.slice_from(u'בינד'):
                        return False
                elif among_var == 17:
                    if not self.slice_from(u'װיטש'):
                        return False
                elif among_var == 18:
                    if not self.slice_from(u'זינג'):
                        return False
                elif among_var == 19:
                    if not self.slice_from(u'טרינק'):
                        return False
                elif among_var == 20:
                    if not self.slice_from(u'צװינג'):
                        return False
                elif among_var == 21:
                    if not self.slice_from(u'שלינג'):
                        return False
                elif among_var == 22:
                    if not self.slice_from(u'בײג'):
                        return False
                elif among_var == 23:
                    if not self.slice_from(u'הײב'):
                        return False
                elif among_var == 24:
                    if not self.slice_from(u'פארליר'):
                        return False
                elif among_var == 25:
                    if not self.slice_from(u'שטײ'):
                        return False
                elif not self.slice_from(u'שװער'):
                    return False
            elif among_var == 4:
                try:
                    v_2 = self.limit - self.cursor
                    try:
                        if not self.__r_R1():
                            raise lab2()
                        if not self.slice_del():
                            return False
                        raise lab1()
                    except lab2:
                        pass
                    self.cursor = self.limit - v_2
                    if not self.slice_from(u'ט'):
                        return False
                except lab1:
                    pass
                self.ket = self.cursor
                if not self.eq_s_b(u'בראכ'):
                    raise lab0()
                v_3 = self.limit - self.cursor
                try:
                    if not self.eq_s_b(u'גע'):
                        self.cursor = self.limit - v_3
                        raise lab3()
                except lab3:
                    pass
                self.bra = self.cursor
                if not self.slice_from(u'ברענג'):
                    return False
            elif among_var == 5:
                if not self.slice_from(u'גײ'):
                    return False
            elif among_var == 6:
                if not self.slice_from(u'נעמ'):
                    return False
            elif among_var == 7:
                if not self.slice_from(u'שרײב'):
                    return False
            elif among_var == 8:
                if not self.slice_from(u'מײד'):
                    return False
            elif among_var == 9:
                if not self.slice_from(u'בײט'):
                    return False
            elif among_var == 10:
                if not self.slice_from(u'בײס'):
                    return False
            elif among_var == 11:
                if not self.slice_from(u'װײז'):
                    return False
            elif among_var == 12:
                if not self.slice_from(u'טרײב'):
                    return False
            elif among_var == 13:
                if not self.slice_from(u'לײט'):
                    return False
            elif among_var == 14:
                if not self.slice_from(u'קלײב'):
                    return False
            elif among_var == 15:
                if not self.slice_from(u'רײב'):
                    return False
            elif among_var == 16:
                if not self.slice_from(u'רײס'):
                    return False
            elif among_var == 17:
                if not self.slice_from(u'שװײג'):
                    return False
            elif among_var == 18:
                if not self.slice_from(u'שמײס'):
                    return False
            elif among_var == 19:
                if not self.slice_from(u'שנײד'):
                    return False
            elif among_var == 20:
                if not self.slice_from(u'בינד'):
                    return False
            elif among_var == 21:
                if not self.slice_from(u'װיטש'):
                    return False
            elif among_var == 22:
                if not self.slice_from(u'זינג'):
                    return False
            elif among_var == 23:
                if not self.slice_from(u'טרינק'):
                    return False
            elif among_var == 24:
                if not self.slice_from(u'צװינג'):
                    return False
            elif among_var == 25:
                if not self.slice_from(u'שלינג'):
                    return False
            elif among_var == 26:
                if not self.slice_from(u'בײג'):
                    return False
            elif among_var == 27:
                if not self.slice_from(u'הײב'):
                    return False
            elif among_var == 28:
                if not self.slice_from(u'פארליר'):
                    return False
            elif among_var == 29:
                if not self.slice_from(u'שטײ'):
                    return False
            elif among_var == 30:
                if not self.slice_from(u'שװער'):
                    return False
            elif among_var == 31:
                if not self.slice_from(u'ברענג'):
                    return False
            elif among_var == 32:
                if not self.__r_R1():
                    raise lab0()
                if not self.slice_from(u'ה'):
                    return False
            elif among_var == 33:
                try:
                    v_4 = self.limit - self.cursor
                    try:
                        try:
                            v_5 = self.limit - self.cursor
                            try:
                                if not self.eq_s_b(u'ג'):
                                    raise lab7()
                                raise lab6()
                            except lab7:
                                pass
                            self.cursor = self.limit - v_5
                            if not self.eq_s_b(u'ש'):
                                raise lab5()
                        except lab6:
                            pass
                        v_6 = self.limit - self.cursor
                        try:
                            if not self.__r_R1plus3():
                                self.cursor = self.limit - v_6
                                raise lab8()
                            if not self.slice_from(u'יס'):
                                return False
                        except lab8:
                            pass
                        raise lab4()
                    except lab5:
                        pass
                    self.cursor = self.limit - v_4
                    if not self.__r_R1():
                        raise lab0()
                    if not self.slice_del():
                        return False
                except lab4:
                    pass
        except lab0:
            pass
        self.cursor = self.limit - v_1
        v_7 = self.limit - self.cursor
        try:
            self.ket = self.cursor
            among_var = self.find_among_b(YiddishStemmer.a_5)
            if among_var == 0:
                raise lab9()
            self.bra = self.cursor
            if among_var == 1:
                if not self.__r_R1():
                    raise lab9()
                if not self.slice_del():
                    return False
            else:
                if not self.__r_R1():
                    raise lab9()
                if not self.in_grouping_b(YiddishStemmer.g_consonant, 1489, 1520):
                    raise lab9()
                if not self.slice_del():
                    return False
        except lab9:
            pass
        self.cursor = self.limit - v_7
        v_8 = self.limit - self.cursor
        try:
            self.ket = self.cursor
            among_var = self.find_among_b(YiddishStemmer.a_6)
            if among_var == 0:
                raise lab10()
            self.bra = self.cursor
            if among_var == 1:
                if not self.__r_R1():
                    raise lab10()
                if not self.slice_del():
                    return False
        except lab10:
            pass
        self.cursor = self.limit - v_8
        v_9 = self.limit - self.cursor
        try:
            while True:
                v_10 = self.limit - self.cursor
                try:
                    try:
                        while True:
                            v_11 = self.limit - self.cursor
                            try:
                                self.ket = self.cursor
                                try:
                                    v_12 = self.limit - self.cursor
                                    try:
                                        if not self.eq_s_b(u'GE'):
                                            raise lab16()
                                        raise lab15()
                                    except lab16:
                                        pass
                                    self.cursor = self.limit - v_12
                                    if not self.eq_s_b(u'TSU'):
                                        raise lab14()
                                except lab15:
                                    pass
                                self.bra = self.cursor
                                if not self.slice_del():
                                    return False
                                self.cursor = self.limit - v_11
                                raise lab13()
                            except lab14:
                                pass
                            self.cursor = self.limit - v_11
                            if self.cursor <= self.limit_backward:
                                raise lab12()
                            self.cursor -= 1
                    except lab13:
                        pass
                    continue
                except lab12:
                    pass
                self.cursor = self.limit - v_10
                break
        except lab11:
            pass
        self.cursor = self.limit - v_9
        return True

    def _stem(self):
        self.__r_prelude()
        v_2 = self.cursor
        self.__r_mark_regions()
        self.cursor = v_2
        self.limit_backward = self.cursor
        self.cursor = self.limit
        self.__r_standard_suffix()
        self.cursor = self.limit_backward
        return True