from dataclasses import dataclass
from typing import List, Literal, Optional, Union
from .base import BaseInferenceType
@dataclass
class ChatCompletionStreamOutputDelta(BaseInferenceType):
    """A chat completion delta generated by streamed model responses."""
    content: Optional[str] = None
    'The contents of the chunk message.'
    role: Optional[str] = None
    'The role of the author of this message.'