from tests.unit import unittest
from tests.unit import AWSMockServiceTestCase
from boto.vpc import VPCConnection
class TestReplaceNetworkAclAssociation(AWSMockServiceTestCase):
    connection_class = VPCConnection
    get_all_network_acls_vpc_body = b'\n        <DescribeNetworkAclsResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-01/">\n           <requestId>59dbff89-35bd-4eac-99ed-be587EXAMPLE</requestId>\n           <networkAclSet>\n           <item>\n             <networkAclId>acl-5566953c</networkAclId>\n             <vpcId>vpc-5266953b</vpcId>\n             <default>true</default>\n             <entrySet>\n               <item>\n                 <ruleNumber>100</ruleNumber>\n                 <protocol>all</protocol>\n                 <ruleAction>allow</ruleAction>\n                 <egress>true</egress>\n                 <cidrBlock>0.0.0.0/0</cidrBlock>\n               </item>\n               <item>\n                 <ruleNumber>32767</ruleNumber>\n                 <protocol>all</protocol>\n                 <ruleAction>deny</ruleAction>\n                 <egress>true</egress>\n                 <cidrBlock>0.0.0.0/0</cidrBlock>\n               </item>\n               <item>\n                 <ruleNumber>100</ruleNumber>\n                 <protocol>all</protocol>\n                 <ruleAction>allow</ruleAction>\n                 <egress>false</egress>\n                 <cidrBlock>0.0.0.0/0</cidrBlock>\n               </item>\n               <item>\n                 <ruleNumber>32767</ruleNumber>\n                 <protocol>all</protocol>\n                 <ruleAction>deny</ruleAction>\n                 <egress>false</egress>\n                 <cidrBlock>0.0.0.0/0</cidrBlock>\n               </item>\n             </entrySet>\n             <associationSet/>\n             <tagSet/>\n           </item>\n\n         </networkAclSet>\n        </DescribeNetworkAclsResponse>\n    '
    get_all_network_acls_subnet_body = b'\n        <DescribeNetworkAclsResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-01/">\n            <requestId>59dbff89-35bd-4eac-99ed-be587EXAMPLE</requestId>\n            <networkAclSet>\n            <item>\n              <networkAclId>acl-5d659634</networkAclId>\n              <vpcId>vpc-5266953b</vpcId>\n              <default>false</default>\n              <entrySet>\n                <item>\n                  <ruleNumber>110</ruleNumber>\n                  <protocol>6</protocol>\n                  <ruleAction>allow</ruleAction>\n                  <egress>true</egress>\n                  <cidrBlock>0.0.0.0/0</cidrBlock>\n                  <portRange>\n                    <from>49152</from>\n                    <to>65535</to>\n                  </portRange>\n                </item>\n              </entrySet>\n              <associationSet>\n                <item>\n                  <networkAclAssociationId>aclassoc-c26596ab</networkAclAssociationId>\n                  <networkAclId>acl-5d659634</networkAclId>\n                  <subnetId>subnet-f0669599</subnetId>\n                </item>\n                <item>\n                  <networkAclAssociationId>aclassoc-5c659635</networkAclAssociationId>\n                  <networkAclId>acl-5d659634</networkAclId>\n                  <subnetId>subnet-ff669596</subnetId>\n                </item>\n              </associationSet>\n              <tagSet/>\n            </item>\n          </networkAclSet>\n        </DescribeNetworkAclsResponse>\n    '

    def default_body(self):
        return b'\n            <ReplaceNetworkAclAssociationResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-01/">\n               <requestId>59dbff89-35bd-4eac-99ed-be587EXAMPLE</requestId>\n               <newAssociationId>aclassoc-17b85d7e</newAssociationId>\n            </ReplaceNetworkAclAssociationResponse>\n        '

    def test_associate_network_acl(self):
        self.https_connection.getresponse.side_effect = [self.create_response(status_code=200, body=self.get_all_network_acls_subnet_body), self.create_response(status_code=200)]
        response = self.service_connection.associate_network_acl('acl-5fb85d36', 'subnet-ff669596')
        self.assert_request_parameters({'Action': 'ReplaceNetworkAclAssociation', 'NetworkAclId': 'acl-5fb85d36', 'AssociationId': 'aclassoc-5c659635'}, ignore_params_values=['AWSAccessKeyId', 'SignatureMethod', 'SignatureVersion', 'Timestamp', 'Version'])
        self.assertEqual(response, 'aclassoc-17b85d7e')

    def test_disassociate_network_acl(self):
        self.https_connection.getresponse.side_effect = [self.create_response(status_code=200, body=self.get_all_network_acls_vpc_body), self.create_response(status_code=200, body=self.get_all_network_acls_subnet_body), self.create_response(status_code=200)]
        response = self.service_connection.disassociate_network_acl('subnet-ff669596', 'vpc-5266953b')
        self.assert_request_parameters({'Action': 'ReplaceNetworkAclAssociation', 'NetworkAclId': 'acl-5566953c', 'AssociationId': 'aclassoc-5c659635'}, ignore_params_values=['AWSAccessKeyId', 'SignatureMethod', 'SignatureVersion', 'Timestamp', 'Version'])
        self.assertEqual(response, 'aclassoc-17b85d7e')