from nipype.interfaces.base import (
import os
class ExpertAutomatedRegistrationInputSpec(CommandLineInputSpec):
    fixedImage = File(position=-2, desc='Image which defines the space into which the moving image is registered', exists=True, argstr='%s')
    movingImage = File(position=-1, desc="The transform goes from the fixed image's space into the moving image's space", exists=True, argstr='%s')
    resampledImage = traits.Either(traits.Bool, File(), hash_files=False, desc='Registration results', argstr='--resampledImage %s')
    loadTransform = File(desc='Load a transform that is immediately applied to the moving image', exists=True, argstr='--loadTransform %s')
    saveTransform = traits.Either(traits.Bool, File(), hash_files=False, desc='Save the transform that results from registration', argstr='--saveTransform %s')
    initialization = traits.Enum('None', 'Landmarks', 'ImageCenters', 'CentersOfMass', 'SecondMoments', desc='Method to prime the registration process', argstr='--initialization %s')
    registration = traits.Enum('None', 'Initial', 'Rigid', 'Affine', 'BSpline', 'PipelineRigid', 'PipelineAffine', 'PipelineBSpline', desc='Method for the registration process', argstr='--registration %s')
    metric = traits.Enum('MattesMI', 'NormCorr', 'MeanSqrd', desc='Method to quantify image match', argstr='--metric %s')
    expectedOffset = traits.Float(desc='Expected misalignment after initialization', argstr='--expectedOffset %f')
    expectedRotation = traits.Float(desc='Expected misalignment after initialization', argstr='--expectedRotation %f')
    expectedScale = traits.Float(desc='Expected misalignment after initialization', argstr='--expectedScale %f')
    expectedSkew = traits.Float(desc='Expected misalignment after initialization', argstr='--expectedSkew %f')
    verbosityLevel = traits.Enum('Silent', 'Standard', 'Verbose', desc='Level of detail of reporting progress', argstr='--verbosityLevel %s')
    sampleFromOverlap = traits.Bool(desc='Limit metric evaluation to the fixed image region overlapped by the moving image', argstr='--sampleFromOverlap ')
    fixedImageMask = File(desc='Image which defines a mask for the fixed image', exists=True, argstr='--fixedImageMask %s')
    randomNumberSeed = traits.Int(desc='Seed to generate a consistent random number sequence', argstr='--randomNumberSeed %d')
    numberOfThreads = traits.Int(desc='Number of CPU threads to use', argstr='--numberOfThreads %d')
    minimizeMemory = traits.Bool(desc='Reduce the amount of memory required at the cost of increased computation time', argstr='--minimizeMemory ')
    interpolation = traits.Enum('NearestNeighbor', 'Linear', 'BSpline', desc='Method for interpolation within the optimization process', argstr='--interpolation %s')
    fixedLandmarks = InputMultiPath(traits.List(traits.Float(), minlen=3, maxlen=3), desc='Ordered list of landmarks in the fixed image', argstr='--fixedLandmarks %s...')
    movingLandmarks = InputMultiPath(traits.List(traits.Float(), minlen=3, maxlen=3), desc='Ordered list of landmarks in the moving image', argstr='--movingLandmarks %s...')
    rigidMaxIterations = traits.Int(desc='Maximum number of rigid optimization iterations', argstr='--rigidMaxIterations %d')
    rigidSamplingRatio = traits.Float(desc='Portion of the image to use in computing the metric during rigid registration', argstr='--rigidSamplingRatio %f')
    affineMaxIterations = traits.Int(desc='Maximum number of affine optimization iterations', argstr='--affineMaxIterations %d')
    affineSamplingRatio = traits.Float(desc='Portion of the image to use in computing the metric during affine registration', argstr='--affineSamplingRatio %f')
    bsplineMaxIterations = traits.Int(desc='Maximum number of bspline optimization iterations', argstr='--bsplineMaxIterations %d')
    bsplineSamplingRatio = traits.Float(desc='Portion of the image to use in computing the metric during BSpline registration', argstr='--bsplineSamplingRatio %f')
    controlPointSpacing = traits.Int(desc='Number of pixels between control points', argstr='--controlPointSpacing %d')