import graphene
import mlflow
from mlflow.server.graphql.autogenerated_graphql_schema import (
from mlflow.utils.proto_json_utils import parse_dict
class TestMutation(graphene.ObjectType):
    output = graphene.String(description='Echoes the input string')