from antlr4 import *
from io import StringIO
import sys
class LaTeXLexer(Lexer):
    atn = ATNDeserializer().deserialize(serializedATN())
    decisionsToDFA = [DFA(ds, i) for i, ds in enumerate(atn.decisionToState)]
    T__0 = 1
    T__1 = 2
    WS = 3
    THINSPACE = 4
    MEDSPACE = 5
    THICKSPACE = 6
    QUAD = 7
    QQUAD = 8
    NEGTHINSPACE = 9
    NEGMEDSPACE = 10
    NEGTHICKSPACE = 11
    CMD_LEFT = 12
    CMD_RIGHT = 13
    IGNORE = 14
    ADD = 15
    SUB = 16
    MUL = 17
    DIV = 18
    L_PAREN = 19
    R_PAREN = 20
    L_BRACE = 21
    R_BRACE = 22
    L_BRACE_LITERAL = 23
    R_BRACE_LITERAL = 24
    L_BRACKET = 25
    R_BRACKET = 26
    BAR = 27
    R_BAR = 28
    L_BAR = 29
    L_ANGLE = 30
    R_ANGLE = 31
    FUNC_LIM = 32
    LIM_APPROACH_SYM = 33
    FUNC_INT = 34
    FUNC_SUM = 35
    FUNC_PROD = 36
    FUNC_EXP = 37
    FUNC_LOG = 38
    FUNC_LG = 39
    FUNC_LN = 40
    FUNC_SIN = 41
    FUNC_COS = 42
    FUNC_TAN = 43
    FUNC_CSC = 44
    FUNC_SEC = 45
    FUNC_COT = 46
    FUNC_ARCSIN = 47
    FUNC_ARCCOS = 48
    FUNC_ARCTAN = 49
    FUNC_ARCCSC = 50
    FUNC_ARCSEC = 51
    FUNC_ARCCOT = 52
    FUNC_SINH = 53
    FUNC_COSH = 54
    FUNC_TANH = 55
    FUNC_ARSINH = 56
    FUNC_ARCOSH = 57
    FUNC_ARTANH = 58
    L_FLOOR = 59
    R_FLOOR = 60
    L_CEIL = 61
    R_CEIL = 62
    FUNC_SQRT = 63
    FUNC_OVERLINE = 64
    CMD_TIMES = 65
    CMD_CDOT = 66
    CMD_DIV = 67
    CMD_FRAC = 68
    CMD_BINOM = 69
    CMD_DBINOM = 70
    CMD_TBINOM = 71
    CMD_MATHIT = 72
    UNDERSCORE = 73
    CARET = 74
    COLON = 75
    DIFFERENTIAL = 76
    LETTER = 77
    DIGIT = 78
    EQUAL = 79
    NEQ = 80
    LT = 81
    LTE = 82
    LTE_Q = 83
    LTE_S = 84
    GT = 85
    GTE = 86
    GTE_Q = 87
    GTE_S = 88
    BANG = 89
    SINGLE_QUOTES = 90
    SYMBOL = 91
    channelNames = [u'DEFAULT_TOKEN_CHANNEL', u'HIDDEN']
    modeNames = ['DEFAULT_MODE']
    literalNames = ['<INVALID>', "','", "'.'", "'\\quad'", "'\\qquad'", "'\\negmedspace'", "'\\negthickspace'", "'\\left'", "'\\right'", "'+'", "'-'", "'*'", "'/'", "'('", "')'", "'{'", "'}'", "'\\{'", "'\\}'", "'['", "']'", "'|'", "'\\right|'", "'\\left|'", "'\\langle'", "'\\rangle'", "'\\lim'", "'\\sum'", "'\\prod'", "'\\exp'", "'\\log'", "'\\lg'", "'\\ln'", "'\\sin'", "'\\cos'", "'\\tan'", "'\\csc'", "'\\sec'", "'\\cot'", "'\\arcsin'", "'\\arccos'", "'\\arctan'", "'\\arccsc'", "'\\arcsec'", "'\\arccot'", "'\\sinh'", "'\\cosh'", "'\\tanh'", "'\\arsinh'", "'\\arcosh'", "'\\artanh'", "'\\lfloor'", "'\\rfloor'", "'\\lceil'", "'\\rceil'", "'\\sqrt'", "'\\overline'", "'\\times'", "'\\cdot'", "'\\div'", "'\\binom'", "'\\dbinom'", "'\\tbinom'", "'\\mathit'", "'_'", "'^'", "':'", "'\\neq'", "'<'", "'\\leqq'", "'\\leqslant'", "'>'", "'\\geqq'", "'\\geqslant'", "'!'"]
    symbolicNames = ['<INVALID>', 'WS', 'THINSPACE', 'MEDSPACE', 'THICKSPACE', 'QUAD', 'QQUAD', 'NEGTHINSPACE', 'NEGMEDSPACE', 'NEGTHICKSPACE', 'CMD_LEFT', 'CMD_RIGHT', 'IGNORE', 'ADD', 'SUB', 'MUL', 'DIV', 'L_PAREN', 'R_PAREN', 'L_BRACE', 'R_BRACE', 'L_BRACE_LITERAL', 'R_BRACE_LITERAL', 'L_BRACKET', 'R_BRACKET', 'BAR', 'R_BAR', 'L_BAR', 'L_ANGLE', 'R_ANGLE', 'FUNC_LIM', 'LIM_APPROACH_SYM', 'FUNC_INT', 'FUNC_SUM', 'FUNC_PROD', 'FUNC_EXP', 'FUNC_LOG', 'FUNC_LG', 'FUNC_LN', 'FUNC_SIN', 'FUNC_COS', 'FUNC_TAN', 'FUNC_CSC', 'FUNC_SEC', 'FUNC_COT', 'FUNC_ARCSIN', 'FUNC_ARCCOS', 'FUNC_ARCTAN', 'FUNC_ARCCSC', 'FUNC_ARCSEC', 'FUNC_ARCCOT', 'FUNC_SINH', 'FUNC_COSH', 'FUNC_TANH', 'FUNC_ARSINH', 'FUNC_ARCOSH', 'FUNC_ARTANH', 'L_FLOOR', 'R_FLOOR', 'L_CEIL', 'R_CEIL', 'FUNC_SQRT', 'FUNC_OVERLINE', 'CMD_TIMES', 'CMD_CDOT', 'CMD_DIV', 'CMD_FRAC', 'CMD_BINOM', 'CMD_DBINOM', 'CMD_TBINOM', 'CMD_MATHIT', 'UNDERSCORE', 'CARET', 'COLON', 'DIFFERENTIAL', 'LETTER', 'DIGIT', 'EQUAL', 'NEQ', 'LT', 'LTE', 'LTE_Q', 'LTE_S', 'GT', 'GTE', 'GTE_Q', 'GTE_S', 'BANG', 'SINGLE_QUOTES', 'SYMBOL']
    ruleNames = ['T__0', 'T__1', 'WS', 'THINSPACE', 'MEDSPACE', 'THICKSPACE', 'QUAD', 'QQUAD', 'NEGTHINSPACE', 'NEGMEDSPACE', 'NEGTHICKSPACE', 'CMD_LEFT', 'CMD_RIGHT', 'IGNORE', 'ADD', 'SUB', 'MUL', 'DIV', 'L_PAREN', 'R_PAREN', 'L_BRACE', 'R_BRACE', 'L_BRACE_LITERAL', 'R_BRACE_LITERAL', 'L_BRACKET', 'R_BRACKET', 'BAR', 'R_BAR', 'L_BAR', 'L_ANGLE', 'R_ANGLE', 'FUNC_LIM', 'LIM_APPROACH_SYM', 'FUNC_INT', 'FUNC_SUM', 'FUNC_PROD', 'FUNC_EXP', 'FUNC_LOG', 'FUNC_LG', 'FUNC_LN', 'FUNC_SIN', 'FUNC_COS', 'FUNC_TAN', 'FUNC_CSC', 'FUNC_SEC', 'FUNC_COT', 'FUNC_ARCSIN', 'FUNC_ARCCOS', 'FUNC_ARCTAN', 'FUNC_ARCCSC', 'FUNC_ARCSEC', 'FUNC_ARCCOT', 'FUNC_SINH', 'FUNC_COSH', 'FUNC_TANH', 'FUNC_ARSINH', 'FUNC_ARCOSH', 'FUNC_ARTANH', 'L_FLOOR', 'R_FLOOR', 'L_CEIL', 'R_CEIL', 'FUNC_SQRT', 'FUNC_OVERLINE', 'CMD_TIMES', 'CMD_CDOT', 'CMD_DIV', 'CMD_FRAC', 'CMD_BINOM', 'CMD_DBINOM', 'CMD_TBINOM', 'CMD_MATHIT', 'UNDERSCORE', 'CARET', 'COLON', 'WS_CHAR', 'DIFFERENTIAL', 'LETTER', 'DIGIT', 'EQUAL', 'NEQ', 'LT', 'LTE', 'LTE_Q', 'LTE_S', 'GT', 'GTE', 'GTE_Q', 'GTE_S', 'BANG', 'SINGLE_QUOTES', 'SYMBOL']
    grammarFileName = 'LaTeX.g4'

    def __init__(self, input=None, output: TextIO=sys.stdout):
        super().__init__(input, output)
        self.checkVersion('4.11.1')
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None