import logging
import xml.etree.ElementTree as ET
from fiona.env import require_gdal_version
from fiona.ogrext import _get_metadata_item
class MetadataItem:
    CREATION_FIELD_DATA_TYPES = 'DMD_CREATIONFIELDDATATYPES'
    CREATION_FIELD_DATA_SUB_TYPES = 'DMD_CREATIONFIELDDATASUBTYPES'
    CREATION_OPTION_LIST = 'DMD_CREATIONOPTIONLIST'
    LAYER_CREATION_OPTION_LIST = 'DS_LAYER_CREATIONOPTIONLIST'
    DATASET_OPEN_OPTIONS = 'DMD_OPENOPTIONLIST'
    EXTENSIONS = 'DMD_EXTENSIONS'
    EXTENSION = 'DMD_EXTENSION'
    VIRTUAL_IO = 'DCAP_VIRTUALIO'
    NOT_NULL_FIELDS = 'DCAP_NOTNULL_FIELDS'
    NOT_NULL_GEOMETRY_FIELDS = 'DCAP_NOTNULL_GEOMFIELDS'
    UNIQUE_FIELDS = 'DCAP_UNIQUE_FIELDS'
    DEFAULT_FIELDS = 'DCAP_DEFAULT_FIELDS'
    OPEN = 'DCAP_OPEN'
    CREATE = 'DCAP_CREATE'