from enum import IntFlag, auto
from typing import Dict, Tuple
from ._utils import deprecate_with_replacement
class PageAttributes:
    """TABLE 3.27 Entries in a page object."""
    TYPE = '/Type'
    PARENT = '/Parent'
    LAST_MODIFIED = '/LastModified'
    RESOURCES = '/Resources'
    MEDIABOX = '/MediaBox'
    CROPBOX = '/CropBox'
    BLEEDBOX = '/BleedBox'
    TRIMBOX = '/TrimBox'
    ARTBOX = '/ArtBox'
    BOX_COLOR_INFO = '/BoxColorInfo'
    CONTENTS = '/Contents'
    ROTATE = '/Rotate'
    GROUP = '/Group'
    THUMB = '/Thumb'
    B = '/B'
    DUR = '/Dur'
    TRANS = '/Trans'
    ANNOTS = '/Annots'
    AA = '/AA'
    METADATA = '/Metadata'
    PIECE_INFO = '/PieceInfo'
    STRUCT_PARENTS = '/StructParents'
    ID = '/ID'
    PZ = '/PZ'
    TABS = '/Tabs'
    TEMPLATE_INSTANTIATED = '/TemplateInstantiated'
    PRES_STEPS = '/PresSteps'
    USER_UNIT = '/UserUnit'
    VP = '/VP'