from __future__ import annotations
import math
from typing import List, NamedTuple, Union
import torch
import torchaudio
import torchaudio.lib.pybind11_prefixctc as cuctc
class CUCTCHypothesis(NamedTuple):
    """Represents hypothesis generated by CUCTC beam search decoder :class:`CUCTCDecoder`."""
    tokens: List[int]
    'Predicted sequence of token IDs. Shape `(L, )`, where `L` is the length of the output sequence'
    words: List[str]
    'List of predicted tokens. Algin with modeling unit.\n    '
    score: float
    'Score corresponding to hypothesis'