from hashlib import md5
import re
import logging; log = logging.getLogger(__name__)
from warnings import warn
from passlib.utils import to_unicode
from passlib.utils.binary import h64
from passlib.utils.compat import byte_elem_value, irange, u, \
import passlib.utils.handlers as uh
class sun_md5_crypt(uh.HasRounds, uh.HasSalt, uh.GenericHandler):
    """This class implements the Sun-MD5-Crypt password hash, and follows the :ref:`password-hash-api`.

    It supports a variable-length salt, and a variable number of rounds.

    The :meth:`~passlib.ifc.PasswordHash.using` method accepts the following optional keywords:

    :type salt: str
    :param salt:
        Optional salt string.
        If not specified, a salt will be autogenerated (this is recommended).
        If specified, it must be drawn from the regexp range ``[./0-9A-Za-z]``.

    :type salt_size: int
    :param salt_size:
        If no salt is specified, this parameter can be used to specify
        the size (in characters) of the autogenerated salt.
        It currently defaults to 8.

    :type rounds: int
    :param rounds:
        Optional number of rounds to use.
        Defaults to 34000, must be between 0 and 4294963199, inclusive.

    :type bare_salt: bool
    :param bare_salt:
        Optional flag used to enable an alternate salt digest behavior
        used by some hash strings in this scheme.
        This flag can be ignored by most users.
        Defaults to ``False``.
        (see :ref:`smc-bare-salt` for details).

    :type relaxed: bool
    :param relaxed:
        By default, providing an invalid value for one of the other
        keywords will result in a :exc:`ValueError`. If ``relaxed=True``,
        and the error can be corrected, a :exc:`~passlib.exc.PasslibHashWarning`
        will be issued instead. Correctable errors include ``rounds``
        that are too small or too large, and ``salt`` strings that are too long.

        .. versionadded:: 1.6
    """
    name = 'sun_md5_crypt'
    setting_kwds = ('salt', 'rounds', 'bare_salt', 'salt_size')
    checksum_chars = uh.HASH64_CHARS
    checksum_size = 22
    default_salt_size = 8
    max_salt_size = None
    salt_chars = uh.HASH64_CHARS
    default_rounds = 34000
    min_rounds = 0
    max_rounds = 4294963199
    rounds_cost = 'linear'
    ident_values = (u('$md5$'), u('$md5,'))
    bare_salt = False

    def __init__(self, bare_salt=False, **kwds):
        self.bare_salt = bare_salt
        super(sun_md5_crypt, self).__init__(**kwds)

    @classmethod
    def identify(cls, hash):
        hash = uh.to_unicode_for_identify(hash)
        return hash.startswith(cls.ident_values)

    @classmethod
    def from_string(cls, hash):
        hash = to_unicode(hash, 'ascii', 'hash')
        if hash.startswith(u('$md5$')):
            rounds = 0
            salt_idx = 5
        elif hash.startswith(u('$md5,rounds=')):
            idx = hash.find(u('$'), 12)
            if idx == -1:
                raise uh.exc.MalformedHashError(cls, 'unexpected end of rounds')
            rstr = hash[12:idx]
            try:
                rounds = int(rstr)
            except ValueError:
                raise uh.exc.MalformedHashError(cls, 'bad rounds')
            if rstr != unicode(rounds):
                raise uh.exc.ZeroPaddedRoundsError(cls)
            if rounds == 0:
                raise uh.exc.MalformedHashError(cls, 'explicit zero rounds')
            salt_idx = idx + 1
        else:
            raise uh.exc.InvalidHashError(cls)
        chk_idx = hash.rfind(u('$'), salt_idx)
        if chk_idx == -1:
            salt = hash[salt_idx:]
            chk = None
            bare_salt = True
        elif chk_idx == len(hash) - 1:
            if chk_idx > salt_idx and hash[-2] == u('$'):
                raise uh.exc.MalformedHashError(cls, "too many '$' separators")
            salt = hash[salt_idx:-1]
            chk = None
            bare_salt = False
        elif chk_idx > 0 and hash[chk_idx - 1] == u('$'):
            salt = hash[salt_idx:chk_idx - 1]
            chk = hash[chk_idx + 1:]
            bare_salt = False
        else:
            salt = hash[salt_idx:chk_idx]
            chk = hash[chk_idx + 1:]
            bare_salt = True
        return cls(rounds=rounds, salt=salt, checksum=chk, bare_salt=bare_salt)

    def to_string(self, _withchk=True):
        ss = u('') if self.bare_salt else u('$')
        rounds = self.rounds
        if rounds > 0:
            hash = u('$md5,rounds=%d$%s%s') % (rounds, self.salt, ss)
        else:
            hash = u('$md5$%s%s') % (self.salt, ss)
        if _withchk:
            chk = self.checksum
            hash = u('%s$%s') % (hash, chk)
        return uascii_to_str(hash)

    def _calc_checksum(self, secret):
        if isinstance(secret, unicode):
            secret = secret.encode('utf-8')
        config = str_to_bascii(self.to_string(_withchk=False))
        return raw_sun_md5_crypt(secret, self.rounds, config).decode('ascii')