import os
from ...base import (
class gtractFiberTrackingInputSpec(CommandLineInputSpec):
    inputTensorVolume = File(desc='Required (for Free, Streamline, GraphSearch, and Guided fiber tracking methods): input tensor image file name', exists=True, argstr='--inputTensorVolume %s')
    inputAnisotropyVolume = File(desc='Required (for Free, Streamline, GraphSearch, and Guided fiber tracking methods): input anisotropy image file name', exists=True, argstr='--inputAnisotropyVolume %s')
    inputStartingSeedsLabelMapVolume = File(desc='Required (for Free, Streamline, GraphSearch, and Guided fiber tracking methods): input starting seeds LabelMap image file name', exists=True, argstr='--inputStartingSeedsLabelMapVolume %s')
    startingSeedsLabel = traits.Int(desc='Label value for Starting Seeds (required if Label number used to create seed point in Slicer was not 1)', argstr='--startingSeedsLabel %d')
    inputEndingSeedsLabelMapVolume = File(desc='Required (for Streamline, GraphSearch, and Guided fiber tracking methods): input ending seeds LabelMap image file name', exists=True, argstr='--inputEndingSeedsLabelMapVolume %s')
    endingSeedsLabel = traits.Int(desc='Label value for Ending Seeds (required if Label number used to create seed point in Slicer was not 1)', argstr='--endingSeedsLabel %d')
    inputTract = File(desc='Required (for Guided fiber tracking method): guide fiber in vtkPolydata file containing one tract line.', exists=True, argstr='--inputTract %s')
    outputTract = traits.Either(traits.Bool, File(), hash_files=False, desc='Required (for Free, Streamline, GraphSearch, and Guided fiber tracking methods): name of output vtkPolydata file containing tract lines and the point data collected along them.', argstr='--outputTract %s')
    writeXMLPolyDataFile = traits.Bool(desc='Flag to make use of the XML format for vtkPolyData fiber tracts.', argstr='--writeXMLPolyDataFile ')
    trackingMethod = traits.Enum('Guided', 'Free', 'Streamline', 'GraphSearch', desc='Fiber tracking Filter Type: Guided|Free|Streamline|GraphSearch', argstr='--trackingMethod %s')
    guidedCurvatureThreshold = traits.Float(desc='Guided Curvature Threshold (Degrees)', argstr='--guidedCurvatureThreshold %f')
    maximumGuideDistance = traits.Float(desc='Maximum distance for using the guide fiber direction', argstr='--maximumGuideDistance %f')
    seedThreshold = traits.Float(desc='Anisotropy threshold for seed selection (recommended for Free fiber tracking)', argstr='--seedThreshold %f')
    trackingThreshold = traits.Float(desc='Anisotropy threshold for fiber tracking (anisotropy values of the next point along the path)', argstr='--trackingThreshold %f')
    curvatureThreshold = traits.Float(desc='Curvature threshold in degrees (recommended for Free  fiber tracking)', argstr='--curvatureThreshold %f')
    branchingThreshold = traits.Float(desc='Anisotropy Branching threshold (recommended for GraphSearch fiber tracking method)', argstr='--branchingThreshold %f')
    maximumBranchPoints = traits.Int(desc='Maximum branch points (recommended for GraphSearch fiber tracking method)', argstr='--maximumBranchPoints %d')
    useRandomWalk = traits.Bool(desc='Flag to use random walk.', argstr='--useRandomWalk ')
    randomSeed = traits.Int(desc='Random number generator seed', argstr='--randomSeed %d')
    branchingAngle = traits.Float(desc='Branching angle in degrees (recommended for GraphSearch fiber tracking method)', argstr='--branchingAngle %f')
    minimumLength = traits.Float(desc='Minimum fiber length. Helpful for filtering invalid tracts.', argstr='--minimumLength %f')
    maximumLength = traits.Float(desc='Maximum fiber length (voxels)', argstr='--maximumLength %f')
    stepSize = traits.Float(desc='Fiber tracking step size', argstr='--stepSize %f')
    useLoopDetection = traits.Bool(desc='Flag to make use of loop detection.', argstr='--useLoopDetection ')
    useTend = traits.Bool(desc='Flag to make use of Tend F and Tend G parameters.', argstr='--useTend ')
    tendF = traits.Float(desc='Tend F parameter', argstr='--tendF %f')
    tendG = traits.Float(desc='Tend G parameter', argstr='--tendG %f')
    numberOfThreads = traits.Int(desc='Explicitly specify the maximum number of threads to use.', argstr='--numberOfThreads %d')