import os
from ..base import (
class MedicAlgorithmSPECTRE2010InputSpec(CommandLineInputSpec):
    inInput = File(desc='Input volume to be skullstripped.', exists=True, argstr='--inInput %s')
    inAtlas = File(desc='SPECTRE atlas description file. A text file enumerating atlas files and landmarks.', exists=True, argstr='--inAtlas %s')
    inInitial = traits.Int(desc='Erosion of the initial mask, which is based on the probability mask and the classification., The initial mask is output as the d0 volume at the conclusion of SPECTRE.', argstr='--inInitial %d')
    inImage = traits.Enum('T1_SPGR', 'T1_ALT', 'T1_MPRAGE', 'T2', 'FLAIR', desc='Set the image modality. MP-RAGE is recommended for most T1 sequence images.', argstr='--inImage %s')
    inOutput = traits.Enum('true', 'false', desc='Determines if the output results are transformed back into the space of the original input image.', argstr='--inOutput %s')
    inFind = traits.Enum('true', 'false', desc='Find Midsaggital Plane', argstr='--inFind %s')
    inRun = traits.Enum('true', 'false', desc='Run Smooth Brain Mask', argstr='--inRun %s')
    inResample = traits.Enum('true', 'false', desc='Determines if the data is resampled to be isotropic during the processing.', argstr='--inResample %s')
    inInitial2 = traits.Float(desc='Initial probability threshold', argstr='--inInitial2 %f')
    inMinimum = traits.Float(desc='Minimum probability threshold', argstr='--inMinimum %f')
    inMMC = traits.Int(desc='The size of the dilation step within the Modified Morphological Closing.', argstr='--inMMC %d')
    inMMC2 = traits.Int(desc='The size of the erosion step within the Modified Morphological Closing.', argstr='--inMMC2 %d')
    inInhomogeneity = traits.Enum('true', 'false', desc="Set to false by default, this parameter will make FANTASM try to do inhomogeneity correction during it's iterative cycle.", argstr='--inInhomogeneity %s')
    inSmoothing = traits.Float(argstr='--inSmoothing %f')
    inBackground = traits.Float(argstr='--inBackground %f')
    inOutput2 = traits.Enum('true', 'false', desc='Output Plane?', argstr='--inOutput2 %s')
    inOutput3 = traits.Enum('true', 'false', desc='Output Split-Halves?', argstr='--inOutput3 %s')
    inOutput4 = traits.Enum('true', 'false', desc='Output Segmentation on Plane?', argstr='--inOutput4 %s')
    inDegrees = traits.Enum('Rigid - 6', 'Global rescale - 7', 'Specific rescale - 9', 'Affine - 12', desc='Degrees of freedom', argstr='--inDegrees %s')
    inCost = traits.Enum('Correlation ratio', 'Least squares', 'Normalized cross correlation', 'Normalized mutual information', desc='Cost function', argstr='--inCost %s')
    inRegistration = traits.Enum('Trilinear', 'Bspline 3rd order', 'Bspline 4th order', 'Cubic Lagrangian', 'Quintic Lagrangian', 'Heptic Lagrangian', 'Windowed sinc', desc='Registration interpolation', argstr='--inRegistration %s')
    inOutput5 = traits.Enum('Trilinear', 'Bspline 3rd order', 'Bspline 4th order', 'Cubic Lagrangian', 'Quintic Lagrangian', 'Heptic Lagrangian', 'Windowed sinc', 'Nearest Neighbor', desc='Output interpolation', argstr='--inOutput5 %s')
    inApply = traits.Enum('All', 'X', 'Y', 'Z', desc='Apply rotation', argstr='--inApply %s')
    inMinimum2 = traits.Float(desc='Minimum angle', argstr='--inMinimum2 %f')
    inMaximum = traits.Float(desc='Maximum angle', argstr='--inMaximum %f')
    inCoarse = traits.Float(desc='Coarse angle increment', argstr='--inCoarse %f')
    inFine = traits.Float(desc='Fine angle increment', argstr='--inFine %f')
    inMultiple = traits.Int(desc='Multiple of tolerance to bracket the minimum', argstr='--inMultiple %d')
    inNumber = traits.Int(desc='Number of iterations', argstr='--inNumber %d')
    inNumber2 = traits.Int(desc='Number of minima from Level 8 to test at Level 4', argstr='--inNumber2 %d')
    inUse = traits.Enum('true', 'false', desc='Use the max of the min resolutions of the two datasets when resampling', argstr='--inUse %s')
    inSubsample = traits.Enum('true', 'false', desc='Subsample image for speed', argstr='--inSubsample %s')
    inSkip = traits.Enum('true', 'false', desc='Skip multilevel search (Assume images are close to alignment)', argstr='--inSkip %s')
    inMultithreading = traits.Enum('true', 'false', desc='Set to false by default, this parameter controls the multithreaded behavior of the linear registration.', argstr='--inMultithreading %s')
    xPrefExt = traits.Enum('nrrd', desc='Output File Type', argstr='--xPrefExt %s')
    outOriginal = traits.Either(traits.Bool, File(), hash_files=False, desc='If Output in Original Space Flag is true then outputs the original input volume. Otherwise outputs the axialy reoriented input volume.', argstr='--outOriginal %s')
    outStripped = traits.Either(traits.Bool, File(), hash_files=False, desc='Skullstripped result of the input volume with just the brain.', argstr='--outStripped %s')
    outMask = traits.Either(traits.Bool, File(), hash_files=False, desc='Binary Mask of the skullstripped result with just the brain', argstr='--outMask %s')
    outPrior = traits.Either(traits.Bool, File(), hash_files=False, desc='Probability prior from the atlas registrations', argstr='--outPrior %s')
    outFANTASM = traits.Either(traits.Bool, File(), hash_files=False, desc='Tissue classification of the whole input volume.', argstr='--outFANTASM %s')
    outd0 = traits.Either(traits.Bool, File(), hash_files=False, desc='Initial Brainmask', argstr='--outd0 %s')
    outMidsagittal = traits.Either(traits.Bool, File(), hash_files=False, desc='Plane dividing the brain hemispheres', argstr='--outMidsagittal %s')
    outSplitHalves = traits.Either(traits.Bool, File(), hash_files=False, desc='Skullstripped mask of the brain with the hemispheres divided.', argstr='--outSplitHalves %s')
    outSegmentation = traits.Either(traits.Bool, File(), hash_files=False, desc='2D image showing the tissue classification on the midsagittal plane', argstr='--outSegmentation %s')
    null = traits.Str(desc='Execution Time', argstr='--null %s')
    xDefaultMem = traits.Int(desc='Set default maximum heap size', argstr='-xDefaultMem %d')
    xMaxProcess = traits.Int(1, desc='Set default maximum number of processes.', argstr='-xMaxProcess %d', usedefault=True)