import math
import time
import warnings
from dataclasses import dataclass
from itertools import product
import networkx as nx
@dataclass
class CostMatrix:
    C: ...
    lsa_row_ind: ...
    lsa_col_ind: ...
    ls: ...