from __future__ import absolute_import
from apitools.base.protorpclite import messages as _messages
from apitools.base.py import encoding
from apitools.base.py import extra_types
class LearningGenaiRecitationDocAttribution(_messages.Message):
    """The proto defines the attribution information for a document using
  whatever fields are most applicable for that document's datasource. For
  example, a Wikipedia article's attribution is in the form of its article
  title, a website is in the form of a URL, and a Github repo is in the form
  of a repo name. Next id: 30

  Enums:
    DatasetValueValuesEnum: The dataset this document comes from.

  Fields:
    amarnaId: A string attribute.
    arxivId: A string attribute.
    author: A string attribute.
    bibkey: A string attribute.
    biorxivId: ID of the paper in bioarxiv like ddoi.org/{biorxiv_id} eg:
      https://doi.org/10.1101/343517
    bookTitle: A string attribute.
    bookVolumeId: The Oceanographers full-view books dataset uses a 'volume
      id' as the unique ID of a book. There is a deterministic function from a
      volume id to a URL under the books.google.com domain. Marked as
      'optional' since a volume ID of zero is potentially possible and we want
      to distinguish that from the volume ID not being set.
    conversationId: A string attribute.
    dataset: The dataset this document comes from.
    filepath: A string attribute.
    geminiId: A string attribute.
    gnewsArticleTitle: A string attribute.
    goodallExampleId: A string attribute.
    isOptOut: Whether the document is opted out.
    isPrompt: When true, this attribution came from the user's prompt.
    lamdaExampleId: A string attribute.
    license: A string attribute.
    meenaConversationId: A string attribute.
    naturalLanguageCode: Natural (not programming) language of the document.
      Language code as defined by
      http://www.unicode.org/reports/tr35/#Identifiers and
      https://tools.ietf.org/html/bcp47. Currently applicable to full-view
      books. Use docinfo-util.h to set & read language fields. See go/iii.
    noAttribution: True if this doc has no attribution information available.
      We use an explicit field for this instead of just implicitly leaving all
      the DocAttribution fields blank to distinguish a case where a
      bug/oversight has left the attribution information empty vs when we
      really have no attribution information available.
    podcastUtteranceId: A string attribute.
    publicationDate: A GoogleTypeDate attribute.
    qualityScoreExperimentOnly: This field is for opt-out experiment only,
      MUST never be used during actual production/serving.
    repo: Github repository
    url: URL of a webdoc
    volumeId: A string attribute.
    wikipediaArticleTitle: Wikipedia article title. The Wikipedia TFDS dataset
      includes article titles but not URLs. While a URL is to the best of our
      knowledge a deterministic function of the title, we store the original
      title to reflect the information in the original dataset.
    youtubeVideoId: A string attribute.
  """

    class DatasetValueValuesEnum(_messages.Enum):
        """The dataset this document comes from.

    Values:
      DATASET_UNSPECIFIED: <no description>
      WIKIPEDIA: Wikipedia article Tensorflow datasets used by Tarzan and
        maintained by TFDS team.
      WEBDOCS: Webdocs that have been filtered from the docjoins by the Tarzan
        team for use in the Tarzan training set.
      WEBDOCS_FINETUNE: <no description>
      GITHUB_MIRROR: <no description>
      BOOKS_FULL_VIEW: 'Full view' books dataset maintained by Oceanographers
        team, meaning 'ok to view the book in full in all localities'. Largely
        the same as 'public domain', but with potentially subtle distinction.
      BOOKS_PRIVATE: Filtered private books used by ULM: http://google3/learni
        ng/multipod/pax/lm/params/ulm/tasks.py;l=123;rcl=494241309. which
        corresponds with /cns/mf-d/home/multipod-language-
        data/private_books/books_filtered_en_resharded@50000
      GNEWS: Google news dataset referenced in: http://google3/learning/brain/
        research/conversation/meena/t5/pretrain_tasks.py;l=922;rcl=496534668
      ULM_DOCJOINS: The docjoins data for ULM /cns/yo-d/home/multipod-
        language-data/docjoins/rs=6.3/20220728/100B_docstructure_split/example
        s_en.tfrecord_lattice_05_score_01_HFV13@3929
      ULM_DOCJOINS_DEDUPED: <no description>
      MEENA_FC: Meena full conversations. http://google3/learning/brain/resear
        ch/conversation/meena/t5/pretrain_mixtures.py;l=675;rcl=496583228
      PODCAST: <no description>
      AQUA: <no description>
      WEB_ASR: <no description>
      BARD_GOLDEN: <no description>
      COMMON_SENSE_REASONING: <no description>
      MATH: <no description>
      MATH_REASONING: <no description>
      CLEAN_ARXIV: <no description>
      LAMDA_FACTUALITY_E2E_QUERY_GENERATION: <no description>
      LAMDA_FACTUALITY_E2E_RESPONSE_GENERATION: <no description>
      MASSIVE_FORUM_THREAD_SCORED_BARD: <no description>
      MASSIVE_FORUM_THREAD_SCORED_LONG_200: <no description>
      MASSIVE_FORUM_THREAD_SCORED_LONG_500: <no description>
      DOCUMENT_CHUNKS: <no description>
      MEENA_RESEARCH_PHASE_GOLDEN_MARKDOWN: <no description>
      MEENA_RESEARCH_PHASE_GOOGLERS: <no description>
      MEENA_RESPONSE_SAFETY_HUMAN_GEN: <no description>
      MEENA_RESPONSE_SAFETY_SCHEMA_NO_BROADCAST: <no description>
      MEENA_RESPONSE_SAFETY_V3_HUMAN_GEN2: <no description>
      MEENA_RESPONSE_SAFETY_V3_SCHEMA_NO_BROADCAST: <no description>
      LAMDA_FACTUALITY_TRIGGER: <no description>
      LAMDA_SAFETY_V2_SCHEMA_NO_BROADCAST: <no description>
      LAMDA_SSI_DISCRIMINATIVE: <no description>
      ASSISTANT_PERSONALITY_SAFETY: <no description>
      PODCAST_FINETUNE_DIALOG: <no description>
      WORLD_QUERY_GENERATOR: <no description>
      C4_JOINED_DOCJOINS: <no description>
      HOL4_THEORIES: <no description>
      HOL_LIGHT_THEORIES: <no description>
      HOLSTEPS: <no description>
      ISABELLE_STEP: <no description>
      ISABELLE_THEORIES: <no description>
      LEAN_MATHLIB_THEORIES: <no description>
      LEAN_STEP: <no description>
      MIZAR_THEORIES: <no description>
      COQ_STEP: <no description>
      COQ_THEORIES: <no description>
      AMPS_KHAN: Academic dataset of math text. http://google3/learning/brain/
        research/conversation/meena/seqio/mixtures/experimental/bard.py;rcl=50
        0222380
      AMPS_MATHEMATICA: <no description>
      CODEY_CODE: <no description>
      CODE_QA_SE: <no description>
      CODE_QA_SO: <no description>
      CODE_QA_FT_FORMAT: <no description>
      CODE_QA_FT_KNOWLEDGE: <no description>
      CODE_QA_GITHUB_FILTERED_CODE: <no description>
      BARD_PERSONALITY_GOLDEN: <no description>
      ULM_DOCJOINS_WITH_URLS_EN: <no description>
      ULM_DOCJOINS_WITH_URLS_I18N: <no description>
      GOODALL_MTV5_GITHUB: Datasets managed by the Goodall team: deepmind-
        goodall@google.com
      GOODALL_MTV5_BOOKS: <no description>
      GOODALL_MTV5_C4: <no description>
      GOODALL_MTV5_WIKIPEDIA: <no description>
      GOODALL_MW_TOP_100B: <no description>
      GOODALL_MW_STACK_EXCHANGE: <no description>
      GOODALL_MW_TOP_0_10B: <no description>
      GOODALL_MW_TOP_10B_20B: <no description>
      CODEY_NOTEBOOK_LM_PRETRAINING: Datasets used by Codepoet
      VERTEX_SAFE_FLAN: Datasets used by Vertex
      GITHUB_MIRROR_V1_0_1: <no description>
      GITHUB_MIRROR_V2_1_0: <no description>
      CMS_WIKIPEDIA_LANG_FILTERED: Datasets used by Gemini Public data
      CMS_STACKOVERFLOW_MULTILINGUAL: <no description>
      CMS_STACKEXCHANGE: <no description>
      PUBMED: <no description>
      GEMINI_DOCJOINS_EN_TOP10B_GCC: Public webdocs
      GEMINI_DOCJOINS_EN_TOP10B_TOP20B_GCC: <no description>
      GEMINI_DOCJOINS_EN_TOP20B_TOP100B_GCC: <no description>
      GEMINI_DOCJOINS_EN_TOP100B_ALL_INDEXED_GCC: <no description>
      GEMINI_DOCJOINS_I18N_TOP10B_GCC: <no description>
      GEMINI_DOCJOINS_I18N_TOP10B_TOP20B_GCC: <no description>
      GEMINI_DOCJOINS_I18N_TOP20B_TOP100B_GCC: <no description>
      SIMPLIFIED_HTML_V1_GCC: <no description>
      GEMINI_DOCJOINS_TOXICITY_TAGGED_GCC: <no description>
      CMS_GITHUB_V4: Github
      GITHUB_HTML_V4: <no description>
      GITHUB_OTHER_V4: <no description>
      GITHUB_LONG_TAIL_V4: <no description>
      CMS_GITHUB_MULTIFILE_V4: <no description>
      GITHUB_DIFFS_WITH_COMMIT_MESSAGE: <no description>
      ULM_ARXIV: Arxiv
      NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_040623_LONG_DEDUP_ENONLY: Others
      NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_040623_LONG_DEDUP_NONENONLY: <no
        description>
      QUORA: <no description>
      PODCASTS_ROBOTSTXT: <no description>
      COMBINED_REDDIT: <no description>
      CANARIES_SHUFFLED: <no description>
      CLM_TRANSLATE_DATAV2_ALLTIERS_GCC_MIX: <no description>
      TECHDOCS_DATA_SOURCE: <no description>
      SCIENCE_PDF_70M_DOCS_FILTERED: <no description>
      GEMINI_V1_CMS_WIKIPEDIA_LANG_FILTERED: Gemini V1, order by precedence.
        Wikipedia
      GEMINI_V1_WIKIPEDIA_DIFFS: <no description>
      GEMINI_V1_DOCJOINS_EN_TOP10B_GCC_NODEDUP_050523: Public webdocs
      GEMINI_V1_DOCJOINS_EN_TOP10B_TOP20B_GCC_NODEDUP_050523: <no description>
      GEMINI_V1_DOCJOINS_EN_TOP20B_TOP100B_GCC_NODEDUP_050523: <no
        description>
      GEMINI_V1_DOCJOINS_EN_TOP100B_ALL_INDEXED_GCC_NODEDUP_050523: <no
        description>
      GEMINI_V1_DOCJOINS_I18N_TOP10B_GCC_050523: <no description>
      GEMINI_V1_DOCJOINS_I18N_TOP10B_TOP20B_GCC_050523: <no description>
      GEMINI_V1_DOCJOINS_I18N_TOP20B_TOP100B_GCC_050523: <no description>
      GEMINI_V1_SIMPLIFIED_HTML_V2_GCC: <no description>
      GEMINI_V1_CMS_STACKOVERFLOW_MULTILINGUAL_V2: <no description>
      GEMINI_V1_CMS_STACKEXCHANGE_DECONT: <no description>
      GEMINI_V1_QUORA: <no description>
      GEMINI_V1_COMBINED_REDDIT: <no description>
      GEMINI_V1_DOCJOIN_100B_EN_TOXICITY_TAGGED_GCC_FIXED_TAGS: <no
        description>
      GEMINI_V1_PUBMED: <no description>
      GEMINI_V1_WEB_MATH_V2: <no description>
      GEMINI_V1_CMS_GITHUB_V7: GitHub dataset with license info. We prefer
        this to help cite proper licenses for code recitation.
      GEMINI_V1_CMS_GITHUB_DECONTAMINATED_V_7: <no description>
      GEMINI_V1_GITHUB_DIFF_WITH_COMMIT_MESSAGE_V2: <no description>
      GEMINI_V1_GITHUB_HTML_CSS_XML_V4: <no description>
      GEMINI_V1_GITHUB_OTHER_V4: <no description>
      GEMINI_V1_GITHUB_LONG_TAIL_V4: <no description>
      GEMINI_V1_GITHUB_JUPTYER_NOTEBOOKS_SSTABLE: <no description>
      GEMINI_V1_ULM_ARXIV_SSTABLE: ArXiv
      GEMINI_V1_PODCASTS_ROBOTSTXT: Citable misc
      GEMINI_V1_SCIENCE_PDF_68M_HQ_DOCS_GCC: <no description>
      GEMINI_V1_GITHUB_TECHDOCS_V2: <no description>
      GEMINI_V1_NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_LONG_DEDUP_EN: Non-public
        books
      GEMINI_V1_NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_LONG_DEDUP_NONEN: <no
        description>
      GEMINI_V1_STEM_BOOKS_650K_TEXT: <no description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_M3W_V2_FILTERED: Other
      GEMINI_V1_VQCOCA_1B_MULTIRES_WEBLI_EN_V4_350M_PREFIXED_FILTERED_IMAGE2TE
        XT: <no description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_SCREENAI_PREFIXED_FILTERED_IMAGE2TEXT: <no
        description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_CULTURE_PREFIXED_FILTERED_IMAGE2TEXT: <no
        description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_CC3M_EN_PREFIXED_IMAGE2TEXT: <no
        description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_CC3M_I18N_PREFIXED_IMAGE2TEXT: <no
        description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_OCR_EN_PREFIXED_FILTERED_IMAGE2TEXT: <no
        description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_OCR_NON_EN_PREFIXED_FILTERED_IMAGE2TEXT:
        <no description>
      GEMINI_V1_VQCOCA_1B_MULTIRES_VTP_4F_VIDEO2TEXT_PREFIX: <no description>
      GEMINI_V1_FORMAL_MATH_WITHOUT_HOLSTEPS_AND_MIZAR: <no description>
      GEMINI_V1_TRANSLATE_DATAV2_ALLTIERS_GCC_MIX: <no description>
      GEMINI_V1_CANARIES_SHUFFLED_DOCJOIN_EN_NONEN_CODE_ARXIV_TRANSLATE: <no
        description>
      DUET_CLOUD_SECURITY_DOCS: Duet AI finetune datasets, order by
        precedence.
      DUET_GITHUB_CODE_SNIPPETS: <no description>
      DUET_GITHUB_FILES: <no description>
      DUET_GOBYEXAMPLE: <no description>
      DUET_GOLANG_DOCS: <no description>
      DUET_CLOUD_DOCS_TROUBLESHOOTING_TABLES: <no description>
      DUET_DEVSITE_DOCS: <no description>
      DUET_CLOUD_BLOG_POSTS: <no description>
      DUET_CLOUD_PODCAST_EPISODES: <no description>
      DUET_YOUTUBE_VIDEOS: <no description>
      DUET_CLOUD_SKILLS_BOOST: <no description>
      DUET_CLOUD_DOCS: <no description>
      DUET_CLOUD_GITHUB_CODE_SNIPPETS_GENERATED: <no description>
      DUET_CLOUD_GITHUB_CODE_SNIPPETS_HANDWRITTEN: <no description>
      DUET_GOOGLESQL_GENERATION: <no description>
      DUET_CLOUD_IX_PROMPTS: <no description>
      DUET_RAD: <no description>
      DUET_STACKOVERFLOW_ISSUES: <no description>
      DUET_STACKOVERFLOW_ANSWERS: <no description>
      BARD_ARCADE_GITHUB: Bard ARCADE finetune dataset
      MOBILE_ASSISTANT_MAGI_FILTERED_0825_373K: Mobile assistant finetune
        datasets.
      MOBILE_ASSISTANT_PALM24B_FILTERED_400K: <no description>
      GENESIS_NEWS_INSIGHTS: Genesis fine tuned datasets.
      LABS_AQA_DSCOUT: LABS AQA fine-tune datasets.
      LABS_AQA_TAILWIND: <no description>
      LABS_AQA_DELEWARE: <no description>
      GEMINI_MULTIMODAL_FT_URL: Gemini multimodal instruction tune(IT) and
        fine tune(FT) datasets datasets.
      GEMINI_MULTIMODAL_FT_YT: <no description>
      GEMINI_MULTIMODAL_FT_SHUTTERSTOCK: <no description>
      GEMINI_MULTIMODAL_FT_NONE: <no description>
      GEMINI_MULTIMODAL_FT_OTHER: <no description>
      GEMINI_MULTIMODAL_FT_INK: <no description>
      GEMINI_MULTIMODAL_IT: <no description>
      GEMINI_IT_SHUTTERSTOCK: Gemini IT 1.2.7 datasets
      GEMINI_IT_M3W: <no description>
      GEMINI_IT_HEDGING: <no description>
      GEMINI_IT_DSCOUT_FACTUALITY: <no description>
      GEMINI_IT_AQUAMUSE: <no description>
      GEMINI_IT_SHOTGUN: <no description>
      GEMINI_IT_ACI_BENCH: <no description>
      GEMINI_IT_SPIDER_FILTERED: <no description>
      GEMINI_IT_TAB_SUM_BQ: <no description>
      GEMINI_IT_QA_WITH_URL: <no description>
      GEMINI_IT_CODE_INSTRUCT: <no description>
      GEMINI_IT_MED_PALM: <no description>
      GEMINI_IT_TASK_ORIENTED_DIALOG: <no description>
      GEMINI_IT_NIMBUS_GROUNDING_TO_PROMPT: <no description>
      GEMINI_IT_EITL_GEN: <no description>
      GEMINI_IT_HITL_GEN: <no description>
      GEMINI_IT_MECH: <no description>
      GEMINI_IT_TABLE_GEN: <no description>
      GEMINI_IT_NIMBUS_DECIBEL: <no description>
      GEMINI_IT_CLOUD_CODE_IF: <no description>
      GEMINI_IT_CLOUD_EUR_LEX_JSON: <no description>
      GEMINI_IT_CLOUD_OASST: <no description>
      GEMINI_IT_CLOUD_SELF_INSTRUCT: <no description>
      GEMINI_IT_CLOUD_UCS_AQUAMUSE: <no description>
      GEMIT_BRIDGE_SUFFIX_FT: Gemit Bridge ULM FT dataset
      CLOUD_SECURITY_PRETRAINING: Cloud Security fine tuned datasets.
      CLOUD_SECURITY_FINETUNING: <no description>
      CLOUD_SECURITY_RAG_CISA: <no description>
      GEMINI_GOOSE_PUBLIC: Gemini Goose FT datasets.
      GEMINI_GOOSE_SILOED: <no description>
      GEMINI_V2_CMS_WIKIPEDIA_LANG_FILTERED_GCC_PII: Gemini V2 datasets
      GEMINI_V2_WIKIPEDIA_DIFFS_COMPLIANT: <no description>
      GEMINI_V2_ENGLISH_ARTICLES_TOP10B_211123_PII_FILTERED: <no description>
      GEMINI_V2_ENGLISH_NONARTICLES_TOP10B_211123_PII_FILTERED: <no
        description>
      GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP10B_111323_WITHOUT_CJKT_STOP_NONARTIC
        LES_COMPLIANT: <no description>
      GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP10B_111323_WITHOUT_CJKT_STOP_ARTICLES
        _COMPLIANT: <no description>
      GEMINI_V2_ENGLISH_ARTICLES_TOP20B_211123_PII_FILTERED: <no description>
      GEMINI_V2_ENGLISH_NONARTICLES_TOP20B_211123_PII_FILTERED: <no
        description>
      GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP20B_111323_WITHOUT_CJKT_STOP_NONARTIC
        LES_COMPLIANT: <no description>
      GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP20B_111323_WITHOUT_CJKT_STOP_ARTICLES
        _COMPLIANT: <no description>
      GEMINI_V2_ENGLISH_ARTICLES_TOP100B_211123_PII_FILTERED: <no description>
      GEMINI_V2_ENGLISH_NONARTICLES_TOP100B_211123_PII_FILTERED: <no
        description>
      GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP100B_111323_WITHOUT_CJKT_STOP_NONARTI
        CLES_COMPLIANT: <no description>
      GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP100B_111323_WITHOUT_CJKT_STOP_ARTICLE
        S_COMPLIANT: <no description>
      GEMINI_V2_ENGLISH_ARTICLES_TOP500B_211123_PII_FILTERED: <no description>
      GEMINI_V2_ENGLISH_NONARTICLES_TOP500B_211123_PII_FILTERED: <no
        description>
      GEMINI_V2_QUORA_COMPLIANT: <no description>
      GEMINI_V2_FORUMS_V2_COMPLIANT: <no description>
      GEMINI_V2_CMS_STACKOVERFLOW_MULTILINGUAL_V2_COMPLIANT: <no description>
      GEMINI_V2_SIMPLIFIED_HTML_V2_CORRECT_FORMAT_COMPLIANT: <no description>
      GEMINI_V2_GEMINI_DOCJOINS_TOXICITY_TAGGED_FIXED_TAGS_COMPLIANT: <no
        description>
      GEMINI_V2_CODEWEB_V1_COMPLIANT: <no description>
      GEMINI_V2_LEETCODE_GCC_PII: <no description>
      GEMINI_V2_CODE_CONTESTS_COMPLIANT: <no description>
      GEMINI_V2_CMS_GITHUB_MULTI_FILE_FOR_FIM_GEMBAGZ_FIXED_BYTES_LENGTHS: <no
        description>
      GEMINI_V2_GITHUB_EVALED_LANGUAGES_COMPLIANT: <no description>
      GEMINI_V2_GITHUB_NON_EVAL_HIGH_PRI_LANGUAGES_COMPLIANT: <no description>
      GEMINI_V2_GITHUB_LOW_PRI_LANGUAGES_AND_CONFIGS_COMPLIANT: <no
        description>
      GEMINI_V2_GITHUB_LONG_TAIL_AND_STRUCTURED_DATA_COMPLIANT: <no
        description>
      GEMINI_V2_GITHUB_PYTHON_NOTEBOOKS_COMPLIANT: <no description>
      GEMINI_V2_GITHUB_DIFFS_COMPLIANT: <no description>
      GEMINI_V2_GITHUB_TECHDOCS_COMPLIANT: <no description>
      GEMINI_V2_HIGH_QUALITY_CODE_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_SCIENCE_PDF_68M_HQ_DOCS_DEDUP_COMPLIANT_CLEAN_TEX: <no
        description>
      GEMINI_V2_ARXIV_2023_COMPLIANT: <no description>
      GEMINI_V2_FORMAL_COMPLIANT: <no description>
      GEMINI_V2_CMS_STACKEXCHANGE_COMPLIANT: <no description>
      GEMINI_V2_PUBMED_COMPLIANT: <no description>
      GEMINI_V2_WEB_MATH_V3_COMPLIANT: <no description>
      GEMINI_V2_SCIENCEWEB_V0_GCC_PII: <no description>
      GEMINI_V2_WEB_POLYMATH_V1_COMPLIANT: <no description>
      GEMINI_V2_MATH_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_BIOLOGY_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_PHYSICS_V2_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_CHEMISTRY_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_MACHINE_LEARNING_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_QA_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_ECONOMICS_V2_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_MEDICAL_TARGETED_DATA_COMPLIANT2: <no description>
      GEMINI_V2_CHESS_COMPLIANT: <no description>
      GEMINI_V2_YOUTUBE_SCIENCE_V4_FILTERED_COMPLIANT: <no description>
      GEMINI_V2_GOALDMINE_XL_GENERATED_PLUS_GT_NO_DM_MATH_COMPLIANT: <no
        description>
      GEMINI_V2_FIRSTTIMES_SCIENCE_PDF_DEDUP_HQ_LENGTH_FILTERED_COMPLIANT: <no
        description>
      GEMINI_V2_PODCASTS_COMPLIANT: <no description>
      GEMINI_V2_EN_NONSCIENCE_PDF_DEDUP_46M_DOCS_COMPLIANT: <no description>
      GEMINI_V2_NONPUB_COPYRIGHT_BOOKS_V3_70_CONF_082323_LONG_DEDUP_ENONLY_COM
        PLIANT: <no description>
      GEMINI_V2_STEM_COPYRIGHT_BOOKS_V3_111823_LONG_DEDUP_ENONLY_COMPLIANT:
        <no description>
      GEMINI_V2_STEM_BOOKS_318K_TEXT_COMPLIANT: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_M3W_WITH_IMAGE_TOKENS_INSERTED_INTERLEA
        VED_COMPLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_M3W_WITH_IMAGE_TOKENS_INSERTED_INTERLEA
        VED_COMPLIANT_PII_FILTERED_SOFT: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_EN_V4_350M_T2I_TEXT_TO_IMAGE_COMP
        LIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SHUTTERSTOCK_IMAGE_TO_TEXT_COMPLIANT_PI
        I_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_EN_V4_350M_IMAGE_TO_TEXT_COMPLIAN
        T_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_OCR_I18N_680M_IMAGE_TO_TEXT_COMPL
        IANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_DOC_IMAGE_TO_TEXT_COMPLIANT_PII
        _FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SCREENAI_FULL_HTML_75M_IMAGE_TO_TEXT_CO
        MPLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SCREENAI_V1_1_IMAGE_TO_TEXT_COMPLIANT_P
        II_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_OCR_DOC_240M_IMAGE_TO_TEXT_COMPLI
        ANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SHUTTERSTOCK_VIDEO_VIDEO_TO_TEXT_COMPLI
        ANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_M4W_INTERLEAVED_COMPLIANT_PII_FILTERED_
        SOFT: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CULTURE_IMAGE_TO_TEXT_COMPLIANT_PII_FIL
        TERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_DETECTION_IMAGE_TO_TEXT_COMPLIANT
        _PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_ALT_TEXT_NONEN_500M_IMAGE_TO_TEXT
        _COMPLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SPATIAL_AWARE_PALI_IMAGE_TO_TEXT_COMPLI
        ANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_TABLE2HTML_3D_IMAGE_TO_TEXT_COM
        PLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_TABLE2MD_V2_EN_IMAGE_TO_TEXT_COMPLIANT_
        PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_TABLE2MD_V2_NON_EN_IMAGE_TO_TEXT_COMPLI
        ANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_3D_DOC_IMAGE_TO_TEXT_COMPLIANT_
        PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CC3M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTER
        ED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_INFOGRAPHICS_LARGE_WEB_IMAGE_TO_TEXT_CO
        MPLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_BIORXIV_IMAGE_TO_TEXT_COMPLIANT_PII_FIL
        TERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_PHOTOMATH_IM2SOL_PROBLEM_AND_SOLUTION_I
        MAGE_TO_TEXT_COMPLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_PLOT2TABLE_V2_IMAGE_TO_TEXT_COMPLIANT_P
        II_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_TIKZ_DERENDERING_MERGED_IMAGE_TO_TEXT_C
        OMPLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_TABLE2HTML_2D_IMAGE_TO_TEXT_COM
        PLIANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WIKIPEDIA_EQUATIONS_IMAGE_TO_TEXT_COMPL
        IANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_PHOTOMATH_EQ2LATEX_IMAGE_TO_TEXT_COMPLI
        ANT_PII_FILTERED: <no description>
      GEMINI_V2_CACHED_VQCOCA_MMFT_17T_ARXIV_EQUATIONS_V2_IMAGE_TO_TEXT_COMPLI
        ANT_PII_FILTERED: <no description>
      GEMINI_V2_USM2B_MLPV5_YT_ASR_SUP_GEMBAGZ_V2_COMPLIANT: <no description>
      GEMINI_V2_USM2B_MLPV5_YT_ASR_1P5M_GEMBAGZ_V2_COMPLIANT: <no description>
      GEMINI_V2_USM2B_MLPV5_YT_ASR_4M_GEMBAGZ_V2_COMPLIANT: <no description>
      GEMINI_V2_USM2B_MLPV5_YT_TTS_SUP_GEMBAGZ_V2_COMPLIANT: <no description>
      GEMINI_V2_USM2B_MLPV5_YT_TTS_1P5M_GEMBAGZ_V2_COMPLIANT: <no description>
      GEMINI_V2_USM2B_MLPV5_YT_TTS_4M_GEMBAGZ_V2_COMPLIANT: <no description>
      GEMINI_V2_USM2B_MLPV5_PODIOSET_INTERLEAVE_ENUS_GEMBAGZ_V2_COMPLIANT: <no
        description>
      GEMINI_V2_USM2B_MLPV5_PODIOSET_INTERLEAVE_I18N_GEMBAGZ_V2_COMPLIANT: <no
        description>
      GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_SCIENCE_ENUS_GEMBAGZ_V2_COMPLIANT:
        <no description>
      GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_SCIENCE_I18N_GEMBAGZ_V2_COMPLIANT:
        <no description>
      GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_1P5M_GEMBAGZ_V2_COMPLIANT: <no
        description>
      GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_HEAD_4M_GEMBAGZ_V2_COMPLIANT: <no
        description>
      GEMINI_V2_CLM_TRANSLATE_DATAV3_WEB_UNWMT_INCR_MIX: <no description>
      GEMINI_V2_NTL_NTLV4A_MONOLINGUAL_DEDUP_N5: <no description>
      GEMINI_V2_NTL_STT_TRANSLATE_DEDUP_N5: <no description>
      GEMINI_V2_NTL_TRANSLIT_BILEX_TRANSLATE_DEDUP_N5: <no description>
      GEMINI_V2_NTL_SYN_BT_TRANSLATE_DEDUP_N5: <no description>
      GEMINI_V2_NTL_SYN_FT_FIXED_TRANSLATE_DEDUP_N5: <no description>
      GEMINI_V2_CANARIES_SHUFFLED_COMPLIANT: <no description>
      CLOUD_GEMIT_CLOUD_FACTUALITY_GROUNDING_MAGI: Cloud gemit pro FT
        datasets.
      CLOUD_GEMIT_MT_DIALGUE_LMSYS: <no description>
      CLOUD_GEMIT_MTS_DIALOGUE_V3: <no description>
      CLOUD_GEMIT_COMMIT_MSG_GEN_V3: <no description>
      CLOUD_GEMIT_CODE_IF_V1: <no description>
      CLOUD_GEMIT_CODE_SELF_REPAIR: <no description>
      CLOUD_GEMIT_IDENTITY: <no description>
      CLOUD_GEMIT_SEARCH_AUGMENTED_RESPONSE_GENERATION: Cloud gemit ultra FT
        datasets.
      CLOUD_GEMIT_AMPS: <no description>
      CLOUD_GEMIT_AQUA: <no description>
      CLOUD_GEMIT_COMMON_SENSE_REASONING_SCHEMA: <no description>
      CLOUD_GEMIT_GSM8K_SCHEMA: <no description>
      GEMINI_V1_TAIL_PATCH_TRANSLATION_UN: Gemini V1 tail patch translation.
      GEMINI_V1_TAIL_PATCH_TRANSLATION_WMT_EUROPARL: <no description>
      GEMINI_V1_TAIL_PATCH_TRANSLATION_WMT_NEWSCOMMENTARY: <no description>
      GEMINI_V1_TAIL_PATCH_TRANSLATION_2021_INCR: <no description>
      GEMINI_V1_TAIL_PATCH_GOALDMINE: Gemini V1 tail patch others.
      GEMINI_V1_TAIL_PATCH_PHOTOMATH_IM2SOL_PROBLEM_AND_SOLUTION: <no
        description>
      GEMINI_V1_TAIL_PATCH_CCAI_DIALOG_SUM_HUMAN: Gemini V1 and V2 shared tail
        patch.
      GEMINI_V1_TAIL_PATCH_MATH_REASONING_PUNTING: <no description>
      GEMINI_V1_TAIL_PATCH_MATH_REASONING_NON_PUNTING: <no description>
      GEMINI_V1_TAIL_PATCH_JSON_TABLE_EXTRACTION: <no description>
      GEMINI_V1_TAIL_PATCH_BIRD_SQL_LITE: <no description>
      GEMINI_V1_TAIL_PATCH_OPEN_BOOKS_QA_ANSWERABLE: <no description>
      GEMINI_V1_TAIL_PATCH_OPEN_BOOKS_QA_UNANSWERABLE: <no description>
      GEMINI_V2_TAIL_PATCH_CCAI_DIALOG_SUM_HUMAN: <no description>
      GEMINI_V2_TAIL_PATCH_MATH_REASONING_PUNTING: <no description>
      GEMINI_V2_TAIL_PATCH_MATH_REASONING_NON_PUNTING: <no description>
      GEMINI_V2_TAIL_PATCH_JSON_TABLE_EXTRACTION: <no description>
      GEMINI_V2_TAIL_PATCH_BIRD_SQL_LITE: <no description>
      GEMINI_V2_TAIL_PATCH_OPEN_BOOKS_QA_ANSWERABLE: <no description>
      GEMINI_V2_TAIL_PATCH_OPEN_BOOKS_QA_UNANSWERABLE: <no description>
      GEMINI_V2_TAIL_PATCH_PMC: Gemini V2 only tail patch.
    """
        DATASET_UNSPECIFIED = 0
        WIKIPEDIA = 1
        WEBDOCS = 2
        WEBDOCS_FINETUNE = 3
        GITHUB_MIRROR = 4
        BOOKS_FULL_VIEW = 5
        BOOKS_PRIVATE = 6
        GNEWS = 7
        ULM_DOCJOINS = 8
        ULM_DOCJOINS_DEDUPED = 9
        MEENA_FC = 10
        PODCAST = 11
        AQUA = 12
        WEB_ASR = 13
        BARD_GOLDEN = 14
        COMMON_SENSE_REASONING = 15
        MATH = 16
        MATH_REASONING = 17
        CLEAN_ARXIV = 18
        LAMDA_FACTUALITY_E2E_QUERY_GENERATION = 19
        LAMDA_FACTUALITY_E2E_RESPONSE_GENERATION = 20
        MASSIVE_FORUM_THREAD_SCORED_BARD = 21
        MASSIVE_FORUM_THREAD_SCORED_LONG_200 = 22
        MASSIVE_FORUM_THREAD_SCORED_LONG_500 = 23
        DOCUMENT_CHUNKS = 24
        MEENA_RESEARCH_PHASE_GOLDEN_MARKDOWN = 25
        MEENA_RESEARCH_PHASE_GOOGLERS = 26
        MEENA_RESPONSE_SAFETY_HUMAN_GEN = 27
        MEENA_RESPONSE_SAFETY_SCHEMA_NO_BROADCAST = 28
        MEENA_RESPONSE_SAFETY_V3_HUMAN_GEN2 = 29
        MEENA_RESPONSE_SAFETY_V3_SCHEMA_NO_BROADCAST = 30
        LAMDA_FACTUALITY_TRIGGER = 31
        LAMDA_SAFETY_V2_SCHEMA_NO_BROADCAST = 32
        LAMDA_SSI_DISCRIMINATIVE = 33
        ASSISTANT_PERSONALITY_SAFETY = 34
        PODCAST_FINETUNE_DIALOG = 35
        WORLD_QUERY_GENERATOR = 36
        C4_JOINED_DOCJOINS = 37
        HOL4_THEORIES = 38
        HOL_LIGHT_THEORIES = 39
        HOLSTEPS = 40
        ISABELLE_STEP = 41
        ISABELLE_THEORIES = 42
        LEAN_MATHLIB_THEORIES = 43
        LEAN_STEP = 44
        MIZAR_THEORIES = 45
        COQ_STEP = 46
        COQ_THEORIES = 47
        AMPS_KHAN = 48
        AMPS_MATHEMATICA = 49
        CODEY_CODE = 50
        CODE_QA_SE = 51
        CODE_QA_SO = 52
        CODE_QA_FT_FORMAT = 53
        CODE_QA_FT_KNOWLEDGE = 54
        CODE_QA_GITHUB_FILTERED_CODE = 55
        BARD_PERSONALITY_GOLDEN = 56
        ULM_DOCJOINS_WITH_URLS_EN = 57
        ULM_DOCJOINS_WITH_URLS_I18N = 58
        GOODALL_MTV5_GITHUB = 59
        GOODALL_MTV5_BOOKS = 60
        GOODALL_MTV5_C4 = 61
        GOODALL_MTV5_WIKIPEDIA = 62
        GOODALL_MW_TOP_100B = 63
        GOODALL_MW_STACK_EXCHANGE = 64
        GOODALL_MW_TOP_0_10B = 65
        GOODALL_MW_TOP_10B_20B = 66
        CODEY_NOTEBOOK_LM_PRETRAINING = 67
        VERTEX_SAFE_FLAN = 68
        GITHUB_MIRROR_V1_0_1 = 69
        GITHUB_MIRROR_V2_1_0 = 70
        CMS_WIKIPEDIA_LANG_FILTERED = 71
        CMS_STACKOVERFLOW_MULTILINGUAL = 72
        CMS_STACKEXCHANGE = 73
        PUBMED = 74
        GEMINI_DOCJOINS_EN_TOP10B_GCC = 75
        GEMINI_DOCJOINS_EN_TOP10B_TOP20B_GCC = 76
        GEMINI_DOCJOINS_EN_TOP20B_TOP100B_GCC = 77
        GEMINI_DOCJOINS_EN_TOP100B_ALL_INDEXED_GCC = 78
        GEMINI_DOCJOINS_I18N_TOP10B_GCC = 79
        GEMINI_DOCJOINS_I18N_TOP10B_TOP20B_GCC = 80
        GEMINI_DOCJOINS_I18N_TOP20B_TOP100B_GCC = 81
        SIMPLIFIED_HTML_V1_GCC = 82
        GEMINI_DOCJOINS_TOXICITY_TAGGED_GCC = 83
        CMS_GITHUB_V4 = 84
        GITHUB_HTML_V4 = 85
        GITHUB_OTHER_V4 = 86
        GITHUB_LONG_TAIL_V4 = 87
        CMS_GITHUB_MULTIFILE_V4 = 88
        GITHUB_DIFFS_WITH_COMMIT_MESSAGE = 89
        ULM_ARXIV = 90
        NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_040623_LONG_DEDUP_ENONLY = 91
        NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_040623_LONG_DEDUP_NONENONLY = 92
        QUORA = 93
        PODCASTS_ROBOTSTXT = 94
        COMBINED_REDDIT = 95
        CANARIES_SHUFFLED = 96
        CLM_TRANSLATE_DATAV2_ALLTIERS_GCC_MIX = 97
        TECHDOCS_DATA_SOURCE = 98
        SCIENCE_PDF_70M_DOCS_FILTERED = 99
        GEMINI_V1_CMS_WIKIPEDIA_LANG_FILTERED = 100
        GEMINI_V1_WIKIPEDIA_DIFFS = 101
        GEMINI_V1_DOCJOINS_EN_TOP10B_GCC_NODEDUP_050523 = 102
        GEMINI_V1_DOCJOINS_EN_TOP10B_TOP20B_GCC_NODEDUP_050523 = 103
        GEMINI_V1_DOCJOINS_EN_TOP20B_TOP100B_GCC_NODEDUP_050523 = 104
        GEMINI_V1_DOCJOINS_EN_TOP100B_ALL_INDEXED_GCC_NODEDUP_050523 = 105
        GEMINI_V1_DOCJOINS_I18N_TOP10B_GCC_050523 = 106
        GEMINI_V1_DOCJOINS_I18N_TOP10B_TOP20B_GCC_050523 = 107
        GEMINI_V1_DOCJOINS_I18N_TOP20B_TOP100B_GCC_050523 = 108
        GEMINI_V1_SIMPLIFIED_HTML_V2_GCC = 109
        GEMINI_V1_CMS_STACKOVERFLOW_MULTILINGUAL_V2 = 110
        GEMINI_V1_CMS_STACKEXCHANGE_DECONT = 111
        GEMINI_V1_QUORA = 112
        GEMINI_V1_COMBINED_REDDIT = 113
        GEMINI_V1_DOCJOIN_100B_EN_TOXICITY_TAGGED_GCC_FIXED_TAGS = 114
        GEMINI_V1_PUBMED = 115
        GEMINI_V1_WEB_MATH_V2 = 116
        GEMINI_V1_CMS_GITHUB_V7 = 117
        GEMINI_V1_CMS_GITHUB_DECONTAMINATED_V_7 = 118
        GEMINI_V1_GITHUB_DIFF_WITH_COMMIT_MESSAGE_V2 = 119
        GEMINI_V1_GITHUB_HTML_CSS_XML_V4 = 120
        GEMINI_V1_GITHUB_OTHER_V4 = 121
        GEMINI_V1_GITHUB_LONG_TAIL_V4 = 122
        GEMINI_V1_GITHUB_JUPTYER_NOTEBOOKS_SSTABLE = 123
        GEMINI_V1_ULM_ARXIV_SSTABLE = 124
        GEMINI_V1_PODCASTS_ROBOTSTXT = 125
        GEMINI_V1_SCIENCE_PDF_68M_HQ_DOCS_GCC = 126
        GEMINI_V1_GITHUB_TECHDOCS_V2 = 127
        GEMINI_V1_NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_LONG_DEDUP_EN = 128
        GEMINI_V1_NONPUB_COPYRIGHT_BOOKS_V2_70_CONF_LONG_DEDUP_NONEN = 129
        GEMINI_V1_STEM_BOOKS_650K_TEXT = 130
        GEMINI_V1_VQCOCA_1B_MULTIRES_M3W_V2_FILTERED = 131
        GEMINI_V1_VQCOCA_1B_MULTIRES_WEBLI_EN_V4_350M_PREFIXED_FILTERED_IMAGE2TEXT = 132
        GEMINI_V1_VQCOCA_1B_MULTIRES_SCREENAI_PREFIXED_FILTERED_IMAGE2TEXT = 133
        GEMINI_V1_VQCOCA_1B_MULTIRES_CULTURE_PREFIXED_FILTERED_IMAGE2TEXT = 134
        GEMINI_V1_VQCOCA_1B_MULTIRES_CC3M_EN_PREFIXED_IMAGE2TEXT = 135
        GEMINI_V1_VQCOCA_1B_MULTIRES_CC3M_I18N_PREFIXED_IMAGE2TEXT = 136
        GEMINI_V1_VQCOCA_1B_MULTIRES_OCR_EN_PREFIXED_FILTERED_IMAGE2TEXT = 137
        GEMINI_V1_VQCOCA_1B_MULTIRES_OCR_NON_EN_PREFIXED_FILTERED_IMAGE2TEXT = 138
        GEMINI_V1_VQCOCA_1B_MULTIRES_VTP_4F_VIDEO2TEXT_PREFIX = 139
        GEMINI_V1_FORMAL_MATH_WITHOUT_HOLSTEPS_AND_MIZAR = 140
        GEMINI_V1_TRANSLATE_DATAV2_ALLTIERS_GCC_MIX = 141
        GEMINI_V1_CANARIES_SHUFFLED_DOCJOIN_EN_NONEN_CODE_ARXIV_TRANSLATE = 142
        DUET_CLOUD_SECURITY_DOCS = 143
        DUET_GITHUB_CODE_SNIPPETS = 144
        DUET_GITHUB_FILES = 145
        DUET_GOBYEXAMPLE = 146
        DUET_GOLANG_DOCS = 147
        DUET_CLOUD_DOCS_TROUBLESHOOTING_TABLES = 148
        DUET_DEVSITE_DOCS = 149
        DUET_CLOUD_BLOG_POSTS = 150
        DUET_CLOUD_PODCAST_EPISODES = 151
        DUET_YOUTUBE_VIDEOS = 152
        DUET_CLOUD_SKILLS_BOOST = 153
        DUET_CLOUD_DOCS = 154
        DUET_CLOUD_GITHUB_CODE_SNIPPETS_GENERATED = 155
        DUET_CLOUD_GITHUB_CODE_SNIPPETS_HANDWRITTEN = 156
        DUET_GOOGLESQL_GENERATION = 157
        DUET_CLOUD_IX_PROMPTS = 158
        DUET_RAD = 159
        DUET_STACKOVERFLOW_ISSUES = 160
        DUET_STACKOVERFLOW_ANSWERS = 161
        BARD_ARCADE_GITHUB = 162
        MOBILE_ASSISTANT_MAGI_FILTERED_0825_373K = 163
        MOBILE_ASSISTANT_PALM24B_FILTERED_400K = 164
        GENESIS_NEWS_INSIGHTS = 165
        LABS_AQA_DSCOUT = 166
        LABS_AQA_TAILWIND = 167
        LABS_AQA_DELEWARE = 168
        GEMINI_MULTIMODAL_FT_URL = 169
        GEMINI_MULTIMODAL_FT_YT = 170
        GEMINI_MULTIMODAL_FT_SHUTTERSTOCK = 171
        GEMINI_MULTIMODAL_FT_NONE = 172
        GEMINI_MULTIMODAL_FT_OTHER = 173
        GEMINI_MULTIMODAL_FT_INK = 174
        GEMINI_MULTIMODAL_IT = 175
        GEMINI_IT_SHUTTERSTOCK = 176
        GEMINI_IT_M3W = 177
        GEMINI_IT_HEDGING = 178
        GEMINI_IT_DSCOUT_FACTUALITY = 179
        GEMINI_IT_AQUAMUSE = 180
        GEMINI_IT_SHOTGUN = 181
        GEMINI_IT_ACI_BENCH = 182
        GEMINI_IT_SPIDER_FILTERED = 183
        GEMINI_IT_TAB_SUM_BQ = 184
        GEMINI_IT_QA_WITH_URL = 185
        GEMINI_IT_CODE_INSTRUCT = 186
        GEMINI_IT_MED_PALM = 187
        GEMINI_IT_TASK_ORIENTED_DIALOG = 188
        GEMINI_IT_NIMBUS_GROUNDING_TO_PROMPT = 189
        GEMINI_IT_EITL_GEN = 190
        GEMINI_IT_HITL_GEN = 191
        GEMINI_IT_MECH = 192
        GEMINI_IT_TABLE_GEN = 193
        GEMINI_IT_NIMBUS_DECIBEL = 194
        GEMINI_IT_CLOUD_CODE_IF = 195
        GEMINI_IT_CLOUD_EUR_LEX_JSON = 196
        GEMINI_IT_CLOUD_OASST = 197
        GEMINI_IT_CLOUD_SELF_INSTRUCT = 198
        GEMINI_IT_CLOUD_UCS_AQUAMUSE = 199
        GEMIT_BRIDGE_SUFFIX_FT = 200
        CLOUD_SECURITY_PRETRAINING = 201
        CLOUD_SECURITY_FINETUNING = 202
        CLOUD_SECURITY_RAG_CISA = 203
        GEMINI_GOOSE_PUBLIC = 204
        GEMINI_GOOSE_SILOED = 205
        GEMINI_V2_CMS_WIKIPEDIA_LANG_FILTERED_GCC_PII = 206
        GEMINI_V2_WIKIPEDIA_DIFFS_COMPLIANT = 207
        GEMINI_V2_ENGLISH_ARTICLES_TOP10B_211123_PII_FILTERED = 208
        GEMINI_V2_ENGLISH_NONARTICLES_TOP10B_211123_PII_FILTERED = 209
        GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP10B_111323_WITHOUT_CJKT_STOP_NONARTICLES_COMPLIANT = 210
        GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP10B_111323_WITHOUT_CJKT_STOP_ARTICLES_COMPLIANT = 211
        GEMINI_V2_ENGLISH_ARTICLES_TOP20B_211123_PII_FILTERED = 212
        GEMINI_V2_ENGLISH_NONARTICLES_TOP20B_211123_PII_FILTERED = 213
        GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP20B_111323_WITHOUT_CJKT_STOP_NONARTICLES_COMPLIANT = 214
        GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP20B_111323_WITHOUT_CJKT_STOP_ARTICLES_COMPLIANT = 215
        GEMINI_V2_ENGLISH_ARTICLES_TOP100B_211123_PII_FILTERED = 216
        GEMINI_V2_ENGLISH_NONARTICLES_TOP100B_211123_PII_FILTERED = 217
        GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP100B_111323_WITHOUT_CJKT_STOP_NONARTICLES_COMPLIANT = 218
        GEMINI_V2_GEMINI_DOCJOINS_NONEN_TOP100B_111323_WITHOUT_CJKT_STOP_ARTICLES_COMPLIANT = 219
        GEMINI_V2_ENGLISH_ARTICLES_TOP500B_211123_PII_FILTERED = 220
        GEMINI_V2_ENGLISH_NONARTICLES_TOP500B_211123_PII_FILTERED = 221
        GEMINI_V2_QUORA_COMPLIANT = 222
        GEMINI_V2_FORUMS_V2_COMPLIANT = 223
        GEMINI_V2_CMS_STACKOVERFLOW_MULTILINGUAL_V2_COMPLIANT = 224
        GEMINI_V2_SIMPLIFIED_HTML_V2_CORRECT_FORMAT_COMPLIANT = 225
        GEMINI_V2_GEMINI_DOCJOINS_TOXICITY_TAGGED_FIXED_TAGS_COMPLIANT = 226
        GEMINI_V2_CODEWEB_V1_COMPLIANT = 227
        GEMINI_V2_LEETCODE_GCC_PII = 228
        GEMINI_V2_CODE_CONTESTS_COMPLIANT = 229
        GEMINI_V2_CMS_GITHUB_MULTI_FILE_FOR_FIM_GEMBAGZ_FIXED_BYTES_LENGTHS = 230
        GEMINI_V2_GITHUB_EVALED_LANGUAGES_COMPLIANT = 231
        GEMINI_V2_GITHUB_NON_EVAL_HIGH_PRI_LANGUAGES_COMPLIANT = 232
        GEMINI_V2_GITHUB_LOW_PRI_LANGUAGES_AND_CONFIGS_COMPLIANT = 233
        GEMINI_V2_GITHUB_LONG_TAIL_AND_STRUCTURED_DATA_COMPLIANT = 234
        GEMINI_V2_GITHUB_PYTHON_NOTEBOOKS_COMPLIANT = 235
        GEMINI_V2_GITHUB_DIFFS_COMPLIANT = 236
        GEMINI_V2_GITHUB_TECHDOCS_COMPLIANT = 237
        GEMINI_V2_HIGH_QUALITY_CODE_TARGETED_DATA_COMPLIANT2 = 238
        GEMINI_V2_SCIENCE_PDF_68M_HQ_DOCS_DEDUP_COMPLIANT_CLEAN_TEX = 239
        GEMINI_V2_ARXIV_2023_COMPLIANT = 240
        GEMINI_V2_FORMAL_COMPLIANT = 241
        GEMINI_V2_CMS_STACKEXCHANGE_COMPLIANT = 242
        GEMINI_V2_PUBMED_COMPLIANT = 243
        GEMINI_V2_WEB_MATH_V3_COMPLIANT = 244
        GEMINI_V2_SCIENCEWEB_V0_GCC_PII = 245
        GEMINI_V2_WEB_POLYMATH_V1_COMPLIANT = 246
        GEMINI_V2_MATH_TARGETED_DATA_COMPLIANT2 = 247
        GEMINI_V2_BIOLOGY_TARGETED_DATA_COMPLIANT2 = 248
        GEMINI_V2_PHYSICS_V2_TARGETED_DATA_COMPLIANT2 = 249
        GEMINI_V2_CHEMISTRY_TARGETED_DATA_COMPLIANT2 = 250
        GEMINI_V2_MACHINE_LEARNING_TARGETED_DATA_COMPLIANT2 = 251
        GEMINI_V2_QA_TARGETED_DATA_COMPLIANT2 = 252
        GEMINI_V2_ECONOMICS_V2_TARGETED_DATA_COMPLIANT2 = 253
        GEMINI_V2_MEDICAL_TARGETED_DATA_COMPLIANT2 = 254
        GEMINI_V2_CHESS_COMPLIANT = 255
        GEMINI_V2_YOUTUBE_SCIENCE_V4_FILTERED_COMPLIANT = 256
        GEMINI_V2_GOALDMINE_XL_GENERATED_PLUS_GT_NO_DM_MATH_COMPLIANT = 257
        GEMINI_V2_FIRSTTIMES_SCIENCE_PDF_DEDUP_HQ_LENGTH_FILTERED_COMPLIANT = 258
        GEMINI_V2_PODCASTS_COMPLIANT = 259
        GEMINI_V2_EN_NONSCIENCE_PDF_DEDUP_46M_DOCS_COMPLIANT = 260
        GEMINI_V2_NONPUB_COPYRIGHT_BOOKS_V3_70_CONF_082323_LONG_DEDUP_ENONLY_COMPLIANT = 261
        GEMINI_V2_STEM_COPYRIGHT_BOOKS_V3_111823_LONG_DEDUP_ENONLY_COMPLIANT = 262
        GEMINI_V2_STEM_BOOKS_318K_TEXT_COMPLIANT = 263
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_M3W_WITH_IMAGE_TOKENS_INSERTED_INTERLEAVED_COMPLIANT_PII_FILTERED = 264
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_M3W_WITH_IMAGE_TOKENS_INSERTED_INTERLEAVED_COMPLIANT_PII_FILTERED_SOFT = 265
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_EN_V4_350M_T2I_TEXT_TO_IMAGE_COMPLIANT_PII_FILTERED = 266
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SHUTTERSTOCK_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 267
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_EN_V4_350M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 268
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_OCR_I18N_680M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 269
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_DOC_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 270
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SCREENAI_FULL_HTML_75M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 271
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SCREENAI_V1_1_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 272
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_OCR_DOC_240M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 273
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SHUTTERSTOCK_VIDEO_VIDEO_TO_TEXT_COMPLIANT_PII_FILTERED = 274
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_M4W_INTERLEAVED_COMPLIANT_PII_FILTERED_SOFT = 275
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CULTURE_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 276
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_DETECTION_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 277
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WEBLI_ALT_TEXT_NONEN_500M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 278
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_SPATIAL_AWARE_PALI_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 279
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_TABLE2HTML_3D_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 280
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_TABLE2MD_V2_EN_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 281
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_TABLE2MD_V2_NON_EN_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 282
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_3D_DOC_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 283
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CC3M_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 284
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_INFOGRAPHICS_LARGE_WEB_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 285
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_BIORXIV_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 286
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_PHOTOMATH_IM2SOL_PROBLEM_AND_SOLUTION_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 287
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_PLOT2TABLE_V2_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 288
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_TIKZ_DERENDERING_MERGED_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 289
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_CLOUDAI_TABLE2HTML_2D_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 290
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_WIKIPEDIA_EQUATIONS_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 291
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_PHOTOMATH_EQ2LATEX_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 292
        GEMINI_V2_CACHED_VQCOCA_MMFT_17T_ARXIV_EQUATIONS_V2_IMAGE_TO_TEXT_COMPLIANT_PII_FILTERED = 293
        GEMINI_V2_USM2B_MLPV5_YT_ASR_SUP_GEMBAGZ_V2_COMPLIANT = 294
        GEMINI_V2_USM2B_MLPV5_YT_ASR_1P5M_GEMBAGZ_V2_COMPLIANT = 295
        GEMINI_V2_USM2B_MLPV5_YT_ASR_4M_GEMBAGZ_V2_COMPLIANT = 296
        GEMINI_V2_USM2B_MLPV5_YT_TTS_SUP_GEMBAGZ_V2_COMPLIANT = 297
        GEMINI_V2_USM2B_MLPV5_YT_TTS_1P5M_GEMBAGZ_V2_COMPLIANT = 298
        GEMINI_V2_USM2B_MLPV5_YT_TTS_4M_GEMBAGZ_V2_COMPLIANT = 299
        GEMINI_V2_USM2B_MLPV5_PODIOSET_INTERLEAVE_ENUS_GEMBAGZ_V2_COMPLIANT = 300
        GEMINI_V2_USM2B_MLPV5_PODIOSET_INTERLEAVE_I18N_GEMBAGZ_V2_COMPLIANT = 301
        GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_SCIENCE_ENUS_GEMBAGZ_V2_COMPLIANT = 302
        GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_SCIENCE_I18N_GEMBAGZ_V2_COMPLIANT = 303
        GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_1P5M_GEMBAGZ_V2_COMPLIANT = 304
        GEMINI_V2_USM2B_MLPV5_YT_INTERLEAVE_HEAD_4M_GEMBAGZ_V2_COMPLIANT = 305
        GEMINI_V2_CLM_TRANSLATE_DATAV3_WEB_UNWMT_INCR_MIX = 306
        GEMINI_V2_NTL_NTLV4A_MONOLINGUAL_DEDUP_N5 = 307
        GEMINI_V2_NTL_STT_TRANSLATE_DEDUP_N5 = 308
        GEMINI_V2_NTL_TRANSLIT_BILEX_TRANSLATE_DEDUP_N5 = 309
        GEMINI_V2_NTL_SYN_BT_TRANSLATE_DEDUP_N5 = 310
        GEMINI_V2_NTL_SYN_FT_FIXED_TRANSLATE_DEDUP_N5 = 311
        GEMINI_V2_CANARIES_SHUFFLED_COMPLIANT = 312
        CLOUD_GEMIT_CLOUD_FACTUALITY_GROUNDING_MAGI = 313
        CLOUD_GEMIT_MT_DIALGUE_LMSYS = 314
        CLOUD_GEMIT_MTS_DIALOGUE_V3 = 315
        CLOUD_GEMIT_COMMIT_MSG_GEN_V3 = 316
        CLOUD_GEMIT_CODE_IF_V1 = 317
        CLOUD_GEMIT_CODE_SELF_REPAIR = 318
        CLOUD_GEMIT_IDENTITY = 319
        CLOUD_GEMIT_SEARCH_AUGMENTED_RESPONSE_GENERATION = 320
        CLOUD_GEMIT_AMPS = 321
        CLOUD_GEMIT_AQUA = 322
        CLOUD_GEMIT_COMMON_SENSE_REASONING_SCHEMA = 323
        CLOUD_GEMIT_GSM8K_SCHEMA = 324
        GEMINI_V1_TAIL_PATCH_TRANSLATION_UN = 325
        GEMINI_V1_TAIL_PATCH_TRANSLATION_WMT_EUROPARL = 326
        GEMINI_V1_TAIL_PATCH_TRANSLATION_WMT_NEWSCOMMENTARY = 327
        GEMINI_V1_TAIL_PATCH_TRANSLATION_2021_INCR = 328
        GEMINI_V1_TAIL_PATCH_GOALDMINE = 329
        GEMINI_V1_TAIL_PATCH_PHOTOMATH_IM2SOL_PROBLEM_AND_SOLUTION = 330
        GEMINI_V1_TAIL_PATCH_CCAI_DIALOG_SUM_HUMAN = 331
        GEMINI_V1_TAIL_PATCH_MATH_REASONING_PUNTING = 332
        GEMINI_V1_TAIL_PATCH_MATH_REASONING_NON_PUNTING = 333
        GEMINI_V1_TAIL_PATCH_JSON_TABLE_EXTRACTION = 334
        GEMINI_V1_TAIL_PATCH_BIRD_SQL_LITE = 335
        GEMINI_V1_TAIL_PATCH_OPEN_BOOKS_QA_ANSWERABLE = 336
        GEMINI_V1_TAIL_PATCH_OPEN_BOOKS_QA_UNANSWERABLE = 337
        GEMINI_V2_TAIL_PATCH_CCAI_DIALOG_SUM_HUMAN = 338
        GEMINI_V2_TAIL_PATCH_MATH_REASONING_PUNTING = 339
        GEMINI_V2_TAIL_PATCH_MATH_REASONING_NON_PUNTING = 340
        GEMINI_V2_TAIL_PATCH_JSON_TABLE_EXTRACTION = 341
        GEMINI_V2_TAIL_PATCH_BIRD_SQL_LITE = 342
        GEMINI_V2_TAIL_PATCH_OPEN_BOOKS_QA_ANSWERABLE = 343
        GEMINI_V2_TAIL_PATCH_OPEN_BOOKS_QA_UNANSWERABLE = 344
        GEMINI_V2_TAIL_PATCH_PMC = 345
    amarnaId = _messages.StringField(1)
    arxivId = _messages.StringField(2)
    author = _messages.StringField(3)
    bibkey = _messages.StringField(4)
    biorxivId = _messages.StringField(5)
    bookTitle = _messages.StringField(6)
    bookVolumeId = _messages.IntegerField(7)
    conversationId = _messages.StringField(8)
    dataset = _messages.EnumField('DatasetValueValuesEnum', 9)
    filepath = _messages.StringField(10)
    geminiId = _messages.StringField(11)
    gnewsArticleTitle = _messages.StringField(12)
    goodallExampleId = _messages.StringField(13)
    isOptOut = _messages.BooleanField(14)
    isPrompt = _messages.BooleanField(15)
    lamdaExampleId = _messages.StringField(16)
    license = _messages.StringField(17)
    meenaConversationId = _messages.StringField(18)
    naturalLanguageCode = _messages.StringField(19)
    noAttribution = _messages.BooleanField(20)
    podcastUtteranceId = _messages.StringField(21)
    publicationDate = _messages.MessageField('GoogleTypeDate', 22)
    qualityScoreExperimentOnly = _messages.FloatField(23)
    repo = _messages.StringField(24)
    url = _messages.StringField(25)
    volumeId = _messages.StringField(26)
    wikipediaArticleTitle = _messages.StringField(27)
    youtubeVideoId = _messages.StringField(28)