from ipywidgets import (
from ipywidgets.widgets.trait_types import TypedTuple
from traitlets import (
from .._base.Three import ThreeWidget
from .._base.uniforms import uniforms_serialization
from ..enums import *
from ..traits import *
from ..core.BaseGeometry_autogen import BaseGeometry
import inspect
@register
class IcosahedronGeometry(BaseGeometry):
    """IcosahedronGeometry

    Autogenerated by generate-wrappers.js
    See https://threejs.org/docs/#api/geometries/IcosahedronGeometry
    """

    def __init__(self, radius=1, detail=0, **kwargs):
        kwargs['radius'] = radius
        kwargs['detail'] = detail
        super(IcosahedronGeometry, self).__init__(**kwargs)
    _model_name = Unicode('IcosahedronGeometryModel').tag(sync=True)
    radius = IEEEFloat(1, allow_none=False).tag(sync=True)
    detail = CInt(0, allow_none=False).tag(sync=True)
    type = Unicode('IcosahedronGeometry', allow_none=False).tag(sync=True)