import os
import unittest
from websocket._url import (
class UrlTest(unittest.TestCase):

    def test_address_in_network(self):
        self.assertTrue(_is_address_in_network('127.0.0.1', '127.0.0.0/8'))
        self.assertTrue(_is_address_in_network('127.1.0.1', '127.0.0.0/8'))
        self.assertFalse(_is_address_in_network('127.1.0.1', '127.0.0.0/24'))

    def testParseUrl(self):
        p = parse_url('ws://www.example.com/r')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 80)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], False)
        p = parse_url('ws://www.example.com/r/')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 80)
        self.assertEqual(p[2], '/r/')
        self.assertEqual(p[3], False)
        p = parse_url('ws://www.example.com/')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 80)
        self.assertEqual(p[2], '/')
        self.assertEqual(p[3], False)
        p = parse_url('ws://www.example.com')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 80)
        self.assertEqual(p[2], '/')
        self.assertEqual(p[3], False)
        p = parse_url('ws://www.example.com:8080/r')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], False)
        p = parse_url('ws://www.example.com:8080/')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/')
        self.assertEqual(p[3], False)
        p = parse_url('ws://www.example.com:8080')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/')
        self.assertEqual(p[3], False)
        p = parse_url('wss://www.example.com:8080/r')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], True)
        p = parse_url('wss://www.example.com:8080/r?key=value')
        self.assertEqual(p[0], 'www.example.com')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/r?key=value')
        self.assertEqual(p[3], True)
        self.assertRaises(ValueError, parse_url, 'http://www.example.com/r')
        p = parse_url('ws://[2a03:4000:123:83::3]/r')
        self.assertEqual(p[0], '2a03:4000:123:83::3')
        self.assertEqual(p[1], 80)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], False)
        p = parse_url('ws://[2a03:4000:123:83::3]:8080/r')
        self.assertEqual(p[0], '2a03:4000:123:83::3')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], False)
        p = parse_url('wss://[2a03:4000:123:83::3]/r')
        self.assertEqual(p[0], '2a03:4000:123:83::3')
        self.assertEqual(p[1], 443)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], True)
        p = parse_url('wss://[2a03:4000:123:83::3]:8080/r')
        self.assertEqual(p[0], '2a03:4000:123:83::3')
        self.assertEqual(p[1], 8080)
        self.assertEqual(p[2], '/r')
        self.assertEqual(p[3], True)