from sentry_sdk._types import TYPE_CHECKING
class SPANDATA:
    """
    Additional information describing the type of the span.
    See: https://develop.sentry.dev/sdk/performance/span-data-conventions/
    """
    DB_NAME = 'db.name'
    '\n    The name of the database being accessed. For commands that switch the database, this should be set to the target database (even if the command fails).\n    Example: myDatabase\n    '
    DB_USER = 'db.user'
    '\n    The name of the database user used for connecting to the database.\n    See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md\n    Example: my_user\n    '
    DB_OPERATION = 'db.operation'
    '\n    The name of the operation being executed, e.g. the MongoDB command name such as findAndModify, or the SQL keyword.\n    See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md\n    Example: findAndModify, HMSET, SELECT\n    '
    DB_SYSTEM = 'db.system'
    '\n    An identifier for the database management system (DBMS) product being used.\n    See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md\n    Example: postgresql\n    '
    CACHE_HIT = 'cache.hit'
    '\n    A boolean indicating whether the requested data was found in the cache.\n    Example: true\n    '
    CACHE_ITEM_SIZE = 'cache.item_size'
    '\n    The size of the requested data in bytes.\n    Example: 58\n    '
    HTTP_QUERY = 'http.query'
    '\n    The Query string present in the URL.\n    Example: ?foo=bar&bar=baz\n    '
    HTTP_FRAGMENT = 'http.fragment'
    '\n    The Fragments present in the URL.\n    Example: #foo=bar\n    '
    HTTP_METHOD = 'http.method'
    '\n    The HTTP method used.\n    Example: GET\n    '
    HTTP_STATUS_CODE = 'http.response.status_code'
    '\n    The HTTP status code as an integer.\n    Example: 418\n    '
    SERVER_ADDRESS = 'server.address'
    '\n    Name of the database host.\n    Example: example.com\n    '
    SERVER_PORT = 'server.port'
    '\n    Logical server port number\n    Example: 80; 8080; 443\n    '
    SERVER_SOCKET_ADDRESS = 'server.socket.address'
    '\n    Physical server IP address or Unix socket address.\n    Example: 10.5.3.2\n    '
    SERVER_SOCKET_PORT = 'server.socket.port'
    '\n    Physical server port.\n    Recommended: If different than server.port.\n    Example: 16456\n    '
    CODE_FILEPATH = 'code.filepath'
    '\n    The source code file name that identifies the code unit as uniquely as possible (preferably an absolute file path).\n    Example: "/app/myapplication/http/handler/server.py"\n    '
    CODE_LINENO = 'code.lineno'
    '\n    The line number in `code.filepath` best representing the operation. It SHOULD point within the code unit named in `code.function`.\n    Example: 42\n    '
    CODE_FUNCTION = 'code.function'
    '\n    The method or function name, or equivalent (usually rightmost part of the code unit\'s name).\n    Example: "server_request"\n    '
    CODE_NAMESPACE = 'code.namespace'
    '\n    The "namespace" within which `code.function` is defined. Usually the qualified class or module name, such that `code.namespace` + some separator + `code.function` form a unique identifier for the code unit.\n    Example: "http.handler"\n    '