import argparse
import collections
import datetime
import getpass
import logging
import os
import pprint
import sys
import time
from oslo_utils import netutils
from oslo_utils import strutils
from oslo_utils import timeutils
import novaclient
from novaclient import api_versions
from novaclient import base
from novaclient import client
from novaclient import exceptions
from novaclient.i18n import _
from novaclient import shell
from novaclient import utils
from novaclient.v2 import availability_zones
from novaclient.v2 import quotas
from novaclient.v2 import servers
@utils.arg('--flavor', default=None, metavar='<flavor>', help=_("Name or ID of flavor (see 'nova flavor-list')."))
@utils.arg('--image', default=None, metavar='<image>', help=_("Name or ID of image (see 'glance image-list'). "))
@utils.arg('--image-with', default=[], type=_key_value_pairing, action='append', metavar='<key=value>', help=_("Image metadata property (see 'glance image-show'). "))
@utils.arg('--boot-volume', default=None, metavar='<volume_id>', help=_('Volume ID to boot from.'))
@utils.arg('--snapshot', default=None, metavar='<snapshot_id>', help=_('Snapshot ID to boot from (will create a volume).'))
@utils.arg('--min-count', default=None, type=int, metavar='<number>', help=_('Boot at least <number> servers (limited by quota).'))
@utils.arg('--max-count', default=None, type=int, metavar='<number>', help=_('Boot up to <number> servers (limited by quota).'))
@utils.arg('--meta', metavar='<key=value>', action='append', default=[], help=_('Record arbitrary key/value metadata to /meta_data.json on the metadata server. Can be specified multiple times.'))
@utils.arg('--file', metavar='<dst-path=src-path>', action='append', dest='files', default=[], help=_("Store arbitrary files from <src-path> locally to <dst-path> on the new server. More files can be injected using multiple '--file' options. Limited by the 'injected_files' quota value. The default value is 5. You can get the current quota value by 'Personality' limit from 'nova limits' command."), start_version='2.0', end_version='2.56')
@utils.arg('--key-name', default=os.environ.get('NOVACLIENT_DEFAULT_KEY_NAME'), metavar='<key-name>', help=_('Key name of keypair that should be created earlier with            the command keypair-add.'))
@utils.arg('name', metavar='<name>', help=_('Name for the new server.'))
@utils.arg('--user-data', default=None, metavar='<user-data>', help=_('user data file to pass to be exposed by the metadata server.'))
@utils.arg('--availability-zone', default=None, metavar='<availability-zone>', help=_('The availability zone for server placement.'))
@utils.arg('--security-groups', default=None, metavar='<security-groups>', help=_('Comma separated list of security group names.'))
@utils.arg('--block-device-mapping', metavar='<dev-name=mapping>', action='append', default=[], help=_('Block device mapping in the format <dev-name>=<id>:<type>:<size(GiB)>:<delete-on-terminate>.'))
@utils.arg('--block-device', metavar='key1=value1[,key2=value2...]', action='append', default=[], start_version='2.0', end_version='2.31', help=_("Block device mapping with the keys: id=UUID (image_id, snapshot_id or volume_id only if using source image, snapshot or volume) source=source type (image, snapshot, volume or blank), dest=destination type of the block device (volume or local), bus=device's bus (e.g. uml, lxc, virtio, ...; if omitted, hypervisor driver chooses a suitable default, honoured only if device type is supplied) type=device type (e.g. disk, cdrom, ...; defaults to 'disk') device=name of the device (e.g. vda, xda, ...; if omitted, hypervisor driver chooses suitable device depending on selected bus; note the libvirt driver always uses default device names), size=size of the block device in MiB(for swap) and in GiB(for other formats) (if omitted, hypervisor driver calculates size), format=device will be formatted (e.g. swap, ntfs, ...; optional), bootindex=integer used for ordering the boot disks (for image backed instances it is equal to 0, for others need to be specified) and shutdown=shutdown behaviour (either preserve or remove, for local destination set to remove)."))
@utils.arg('--block-device', metavar='key1=value1[,key2=value2...]', action='append', default=[], start_version='2.32', end_version='2.32', help=_("Block device mapping with the keys: id=UUID (image_id, snapshot_id or volume_id only if using source image, snapshot or volume) source=source type (image, snapshot, volume or blank), dest=destination type of the block device (volume or local), bus=device's bus (e.g. uml, lxc, virtio, ...; if omitted, hypervisor driver chooses a suitable default, honoured only if device type is supplied) type=device type (e.g. disk, cdrom, ...; defaults to 'disk') device=name of the device (e.g. vda, xda, ...; tag=device metadata tag (optional) if omitted, hypervisor driver chooses suitable device depending on selected bus; note the libvirt driver always uses default device names), size=size of the block device in MiB(for swap) and in GiB(for other formats) (if omitted, hypervisor driver calculates size), format=device will be formatted (e.g. swap, ntfs, ...; optional), bootindex=integer used for ordering the boot disks (for image backed instances it is equal to 0, for others need to be specified) and shutdown=shutdown behaviour (either preserve or remove, for local destination set to remove)."))
@utils.arg('--block-device', metavar='key1=value1[,key2=value2...]', action='append', default=[], start_version='2.33', end_version='2.41', help=_("Block device mapping with the keys: id=UUID (image_id, snapshot_id or volume_id only if using source image, snapshot or volume) source=source type (image, snapshot, volume or blank), dest=destination type of the block device (volume or local), bus=device's bus (e.g. uml, lxc, virtio, ...; if omitted, hypervisor driver chooses a suitable default, honoured only if device type is supplied) type=device type (e.g. disk, cdrom, ...; defaults to 'disk') device=name of the device (e.g. vda, xda, ...; if omitted, hypervisor driver chooses suitable device depending on selected bus; note the libvirt driver always uses default device names), size=size of the block device in MiB(for swap) and in GiB(for other formats) (if omitted, hypervisor driver calculates size), format=device will be formatted (e.g. swap, ntfs, ...; optional), bootindex=integer used for ordering the boot disks (for image backed instances it is equal to 0, for others need to be specified) and shutdown=shutdown behaviour (either preserve or remove, for local destination set to remove)."))
@utils.arg('--block-device', metavar='key1=value1[,key2=value2...]', action='append', default=[], start_version='2.42', end_version='2.66', help=_("Block device mapping with the keys: id=UUID (image_id, snapshot_id or volume_id only if using source image, snapshot or volume) source=source type (image, snapshot, volume or blank), dest=destination type of the block device (volume or local), bus=device's bus (e.g. uml, lxc, virtio, ...; if omitted, hypervisor driver chooses a suitable default, honoured only if device type is supplied) type=device type (e.g. disk, cdrom, ...; defaults to 'disk') device=name of the device (e.g. vda, xda, ...; if omitted, hypervisor driver chooses suitable device depending on selected bus; note the libvirt driver always uses default device names), size=size of the block device in MiB(for swap) and in GiB(for other formats) (if omitted, hypervisor driver calculates size), format=device will be formatted (e.g. swap, ntfs, ...; optional), bootindex=integer used for ordering the boot disks (for image backed instances it is equal to 0, for others need to be specified), shutdown=shutdown behaviour (either preserve or remove, for local destination set to remove) and tag=device metadata tag (optional)."))
@utils.arg('--block-device', metavar='key1=value1[,key2=value2...]', action='append', default=[], start_version='2.67', help=_("Block device mapping with the keys: id=UUID (image_id, snapshot_id or volume_id only if using source image, snapshot or volume) source=source type (image, snapshot, volume or blank), dest=destination type of the block device (volume or local), bus=device's bus (e.g. uml, lxc, virtio, ...; if omitted, hypervisor driver chooses a suitable default, honoured only if device type is supplied) type=device type (e.g. disk, cdrom, ...; defaults to 'disk') device=name of the device (e.g. vda, xda, ...; if omitted, hypervisor driver chooses suitable device depending on selected bus; note the libvirt driver always uses default device names), size=size of the block device in MiB(for swap) and in GiB(for other formats) (if omitted, hypervisor driver calculates size), format=device will be formatted (e.g. swap, ntfs, ...; optional), bootindex=integer used for ordering the boot disks (for image backed instances it is equal to 0, for others need to be specified), shutdown=shutdown behaviour (either preserve or remove, for local destination set to remove) and tag=device metadata tag (optional), volume_type=type of volume to create (either ID or name) when source is blank, image or snapshot and dest is volume (optional)."))
@utils.arg('--swap', metavar='<swap_size>', default=None, help=_('Create and attach a local swap block device of <swap_size> MiB.'))
@utils.arg('--ephemeral', metavar='size=<size>[,format=<format>]', action='append', default=[], help=_('Create and attach a local ephemeral block device of <size> GiB and format it to <format>.'))
@utils.arg('--hint', action='append', dest='scheduler_hints', type=_key_value_pairing, default=[], metavar='<key=value>', help=_('Send arbitrary key/value pairs to the scheduler for custom use.'))
@utils.arg('--nic', metavar='<net-id=net-uuid,net-name=network-name,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid>', action='append', dest='nics', default=[], start_version='2.0', end_version='2.31', help=_('Create a NIC on the server. Specify option multiple times to create multiple NICs. net-id: attach NIC to network with this UUID net-name: attach NIC to network with this name (either port-id or net-id or net-name must be provided), v4-fixed-ip: IPv4 fixed address for NIC (optional), v6-fixed-ip: IPv6 fixed address for NIC (optional), port-id: attach NIC to port with this UUID (either port-id or net-id must be provided).'))
@utils.arg('--nic', metavar='<net-id=net-uuid,net-name=network-name,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid,tag=tag>', action='append', dest='nics', default=[], start_version='2.32', end_version='2.36', help=_('Create a NIC on the server. Specify option multiple times to create multiple nics. net-id: attach NIC to network with this UUID net-name: attach NIC to network with this name (either port-id or net-id or net-name must be provided), v4-fixed-ip: IPv4 fixed address for NIC (optional), v6-fixed-ip: IPv6 fixed address for NIC (optional), port-id: attach NIC to port with this UUID tag: interface metadata tag (optional) (either port-id or net-id must be provided).'))
@utils.arg('--nic', metavar='<auto,none,net-id=net-uuid,net-name=network-name,port-id=port-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr>', action='append', dest='nics', default=[], start_version='2.37', end_version='2.41', help=_("Create a NIC on the server. Specify option multiple times to create multiple nics unless using the special 'auto' or 'none' values. auto: automatically allocate network resources if none are available. This cannot be specified with any other nic value and cannot be specified multiple times. none: do not attach a NIC at all. This cannot be specified with any other nic value and cannot be specified multiple times. net-id: attach NIC to network with a specific UUID. net-name: attach NIC to network with this name (either port-id or net-id or net-name must be provided), v4-fixed-ip: IPv4 fixed address for NIC (optional), v6-fixed-ip: IPv6 fixed address for NIC (optional), port-id: attach NIC to port with this UUID (either port-id or net-id must be provided)."))
@utils.arg('--nic', metavar='<auto,none,net-id=net-uuid,net-name=network-name,port-id=port-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,tag=tag>', action='append', dest='nics', default=[], start_version='2.42', help=_("Create a NIC on the server. Specify option multiple times to create multiple nics unless using the special 'auto' or 'none' values. auto: automatically allocate network resources if none are available. This cannot be specified with any other nic value and cannot be specified multiple times. none: do not attach a NIC at all. This cannot be specified with any other nic value and cannot be specified multiple times. net-id: attach NIC to network with a specific UUID. net-name: attach NIC to network with this name (either port-id or net-id or net-name must be provided), v4-fixed-ip: IPv4 fixed address for NIC (optional), v6-fixed-ip: IPv6 fixed address for NIC (optional), port-id: attach NIC to port with this UUID tag: interface metadata tag (optional) (either port-id or net-id must be provided)."))
@utils.arg('--config-drive', metavar='<value>', dest='config_drive', default=False, help=_('Enable config drive. The value must be a boolean value.'))
@utils.arg('--poll', dest='poll', action='store_true', default=False, help=_('Report the new server boot progress until it completes.'))
@utils.arg('--admin-pass', dest='admin_pass', metavar='<value>', default=None, help=_('Admin password for the instance.'))
@utils.arg('--access-ip-v4', dest='access_ip_v4', metavar='<value>', default=None, help=_('Alternative access IPv4 of the instance.'))
@utils.arg('--access-ip-v6', dest='access_ip_v6', metavar='<value>', default=None, help=_('Alternative access IPv6 of the instance.'))
@utils.arg('--description', metavar='<description>', dest='description', default=None, help=_('Description for the server.'), start_version='2.19')
@utils.arg('--tags', metavar='<tags>', default=None, help=_('Tags for the server.Tags must be separated by commas: --tags <tag1,tag2>'), start_version='2.52')
@utils.arg('--return-reservation-id', dest='return_reservation_id', action='store_true', default=False, help=_('Return a reservation id bound to created servers.'))
@utils.arg('--trusted-image-certificate-id', metavar='<trusted-image-certificate-id>', action='append', dest='trusted_image_certificates', default=[], help=_('Trusted image certificate IDs used to validate certificates during the image signature verification process. Defaults to env[OS_TRUSTED_IMAGE_CERTIFICATE_IDS]. May be specified multiple times to pass multiple trusted image certificate IDs.'), start_version='2.63')
@utils.arg('--host', metavar='<host>', dest='host', default=None, help=_('Requested host to create servers. Admin only by default.'), start_version='2.74')
@utils.arg('--hypervisor-hostname', metavar='<hypervisor-hostname>', dest='hypervisor_hostname', default=None, help=_('Requested hypervisor hostname to create servers. Admin only by default.'), start_version='2.74')
@utils.arg('--hostname', help=_('Hostname for the instance. This sets the hostname stored in the metadata server: a utility such as cloud-init running on the guest is required to propagate these changes to the guest.'), start_version='2.90')
def do_boot(cs, args):
    """Boot a new server."""
    boot_args, boot_kwargs = _boot(cs, args)
    server = cs.servers.create(*boot_args, **boot_kwargs)
    if boot_kwargs['reservation_id']:
        new_server = {'reservation_id': server}
        utils.print_dict(new_server)
        return
    else:
        _print_server(cs, args, server)
    if args.poll:
        _poll_for_status(cs.servers.get, server.id, 'building', ['active'])