import os
import flask
from . import exceptions
from ._utils import AttributeDict
def load_dash_env_vars():
    return AttributeDict({var: os.getenv(var, os.getenv(var.lower())) for var in ('DASH_APP_NAME', 'DASH_URL_BASE_PATHNAME', 'DASH_ROUTES_PATHNAME_PREFIX', 'DASH_REQUESTS_PATHNAME_PREFIX', 'DASH_SUPPRESS_CALLBACK_EXCEPTIONS', 'DASH_ASSETS_EXTERNAL_PATH', 'DASH_INCLUDE_ASSETS_FILES', 'DASH_COMPONENTS_CACHE_MAX_AGE', 'DASH_INCLUDE_ASSETS_FILES', 'DASH_SERVE_DEV_BUNDLES', 'DASH_DEBUG', 'DASH_UI', 'DASH_PROPS_CHECK', 'DASH_HOT_RELOAD', 'DASH_HOT_RELOAD_INTERVAL', 'DASH_HOT_RELOAD_WATCH_INTERVAL', 'DASH_HOT_RELOAD_MAX_RETRY', 'DASH_SILENCE_ROUTES_LOGGING', 'DASH_PRUNE_ERRORS', 'DASH_COMPRESS', 'HOST', 'PORT')})