import cirq
def test_map_clean_and_borrowable_qubits_borrows():
    qm = cirq.ops.SimpleQubitManager()
    op = GateAllocAndBorrowInDecompose(3).on(cirq.NamedQubit('original'))
    extra = cirq.LineQubit.range(3)
    circuit = cirq.Circuit(cirq.H.on_each(*extra), cirq.Moment(op), cirq.decompose_once(op, context=cirq.DecompositionContext(qm)))
    cirq.testing.assert_has_diagram(circuit, '\n_b(0): ─────────────────────×───────────qft───×───────────\n                            │           │     │\n_b(1): ─────────────────────┼───×───────#2────┼───×───────\n                            │   │       │     │   │\n_b(2): ─────────────────────┼───┼───×───#3────┼───┼───×───\n                            │   │   │   │     │   │   │\n_c(0): ─────────────────────×───┼───┼───┼─────×───┼───┼───\n                            │   │   │   │     │   │   │\n_c(1): ─────────────────────┼───×───┼───┼─────┼───×───┼───\n                            │   │   │   │     │   │   │\n_c(2): ─────────────────────┼───┼───×───┼─────┼───┼───×───\n                            │   │   │   │     │   │   │\n0: ──────────H──────────────┼───┼───┼───┼─────┼───┼───┼───\n                            │   │   │   │     │   │   │\n1: ──────────H──────────────┼───┼───┼───┼─────┼───┼───┼───\n                            │   │   │   │     │   │   │\n2: ──────────H──────────────┼───┼───┼───┼─────┼───┼───┼───\n                            │   │   │   │     │   │   │\noriginal: ───────TestGate───@───@───@───@─────@───@───@───\n')
    allocated_circuit = cirq.map_clean_and_borrowable_qubits(circuit)
    cirq.testing.assert_has_diagram(allocated_circuit, '\n0: ───────────H──────────×───────────qft───×───────────\n                         │           │     │\n1: ───────────H──────────┼───×───────#2────┼───×───────\n                         │   │       │     │   │\n2: ───────────H──────────┼───┼───×───#3────┼───┼───×───\n                         │   │   │   │     │   │   │\nancilla_0: ──────────────×───┼───┼───┼─────×───┼───┼───\n                         │   │   │   │     │   │   │\nancilla_1: ──────────────┼───×───┼───┼─────┼───×───┼───\n                         │   │   │   │     │   │   │\nancilla_2: ──────────────┼───┼───×───┼─────┼───┼───×───\n                         │   │   │   │     │   │   │\noriginal: ────TestGate───@───@───@───@─────@───@───@───')
    decompose_func = get_decompose_func(GateAllocAndBorrowInDecompose, qm)
    allocated_and_decomposed_circuit = cirq.map_clean_and_borrowable_qubits(cirq.map_operations_and_unroll(circuit, map_func=decompose_func, raise_if_add_qubits=False))
    cirq.testing.assert_has_diagram(allocated_and_decomposed_circuit, '\n0: ───────────H───×───────────qft───×───────────×───────────qft───×───────────\n                  │           │     │           │           │     │\n1: ───────────H───┼───×───────#2────┼───×───────┼───×───────#2────┼───×───────\n                  │   │       │     │   │       │   │       │     │   │\n2: ───────────H───┼───┼───×───#3────┼───┼───×───┼───┼───×───#3────┼───┼───×───\n                  │   │   │   │     │   │   │   │   │   │   │     │   │   │\nancilla_0: ───────×───┼───┼───┼─────×───┼───┼───×───┼───┼───┼─────×───┼───┼───\n                  │   │   │   │     │   │   │   │   │   │   │     │   │   │\nancilla_1: ───────┼───×───┼───┼─────┼───×───┼───┼───×───┼───┼─────┼───×───┼───\n                  │   │   │   │     │   │   │   │   │   │   │     │   │   │\nancilla_2: ───────┼───┼───×───┼─────┼───┼───×───┼───┼───×───┼─────┼───┼───×───\n                  │   │   │   │     │   │   │   │   │   │   │     │   │   │\noriginal: ────────@───@───@───@─────@───@───@───@───@───@───@─────@───@───@───\n            ')
    allocated_and_decomposed_circuit = cirq.map_clean_and_borrowable_qubits(cirq.map_operations_and_unroll(cirq.align_left(circuit), map_func=decompose_func, raise_if_add_qubits=False))
    cirq.testing.assert_has_diagram(allocated_and_decomposed_circuit, '\n0: ───────────H───×───────#2────────×───────×───────────qft───×───────────\n                  │       │         │       │           │     │\n1: ───────────H───┼───×───#3────────┼───×───┼───×───────#2────┼───×───────\n                  │   │   │         │   │   │   │       │     │   │\n2: ───────────H───┼───┼───┼─────────┼───┼───┼───┼───×───#3────┼───┼───×───\n                  │   │   │         │   │   │   │   │   │     │   │   │\nancilla_0: ───×───┼───┼───┼─────×───┼───┼───┼───×───┼───┼─────┼───×───┼───\n              │   │   │   │     │   │   │   │   │   │   │     │   │   │\nancilla_1: ───×───┼───┼───qft───×───┼───┼───×───┼───┼───┼─────×───┼───┼───\n              │   │   │   │     │   │   │   │   │   │   │     │   │   │\nancilla_2: ───┼───×───┼───┼─────┼───×───┼───┼───┼───×───┼─────┼───┼───×───\n              │   │   │   │     │   │   │   │   │   │   │     │   │   │\nancilla_3: ───┼───┼───×───┼─────┼───┼───×───┼───┼───┼───┼─────┼───┼───┼───\n              │   │   │   │     │   │   │   │   │   │   │     │   │   │\noriginal: ────@───@───@───@─────@───@───@───@───@───@───@─────@───@───@───\n')