from sympy.core.singleton import S
from sympy.core.symbol import Symbol
from sympy.functions.elementary.exponential import log
from sympy.functions.elementary.miscellaneous import sqrt
from sympy.functions.elementary.trigonometric import sin
from sympy.plotting.textplot import textplot_str
from sympy.utilities.exceptions import ignore_warnings
def test_axes_alignment():
    x = Symbol('x')
    lines = ['      1 |                                                     ..', '        |                                                  ...  ', '        |                                                ..     ', '        |                                             ...       ', '        |                                          ...          ', '        |                                        ..             ', '        |                                     ...               ', '        |                                  ...                  ', '        |                                ..                     ', '        |                             ...                       ', '      0 |--------------------------...--------------------------', '        |                       ...                             ', '        |                     ..                                ', '        |                  ...                                  ', '        |               ...                                     ', '        |             ..                                        ', '        |          ...                                          ', '        |       ...                                             ', '        |     ..                                                ', '        |  ...                                                  ', '     -1 |_______________________________________________________', '         -1                         0                          1']
    assert lines == list(textplot_str(x, -1, 1))
    lines = ['      1 |                                                     ..', '        |                                                 ....  ', '        |                                              ...      ', '        |                                           ...         ', '        |                                       ....            ', '        |                                    ...                ', '        |                                 ...                   ', '        |                             ....                      ', '      0 |--------------------------...--------------------------', '        |                      ....                             ', '        |                   ...                                 ', '        |                ...                                    ', '        |            ....                                       ', '        |         ...                                           ', '        |      ...                                              ', '        |  ....                                                 ', '     -1 |_______________________________________________________', '         -1                         0                          1']
    assert lines == list(textplot_str(x, -1, 1, H=17))