import grpc
from . import gcs_service_pb2 as src_dot_ray_dot_protobuf_dot_gcs__service__pb2
def add_TaskInfoGcsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {'AddTaskEventData': grpc.unary_unary_rpc_method_handler(servicer.AddTaskEventData, request_deserializer=src_dot_ray_dot_protobuf_dot_gcs__service__pb2.AddTaskEventDataRequest.FromString, response_serializer=src_dot_ray_dot_protobuf_dot_gcs__service__pb2.AddTaskEventDataReply.SerializeToString), 'GetTaskEvents': grpc.unary_unary_rpc_method_handler(servicer.GetTaskEvents, request_deserializer=src_dot_ray_dot_protobuf_dot_gcs__service__pb2.GetTaskEventsRequest.FromString, response_serializer=src_dot_ray_dot_protobuf_dot_gcs__service__pb2.GetTaskEventsReply.SerializeToString)}
    generic_handler = grpc.method_handlers_generic_handler('ray.rpc.TaskInfoGcsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))