import sys
import weakref
from rdkit import Chem
from rdkit.Chem import rdChemReactions as Reactions
def testAmideRxn(self):
    m = Chem.MolFromSmiles('C1CC1C(=O)NC1OC1')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*C(=O)C1CC1' in ks)
    self.assertTrue('*NC1CO1' in ks)
    m = Chem.MolFromSmiles('C1CC1C(=O)N(C)C1OC1')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*C(=O)C1CC1' in ks)
    self.assertTrue('*N(C)C1CO1' in ks)
    m = Chem.MolFromSmiles('C1CC1C(=O)n1cccc1')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*C(=O)C1CC1' in ks)
    self.assertTrue('*n1cccc1' in ks)
    m = Chem.MolFromSmiles('C1CC1C(=O)CC1OC1')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 0)
    m = Chem.MolFromSmiles('C1CCC(=O)NC1')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 0)
    m = Chem.MolFromSmiles('CC(=O)NC')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    m = Chem.MolFromSmiles('CC(=O)N')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 0)
    m = Chem.MolFromSmiles('C(=O)NCCNC(=O)CC')
    res = RecapDecompose(m, onlyUseReactions=[1])
    self.assertTrue(res)
    self.assertTrue(len(res.children) == 4)
    self.assertTrue(len(res.GetLeaves()) == 3)