from .enums import (
from .constants import (
from ..common.utils import bytes2hex
def describe_rh_flags(x):
    return ' '.join((_DESCR_RH_FLAGS[flag] for flag in (RH_FLAGS.RHF_NONE, RH_FLAGS.RHF_QUICKSTART, RH_FLAGS.RHF_NOTPOT, RH_FLAGS.RHF_NO_LIBRARY_REPLACEMENT, RH_FLAGS.RHF_NO_MOVE, RH_FLAGS.RHF_SGI_ONLY, RH_FLAGS.RHF_GUARANTEE_INIT, RH_FLAGS.RHF_DELTA_C_PLUS_PLUS, RH_FLAGS.RHF_GUARANTEE_START_INIT, RH_FLAGS.RHF_PIXIE, RH_FLAGS.RHF_DEFAULT_DELAY_LOAD, RH_FLAGS.RHF_REQUICKSTART, RH_FLAGS.RHF_REQUICKSTARTED, RH_FLAGS.RHF_CORD, RH_FLAGS.RHF_NO_UNRES_UNDEF, RH_FLAGS.RHF_RLD_ORDER_SAFE) if x & flag))