from __future__ import absolute_import, division, print_function
import unittest
import pytest
from datashader import datashape
from datashader.datashape.util.testing import assert_dshape_equal
from datashader.datashape.parser import parse
from datashader.datashape import coretypes as ct
from datashader.datashape import DataShapeSyntaxError
def test_kiva_datashape(self):
    ds = parse("5 * var * {\n              id: int64,\n              name: string,\n              description: {\n                languages: var * string[2],\n                texts: json,\n              },\n              status: string,\n              funded_amount: float64,\n              basket_amount: json,\n              paid_amount: json,\n              image: {\n                id: int64,\n                template_id: int64,\n              },\n              video: json,\n              activity: string,\n              sector: string,\n              use: string,\n              delinquent: bool,\n              location: {\n                country_code: string[2],\n                country: string,\n                town: json,\n                geo: {\n                  level: string,\n                  pairs: string,\n                  type: string,\n                },\n              },\n              partner_id: int64,\n              posted_date: json,\n              planned_expiration_date: json,\n              loan_amount: float64,\n              currency_exchange_loss_amount: json,\n              borrowers: var * {\n                first_name: string,\n                last_name: string,\n                gender: string[1],\n                pictured: bool,\n              },\n              terms: {\n                disbursal_date: json,\n                disbursal_currency: string[3,'A'],\n                disbursal_amount: float64,\n                loan_amount: float64,\n                local_payments: var * {\n                  due_date: json,\n                  amount: float64,\n                },\n                scheduled_payments: var * {\n                  due_date: json,\n                  amount: float64,\n                },\n                loss_liability: {\n                  nonpayment: string,\n                  currency_exchange: string,\n                  currency_exchange_coverage_rate: json,\n                },\n              },\n              payments: var * {\n                amount: float64,\n                local_amount: float64,\n                processed_date: json,\n                settlement_date: json,\n                rounded_local_amount: float64,\n                currency_exchange_loss_amount: float64,\n                payment_id: int64,\n                comment: json,\n              },\n              funded_date: json,\n              paid_date: json,\n              journal_totals: {\n                entries: int64,\n                bulkEntries: int64,\n              },\n            }\n        ", self.sym)
    self.assertEqual(type(ds[-1]), ct.Record)
    self.assertEqual(len(ds[-1].names), 25)