from breezy import bedding, ignores, tests
from breezy.tests.per_workingtree import TestCaseWithWorkingTree
def test_is_ignored(self):
    tree = self.make_branch_and_tree('.')
    self.build_tree_contents([('.bzrignore', b'./rootdir\nrandomfile*\n*bar\n!bazbar\n?foo\n*.~*\ndir1/*f1\ndir1/?f2\nRE:dir2/.*\\.wombat\npath/from/ro?t\n**/piffle.py\n!b/piffle.py\nunicode\xc2\xb5\ndos\r\n\n#comment\n xx \n')])
    self._set_user_ignore_content(b'')
    self.assertEqual('./rootdir', tree.is_ignored('rootdir'))
    self.assertEqual(None, tree.is_ignored('foo/rootdir'))
    self.assertEqual(None, tree.is_ignored('rootdirtrailer'))
    self.assertEqual('randomfile*', tree.is_ignored('randomfile'))
    self.assertEqual('randomfile*', tree.is_ignored('randomfiles'))
    self.assertEqual('randomfile*', tree.is_ignored('foo/randomfiles'))
    self.assertEqual(None, tree.is_ignored('randomfil'))
    self.assertEqual(None, tree.is_ignored('foo/randomfil'))
    self.assertEqual('path/from/ro?t', tree.is_ignored('path/from/root'))
    self.assertEqual('path/from/ro?t', tree.is_ignored('path/from/roat'))
    self.assertEqual(None, tree.is_ignored('roat'))
    self.assertEqual('**/piffle.py', tree.is_ignored('piffle.py'))
    self.assertEqual('**/piffle.py', tree.is_ignored('a/piffle.py'))
    self.assertEqual(None, tree.is_ignored('b/piffle.py'))
    self.assertEqual('**/piffle.py', tree.is_ignored('foo/bar/piffle.py'))
    self.assertEqual(None, tree.is_ignored('p/iffle.py'))
    self.assertEqual('unicodeµ', tree.is_ignored('unicodeµ'))
    self.assertEqual('unicodeµ', tree.is_ignored('subdir/unicodeµ'))
    self.assertEqual(None, tree.is_ignored('unicodeå'))
    self.assertEqual(None, tree.is_ignored('unicode'))
    self.assertEqual(None, tree.is_ignored('µ'))
    self.assertEqual('dos', tree.is_ignored('dos'))
    self.assertEqual(None, tree.is_ignored('dosfoo'))
    self.assertEqual('*bar', tree.is_ignored('foobar'))
    self.assertEqual('*bar', tree.is_ignored('foo\\nbar'))
    self.assertEqual('*bar', tree.is_ignored('bar'))
    self.assertEqual('*bar', tree.is_ignored('.bar'))
    self.assertEqual(None, tree.is_ignored('bazbar'))
    self.assertEqual('?foo', tree.is_ignored('afoo'))
    self.assertEqual('?foo', tree.is_ignored('.foo'))
    self.assertEqual('*.~*', tree.is_ignored('blah.py.~1~'))
    self.assertEqual('dir1/*f1', tree.is_ignored('dir1/foof1'))
    self.assertEqual('dir1/*f1', tree.is_ignored('dir1/f1'))
    self.assertEqual('dir1/*f1', tree.is_ignored('dir1/.f1'))
    self.assertEqual('dir1/?f2', tree.is_ignored('dir1/ff2'))
    self.assertEqual('dir1/?f2', tree.is_ignored('dir1/.f2'))
    self.assertEqual('RE:dir2/.*\\.wombat', tree.is_ignored('dir2/foo.wombat'))
    self.assertEqual(None, tree.is_ignored('dir2/foo'))
    self.assertEqual(None, tree.is_ignored(''))
    self.assertEqual(None, tree.is_ignored('test/'))
    self.assertEqual(None, tree.is_ignored('#comment'))
    self.assertEqual(' xx ', tree.is_ignored(' xx '))
    self.assertEqual(' xx ', tree.is_ignored('subdir/ xx '))
    self.assertEqual(None, tree.is_ignored('xx'))
    self.assertEqual(None, tree.is_ignored('xx '))
    self.assertEqual(None, tree.is_ignored(' xx'))
    self.assertEqual(None, tree.is_ignored('subdir/xx '))