from unittest import mock
from unittest.mock import call
from osc_lib.cli import format_columns
from osc_lib import exceptions
from openstackclient.network.v2 import subnet as subnet_v2
from openstackclient.tests.unit.identity.v3 import fakes as identity_fakes_v3
from openstackclient.tests.unit.network.v2 import fakes as network_fakes
from openstackclient.tests.unit import utils as tests_utils
def _init_subnet_variables(self):
    self.project = identity_fakes_v3.FakeProject.create_one_project()
    self.domain = identity_fakes_v3.FakeDomain.create_one_domain()
    self._subnet = network_fakes.FakeSubnet.create_one_subnet(attrs={'project_id': self.project.id})
    self._subnet_pool = network_fakes.FakeSubnetPool.create_one_subnet_pool()
    self._subnet_from_pool = network_fakes.FakeSubnet.create_one_subnet(attrs={'project_id': self.project.id, 'subnetpool_id': self._subnet_pool.id, 'dns_nameservers': ['8.8.8.8', '8.8.4.4'], 'host_routes': [{'destination': '10.20.20.0/24', 'nexthop': '10.20.20.1'}, {'destination': '10.30.30.0/24', 'nexthop': '10.30.30.1'}], 'service_types': ['network:router_gateway', 'network:floatingip_agent_gateway']})
    self._subnet_ipv6 = network_fakes.FakeSubnet.create_one_subnet(attrs={'project_id': self.project.id, 'cidr': 'fe80:0:0:a00a::/64', 'enable_dhcp': True, 'dns_nameservers': ['fe80:27ff:a00a:f00f::ffff', 'fe80:37ff:a00a:f00f::ffff'], 'allocation_pools': [{'start': 'fe80::a00a:0:c0de:0:100', 'end': 'fe80::a00a:0:c0de:0:f000'}, {'start': 'fe80::a00a:0:c0de:1:100', 'end': 'fe80::a00a:0:c0de:1:f000'}], 'host_routes': [{'destination': 'fe80:27ff:a00a:f00f::/64', 'nexthop': 'fe80:27ff:a00a:f00f::1'}, {'destination': 'fe80:37ff:a00a:f00f::/64', 'nexthop': 'fe80:37ff:a00a:f00f::1'}], 'ip_version': 6, 'gateway_ip': 'fe80::a00a:0:c0de:0:1', 'ipv6_address_mode': 'slaac', 'ipv6_ra_mode': 'slaac', 'subnetpool_id': 'None', 'service_types': ['network:router_gateway', 'network:floatingip_agent_gateway']})
    self._subnet_ipv6_pd = network_fakes.FakeSubnet.create_one_subnet(attrs={'project_id': self.project.id, 'cidr': '::/64', 'enable_dhcp': True, 'allocation_pools': [{'start': '::1', 'end': '::ffff:ffff:ffff:ffff'}], 'ip_version': 6, 'gateway_ip': '::', 'ipv6_address_mode': 'slaac', 'ipv6_ra_mode': 'slaac', 'subnetpool_id': 'prefix_delegation'})
    self._network = network_fakes.create_one_network(attrs={'id': self._subnet.network_id})
    self._network_segment = network_fakes.create_one_network_segment(attrs={'network_id': self._subnet.network_id})
    self.columns = ('allocation_pools', 'cidr', 'description', 'dns_nameservers', 'enable_dhcp', 'gateway_ip', 'host_routes', 'id', 'ip_version', 'ipv6_address_mode', 'ipv6_ra_mode', 'name', 'network_id', 'project_id', 'segment_id', 'service_types', 'subnetpool_id', 'tags')
    self.data = (subnet_v2.AllocationPoolsColumn(self._subnet.allocation_pools), self._subnet.cidr, self._subnet.description, format_columns.ListColumn(self._subnet.dns_nameservers), self._subnet.enable_dhcp, self._subnet.gateway_ip, subnet_v2.HostRoutesColumn(self._subnet.host_routes), self._subnet.id, self._subnet.ip_version, self._subnet.ipv6_address_mode, self._subnet.ipv6_ra_mode, self._subnet.name, self._subnet.network_id, self._subnet.project_id, self._subnet.segment_id, format_columns.ListColumn(self._subnet.service_types), self._subnet.subnetpool_id, format_columns.ListColumn(self._subnet.tags))
    self.data_subnet_pool = (subnet_v2.AllocationPoolsColumn(self._subnet_from_pool.allocation_pools), self._subnet_from_pool.cidr, self._subnet_from_pool.description, format_columns.ListColumn(self._subnet_from_pool.dns_nameservers), self._subnet_from_pool.enable_dhcp, self._subnet_from_pool.gateway_ip, subnet_v2.HostRoutesColumn(self._subnet_from_pool.host_routes), self._subnet_from_pool.id, self._subnet_from_pool.ip_version, self._subnet_from_pool.ipv6_address_mode, self._subnet_from_pool.ipv6_ra_mode, self._subnet_from_pool.name, self._subnet_from_pool.network_id, self._subnet_from_pool.project_id, self._subnet_from_pool.segment_id, format_columns.ListColumn(self._subnet_from_pool.service_types), self._subnet_from_pool.subnetpool_id, format_columns.ListColumn(self._subnet_from_pool.tags))
    self.data_ipv6 = (subnet_v2.AllocationPoolsColumn(self._subnet_ipv6.allocation_pools), self._subnet_ipv6.cidr, self._subnet_ipv6.description, format_columns.ListColumn(self._subnet_ipv6.dns_nameservers), self._subnet_ipv6.enable_dhcp, self._subnet_ipv6.gateway_ip, subnet_v2.HostRoutesColumn(self._subnet_ipv6.host_routes), self._subnet_ipv6.id, self._subnet_ipv6.ip_version, self._subnet_ipv6.ipv6_address_mode, self._subnet_ipv6.ipv6_ra_mode, self._subnet_ipv6.name, self._subnet_ipv6.network_id, self._subnet_ipv6.project_id, self._subnet_ipv6.segment_id, format_columns.ListColumn(self._subnet_ipv6.service_types), self._subnet_ipv6.subnetpool_id, format_columns.ListColumn(self._subnet_ipv6.tags))
    self.data_ipv6_pd = (subnet_v2.AllocationPoolsColumn(self._subnet_ipv6_pd.allocation_pools), self._subnet_ipv6_pd.cidr, self._subnet_ipv6_pd.description, format_columns.ListColumn(self._subnet_ipv6_pd.dns_nameservers), self._subnet_ipv6_pd.enable_dhcp, self._subnet_ipv6_pd.gateway_ip, subnet_v2.HostRoutesColumn(self._subnet_ipv6_pd.host_routes), self._subnet_ipv6_pd.id, self._subnet_ipv6_pd.ip_version, self._subnet_ipv6_pd.ipv6_address_mode, self._subnet_ipv6_pd.ipv6_ra_mode, self._subnet_ipv6_pd.name, self._subnet_ipv6_pd.network_id, self._subnet_ipv6_pd.project_id, self._subnet_ipv6_pd.segment_id, format_columns.ListColumn(self._subnet_ipv6_pd.service_types), self._subnet_ipv6_pd.subnetpool_id, format_columns.ListColumn(self._subnet_ipv6_pd.tags))