import unittest
from nltk import tgrep
from nltk.tree import ParentedTree
def test_tokenize_link_types(self):
    """
        Test tokenization of basic link types.
        """
    self.assertEqual(tgrep.tgrep_tokenize('A<B'), ['A', '<', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>B'), ['A', '>', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<3B'), ['A', '<3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>3B'), ['A', '>3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<,B'), ['A', '<,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>,B'), ['A', '>,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<-3B'), ['A', '<-3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>-3B'), ['A', '>-3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<-B'), ['A', '<-', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>-B'), ['A', '>-', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A<'B"), ['A', "<'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A>'B"), ['A', ">'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<:B'), ['A', '<:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>:B'), ['A', '>:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<<B'), ['A', '<<', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>>B'), ['A', '>>', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<<,B'), ['A', '<<,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>>,B'), ['A', '>>,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A<<'B"), ['A', "<<'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A>>'B"), ['A', ">>'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A<<:B'), ['A', '<<:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A>>:B'), ['A', '>>:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A.B'), ['A', '.', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A,B'), ['A', ',', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A..B'), ['A', '..', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A,,B'), ['A', ',,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A$B'), ['A', '$', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A$.B'), ['A', '$.', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A$,B'), ['A', '$,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A$..B'), ['A', '$..', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A$,,B'), ['A', '$,,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<B'), ['A', '!', '<', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>B'), ['A', '!', '>', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<3B'), ['A', '!', '<3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>3B'), ['A', '!', '>3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<,B'), ['A', '!', '<,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>,B'), ['A', '!', '>,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<-3B'), ['A', '!', '<-3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>-3B'), ['A', '!', '>-3', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<-B'), ['A', '!', '<-', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>-B'), ['A', '!', '>-', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A!<'B"), ['A', '!', "<'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A!>'B"), ['A', '!', ">'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<:B'), ['A', '!', '<:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>:B'), ['A', '!', '>:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<<B'), ['A', '!', '<<', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>>B'), ['A', '!', '>>', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<<,B'), ['A', '!', '<<,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>>,B'), ['A', '!', '>>,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A!<<'B"), ['A', '!', "<<'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize("A!>>'B"), ['A', '!', ">>'", 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!<<:B'), ['A', '!', '<<:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!>>:B'), ['A', '!', '>>:', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!.B'), ['A', '!', '.', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!,B'), ['A', '!', ',', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!..B'), ['A', '!', '..', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!,,B'), ['A', '!', ',,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!$B'), ['A', '!', '$', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!$.B'), ['A', '!', '$.', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!$,B'), ['A', '!', '$,', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!$..B'), ['A', '!', '$..', 'B'])
    self.assertEqual(tgrep.tgrep_tokenize('A!$,,B'), ['A', '!', '$,,', 'B'])