from __future__ import print_function
from builtins import range
import os.path
import osqp
import datetime
def render_workspace(variables, hfname, cfname):
    """
    Print workspace dimensions
    """
    rho_vectors = variables['rho_vectors']
    data = variables['data']
    linsys_solver = variables['linsys_solver']
    scaling = variables['scaling']
    settings = variables['settings']
    embedded_flag = variables['embedded_flag']
    n = data['n']
    m = data['m']
    incFile = open(hfname, 'w')
    srcFile = open(cfname, 'w')
    fname = os.path.splitext(os.path.basename(hfname))[0]
    incGuard = fname.upper() + '_H'
    incFile.write('#ifndef %s\n' % incGuard)
    incFile.write('#define %s\n\n' % incGuard)
    now = datetime.datetime.now()
    daystr = now.strftime('%B %d, %Y')
    timestr = now.strftime('%H:%M:%S')
    incFile.write('/*\n')
    incFile.write(' * This file was autogenerated by OSQP-Python on %s at %s.\n' % (daystr, timestr))
    incFile.write(' * \n')
    incFile.write(' * This file contains the prototypes for all the workspace variables needed\n')
    incFile.write(' * by OSQP. The actual data is contained inside workspace.c.\n')
    incFile.write(' */\n\n')
    srcFile.write('/*\n')
    srcFile.write(' * This file was autogenerated by OSQP-Python on %s at %s.\n' % (daystr, timestr))
    srcFile.write(' * \n')
    srcFile.write(' * This file contains the workspace variables needed by OSQP.\n')
    srcFile.write(' */\n\n')
    incFile.write('#include "types.h"\n')
    incFile.write('#include "qdldl_interface.h"\n\n')
    srcFile.write('#include "types.h"\n')
    srcFile.write('#include "qdldl_interface.h"\n\n')
    write_data_src(srcFile, data)
    write_data_inc(incFile, data)
    write_settings_src(srcFile, settings, embedded_flag)
    write_settings_inc(incFile, settings, embedded_flag)
    write_scaling_src(srcFile, scaling)
    write_scaling_inc(incFile, scaling)
    write_linsys_solver_src(srcFile, linsys_solver, embedded_flag)
    write_linsys_solver_inc(incFile, linsys_solver, embedded_flag)
    write_solution_src(srcFile, data)
    write_solution_inc(incFile, data)
    write_info_src(srcFile)
    write_info_inc(incFile)
    write_workspace_src(srcFile, n, m, rho_vectors, embedded_flag)
    write_workspace_inc(incFile, n, m, rho_vectors, embedded_flag)
    incFile.write('#endif // ifndef %s\n' % incGuard)
    incFile.close()
    srcFile.close()