import numpy
import numpy as np
import datetime
import pytest
from numpy.testing import (
from numpy.compat import pickle
def test_timedelta_scalar_construction(self):
    assert_equal(np.timedelta64(7, 'D'), np.timedelta64(1, 'W'))
    assert_equal(np.timedelta64(120, 's'), np.timedelta64(2, 'm'))
    assert_equal(np.timedelta64(), np.timedelta64(0))
    assert_equal(np.timedelta64(None), np.timedelta64('NaT'))
    assert_equal(str(np.timedelta64('NaT')), 'NaT')
    assert_equal(repr(np.timedelta64('NaT')), "numpy.timedelta64('NaT')")
    assert_equal(str(np.timedelta64(3, 's')), '3 seconds')
    assert_equal(repr(np.timedelta64(-3, 's')), "numpy.timedelta64(-3,'s')")
    assert_equal(repr(np.timedelta64(12)), 'numpy.timedelta64(12)')
    assert_equal(np.timedelta64(12).dtype, np.dtype('m8'))
    a = np.timedelta64(2, 'h')
    b = np.array(2, dtype='m8[h]')
    assert_equal(a.dtype, np.dtype('m8[h]'))
    assert_equal(b.dtype, np.dtype('m8[h]'))
    assert_equal(np.timedelta64(a), a)
    assert_equal(np.timedelta64(a).dtype, np.dtype('m8[h]'))
    assert_equal(np.timedelta64(b), a)
    assert_equal(np.timedelta64(b).dtype, np.dtype('m8[h]'))
    assert_equal(np.timedelta64(a, 's'), a)
    assert_equal(np.timedelta64(a, 's').dtype, np.dtype('m8[s]'))
    assert_equal(np.timedelta64(b, 's'), a)
    assert_equal(np.timedelta64(b, 's').dtype, np.dtype('m8[s]'))
    assert_equal(np.timedelta64(5, 'D'), np.timedelta64(datetime.timedelta(days=5)))
    assert_equal(np.timedelta64(102347621, 's'), np.timedelta64(datetime.timedelta(seconds=102347621)))
    assert_equal(np.timedelta64(-10234760000, 'us'), np.timedelta64(datetime.timedelta(microseconds=-10234760000)))
    assert_equal(np.timedelta64(10234760000, 'us'), np.timedelta64(datetime.timedelta(microseconds=10234760000)))
    assert_equal(np.timedelta64(1023476, 'ms'), np.timedelta64(datetime.timedelta(milliseconds=1023476)))
    assert_equal(np.timedelta64(10, 'm'), np.timedelta64(datetime.timedelta(minutes=10)))
    assert_equal(np.timedelta64(281, 'h'), np.timedelta64(datetime.timedelta(hours=281)))
    assert_equal(np.timedelta64(28, 'W'), np.timedelta64(datetime.timedelta(weeks=28)))
    a = np.timedelta64(3, 's')
    assert_raises(TypeError, np.timedelta64, a, 'M')
    assert_raises(TypeError, np.timedelta64, a, 'Y')
    a = np.timedelta64(6, 'M')
    assert_raises(TypeError, np.timedelta64, a, 'D')
    assert_raises(TypeError, np.timedelta64, a, 'h')
    a = np.timedelta64(1, 'Y')
    assert_raises(TypeError, np.timedelta64, a, 'D')
    assert_raises(TypeError, np.timedelta64, a, 'm')
    a = datetime.timedelta(seconds=3)
    assert_raises(TypeError, np.timedelta64, a, 'M')
    assert_raises(TypeError, np.timedelta64, a, 'Y')
    a = datetime.timedelta(weeks=3)
    assert_raises(TypeError, np.timedelta64, a, 'M')
    assert_raises(TypeError, np.timedelta64, a, 'Y')
    a = datetime.timedelta()
    assert_raises(TypeError, np.timedelta64, a, 'M')
    assert_raises(TypeError, np.timedelta64, a, 'Y')