import shutil
import sys
from breezy import (branch, controldir, errors, info, osutils, tests, upgrade,
from breezy.bzr import bzrdir
from breezy.transport import memory
def test_info_standalone(self):
    transport = self.get_transport()
    tree1 = self.make_branch_and_tree('standalone', 'knit')
    self.build_tree(['standalone/a'])
    tree1.add('a')
    branch1 = tree1.branch
    out, err = self.run_bzr('info standalone')
    self.assertEqualDiff('Standalone tree (format: knit)\nLocation:\n  branch root: standalone\n', out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info standalone -v')
    self.assertEqualDiff('Standalone tree (format: knit)\nLocation:\n  branch root: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: Knit repository format 1\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         0 unchanged\n         0 modified\n         1 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         0 revisions\n\nRepository:\n         0 revisions\n', out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info standalone -vv')
    self.assertEqualDiff('Standalone tree (format: knit)\nLocation:\n  branch root: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: Knit repository format 1\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         0 unchanged\n         0 modified\n         1 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         0 revisions\n         0 committers\n\nRepository:\n         0 revisions\n', out)
    self.assertEqual('', err)
    tree1.commit('commit one')
    rev = branch1.repository.get_revision(branch1.last_revision())
    datestring_first = osutils.format_date(rev.timestamp, rev.timezone)
    branch2 = branch1.controldir.sprout('branch').open_branch()
    branch2.set_push_location(branch1.controldir.root_transport.base)
    out, err = self.run_bzr('info branch')
    self.assertEqualDiff('Standalone tree (format: knit)\nLocation:\n  branch root: branch\n\nRelated branches:\n    push branch: standalone\n  parent branch: standalone\n', out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info branch --verbose')
    self.assertEqualDiff('Standalone tree (format: knit)\nLocation:\n  branch root: branch\n\nRelated branches:\n    push branch: standalone\n  parent branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: Knit repository format 1\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(datestring_first, datestring_first), out)
    self.assertEqual('', err)
    branch1.controldir.sprout('bound')
    knit1_format = controldir.format_registry.make_controldir('knit')
    upgrade.upgrade('bound', knit1_format)
    branch3 = controldir.ControlDir.open('bound').open_branch()
    branch3.bind(branch1)
    bound_tree = branch3.controldir.open_workingtree()
    out, err = self.run_bzr('info -v bound')
    self.assertEqualDiff('Checkout (format: knit)\nLocation:\n       checkout root: bound\n  checkout of branch: standalone\n\nRelated branches:\n  parent branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: {}\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(bound_tree._format.get_format_description(), branch3._format.get_format_description(), branch3.repository._format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    branch4 = controldir.ControlDir.create_branch_convenience('checkout', format=knit1_format)
    branch4.bind(branch1)
    branch4.controldir.open_workingtree().update()
    out, err = self.run_bzr('info checkout --verbose')
    self.assertEqualDiff('Checkout (format: knit)\nLocation:\n       checkout root: checkout\n  checkout of branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(branch4.repository._format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    tree5 = branch1.create_checkout('lightcheckout', lightweight=True)
    branch5 = tree5.branch
    out, err = self.run_bzr('info -v lightcheckout')
    if 'metaweave' in controldir.format_registry:
        format_description = 'knit or metaweave'
    else:
        format_description = 'knit'
    self.assertEqualDiff('Lightweight checkout (format: {})\nLocation:\n  light checkout root: lightcheckout\n   checkout of branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: Knit repository format 1\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(format_description, datestring_first, datestring_first), out)
    self.assertEqual('', err)
    self.build_tree(['standalone/b'])
    tree1.add('b')
    tree1.commit('commit two')
    rev = branch1.repository.get_revision(branch1.last_revision())
    datestring_last = osutils.format_date(rev.timestamp, rev.timezone)
    out, err = self.run_bzr('info -v branch')
    self.assertEqualDiff('Standalone tree (format: knit)\nLocation:\n  branch root: branch\n\nRelated branches:\n    push branch: standalone\n  parent branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: Knit repository format 1\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(datestring_first, datestring_first), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info -v bound')
    self.assertEqualDiff('Checkout (format: knit)\nLocation:\n       checkout root: bound\n  checkout of branch: standalone\n\nRelated branches:\n  parent branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: {}\n\nControl directory:\n         1 branches\n\nBranch is out of date: missing 1 revision.\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(branch3.repository._format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info -v checkout')
    self.assertEqualDiff('Checkout (format: knit)\nLocation:\n       checkout root: checkout\n  checkout of branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: {}\n\nControl directory:\n         1 branches\n\nBranch is out of date: missing 1 revision.\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(branch4.repository._format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info lightcheckout --verbose')
    self.assertEqualDiff('Lightweight checkout (format: {})\nLocation:\n  light checkout root: lightcheckout\n   checkout of branch: standalone\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: Branch format 5\n    repository: Knit repository format 1\n\nControl directory:\n         1 branches\n\nWorking tree is out of date: missing 1 revision.\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         2 revisions\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         2 revisions\n'.format(format_description, datestring_first, datestring_last), out)
    self.assertEqual('', err)