from unittest import mock
from oslo_serialization import jsonutils
from heat.common import exception
from heat.engine import constraints
from heat.engine import function
from heat.engine.hot import functions as hot_funcs
from heat.engine.hot import parameters as hot_param
from heat.engine import parameters
from heat.engine import plugin_manager
from heat.engine import properties
from heat.engine import resources
from heat.engine import rsrc_defn
from heat.engine import support
from heat.engine import translation
from heat.tests import common
def test_schema_from_params(self):
    params_snippet = {'DBUsername': {'Type': 'String', 'Description': 'The WordPress database admin account username', 'Default': 'admin', 'MinLength': '1', 'AllowedPattern': '[a-zA-Z][a-zA-Z0-9]*', 'NoEcho': 'true', 'MaxLength': '16', 'ConstraintDescription': 'must begin with a letter and contain only alphanumeric characters.'}, 'KeyName': {'Type': 'String', 'Description': 'Name of an existing EC2 KeyPair to enable SSH access to the instances'}, 'LinuxDistribution': {'Default': 'F17', 'Type': 'String', 'Description': 'Distribution of choice', 'AllowedValues': ['F18', 'F17', 'U10', 'RHEL-6.1', 'RHEL-6.2', 'RHEL-6.3']}, 'DBPassword': {'Type': 'String', 'Description': 'The WordPress database admin account password', 'Default': 'admin', 'MinLength': '1', 'AllowedPattern': '[a-zA-Z0-9]*', 'NoEcho': 'true', 'MaxLength': '41', 'ConstraintDescription': 'must contain only alphanumeric characters.'}, 'DBName': {'AllowedPattern': '[a-zA-Z][a-zA-Z0-9]*', 'Type': 'String', 'Description': 'The WordPress database name', 'MaxLength': '64', 'Default': 'wordpress', 'MinLength': '1', 'ConstraintDescription': 'must begin with a letter and contain only alphanumeric characters.'}, 'InstanceType': {'Default': 'm1.large', 'Type': 'String', 'ConstraintDescription': 'must be a valid EC2 instance type.', 'Description': 'WebServer EC2 instance type', 'AllowedValues': ['t1.micro', 'm1.small', 'm1.large', 'm1.xlarge', 'm2.xlarge', 'm2.2xlarge', 'm2.4xlarge', 'c1.medium', 'c1.xlarge', 'cc1.4xlarge']}, 'DBRootPassword': {'Type': 'String', 'Description': 'Root password for MySQL', 'Default': 'admin', 'MinLength': '1', 'AllowedPattern': '[a-zA-Z0-9]*', 'NoEcho': 'true', 'MaxLength': '41', 'ConstraintDescription': 'must contain only alphanumeric characters.'}}
    expected = {'DBUsername': {'type': 'string', 'description': 'The WordPress database admin account username', 'required': False, 'update_allowed': True, 'immutable': False, 'constraints': [{'length': {'min': 1, 'max': 16}, 'description': 'must begin with a letter and contain only alphanumeric characters.'}, {'allowed_pattern': '[a-zA-Z][a-zA-Z0-9]*', 'description': 'must begin with a letter and contain only alphanumeric characters.'}]}, 'LinuxDistribution': {'type': 'string', 'description': 'Distribution of choice', 'required': False, 'update_allowed': True, 'immutable': False, 'constraints': [{'allowed_values': ['F18', 'F17', 'U10', 'RHEL-6.1', 'RHEL-6.2', 'RHEL-6.3']}]}, 'InstanceType': {'type': 'string', 'description': 'WebServer EC2 instance type', 'required': False, 'update_allowed': True, 'immutable': False, 'constraints': [{'allowed_values': ['t1.micro', 'm1.small', 'm1.large', 'm1.xlarge', 'm2.xlarge', 'm2.2xlarge', 'm2.4xlarge', 'c1.medium', 'c1.xlarge', 'cc1.4xlarge'], 'description': 'must be a valid EC2 instance type.'}]}, 'DBRootPassword': {'type': 'string', 'description': 'Root password for MySQL', 'required': False, 'update_allowed': True, 'immutable': False, 'constraints': [{'length': {'min': 1, 'max': 41}, 'description': 'must contain only alphanumeric characters.'}, {'allowed_pattern': '[a-zA-Z0-9]*', 'description': 'must contain only alphanumeric characters.'}]}, 'KeyName': {'type': 'string', 'description': 'Name of an existing EC2 KeyPair to enable SSH access to the instances', 'required': True, 'update_allowed': True, 'immutable': False}, 'DBPassword': {'type': 'string', 'description': 'The WordPress database admin account password', 'required': False, 'update_allowed': True, 'immutable': False, 'constraints': [{'length': {'min': 1, 'max': 41}, 'description': 'must contain only alphanumeric characters.'}, {'allowed_pattern': '[a-zA-Z0-9]*', 'description': 'must contain only alphanumeric characters.'}]}, 'DBName': {'type': 'string', 'description': 'The WordPress database name', 'required': False, 'update_allowed': True, 'immutable': False, 'constraints': [{'length': {'min': 1, 'max': 64}, 'description': 'must begin with a letter and contain only alphanumeric characters.'}, {'allowed_pattern': '[a-zA-Z][a-zA-Z0-9]*', 'description': 'must begin with a letter and contain only alphanumeric characters.'}]}}
    params = dict(((n, parameters.Schema.from_dict(n, s)) for n, s in params_snippet.items()))
    props_schemata = properties.Properties.schema_from_params(params)
    self.assertEqual(expected, dict(((n, dict(s)) for n, s in props_schemata.items())))