import math
import operator
import pyomo.common.unittest as unittest
from pyomo.core.expr.compare import assertExpressionsEqual
import pyomo.core.expr as EXPR
from pyomo.core.expr import (
from pyomo.core.expr.numeric_expr import (
from pyomo.core.expr.numvalue import NumericValue, native_types, native_numeric_types
from .test_numeric_expr_dispatcher import Base
def test_mutable_lin_iadd(self):
    mutable_lin = _MutableLinearExpression([])
    tests = [(mutable_lin, self.invalid, NotImplemented), (mutable_lin, self.asbinary, _MutableLinearExpression([self.mon_bin])), (mutable_lin, self.zero, _MutableLinearExpression([])), (mutable_lin, self.one, _MutableLinearExpression([1])), (mutable_lin, self.native, _MutableLinearExpression([5])), (mutable_lin, self.npv, _MutableLinearExpression([self.npv])), (mutable_lin, self.param, _MutableLinearExpression([6])), (mutable_lin, self.param_mut, _MutableLinearExpression([self.param_mut])), (mutable_lin, self.var, _MutableLinearExpression([self.mon_var])), (mutable_lin, self.mon_native, _MutableLinearExpression([self.mon_native])), (mutable_lin, self.mon_param, _MutableLinearExpression([self.mon_param])), (mutable_lin, self.mon_npv, _MutableLinearExpression([self.mon_npv])), (mutable_lin, self.linear, _MutableLinearExpression(self.linear.args)), (mutable_lin, self.sum, _MutableSumExpression(self.sum.args)), (mutable_lin, self.other, _MutableSumExpression([self.other])), (mutable_lin, self.mutable_l0, _MutableLinearExpression([])), (mutable_lin, self.mutable_l1, _MutableLinearExpression(self.mutable_l1.args)), (mutable_lin, self.mutable_l2, _MutableSumExpression(self.mutable_l2.args)), (mutable_lin, self.param0, _MutableLinearExpression([])), (mutable_lin, self.param1, _MutableLinearExpression([1])), (mutable_lin, self.mutable_l3, _MutableLinearExpression([self.npv]))]
    self._run_iadd_cases(tests, operator.iadd)
    mutable_lin = _MutableLinearExpression([self.mon_bin])
    tests = [(mutable_lin, self.invalid, NotImplemented), (mutable_lin, self.asbinary, _MutableLinearExpression([self.mon_bin, self.mon_bin])), (mutable_lin, self.zero, _MutableLinearExpression([self.mon_bin])), (mutable_lin, self.one, _MutableLinearExpression([self.mon_bin, 1])), (mutable_lin, self.native, _MutableLinearExpression([self.mon_bin, 5])), (mutable_lin, self.npv, _MutableLinearExpression([self.mon_bin, self.npv])), (mutable_lin, self.param, _MutableLinearExpression([self.mon_bin, 6])), (mutable_lin, self.param_mut, _MutableLinearExpression([self.mon_bin, self.param_mut])), (mutable_lin, self.var, _MutableLinearExpression([self.mon_bin, self.mon_var])), (mutable_lin, self.mon_native, _MutableLinearExpression([self.mon_bin, self.mon_native])), (mutable_lin, self.mon_param, _MutableLinearExpression([self.mon_bin, self.mon_param])), (mutable_lin, self.mon_npv, _MutableLinearExpression([self.mon_bin, self.mon_npv])), (mutable_lin, self.linear, _MutableLinearExpression([self.mon_bin] + self.linear.args)), (mutable_lin, self.sum, _MutableSumExpression([self.mon_bin] + self.sum.args)), (mutable_lin, self.other, _MutableSumExpression([self.mon_bin, self.other])), (mutable_lin, self.mutable_l0, _MutableLinearExpression([self.mon_bin])), (mutable_lin, self.mutable_l1, _MutableLinearExpression([self.mon_bin] + self.mutable_l1.args)), (mutable_lin, self.mutable_l2, _MutableSumExpression([self.mon_bin] + self.mutable_l2.args)), (mutable_lin, self.param0, _MutableLinearExpression([self.mon_bin])), (mutable_lin, self.param1, _MutableLinearExpression([self.mon_bin, 1])), (mutable_lin, self.mutable_l3, _MutableLinearExpression([self.mon_bin, self.npv]))]
    self._run_iadd_cases(tests, operator.iadd)