from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from googlecloudsdk.api_lib.firebase.test import arg_file
from googlecloudsdk.api_lib.firebase.test import arg_validate
from googlecloudsdk.api_lib.firebase.test import exceptions
from googlecloudsdk.calliope import actions
from googlecloudsdk.calliope import arg_parsers
from googlecloudsdk.calliope import base
from googlecloudsdk.core import log
import six
def AddAndroidTestArgs(parser):
    """Register args which are specific to Android test commands.

  Args:
    parser: An argparse parser used to add arguments that follow a command in
        the CLI.
  """
    parser.add_argument('--app', category=base.COMMONLY_USED_FLAGS, help='The path to the application binary file. The path may be in the local filesystem or in Google Cloud Storage using gs:// notation. Android App Bundles are specified as .aab, all other files are assumed to be APKs.')
    parser.add_argument('--app-package', action=actions.DeprecationAction('--app-package', removed=True), help='The Java package of the application under test. By default, the application package name is parsed from the APK manifest.')
    parser.add_argument('--additional-apks', type=arg_parsers.ArgList(min_length=1, max_length=100), metavar='APK', help='A list of up to 100 additional APKs to install, in addition to those being directly tested. The path may be in the local filesystem or in Google Cloud Storage using gs:// notation.')
    parser.add_argument('--auto-google-login', action='store_true', default=None, help='Automatically log into the test device using a preconfigured Google account before beginning the test. Enabled by default, use --no-auto-google-login to disable.')
    parser.add_argument('--directories-to-pull', type=arg_parsers.ArgList(), metavar='DIR_TO_PULL', help="A list of paths that will be copied from the device's storage to the designated results bucket after the test is complete. These must be absolute paths under `/sdcard`, `/storage`, or `/data/local/tmp` (for example, `--directories-to-pull /sdcard/tempDir1,/data/local/tmp/tempDir2`). Path names are restricted to the characters ```a-zA-Z0-9_-./+```. The paths `/sdcard` and `/data` will be made available and treated as implicit path substitutions. E.g. if `/sdcard` on a particular device does not map to external storage, the system will replace it with the external storage path prefix for that device. Note that access to some directories on API levels 29 and later may also be limited by scoped storage rules.")
    parser.add_argument('--environment-variables', type=arg_parsers.ArgDict(), metavar='KEY=VALUE', help='      A comma-separated, key=value map of environment variables and their\n      desired values. The environment variables are mirrored as extra options to\n      the `am instrument -e KEY1 VALUE1 ...` command and passed to your test\n      runner (typically AndroidJUnitRunner). Examples:\n\n      Enable code coverage and provide a directory to store the coverage\n      results when using Android Test Orchestrator (`--use-orchestrator`):\n\n      ```\n      --environment-variables clearPackageData=true,coverage=true,coverageFilePath=/sdcard/Download/\n      ```\n\n      Enable code coverage and provide a file path to store the coverage\n      results when *not* using Android Test Orchestrator\n      (`--no-use-orchestrator`):\n\n      ```\n      --environment-variables coverage=true,coverageFile=/sdcard/Download/coverage.ec\n      ```\n\n      Note: If you need to embed a comma into a `VALUE` string, please refer to\n      `gcloud topic escaping` for ways to change the default list delimiter.\n      ')
    parser.add_argument('--network-profile', metavar='PROFILE_ID', help='The name of the network traffic profile, for example `--network-profile=LTE`, which consists of a set of parameters to emulate network conditions when running the test (default: no network shaping; see available profiles listed by the $ {grandparent_command} network-profiles list command). This feature only works on physical devices.')
    parser.add_argument('--obb-files', type=arg_parsers.ArgList(min_length=1, max_length=2), metavar='OBB_FILE', help='A list of one or two Android OBB file names which will be copied to each test device before the tests will run (default: None). Each OBB file name must conform to the format as specified by Android (e.g. [main|patch].0300110.com.example.android.obb) and will be installed into <shared-storage>/Android/obb/<package-name>/ on the test device.')
    parser.add_argument('--other-files', type=arg_parsers.ArgDict(min_length=1), metavar='DEVICE_PATH=FILE_PATH', help='      A list of device-path=file-path pairs that indicate the device paths to\n      push files to the device before starting tests, and the paths of files to\n      push.\n\n      Device paths must be under absolute, approved paths\n      (${EXTERNAL_STORAGE}, or ${ANDROID_DATA}/local/tmp). Source file paths may\n      be in the local filesystem or in Google Cloud Storage (gs://...).\n\n      Examples:\n\n      ```\n      --other-files /sdcard/dir1/file1.txt=local/file.txt,/storage/dir2/file2.jpg=gs://bucket/file.jpg\n      ```\n\n      This flag only copies files to the device. To install files, like OBB or\n      APK files, see --obb-files and --additional-apks.\n      ')
    parser.add_argument('--performance-metrics', action='store_true', default=None, help='Monitor and record performance metrics: CPU, memory, network usage, and FPS (game-loop only). Enabled by default, use --no-performance-metrics to disable.')
    parser.add_argument('--results-history-name', help="The history name for your test results (an arbitrary string label; default: the application's label from the APK manifest). All tests which use the same history name will have their results grouped together in the Firebase console in a time-ordered test history list.")
    parser.add_argument('--robo-script', category=ANDROID_ROBO_TEST, help='The path to a Robo Script JSON file. The path may be in the local filesystem or in Google Cloud Storage using gs:// notation. You can guide the Robo test to perform specific actions by recording a Robo Script in Android Studio and then specifying this argument. Learn more at https://firebase.google.com/docs/test-lab/robo-ux-test#scripting.')
    parser.add_argument('--type', category=base.COMMONLY_USED_FLAGS, choices=['instrumentation', 'robo', 'game-loop'], help='The type of test to run.')
    parser.add_argument('--test', category=base.COMMONLY_USED_FLAGS, help='The path to the binary file containing instrumentation tests. The given path may be in the local filesystem or in Google Cloud Storage using a URL beginning with `gs://`.')
    parser.add_argument('--test-package', action=actions.DeprecationAction('--test-package', removed=True), category=ANDROID_INSTRUMENTATION_TEST, help='The Java package name of the instrumentation test. By default, the test package name is parsed from the APK manifest.')
    parser.add_argument('--test-runner-class', category=ANDROID_INSTRUMENTATION_TEST, help='The fully-qualified Java class name of the instrumentation test runner (default: the last name extracted from the APK manifest).')
    parser.add_argument('--test-targets', category=ANDROID_INSTRUMENTATION_TEST, type=arg_parsers.ArgList(min_length=1), metavar='TEST_TARGET', help='      A list of one or more test target filters to apply (default: run all test\n      targets). Each target filter must be fully qualified with the package\n      name, class name, or test annotation desired. Any test filter supported by\n      `am instrument -e ...` is supported. See\n       https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner\n       for more information. Examples:\n\n         * `--test-targets "package com.my.package.name"`\n         * `--test-targets "notPackage com.package.to.skip"`\n         * `--test-targets "class com.foo.ClassName"`\n         * `--test-targets "notClass com.foo.ClassName#testMethodToSkip"`\n         * `--test-targets "annotation com.foo.AnnotationToRun"`\n         * `--test-targets "size large notAnnotation com.foo.AnnotationToSkip"`\n      ')
    parser.add_argument('--use-orchestrator', category=ANDROID_INSTRUMENTATION_TEST, action='store_true', default=None, help='Whether each test runs in its own Instrumentation instance with the Android Test Orchestrator (default: Orchestrator is not used, same as specifying --no-use-orchestrator). Orchestrator is only compatible with AndroidJUnitRunner v1.1 or higher. See https://developer.android.com/training/testing/junit-runner.html#using-android-test-orchestrator for more information about Android Test Orchestrator.')
    parser.add_argument('--robo-directives', metavar='TYPE:RESOURCE_NAME=INPUT', category=ANDROID_ROBO_TEST, type=arg_parsers.ArgDict(), help='A comma-separated (`<type>:<key>=<value>`) map of `robo_directives` that you can use to customize the behavior of Robo test. The `type` specifies the action type of the directive, which may take on values `click`, `text` or `ignore`. If no `type` is provided, `text` will be used by default. Each key should be the Android resource name of a target UI element and each value should be the text input for that element. Values are only permitted for `text` type elements, so no value should be specified for `click` and `ignore` type elements. No more than one `click` element is allowed.\n\nTo provide custom login credentials for your app, use\n\n    --robo-directives text:username_resource=username,text:password_resource=password\n\nTo instruct Robo to click on the sign-in button, use\n\n    --robo-directives click:sign_in_button=\n\nTo instruct Robo to ignore any UI elements with resource names which equal or start with the user-defined value, use\n\n  --robo-directives ignore:ignored_ui_element_resource_name=\n\nTo learn more about Robo test and robo_directives, see https://firebase.google.com/docs/test-lab/android/command-line#custom_login_and_text_input_with_robo_test.\n\nCaution: You should only use credentials for test accounts that are not associated with real users.')
    parser.add_argument('--scenario-numbers', metavar='int', type=arg_parsers.ArgList(element_type=int, min_length=1, max_length=1024), category=ANDROID_GAME_LOOP_TEST, help='A list of game-loop scenario numbers which will be run as part of the test (default: all scenarios). A maximum of 1024 scenarios may be specified in one test matrix, but the maximum number may also be limited by the overall test *--timeout* setting.')
    parser.add_argument('--scenario-labels', metavar='LABEL', type=arg_parsers.ArgList(min_length=1), category=ANDROID_GAME_LOOP_TEST, help='A list of game-loop scenario labels (default: None). Each game-loop scenario may be labeled in the APK manifest file with one or more arbitrary strings, creating logical groupings (e.g. GPU_COMPATIBILITY_TESTS). If *--scenario-numbers* and *--scenario-labels* are specified together, Firebase Test Lab will first execute each scenario from *--scenario-numbers*. It will then expand each given scenario label into a list of scenario numbers marked with that label, and execute those scenarios.')