import base64
from datetime import datetime
from tests.unit import unittest
from tests.unit import AWSMockServiceTestCase
from boto.ec2.autoscale import AutoScaleConnection
from boto.ec2.autoscale.group import AutoScalingGroup
from boto.ec2.autoscale.policy import ScalingPolicy
from boto.ec2.autoscale.tag import Tag
from boto.ec2.blockdevicemapping import EBSBlockDeviceType, BlockDeviceMapping
from boto.ec2.autoscale import launchconfig, LaunchConfiguration
def default_body(self):
    return b'\n        <DescribeLaunchConfigurationsResponse>\n          <DescribeLaunchConfigurationsResult>\n            <LaunchConfigurations>\n              <member>\n                <AssociatePublicIpAddress>true</AssociatePublicIpAddress>\n                <SecurityGroups/>\n                <CreatedTime>2013-01-21T23:04:42.200Z</CreatedTime>\n                <KernelId/>\n                <LaunchConfigurationName>my-test-lc</LaunchConfigurationName>\n                <UserData/>\n                <InstanceType>m1.small</InstanceType>\n                <LaunchConfigurationARN>arn:aws:autoscaling:us-east-1:803981987763:launchConfiguration:9dbbbf87-6141-428a-a409-0752edbe6cad:launchConfigurationName/my-test-lc</LaunchConfigurationARN>\n                <BlockDeviceMappings>\n                  <member>\n                    <DeviceName>/dev/xvdp</DeviceName>\n                    <Ebs>\n                      <SnapshotId>snap-1234abcd</SnapshotId>\n                      <Iops>1000</Iops>\n                      <DeleteOnTermination>true</DeleteOnTermination>\n                      <VolumeType>io1</VolumeType>\n                      <VolumeSize>100</VolumeSize>\n                    </Ebs>\n                  </member>\n                  <member>\n                    <VirtualName>ephemeral1</VirtualName>\n                    <DeviceName>/dev/xvdc</DeviceName>\n                  </member>\n                  <member>\n                    <VirtualName>ephemeral0</VirtualName>\n                    <DeviceName>/dev/xvdb</DeviceName>\n                  </member>\n                  <member>\n                    <DeviceName>/dev/xvdh</DeviceName>\n                    <Ebs>\n                      <Iops>2000</Iops>\n                      <DeleteOnTermination>false</DeleteOnTermination>\n                      <VolumeType>io1</VolumeType>\n                      <VolumeSize>200</VolumeSize>\n                    </Ebs>\n                  </member>\n                </BlockDeviceMappings>\n                <ImageId>ami-514ac838</ImageId>\n                <KeyName/>\n                <RamdiskId/>\n                <InstanceMonitoring>\n                  <Enabled>true</Enabled>\n                </InstanceMonitoring>\n                <EbsOptimized>false</EbsOptimized>\n              </member>\n            </LaunchConfigurations>\n          </DescribeLaunchConfigurationsResult>\n          <ResponseMetadata>\n            <RequestId>d05a22f8-b690-11e2-bf8e-2113fEXAMPLE</RequestId>\n          </ResponseMetadata>\n        </DescribeLaunchConfigurationsResponse>\n        '