import unittest
import numpy as np
from pygsp import graphs, filters
def test_filter(self):
    Nf = 5
    g = filters.MexicanHat(self._G, Nf=Nf)
    s1 = self._rs.uniform(size=self._G.N)
    s2 = s1.reshape((self._G.N, 1))
    s3 = g.filter(s1)
    s4 = g.filter(s2)
    s5 = g.analyze(s1)
    assert s3.shape == (self._G.N, Nf)
    np.testing.assert_allclose(s3, s4)
    np.testing.assert_allclose(s3, s5)
    s1 = self._rs.uniform(size=(self._G.N, 4))
    s2 = s1.reshape((self._G.N, 4, 1))
    s3 = g.filter(s1)
    s4 = g.filter(s2)
    s5 = g.analyze(s1)
    assert s3.shape == (self._G.N, 4, Nf)
    np.testing.assert_allclose(s3, s4)
    np.testing.assert_allclose(s3, s5)
    s1 = self._rs.uniform(size=(self._G.N, Nf))
    s2 = s1.reshape((self._G.N, 1, Nf))
    s3 = g.filter(s1)
    s4 = g.filter(s2)
    s5 = g.synthesize(s1)
    assert s3.shape == (self._G.N,)
    np.testing.assert_allclose(s3, s4)
    np.testing.assert_allclose(s3, s5)
    s1 = self._rs.uniform(size=(self._G.N, 10, Nf))
    s3 = g.filter(s1)
    s5 = g.synthesize(s1)
    assert s3.shape == (self._G.N, 10)
    np.testing.assert_allclose(s3, s5)