from kivy.tests.common import GraphicUnitTest
def test_multitouch_dontappear(self):
    eventloop, win, mouse, wid = self.mouse_init()
    mouse.start()
    eventloop.add_input_provider(mouse)
    self.assertEqual(mouse.counter, 0)
    self.assertEqual(mouse.touches, {})
    win.dispatch('on_mouse_down', 10, self.correct_y(win, 10), 'left', {})
    event_id = next(iter(mouse.touches))
    win.dispatch('on_mouse_move', 11, self.correct_y(win, 11), {})
    self.assertEqual(mouse.counter, 1)
    self.assertIsNone(mouse.touches[event_id].ud.get('_drawelement'))
    win.dispatch('on_mouse_up', 10, self.correct_y(win, 10), 'left', {})
    self.assertEqual(mouse.counter, 1)
    self.assertNotIn(event_id, mouse.touches)
    self.advance_frames(1)
    self.render(wid)
    mouse.stop()
    eventloop.remove_input_provider(mouse)