from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
import ipaddress
import re
import textwrap
from googlecloudsdk.calliope import arg_parsers
from googlecloudsdk.calliope import base
from googlecloudsdk.calliope import exceptions
from googlecloudsdk.command_lib.compute import completers
from googlecloudsdk.command_lib.compute import flags
from googlecloudsdk.command_lib.compute.instance_templates import service_proxy_aux_data
def AddServiceProxyConfigArgs(parser, hide_arguments=False, release_track=base.ReleaseTrack.GA):
    """Adds service proxy configuration arguments for instance templates."""
    service_proxy_group = parser.add_group(hidden=hide_arguments)
    service_proxy_spec = {'enabled': None, 'serving-ports': str, 'proxy-port': int, 'tracing': service_proxy_aux_data.TracingState, 'access-log': str, 'network': str}
    service_proxy_help = textwrap.dedent('\n  Controls whether the Traffic Director service proxy (Envoy) and agent are\n  installed and configured on the VM. "cloud-platform" scope is enabled\n  automatically to allow connections to the Traffic Director API. Do not use\n  the --no-scopes flag.\n\n  *enabled*::: If specified, the service-proxy software will be installed when\n  the instance is created. The instance is configured to work with Traffic\n  Director.\n\n  *serving-ports*::: Semi-colon-separated (;) list of the ports, specified\n  inside quotation marks ("), on which the customer\'s application/workload\n  is serving.\n\n  For example:\n\n        serving-ports="80;8080"\n\n  The service proxy will intercept inbound traffic, then forward it to the\n  specified serving port(s) on localhost. If not provided, no incoming traffic\n  is intercepted.\n\n  *proxy-port*::: The port on which the service proxy listens.\n  The VM intercepts traffic and redirects it to this port to be handled by the\n  service proxy. If omitted, the default value is \'15001\'.\n\n  *tracing*::: Enables the service proxy to generate distributed tracing\n  information. If set to ON, the service proxy\'s control plane generates a\n  configuration that enables request ID-based tracing. For more information,\n  refer to the `generate_request_id` documentation for the Envoy proxy. Allowed\n  values are `ON` and `OFF`.\n\n  *access-log*::: The filepath for access logs sent to the service proxy by the\n  control plane. All incoming and outgoing requests are recorded in this file.\n  For more information, refer to the file access log documentation for the Envoy\n  proxy.\n\n  *network*::: The name of a valid VPC network. The Google Cloud Platform VPC\n  network used by the service proxy\'s control plane to generate dynamic\n  configuration for the service proxy.\n  ')
    if release_track == base.ReleaseTrack.ALPHA:
        service_proxy_spec.update({'intercept-dns': None, 'source': str})
        service_proxy_help += textwrap.dedent('\n    *intercept-dns*::: Enables interception of UDP traffic by the service proxy.\n\n    *source*::: The Google Cloud Storage bucket location source\n    for the Envoy. The service-proxy-agent will download the archive from Envoy\n    and install it on the virtual machine, unpacking it into the root (/)\n    directory of the virtual machine. Therefore, the archive must contain not\n    only the executable and license files but they must be located in the\n    correct directories within the archive. For example:\n    /usr/local/bin/envoy and /usr/local/doc/envoy-LICENSE\n    ')
    if release_track == base.ReleaseTrack.ALPHA or release_track == base.ReleaseTrack.BETA:
        service_proxy_spec.update({'intercept-all-outbound-traffic': None, 'exclude-outbound-ip-ranges': str, 'exclude-outbound-port-ranges': str, 'scope': str, 'mesh': str, 'project-number': str})
        service_proxy_help += textwrap.dedent('\n    *intercept-all-outbound-traffic*::: Enables interception of all outgoing\n    traffic. The traffic is intercepted by the service proxy and then redirected\n    to external host.\n\n    *exclude-outbound-ip-ranges*::: Semi-colon-separated (;) list of the IPs or\n    CIDRs, specified inside quotation marks ("), that should be excluded from\n    redirection. Only applies when `intercept-all-outbound-traffic` flag is set.\n\n    For example:\n\n         exclude-outbound-ip-ranges="8.8.8.8;129.168.10.0/24"\n\n    *exclude-outbound-port-ranges*::: Semi-colon-separated (;) list of the ports\n    or port ranges, specified inside quotation marks ("), that should be\n    excluded from redirection. Only applies when\n    `intercept-all-outbound-traffic` flag is set.\n\n    For example:\n\n         exclude-outbound-port-ranges="81;8080-8090"\n\n    *scope*::: Scope defines a logical configuration boundary for a Gateway\n    resource. On VM boot up, the service proxy reaches the Traffic Director to\n    retrieve routing information that corresponds to the routes attached to the\n    gateway with this scope name. When scope is specified, the network value is\n    ignored. You cannot specify `scope` and `mesh` values at the same time.\n\n    *mesh*::: Mesh defines a logical configuration boundary for a Mesh resource.\n    On VM boot up, the service proxy reaches the Traffic Director to retrieve\n    routing information that corresponds to the routes attached to the mesh with\n    this mesh name. When mesh is specified, the network value is ignored. You\n    cannot specify `scope` and `mesh` values at the same time.\n\n    *project-number*::: Project number defines the project where Mesh and\n    Gateway resources are created. If not specified, the project where the\n    instance exists is used.\n    ')
    service_proxy_group.add_argument('--service-proxy', type=arg_parsers.ArgDict(spec=service_proxy_spec, allow_key_only=True, required_keys=['enabled']), hidden=hide_arguments, help=service_proxy_help)
    service_proxy_group.add_argument('--service-proxy-labels', metavar='KEY=VALUE, ...', type=arg_parsers.ArgDict(), hidden=hide_arguments, help="      Labels that you can apply to your service proxy. These will be reflected in your Envoy proxy's bootstrap metadata.\n      These can be any `key=value` pairs that you want to set as proxy metadata (for example, for use with config filtering).\n      You might use these flags for application and version labels: `app=review` and/or `version=canary`.\n      ")
    service_proxy_group.add_argument('--service-proxy-agent-location', metavar='LOCATION', hidden=True, help='      GCS bucket location of service-proxy-agent. Mainly used for testing and development.\n      ')
    service_proxy_group.add_argument('--service-proxy-xds-version', type=int, hidden=True, help='      xDS version of the service proxy to be installed.\n      ')