import pyomo.common.unittest as unittest
from pyomo.common.log import LoggingIntercept
from pyomo.common.dependencies import numpy, numpy_available
from pyomo.core.expr.compare import assertExpressionsEqual
from pyomo.core.expr.numeric_expr import LinearExpression, MonomialTermExpression
from pyomo.core.expr import Expr_if, inequality, LinearExpression, NPV_SumExpression
import pyomo.repn.linear as linear
from pyomo.repn.linear import LinearRepn, LinearRepnVisitor
from pyomo.repn.util import InvalidNumber
from pyomo.environ import (
def test_npv(self):
    m = ConcreteModel()
    m.p = Param(mutable=True, initialize=4)
    nested_expr = 1 / m.p
    pow_expr = m.p ** 0.5
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(nested_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(repn.constant, 1 / 4)
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(pow_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(repn.constant, 2)
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    m.p = 0
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(nested_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(str(repn.constant), 'InvalidNumber(nan)')
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(pow_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(repn.constant, 0)
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    m.p = -1
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(nested_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(repn.constant, -1)
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(pow_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertStructuredAlmostEqual(repn.constant, InvalidNumber(1j))
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    m.p = None
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(nested_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(repn.constant, InvalidNumber(None))
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)
    cfg = VisitorConfig()
    repn = LinearRepnVisitor(*cfg).walk_expression(pow_expr)
    self.assertEqual(cfg.subexpr, {})
    self.assertEqual(cfg.var_map, {})
    self.assertEqual(cfg.var_order, {})
    self.assertEqual(repn.multiplier, 1)
    self.assertEqual(repn.constant, InvalidNumber(None))
    self.assertEqual(repn.linear, {})
    self.assertEqual(repn.nonlinear, None)