from math import fabs
from pyomo.environ import value
def check_8PP_logical_solution(self, eight_process, results):
    self.assertTrue(fabs(value(eight_process.profit.expr) - 68) <= 0.01)
    self.assertTrue(fabs(value(results.problem.upper_bound) - 68) <= 0.01)
    self.assertTrue(value(eight_process.use_unit[2].indicator_var))
    self.assertFalse(value(eight_process.no_unit[2].indicator_var))
    self.assertTrue(value(eight_process.use_unit[4].indicator_var))
    self.assertFalse(value(eight_process.no_unit[4].indicator_var))
    self.assertTrue(value(eight_process.use_unit[6].indicator_var))
    self.assertFalse(value(eight_process.no_unit[6].indicator_var))
    self.assertTrue(value(eight_process.use_unit[8].indicator_var))
    self.assertFalse(value(eight_process.no_unit[8].indicator_var))
    self.assertFalse(value(eight_process.use_unit[1].indicator_var))
    self.assertTrue(value(eight_process.no_unit[1].indicator_var))
    self.assertFalse(value(eight_process.use_unit[3].indicator_var))
    self.assertTrue(value(eight_process.no_unit[3].indicator_var))
    self.assertFalse(value(eight_process.use_unit[5].indicator_var))
    self.assertTrue(value(eight_process.no_unit[5].indicator_var))
    self.assertFalse(value(eight_process.use_unit[7].indicator_var))
    self.assertTrue(value(eight_process.no_unit[7].indicator_var))