from prov.model import ProvDocument, Namespace, Literal, PROV, Identifier
import datetime
def primer_example_alternate():
    g = ProvDocument(namespaces={'ex': 'http://example/', 'dcterms': 'http://purl.org/dc/terms/', 'foaf': 'http://xmlns.com/foaf/0.1/'})
    article = g.entity('ex:article', {'dcterms:title': 'Crime rises in cities'})
    articleV1 = g.entity('ex:articleV1')
    articleV2 = g.entity('ex:articleV2')
    dataSet1 = g.entity('ex:dataSet1')
    dataSet2 = g.entity('ex:dataSet2')
    regionList = g.entity('ex:regionList')
    composition = g.entity('ex:composition')
    chart1 = g.entity('ex:chart1')
    chart2 = g.entity('ex:chart2')
    blogEntry = g.entity('ex:blogEntry')
    compile = g.activity('ex:compile')
    compile2 = g.activity('ex:compile2')
    compose = g.activity('ex:compose')
    correct = g.activity('ex:correct', '2012-03-31T09:21:00', '2012-04-01T15:21:00')
    illustrate = g.activity('ex:illustrate')
    compose.used(dataSet1, attributes={'prov:role': 'ex:dataToCompose'})
    compose.used(regionList, attributes={'prov:role': 'ex:regionsToAggregateBy'})
    composition.wasGeneratedBy(compose)
    illustrate.used(composition)
    chart1.wasGeneratedBy(illustrate)
    chart1.wasGeneratedBy(compile, '2012-03-02T10:30:00')
    derek = g.agent('ex:derek', {'prov:type': PROV['Person'], 'foaf:givenName': 'Derek', 'foaf:mbox': '<mailto:derek@example.org>'})
    compose.wasAssociatedWith(derek)
    illustrate.wasAssociatedWith(derek)
    chartgen = g.agent('ex:chartgen', {'prov:type': PROV['Organization'], 'foaf:name': 'Chart Generators Inc'})
    derek.actedOnBehalfOf(chartgen, compose)
    chart1.wasAttributedTo(derek)
    dataSet2.wasGeneratedBy(correct)
    correct.used(dataSet1)
    dataSet2.wasDerivedFrom(dataSet1, attributes={'prov:type': PROV['Revision']})
    chart2.wasDerivedFrom(dataSet2)
    blogEntry.wasDerivedFrom(article, attributes={'prov:type': PROV['Quotation']})
    articleV1.specializationOf(article)
    articleV1.wasDerivedFrom(dataSet1)
    articleV2.specializationOf(article)
    articleV2.wasDerivedFrom(dataSet2)
    articleV2.alternateOf(articleV1)
    return g