from numpy.testing import (assert_array_equal, assert_array_almost_equal)
from scipy.interpolate import pade
def test_pade_4term_exp():
    an = [1.0, 1.0, 0.5, 1.0 / 6]
    nump, denomp = pade(an, 0)
    assert_array_almost_equal(nump.c, [1.0 / 6, 0.5, 1.0, 1.0])
    assert_array_almost_equal(denomp.c, [1.0])
    nump, denomp = pade(an, 1)
    assert_array_almost_equal(nump.c, [1.0 / 6, 2.0 / 3, 1.0])
    assert_array_almost_equal(denomp.c, [-1.0 / 3, 1.0])
    nump, denomp = pade(an, 2)
    assert_array_almost_equal(nump.c, [1.0 / 3, 1.0])
    assert_array_almost_equal(denomp.c, [1.0 / 6, -2.0 / 3, 1.0])
    nump, denomp = pade(an, 3)
    assert_array_almost_equal(nump.c, [1.0])
    assert_array_almost_equal(denomp.c, [-1.0 / 6, 0.5, -1.0, 1.0])
    nump, denomp = pade(an, 0, 3)
    assert_array_almost_equal(nump.c, [1.0 / 6, 0.5, 1.0, 1.0])
    assert_array_almost_equal(denomp.c, [1.0])
    nump, denomp = pade(an, 1, 2)
    assert_array_almost_equal(nump.c, [1.0 / 6, 2.0 / 3, 1.0])
    assert_array_almost_equal(denomp.c, [-1.0 / 3, 1.0])
    nump, denomp = pade(an, 2, 1)
    assert_array_almost_equal(nump.c, [1.0 / 3, 1.0])
    assert_array_almost_equal(denomp.c, [1.0 / 6, -2.0 / 3, 1.0])
    nump, denomp = pade(an, 3, 0)
    assert_array_almost_equal(nump.c, [1.0])
    assert_array_almost_equal(denomp.c, [-1.0 / 6, 0.5, -1.0, 1.0])
    nump, denomp = pade(an, 0, 2)
    assert_array_almost_equal(nump.c, [0.5, 1.0, 1.0])
    assert_array_almost_equal(denomp.c, [1.0])
    nump, denomp = pade(an, 1, 1)
    assert_array_almost_equal(nump.c, [1.0 / 2, 1.0])
    assert_array_almost_equal(denomp.c, [-1.0 / 2, 1.0])
    nump, denomp = pade(an, 2, 0)
    assert_array_almost_equal(nump.c, [1.0])
    assert_array_almost_equal(denomp.c, [1.0 / 2, -1.0, 1.0])