import sys
import numpy as np
from numpy.core._rational_tests import rational
import pytest
from numpy.testing import (
def test_array_array():
    tobj = type(object)
    ones11 = np.ones((1, 1), np.float64)
    tndarray = type(ones11)
    assert_equal(np.array(ones11, dtype=np.float64), ones11)
    if HAS_REFCOUNT:
        old_refcount = sys.getrefcount(tndarray)
        np.array(ones11)
        assert_equal(old_refcount, sys.getrefcount(tndarray))
    assert_equal(np.array(None, dtype=np.float64), np.array(np.nan, dtype=np.float64))
    if HAS_REFCOUNT:
        old_refcount = sys.getrefcount(tobj)
        np.array(None, dtype=np.float64)
        assert_equal(old_refcount, sys.getrefcount(tobj))
    assert_equal(np.array(1.0, dtype=np.float64), np.ones((), dtype=np.float64))
    if HAS_REFCOUNT:
        old_refcount = sys.getrefcount(np.float64)
        np.array(np.array(1.0, dtype=np.float64), dtype=np.float64)
        assert_equal(old_refcount, sys.getrefcount(np.float64))
    S2 = np.dtype((bytes, 2))
    S3 = np.dtype((bytes, 3))
    S5 = np.dtype((bytes, 5))
    assert_equal(np.array(b'1.0', dtype=np.float64), np.ones((), dtype=np.float64))
    assert_equal(np.array(b'1.0').dtype, S3)
    assert_equal(np.array(b'1.0', dtype=bytes).dtype, S3)
    assert_equal(np.array(b'1.0', dtype=S2), np.array(b'1.'))
    assert_equal(np.array(b'1', dtype=S5), np.ones((), dtype=S5))
    U2 = np.dtype((str, 2))
    U3 = np.dtype((str, 3))
    U5 = np.dtype((str, 5))
    assert_equal(np.array('1.0', dtype=np.float64), np.ones((), dtype=np.float64))
    assert_equal(np.array('1.0').dtype, U3)
    assert_equal(np.array('1.0', dtype=str).dtype, U3)
    assert_equal(np.array('1.0', dtype=U2), np.array(str('1.')))
    assert_equal(np.array('1', dtype=U5), np.ones((), dtype=U5))
    builtins = getattr(__builtins__, '__dict__', __builtins__)
    assert_(hasattr(builtins, 'get'))
    dat = np.array(memoryview(b'1.0'), dtype=np.float64)
    assert_equal(dat, [49.0, 46.0, 48.0])
    assert_(dat.dtype.type is np.float64)
    dat = np.array(memoryview(b'1.0'))
    assert_equal(dat, [49, 46, 48])
    assert_(dat.dtype.type is np.uint8)
    a = np.array(100.0, dtype=np.float64)
    o = type('o', (object,), dict(__array_interface__=a.__array_interface__))
    assert_equal(np.array(o, dtype=np.float64), a)
    a = np.array([(1, 4.0, 'Hello'), (2, 6.0, 'World')], dtype=[('f0', int), ('f1', float), ('f2', str)])
    o = type('o', (object,), dict(__array_struct__=a.__array_struct__))
    assert_equal(bytes(np.array(o).data), bytes(a.data))
    o = type('o', (object,), dict(__array__=lambda *x: np.array(100.0, dtype=np.float64)))()
    assert_equal(np.array(o, dtype=np.float64), np.array(100.0, np.float64))
    nested = 1.5
    for i in range(np.MAXDIMS):
        nested = [nested]
    np.array(nested)
    assert_raises(ValueError, np.array, [nested], dtype=np.float64)
    assert_equal(np.array([None] * 10, dtype=np.float32), np.full((10,), np.nan, dtype=np.float32))
    assert_equal(np.array([[None]] * 10, dtype=np.float32), np.full((10, 1), np.nan, dtype=np.float32))
    assert_equal(np.array([[None] * 10], dtype=np.float32), np.full((1, 10), np.nan, dtype=np.float32))
    assert_equal(np.array([[None] * 10] * 10, dtype=np.float32), np.full((10, 10), np.nan, dtype=np.float32))
    assert_equal(np.array([None] * 10, dtype=np.float64), np.full((10,), np.nan, dtype=np.float64))
    assert_equal(np.array([[None]] * 10, dtype=np.float64), np.full((10, 1), np.nan, dtype=np.float64))
    assert_equal(np.array([[None] * 10], dtype=np.float64), np.full((1, 10), np.nan, dtype=np.float64))
    assert_equal(np.array([[None] * 10] * 10, dtype=np.float64), np.full((10, 10), np.nan, dtype=np.float64))
    assert_equal(np.array([1.0] * 10, dtype=np.float64), np.ones((10,), dtype=np.float64))
    assert_equal(np.array([[1.0]] * 10, dtype=np.float64), np.ones((10, 1), dtype=np.float64))
    assert_equal(np.array([[1.0] * 10], dtype=np.float64), np.ones((1, 10), dtype=np.float64))
    assert_equal(np.array([[1.0] * 10] * 10, dtype=np.float64), np.ones((10, 10), dtype=np.float64))
    assert_equal(np.array((None,) * 10, dtype=np.float64), np.full((10,), np.nan, dtype=np.float64))
    assert_equal(np.array([(None,)] * 10, dtype=np.float64), np.full((10, 1), np.nan, dtype=np.float64))
    assert_equal(np.array([(None,) * 10], dtype=np.float64), np.full((1, 10), np.nan, dtype=np.float64))
    assert_equal(np.array([(None,) * 10] * 10, dtype=np.float64), np.full((10, 10), np.nan, dtype=np.float64))
    assert_equal(np.array((1.0,) * 10, dtype=np.float64), np.ones((10,), dtype=np.float64))
    assert_equal(np.array([(1.0,)] * 10, dtype=np.float64), np.ones((10, 1), dtype=np.float64))
    assert_equal(np.array([(1.0,) * 10], dtype=np.float64), np.ones((1, 10), dtype=np.float64))
    assert_equal(np.array([(1.0,) * 10] * 10, dtype=np.float64), np.ones((10, 10), dtype=np.float64))