from weakref import proxy
import copy
import pickle
import regex
import string
import sys
import unittest
def test_hg_bugs(self):
    self.assertEqual(bool(regex.compile('(?>b)', flags=regex.V1)), True)
    self.assertEqual(bool(regex.compile('^((?>\\w+)|(?>\\s+))*$', flags=regex.V1)), True)
    self.assertEqual(regex.findall('\\((?:(?>[^()]+)|(?R))*\\)', 'a(bcd(e)f)g(h)'), ['(bcd(e)f)', '(h)'])
    self.assertEqual(regex.findall('\\((?:(?:[^()]+)|(?R))*\\)', 'a(bcd(e)f)g(h)'), ['(bcd(e)f)', '(h)'])
    self.assertEqual(regex.findall('\\((?:(?>[^()]+)|(?R))*\\)', 'a(b(cd)e)f)g)h'), ['(b(cd)e)'])
    self.assertEqual(regex.findall('\\((?:(?>[^()]+)|(?R))*\\)', 'a(bc(d(e)f)gh'), ['(d(e)f)'])
    self.assertEqual(regex.findall('(?r)\\((?:(?>[^()]+)|(?R))*\\)', 'a(bc(d(e)f)gh'), ['(d(e)f)'])
    self.assertEqual([m.group() for m in regex.finditer('\\((?:[^()]*+|(?0))*\\)', 'a(b(c(de)fg)h')], ['(c(de)fg)'])
    self.assertEqual(regex.search('a(bc)d', 'abcd', regex.I | regex.V1).group(0), 'abcd')
    self.assertEqual(regex.search('([\\da-f:]+)$', 'E', regex.I | regex.V1).group(0), 'E')
    self.assertEqual(regex.search('([\\da-f:]+)$', 'e', regex.I | regex.V1).group(0), 'e')
    self.assertEqual(regex.search('^(?=ab(de))(abd)(e)', 'abde').groups(), ('de', 'abd', 'e'))
    self.assertEqual(bool(regex.match('\\ ', ' ', flags=regex.X)), True)
    self.assertEqual(regex.search('^(a|)\\1{2}b', 'b').group(0, 1), ('b', ''))
    self.assertEqual(regex.search('^(a){0,0}', 'abc').group(0, 1), ('', None))
    self.assertEqual(regex.search('(?>.*/)b', 'a/b').group(0), 'a/b')
    self.assertEqual(regex.search('((?i)blah)\\s+\\1', 'blah BLAH'), None)
    self.assertEqual(regex.search('(\\()?[^()]+(?(1)\\)|)', '(abcd').group(0), 'abcd')
    self.assertEqual(regex.search('(a*)*', 'a').span(1), (1, 1))
    self.assertEqual(regex.search('(a*)*', 'aa').span(1), (2, 2))
    self.assertEqual(regex.search('(a*)*', 'aaa').span(1), (3, 3))
    self.assertEqual(regex.search('a(?#xxx)*', 'aaa').group(), 'aaa')
    self.assertEqual(regex.search('(?=abc){3}abc', 'abcabcabc').span(), (0, 3))
    self.assertEqual(regex.search('^(?:a(?:(?:))+)+', 'a').span(), (0, 1))
    self.assertEqual(regex.search('^(?:a(?:(?:))+)+', 'aa').span(), (0, 2))
    self.assertEqual(regex.search('a(?x: b c )d', 'abcd').group(0), 'abcd')
    self.assertEqual(regex.search('a#comment\n*', 'aaa', flags=regex.X).group(0), 'aaa')
    self.assertEqual(regex.search('(?V1)(a(?(1)\\1)){1}', 'aaaaaaaaaa').span(0, 1), ((0, 1), (0, 1)))
    self.assertEqual(regex.search('(?V1)(a(?(1)\\1)){2}', 'aaaaaaaaaa').span(0, 1), ((0, 3), (1, 3)))
    self.assertEqual(regex.search('(?V1)(a(?(1)\\1)){3}', 'aaaaaaaaaa').span(0, 1), ((0, 6), (3, 6)))
    self.assertEqual(regex.search('(?V1)(a(?(1)\\1)){4}', 'aaaaaaaaaa').span(0, 1), ((0, 10), (6, 10)))
    self.assertEqual(regex.search('(?V1)(a)(?<=b(?1))', 'baz').group(0), 'a')
    self.assertEqual(regex.findall('(?fi)\\L<keywords>', 'POST, Post, post, poſt, poﬆ, and poﬅ', keywords=['post', 'pos']), ['POST', 'Post', 'post', 'poſt', 'poﬆ', 'poﬅ'])
    self.assertEqual(regex.findall('(?fi)pos|post', 'POST, Post, post, poſt, poﬆ, and poﬅ'), ['POS', 'Pos', 'pos', 'poſ', 'poﬆ', 'poﬅ'])
    self.assertEqual(regex.findall('(?fi)post|pos', 'POST, Post, post, poſt, poﬆ, and poﬅ'), ['POST', 'Post', 'post', 'poſt', 'poﬆ', 'poﬅ'])
    self.assertEqual(regex.findall('(?fi)post|another', 'POST, Post, post, poſt, poﬆ, and poﬅ'), ['POST', 'Post', 'post', 'poſt', 'poﬆ', 'poﬅ'])
    self.assertEqual(regex.search('(?V1)((a)(?1)|(?2))', 'a').group(0, 1, 2), ('a', 'a', None))
    self.assertEqual(regex.search('(?V1)(\\1xx|){6}', 'xx').span(0, 1), ((0, 2), (2, 2)))
    self.assertEqual(regex.search('(a|)+', 'a').group(0, 1), ('a', ''))
    self.assertEqual(regex.search('(a|)*\\d', 'a' * 80), None)
    self.assertEqual(regex.search('^(?:a?b?)*$', 'ac'), None)
    self.assertRaisesRegex(regex.error, self.UNDEF_CHAR_NAME, lambda: regex.compile('\\N{1}'))
    self.assertEqual(regex.search('\\Z', 'a\na\n').span(0), (4, 4))
    self.assertEqual(regex.search('(q1|.)*(q2|.)*(x(a|bc)*y){2,}', 'xayxay').group(0), 'xayxay')
    self.assertEqual(regex.search('(?i)[^a]', 'A'), None)
    self.assertEqual(regex.search('(?i)[[:ascii:]]', 'K'), None)
    self.assertEqual(regex.search('((a|b(?1)c){3,5})', 'baaaaca').group(0, 1, 2), ('aaaa', 'aaaa', 'a'))
    self.assertEqual(regex.findall('(?<=:\\S+ )\\w+', ':9 abc :10 def'), ['abc', 'def'])
    self.assertEqual(regex.findall('(?<=:\\S* )\\w+', ':9 abc :10 def'), ['abc', 'def'])
    self.assertEqual(regex.findall('(?<=:\\S+? )\\w+', ':9 abc :10 def'), ['abc', 'def'])
    self.assertEqual(regex.findall('(?<=:\\S*? )\\w+', ':9 abc :10 def'), ['abc', 'def'])
    self.assertEqual(regex.search('(?:fe)?male', 'female').group(), 'female')
    self.assertEqual([m.group() for m in regex.finditer('(fe)?male: h(?(1)(er)|(is)) (\\w+)', 'female: her dog; male: his cat. asdsasda')], ['female: her dog', 'male: his cat'])
    self.assertEqual(regex.search('(?<rec>\\((?:[^()]++|(?&rec))*\\))', 'aaa(((1+0)+1)+1)bbb').captures('rec'), ['(1+0)', '((1+0)+1)', '(((1+0)+1)+1)'])
    self.assertRaisesRegex(regex.error, self.BAD_ESCAPE, lambda: regex.sub('x', '\\', 'x'))
    fz = '(CAGCCTCCCATTTCAGAATATACATCC){1<e<=2}'
    seq = 'tcagacgagtgcgttgtaaaacgacggccagtCAGCCTCCCATTCAGAATATACATCCcgacggccagttaaaaacaatgccaaggaggtcatagctgtttcctgccagttaaaaacaatgccaaggaggtcatagctgtttcctgacgcactcgtctgagcgggctggcaagg'
    self.assertEqual(regex.search(fz, seq, regex.BESTMATCH)[0], 'tCAGCCTCCCATTCAGAATATACATCC')
    self.assertEqual(regex.findall('c..+/c', 'cA/c\ncAb/c'), ['cAb/c'])
    self.assertEqual(ascii(regex.sub('(\\w+)', '[\\1]', 'अन्\u200dन ന്\u200d किन', regex.WORD)), ascii('[अन्\u200dन] [ന്\u200d] [किन]'))
    self.assertEqual(regex.match('.*a.*ba.*aa', 'ababba'), None)
    self.assertEqual(regex.match('(?<x>a(?<x>b))', 'ab').spans('x'), [(1, 2), (0, 2)])
    self.assertEqual(regex.sub('(-)', lambda m: m.expand('x'), 'a-b-c'), 'axbxc')
    rx = regex.compile('\\bt(est){i<2}', flags=regex.V1)
    self.assertEqual(rx.search('Some text'), None)
    self.assertEqual(rx.findall('Some text'), [])
    self.assertRaisesRegex(regex.error, self.MULTIPLE_REPEAT, lambda: regex.compile('.???'))
    self.assertEqual(regex.escape('foo!?', special_only=False), 'foo\\!\\?')
    self.assertEqual(regex.escape('foo!?', special_only=True), 'foo!\\?')
    self.assertEqual(regex.escape('foo!?'), 'foo!\\?')
    self.assertEqual(regex.escape(b'foo!?', special_only=False), b'foo\\!\\?')
    self.assertEqual(regex.escape(b'foo!?', special_only=True), b'foo!\\?')
    self.assertEqual(regex.escape(b'foo!?'), b'foo!\\?')
    self.assertEqual(regex.search('^([^z]*(?:WWWi|W))?$', 'WWWi').groups(), ('WWWi',))
    self.assertEqual(regex.search('^([^z]*(?:WWWi|w))?$', 'WWWi').groups(), ('WWWi',))
    self.assertEqual(regex.search('^([^z]*?(?:WWWi|W))?$', 'WWWi').groups(), ('WWWi',))
    pat = regex.compile('xxx', flags=regex.FULLCASE | regex.UNICODE)
    self.assertEqual([x.group() for x in pat.finditer('yxxx')], ['xxx'])
    self.assertEqual(pat.findall('yxxx'), ['xxx'])
    raw = 'yxxx'
    self.assertEqual([x.group() for x in pat.finditer(raw)], ['xxx'])
    self.assertEqual(pat.findall(raw), ['xxx'])
    pat = regex.compile('xxx', flags=regex.FULLCASE | regex.IGNORECASE | regex.UNICODE)
    self.assertEqual([x.group() for x in pat.finditer('yxxx')], ['xxx'])
    self.assertEqual(pat.findall('yxxx'), ['xxx'])
    raw = 'yxxx'
    self.assertEqual([x.group() for x in pat.finditer(raw)], ['xxx'])
    self.assertEqual(pat.findall(raw), ['xxx'])
    if sys.version_info >= (3, 7, 0):
        self.assertEqual(regex.sub('(?V0).*', 'x', 'test'), 'xx')
    else:
        self.assertEqual(regex.sub('(?V0).*', 'x', 'test'), 'x')
    self.assertEqual(regex.sub('(?V1).*', 'x', 'test'), 'xx')
    if sys.version_info >= (3, 7, 0):
        self.assertEqual(regex.sub('(?V0).*?', '|', 'test'), '|||||||||')
    else:
        self.assertEqual(regex.sub('(?V0).*?', '|', 'test'), '|t|e|s|t|')
    self.assertEqual(regex.sub('(?V1).*?', '|', 'test'), '|||||||||')
    self.assertEqual(regex.sub('^(@)\\n(?!.*?@)(.*)', '\\1\\n==========\\n\\2', '@\n', flags=regex.DOTALL), '@\n==========\n')
    self.assertEqual(regex.match('(?:cats|cat){e<=1}', 'caz').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?e)(?:cats|cat){e<=1}', 'caz').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?b)(?:cats|cat){e<=1}', 'caz').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?:cat){e<=1}', 'caz').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?e)(?:cat){e<=1}', 'caz').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?b)(?:cat){e<=1}', 'caz').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?:cats){e<=2}', 'c ats').fuzzy_counts, (1, 1, 0))
    self.assertEqual(regex.match('(?e)(?:cats){e<=2}', 'c ats').fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.match('(?b)(?:cats){e<=2}', 'c ats').fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.match('(?:cats){e<=2}', 'c a ts').fuzzy_counts, (0, 2, 0))
    self.assertEqual(regex.match('(?e)(?:cats){e<=2}', 'c a ts').fuzzy_counts, (0, 2, 0))
    self.assertEqual(regex.match('(?b)(?:cats){e<=2}', 'c a ts').fuzzy_counts, (0, 2, 0))
    self.assertEqual(regex.match('(?:cats){e<=1}', 'c ats').fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.match('(?e)(?:cats){e<=1}', 'c ats').fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.match('(?b)(?:cats){e<=1}', 'c ats').fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.findall('\\bof ([a-z]+) of \\1\\b', 'To make use of one of these modules'), [])
    self.assertEqual(regex.sub('x', '\\g<0>', 'x'), 'x')
    self.assertEqual(bool(regex.match('a', 'a', regex.DEBUG)), True)
    self.assertEqual(regex.findall('(?V1)[[b-e]--cd]', 'abcdef'), ['b', 'e'])
    self.assertEqual(regex.findall('(?V1)[b-e--cd]', 'abcdef'), ['b', 'e'])
    self.assertEqual(regex.findall('(?V1)[[bcde]--cd]', 'abcdef'), ['b', 'e'])
    self.assertEqual(regex.findall('(?V1)[bcde--cd]', 'abcdef'), ['b', 'e'])
    self.assertRaisesRegex(regex.error, '^unknown property at position 4$', lambda: regex.compile('\\p{}'))
    self.assertEqual(regex.match('(?:()|(?(1)()|z)){2}(?(2)a|z)', 'a').group(0, 1, 2), ('a', '', ''))
    self.assertEqual(regex.match('(?:()|(?(1)()|z)){0,2}(?(2)a|z)', 'a').group(0, 1, 2), ('a', '', ''))
    chars = ''.join((chr(c) for c in range(65536)))
    self.assertEqual(ascii(''.join(regex.findall('[[:alnum:]]+', chars))), ascii(''.join(regex.findall('[\\p{Alpha}\\p{PosixDigit}]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:alpha:]]+', chars))), ascii(''.join(regex.findall('\\p{Alpha}+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:ascii:]]+', chars))), ascii(''.join(regex.findall('[\\p{InBasicLatin}]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:blank:]]+', chars))), ascii(''.join(regex.findall('[\\p{gc=Space_Separator}\\t]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:cntrl:]]+', chars))), ascii(''.join(regex.findall('\\p{gc=Control}+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:digit:]]+', chars))), ascii(''.join(regex.findall('[0-9]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:graph:]]+', chars))), ascii(''.join(regex.findall('[^\\p{Space}\\p{gc=Control}\\p{gc=Surrogate}\\p{gc=Unassigned}]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:lower:]]+', chars))), ascii(''.join(regex.findall('\\p{Lower}+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:print:]]+', chars))), ascii(''.join(regex.findall('(?V1)[\\p{Graph}\\p{Blank}--\\p{Cntrl}]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:punct:]]+', chars))), ascii(''.join(regex.findall('(?V1)[\\p{gc=Punctuation}\\p{gc=Symbol}--\\p{Alpha}]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:space:]]+', chars))), ascii(''.join(regex.findall('\\p{Whitespace}+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:upper:]]+', chars))), ascii(''.join(regex.findall('\\p{Upper}+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:word:]]+', chars))), ascii(''.join(regex.findall('[\\p{Alpha}\\p{gc=Mark}\\p{Digit}\\p{gc=Connector_Punctuation}\\p{Join_Control}]+', chars))))
    self.assertEqual(ascii(''.join(regex.findall('[[:xdigit:]]+', chars))), ascii(''.join(regex.findall('[0-9A-Fa-f]+', chars))))
    chars = bytes(range(256))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:alnum:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[\\p{Alpha}\\p{PosixDigit}]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:alpha:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)\\p{Alpha}+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:ascii:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[\\x00-\\x7F]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:blank:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[\\p{gc=Space_Separator}\\t]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:cntrl:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)\\p{gc=Control}+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:digit:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[0-9]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:graph:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[^\\p{Space}\\p{gc=Control}\\p{gc=Surrogate}\\p{gc=Unassigned}]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:lower:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)\\p{Lower}+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:print:]]+', chars))), ascii(b''.join(regex.findall(b'(?aV1)[\\p{Graph}\\p{Blank}--\\p{Cntrl}]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:punct:]]+', chars))), ascii(b''.join(regex.findall(b'(?aV1)[\\p{gc=Punctuation}\\p{gc=Symbol}--\\p{Alpha}]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:space:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)\\p{Whitespace}+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:upper:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)\\p{Upper}+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:word:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[\\p{Alpha}\\p{gc=Mark}\\p{Digit}\\p{gc=Connector_Punctuation}\\p{Join_Control}]+', chars))))
    self.assertEqual(ascii(b''.join(regex.findall(b'(?a)[[:xdigit:]]+', chars))), ascii(b''.join(regex.findall(b'(?a)[0-9A-Fa-f]+', chars))))
    self.assertEqual(ascii(regex.search('\\X$', 'ab℃').group()), ascii('℃'))
    self.assertEqual(regex.search('([^L]*)([^R]*R)', 'LtR').groups(), ('', 'LtR'))
    self.assertEqual(regex.sub('(.)', 'x\\1y', 'ab'), 'xayxby')
    self.assertEqual(regex.sub('(?r)(.)', 'x\\1y', 'ab'), 'xayxby')
    self.assertEqual(regex.subf('(.)', 'x{1}y', 'ab'), 'xayxby')
    self.assertEqual(regex.subf('(?r)(.)', 'x{1}y', 'ab'), 'xayxby')
    self.assertEqual(regex.fullmatch('(a)*abc', 'ab', partial=True).span(), (0, 2))
    self.assertEqual(regex.fullmatch('(a)*abc', 'ab', partial=True).partial, True)
    self.assertEqual(regex.search('OXRG', 'OOGOX', partial=True).span(), (3, 5))
    self.assertEqual(regex.search('.XRG', 'OOGOX', partial=True).span(), (3, 5))
    self.assertEqual(regex.search('.{1,3}XRG', 'OOGOX', partial=True).span(), (1, 5))
    self.assertEqual(regex.match('R|R', 'R').span(), (0, 1))
    self.assertEqual(regex.match('(.)(?(1)(?!))', 'xy'), None)
    self.assertEqual(regex.findall('(y)?(\\d)(?(1)\\b\\B)', 'ax1y2z3b'), [('', '1'), ('', '2'), ('', '3')])
    self.assertEqual(regex.findall('(y)?+(\\d)(?(1)\\b\\B)', 'ax1y2z3b'), [('', '1'), ('', '2'), ('', '3')])
    self.assertEqual([m.span() for m in regex.finditer('(?i)(?:error){e}', 'regex failure')], [(0, 5), (5, 10), (10, 13), (13, 13)])
    self.assertEqual([m.span() for m in regex.finditer('(?fi)(?:error){e}', 'regex failure')], [(0, 5), (5, 10), (10, 13), (13, 13)])
    self.assertEqual(regex.search('(?p)\\d+(\\w(\\d*)?|[eE]([+-]\\d+))', '10b12')[0], '10b12')
    self.assertEqual(regex.search('(?p)\\d+(\\w(\\d*)?|[eE]([+-]\\d+))', '10E+12')[0], '10E+12')
    self.assertEqual(regex.search('(?p)(\\w|ae|oe|ue|ss)', 'ae')[0], 'ae')
    self.assertEqual(regex.search('(?p)one(self)?(selfsufficient)?', 'oneselfsufficient')[0], 'oneselfsufficient')
    self.assertEqual(regex.search('(ab\\Kcd)', 'abcd').group(0, 1), ('cd', 'abcd'))
    self.assertEqual(regex.findall('\\w\\w\\K\\w\\w', 'abcdefgh'), ['cd', 'gh'])
    self.assertEqual(regex.findall('(\\w\\w\\K\\w\\w)', 'abcdefgh'), ['abcd', 'efgh'])
    self.assertEqual(regex.search('(?r)(ab\\Kcd)', 'abcd').group(0, 1), ('ab', 'abcd'))
    self.assertEqual(regex.findall('(?r)\\w\\w\\K\\w\\w', 'abcdefgh'), ['ef', 'ab'])
    self.assertEqual(regex.findall('(?r)(\\w\\w\\K\\w\\w)', 'abcdefgh'), ['efgh', 'abcd'])
    self.assertEqual(regex.search('(?(DEFINE)(?<quant>\\d+)(?<item>\\w+))(?&quant) (?&item)', '5 elephants')[0], '5 elephants')
    self.assertEqual(regex.search('(?&routine)(?(DEFINE)(?<routine>.))', 'a').group('routine'), None)
    self.assertEqual(regex.search('(?&routine)(?(DEFINE)(?<routine>.))', 'a').captures('routine'), ['a'])
    self.assertEqual(regex.search('12(*FAIL)|3', '123')[0], '3')
    self.assertEqual(regex.search('(?r)12(*FAIL)|3', '123')[0], '3')
    self.assertEqual(regex.search('\\d+(*PRUNE)\\d', '123'), None)
    self.assertEqual(regex.search('\\d+(?=(*PRUNE))\\d', '123')[0], '123')
    self.assertEqual(regex.search('\\d+(*PRUNE)bcd|[3d]', '123bcd')[0], '123bcd')
    self.assertEqual(regex.search('\\d+(*PRUNE)bcd|[3d]', '123zzd')[0], 'd')
    self.assertEqual(regex.search('\\d+?(*PRUNE)bcd|[3d]', '123bcd')[0], '3bcd')
    self.assertEqual(regex.search('\\d+?(*PRUNE)bcd|[3d]', '123zzd')[0], 'd')
    self.assertEqual(regex.search('\\d++(?<=3(*PRUNE))zzd|[4d]$', '123zzd')[0], '123zzd')
    self.assertEqual(regex.search('\\d++(?<=3(*PRUNE))zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('\\d++(?<=(*PRUNE)3)zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('\\d++(?<=2(*PRUNE)3)zzd|[3d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d(*PRUNE)\\d+', '123'), None)
    self.assertEqual(regex.search('(?r)\\d(?<=(*PRUNE))\\d+', '123')[0], '123')
    self.assertEqual(regex.search('(?r)\\d+(*PRUNE)bcd|[3d]', '123bcd')[0], '123bcd')
    self.assertEqual(regex.search('(?r)\\d+(*PRUNE)bcd|[3d]', '123zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d++(?<=3(*PRUNE))zzd|[4d]$', '123zzd')[0], '123zzd')
    self.assertEqual(regex.search('(?r)\\d++(?<=3(*PRUNE))zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d++(?<=(*PRUNE)3)zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d++(?<=2(*PRUNE)3)zzd|[3d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('\\d+(*SKIP)bcd|[3d]', '123bcd')[0], '123bcd')
    self.assertEqual(regex.search('\\d+(*SKIP)bcd|[3d]', '123zzd')[0], 'd')
    self.assertEqual(regex.search('\\d+?(*SKIP)bcd|[3d]', '123bcd')[0], '3bcd')
    self.assertEqual(regex.search('\\d+?(*SKIP)bcd|[3d]', '123zzd')[0], 'd')
    self.assertEqual(regex.search('\\d++(?<=3(*SKIP))zzd|[4d]$', '123zzd')[0], '123zzd')
    self.assertEqual(regex.search('\\d++(?<=3(*SKIP))zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('\\d++(?<=(*SKIP)3)zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('\\d++(?<=2(*SKIP)3)zzd|[3d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d+(*SKIP)bcd|[3d]', '123bcd')[0], '123bcd')
    self.assertEqual(regex.search('(?r)\\d+(*SKIP)bcd|[3d]', '123zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d++(?<=3(*SKIP))zzd|[4d]$', '123zzd')[0], '123zzd')
    self.assertEqual(regex.search('(?r)\\d++(?<=3(*SKIP))zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d++(?<=(*SKIP)3)zzd|[4d]$', '124zzd')[0], 'd')
    self.assertEqual(regex.search('(?r)\\d++(?<=2(*SKIP)3)zzd|[3d]$', '124zzd')[0], 'd')
    text = 'June 30, December 31, 2013 2012\nsome words follow:\nmore words and numbers 1,234,567 9,876,542\nmore words and numbers 1,234,567 9,876,542'
    self.assertEqual(len(regex.findall('(?<!\\d)(?>2014|2013 ?2012)', text)), 1)
    self.assertEqual(regex.match('1(?>2)', '12').span(), (0, 2))
    self.assertEqual(regex.match('(?V1w)(?=(?=[^A-Z]*+[A-Z])(?=[^a-z]*+[a-z]))(?=\\D*+\\d)(?=\\p{Alphanumeric}*+\\P{Alphanumeric})\\A(?s:.){8,255}+\\Z', 'AAaa11!!')[0], 'AAaa11!!')
    TEST_REGEX = regex.compile('(?smx)\n(?(DEFINE)\n  (?<subcat>\n   ^,[^,]+,\n   )\n)\n\n# Group 2 is defined on this line\n^,([^,]+),\n\n(?:(?!(?&subcat)[\\r\\n]+(?&subcat)).)+\n')
    TEST_DATA = '\n,Cat 1,\n,Brand 1,\nsome\nthing\n,Brand 2,\nother\nthings\n,Cat 2,\n,Brand,\nSome\nthing\n'
    self.assertEqual([m.span(1, 2) for m in TEST_REGEX.finditer(TEST_DATA)], [((-1, -1), (2, 7)), ((-1, -1), (54, 59))])
    self.assertEqual(regex.search('(abcdefgh){e}', '******abcdefghijklmnopqrtuvwxyz', regex.BESTMATCH).span(), (6, 14))
    self.assertEqual(regex.search('(abcdefghi){e}', '******abcdefghijklmnopqrtuvwxyz', regex.BESTMATCH).span(), (6, 15))
    self.assertEqual(regex.match('(?:(?=\\d)\\d+\\b|\\w+)', '123abc').span(), (0, 6))
    self.assertEqual(regex.match('(?(?=\\d)\\d+\\b|\\w+)', '123abc'), None)
    self.assertEqual(regex.search('(?(?<=love\\s)you|(?<=hate\\s)her)', 'I love you').span(), (7, 10))
    self.assertEqual(regex.findall('(?(?<=love\\s)you|(?<=hate\\s)her)', "I love you but I don't hate her either"), ['you', 'her'])
    self.assertEqual(regex.search('(?p)a*(.*?)', 'aaabbb').group(0, 1), ('aaabbb', 'bbb'))
    self.assertEqual(regex.search('(?p)a*(.*)', 'aaabbb').group(0, 1), ('aaabbb', 'bbb'))
    self.assertEqual(regex.sub('(?p)a*(.*?)', '\\1', 'aaabbb'), 'bbb')
    self.assertEqual(regex.sub('(?p)a*(.*)', '\\1', 'aaabbb'), 'bbb')
    self.assertEqual(regex.match('(?irV0)\\L<kw>', '21', kw=['1']).span(), (1, 2))
    self.assertEqual(regex.match('(?irV1)\\L<kw>', '21', kw=['1']).span(), (1, 2))
    self.assertEqual(regex.search('a|b', '111a222').span(), (3, 4))
    self.assertEqual(regex.search('(?r)a|b', '111a222').span(), (3, 4))
    self.assertEqual(regex.search('(?if)<(CLI)><\\1>', '<cli><cli>').span(), (0, 10))
    self.assertEqual(regex.search('(?if)<(CLI)><\\1>', '<cli><clI>').span(), (0, 10))
    self.assertEqual(regex.search('(?ifr)<\\1><(CLI)>', '<cli><clI>').span(), (0, 10))
    r = regex.compile('\\L<options>', options=['foo', 'bar'])
    p = pickle.dumps(r)
    r = pickle.loads(p)
    self.assertEqual(r.match('foo').span(), (0, 3))
    self.assertEqual(regex.match('(x{6}){e<=1}', 'xxxxxx', flags=regex.BESTMATCH).span(), (0, 6))
    self.assertEqual(regex.match('(x{6}){e<=1}', 'xxxxx', flags=regex.BESTMATCH).span(), (0, 5))
    self.assertEqual(regex.match('(x{6}){e<=1}', 'x', flags=regex.BESTMATCH), None)
    self.assertEqual(regex.match('(?r)(x{6}){e<=1}', 'xxxxxx', flags=regex.BESTMATCH).span(), (0, 6))
    self.assertEqual(regex.match('(?r)(x{6}){e<=1}', 'xxxxx', flags=regex.BESTMATCH).span(), (0, 5))
    self.assertEqual(regex.match('(?r)(x{6}){e<=1}', 'x', flags=regex.BESTMATCH), None)
    self.assertRaises(regex.error, lambda: regex.compile(b'00000\\0\\00\\^(\\00\\U05000000'))
    self.assertRaises(regex.error, lambda: regex.compile(b'{e<l'))
    self.assertEqual(bool(regex.compile('((?0)){e}')), True)
    self.assertEqual(bool(regex.compile('\x00?(?0){e}')), True)
    self.assertEqual(regex.findall('((brown)|(lazy)){1<=e<=3} ((dog)|(fox)){1<=e<=3}', 'The quick borwn fax jumped over the lzy hog', regex.ENHANCEMATCH), [('borwn', 'borwn', '', 'fax', '', 'fax'), ('lzy', '', 'lzy', 'hog', 'hog', '')])
    self.assertEqual(regex.search('\\d\\d\\d-\\d\\d-\\d\\d\\d\\d', "My SSN is 999-89-76, but don't tell.", partial=True).span(), (36, 36))
    upper_i = 'Й'
    lower_i = 'й'
    self.assertEqual(bool(regex.match('(?ui)' + upper_i, lower_i)), True)
    self.assertEqual(bool(regex.match('(?ui)' + lower_i, upper_i)), True)
    self.assertEqual(bool(regex.match('(?ai)' + upper_i, lower_i)), False)
    self.assertEqual(bool(regex.match('(?ai)' + lower_i, upper_i)), False)
    self.assertEqual(bool(regex.match('(?afi)' + upper_i, lower_i)), False)
    self.assertEqual(bool(regex.match('(?afi)' + lower_i, upper_i)), False)
    self.assertEqual(bool(regex.search('(?i)\\L<aa>', '22', aa=['121', '22'])), True)
    self.assertEqual(bool(regex.search('(?ri)\\L<aa>', '22', aa=['121', '22'])), True)
    self.assertEqual(bool(regex.search('(?fi)\\L<aa>', '22', aa=['121', '22'])), True)
    self.assertEqual(bool(regex.search('(?fri)\\L<aa>', '22', aa=['121', '22'])), True)
    self.assertEqual(regex.search('(?r)\\1dog..(?<=(\\L<aa>))$', 'ccdogcc', aa=['bcb', 'cc']).span(), (0, 7))
    self.assertEqual(regex.search('(?ir)\\1dog..(?<=(\\L<aa>))$', 'ccdogcc', aa=['bcb', 'cc']).span(), (0, 7))
    self.assertEqual(regex.search('(2)(?:\\1{5}){e<=1}', '3222212').span(), (1, 7))
    self.assertEqual(regex.search('(\\d)(?:\\1{5}){e<=1}', '3222212').span(), (1, 7))
    self.assertEqual(regex.match('\\A(?P<whole>(?>\\((?&whole)\\)|[+\\-]))\\Z', '((-))').span(), (0, 5))
    self.assertEqual(regex.match('\\A(?P<whole>(?>\\((?&whole)\\)|[+\\-]))\\Z', '((-)+)'), None)
    self.assertEqual(regex.match('x.*? (.).*\\1(.*)\\1', 'x  |y| z|').span(), (0, 9))
    self.assertEqual(regex.match('\\.sr (.*?) (.)(.*)\\2(.*)\\2(.*)', '.sr  h |<nw>|<span class="locked">|').span(), (0, 35))
    a = '"\\xF9\\x80\\xAEqdz\\x95L\\xA7\\x89[\\xFE \\x91)\\xF9]\\xDB\'\\x99\\x09=\\x00\\xFD\\x98\\x22\\xDD\\xF1\\xB6\\xC3 Z\\xB6gv\\xA5x\\x93P\\xE1r\\x14\\x8Cv\\x0C\\xC0w\\x15r\\xFFc%" '
    py_regex_pattern = '(?P<http_referer>((?>(?<!\\\\)(?>"(?>\\\\.|[^\\\\"]+)+"|""|(?>\'(?>\\\\.|[^\\\\\']+)+\')|\'\'|(?>`(?>\\\\.|[^\\\\`]+)+`)|``)))) (?P<useragent>((?>(?<!\\\\)(?>"(?>\\\\.|[^\\\\"]+)+"|""|(?>\'(?>\\\\.|[^\\\\\']+)+\')|\'\'|(?>`(?>\\\\.|[^\\\\`]+)+`)|``))))'
    self.assertEqual(bool(regex.search(py_regex_pattern, a)), False)
    self.assertEqual(bool(regex.match('foo(?<=foo)', 'foo')), True)
    self.assertEqual(bool(regex.match('foo(?<!foo)', 'foo')), False)
    self.assertEqual(bool(regex.match('foo(?<=foo|x)', 'foo')), True)
    self.assertEqual(bool(regex.match('foo(?<!foo|x)', 'foo')), False)
    self.assertEqual(bool(regex.match('(?(?=.*\\!.*)(?P<true>.*\\!\\w*\\:.*)|(?P<false>.*))', '!')), False)
    self.assertEqual(regex.match('\\w*(ea)\\w*|\\w*e(?!a)\\w*', 'easier').groups(), ('ea',))
    self.assertEqual(regex.search('(^1234$){i,d}', '12234', regex.BESTMATCH).span(), (0, 5))
    self.assertEqual(regex.search('(^1234$){i,d}', '12234', regex.BESTMATCH).fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.search('(^1234$){s,i,d}', '12234', regex.BESTMATCH).span(), (0, 5))
    self.assertEqual(regex.search('(^1234$){s,i,d}', '12234', regex.BESTMATCH).fuzzy_counts, (0, 1, 0))
    self.assertEqual(regex.search('(^123$){s,i,d}', 'xxxxxxxx123', regex.BESTMATCH).span(), (0, 11))
    self.assertEqual(regex.search('(^123$){s,i,d}', 'xxxxxxxx123', regex.BESTMATCH).fuzzy_counts, (0, 8, 0))
    self.assertEqual(regex.search('a?yz', 'xxxxyz', flags=regex.FULLCASE | regex.IGNORECASE).span(), (4, 6))
    self.assertEqual(regex.findall('(?:(?![a-d]).)+', 'abcdefgh'), ['efgh'])
    self.assertEqual(regex.findall('(?(DEFINE)(?P<mydef>(?:(?![a-d]).)))(?&mydef)+', 'abcdefgh'), ['efgh'])
    self.assertEqual(regex.findall('((\\w{1,3})(\\.{2,10})){1,3}', '"Erm....yes. T..T...Thank you for that."'), [('Erm....', 'Erm', '....'), ('T...', 'T', '...')])
    self.assertEqual(regex.findall('((\\w{1,3})(\\.{2,10})){3}', '"Erm....yes. T..T...Thank you for that."'), [])
    self.assertEqual(regex.findall('((\\w{1,3})(\\.{2,10})){2}', '"Erm....yes. T..T...Thank you for that."'), [('T...', 'T', '...')])
    self.assertEqual(regex.findall('((\\w{1,3})(\\.{2,10})){1}', '"Erm....yes. T..T...Thank you for that."'), [('Erm....', 'Erm', '....'), ('T..', 'T', '..'), ('T...', 'T', '...')])
    self.assertEqual(regex.search('(?:ESTONIA(?!\\w)){e<=1}', 'ESTONIAN WORKERS').group(), 'ESTONIAN')
    self.assertEqual(regex.search('(?:ESTONIA(?=\\W)){e<=1}', 'ESTONIAN WORKERS').group(), 'ESTONIAN')
    self.assertEqual(regex.search('(?:(?<!\\w)ESTONIA){e<=1}', 'BLUB NESTONIA').group(), 'NESTONIA')
    self.assertEqual(regex.search('(?:(?<=\\W)ESTONIA){e<=1}', 'BLUB NESTONIA').group(), 'NESTONIA')
    self.assertEqual(regex.search('(?r)(?:ESTONIA(?!\\w)){e<=1}', 'ESTONIAN WORKERS').group(), 'ESTONIAN')
    self.assertEqual(regex.search('(?r)(?:ESTONIA(?=\\W)){e<=1}', 'ESTONIAN WORKERS').group(), 'ESTONIAN')
    self.assertEqual(regex.search('(?r)(?:(?<!\\w)ESTONIA){e<=1}', 'BLUB NESTONIA').group(), 'NESTONIA')
    self.assertEqual(regex.search('(?r)(?:(?<=\\W)ESTONIA){e<=1}', 'BLUB NESTONIA').group(), 'NESTONIA')
    self.assertEqual(regex.search('(?:A.*B.*CDE){e<=2}', 'A B CYZ').group(), 'A B CYZ')
    self.assertEqual(regex.search('(?:A.*B.*?CDE){e<=2}', 'A B CYZ').group(), 'A B CYZ')
    self.assertEqual(regex.search('(?:A.*?B.*CDE){e<=2}', 'A B CYZ').group(), 'A B CYZ')
    self.assertEqual(regex.search('(?:A.*?B.*?CDE){e<=2}', 'A B CYZ').group(), 'A B CYZ')
    self.assertEqual(regex.escape(' ,0A[', special_only=False, literal_spaces=False), '\\ \\,0A\\[')
    self.assertEqual(regex.escape(' ,0A[', special_only=False, literal_spaces=True), ' \\,0A\\[')
    self.assertEqual(regex.escape(' ,0A[', special_only=True, literal_spaces=False), '\\ ,0A\\[')
    self.assertEqual(regex.escape(' ,0A[', special_only=True, literal_spaces=True), ' ,0A\\[')
    self.assertEqual(regex.escape(' ,0A['), '\\ ,0A\\[')
    self.assertEqual(regex.search('(?(?=A)A|B)', 'A').span(), (0, 1))
    self.assertEqual(regex.search('(?(?=A)A|B)', 'B').span(), (0, 1))
    self.assertEqual(regex.search('(?(?=A)A|)', 'B').span(), (0, 0))
    self.assertEqual(regex.search('(?(?=X)X|)', '').span(), (0, 0))
    self.assertEqual(regex.search('(?(?=X))', '').span(), (0, 0))
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.))(?&func)', 'abc').groups(), (None,))
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.))(?&func)', 'abc').groupdict(), {'func': None})
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.))(?&func)', 'abc').capturesdict(), {'func': ['a']})
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.))(?=(?&func))', 'abc').groups(), (None,))
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.))(?=(?&func))', 'abc').groupdict(), {'func': None})
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.))(?=(?&func))', 'abc').capturesdict(), {'func': ['a']})
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.)).(?<=(?&func))', 'abc').groups(), (None,))
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.)).(?<=(?&func))', 'abc').groupdict(), {'func': None})
    self.assertEqual(regex.search('(?(DEFINE)(?<func>.)).(?<=(?&func))', 'abc').capturesdict(), {'func': ['a']})
    self.assertEqual(bool(regex.match('ab(?#comment\\))cd', 'abcd')), True)
    self.assertEqual(regex.search('[a-z]+ [a-z]*?:', 'foo bar', partial=True).span(), (0, 7))
    self.assertEqual(regex.search('(?r):[a-z]*? [a-z]+', 'foo bar', partial=True).span(), (0, 7))
    self.assertEqual(bool(regex.match('(?u)\\p{Script:Beng}', '৯')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{Script:Bengali}', '৯')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{Script_Extensions:Bengali}', '৯')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{Script_Extensions:Beng}', '৯')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{Script_Extensions:Cakm}', '৯')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{Script_Extensions:Sylo}', '৯')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Latin}', 'P')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Ahom}', 'P')), False)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Common}', '4')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Caucasian_Albanian}', '4')), False)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Arabic}', 'ت')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Balinese}', 'ت')), False)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Devanagari}', 'ज')), True)
    self.assertEqual(bool(regex.match('(?u)\\p{scx:Batak}', 'ज')), False)
    self.assertEqual(regex.fullmatch('(?P<x>.)*(?&x)', 'abc').captures('x'), ['a', 'b', 'c'])
    self.assertEqual(regex.fullmatch('(?P<x>.)*(?&x)', 'abc').group('x'), 'b')
    self.assertEqual(regex.fullmatch('(?P<x>.)(?P<x>.)(?P<x>.)', 'abc').captures('x'), ['a', 'b', 'c'])
    self.assertEqual(regex.fullmatch('(?P<x>.)(?P<x>.)(?P<x>.)', 'abc').group('x'), 'c')
    self.assertEqual(regex.match('(?:ab)*', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)*', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)*?', '', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)*+', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)*+', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)+', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)+', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)+?', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)++', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?:ab)++', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)*', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)*', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)*?', '', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)*+', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)*+', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)+', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)+', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)+?', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)++', 'ab', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)(?:ab)++', 'abab', partial=True).partial, False)
    self.assertEqual(regex.match('a*', '', partial=True).partial, False)
    self.assertEqual(regex.match('a*?', '', partial=True).partial, False)
    self.assertEqual(regex.match('a*+', '', partial=True).partial, False)
    self.assertEqual(regex.match('a+', '', partial=True).partial, True)
    self.assertEqual(regex.match('a+?', '', partial=True).partial, True)
    self.assertEqual(regex.match('a++', '', partial=True).partial, True)
    self.assertEqual(regex.match('a+', 'a', partial=True).partial, False)
    self.assertEqual(regex.match('a+?', 'a', partial=True).partial, False)
    self.assertEqual(regex.match('a++', 'a', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)a*', '', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)a*?', '', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)a*+', '', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)a+', '', partial=True).partial, True)
    self.assertEqual(regex.match('(?r)a+?', '', partial=True).partial, True)
    self.assertEqual(regex.match('(?r)a++', '', partial=True).partial, True)
    self.assertEqual(regex.match('(?r)a+', 'a', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)a+?', 'a', partial=True).partial, False)
    self.assertEqual(regex.match('(?r)a++', 'a', partial=True).partial, False)
    self.assertEqual(regex.match("(?:\\s*\\w+'*)+", 'whatever', partial=True).partial, False)
    pattern = '(?P<termini5>GGCGTCACACTTTGCTATGCCATAGCAT[AG]TTTATCCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCATAACAGAACATATTGACTATCCGGTATTACCCGGCATGACAGGAGTAAAA){e<=1}(?P<gene>[ACGT]{1059}){e<=2}(?P<spacer>TAATCGTCTTGTTTGATACACAAGGGTCGCATCTGCGGCCCTTTTGCTTTTTTAAGTTGTAAGGATATGCCATTCTAGA){e<=0}(?P<barcode>[ACGT]{18}){e<=0}(?P<termini3>AGATCGG[CT]AGAGCGTCGTGTAGGGAAAGAGTGTGG){e<=1}'
    text = 'GCACGGCGTCACACTTTGCTATGCCATAGCATATTTATCCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCATAACAGAACATATTGACTATCCGGTATTACCCGGCATGACAGGAGTAAAAATGGCTATCGACGAAAACAAACAGAAAGCGTTGGCGGCAGCACTGGGCCAGATTGAGAAACAATTTGGTAAAGGCTCCATCATGCGCCTGGGTGAAGACCGTTCCATGGATGTGGAAACCATCTCTACCGGTTCGCTTTCACTGGATATCGCGCTTGGGGCAGGTGGTCTGCCGATGGGCCGTATCGTCGAAATCTACGGACCGGAATCTTCCGGTAAAACCACGCTGACGCTGCAGGTGATCGCCGCAGCGCAGCGTGAAGGTAAAACCTGTGCGTTTATCGATGCTGAACACGCGCTGGACCCAATCTACGCACGTAAACTGGGCGTCGATATCGACAACCTGCTGTGCTCCCAGCCGGACACCGGCGAGCAGGCACTGGAAATCTGTGACGCCCTGGCGCGTTCTGGCGCAGTAGACGTTATCGTCGTTGACTCCGTGGCGGCACTGACGCCGAAAGCGGAAATCGAAGGCGAAATCGGCGACTCTCATATGGGCCTTGCGGCACGTATGATGAGCCAGGCGATGCGTAAGCTGGCGGGTAACCTGAAGCAGTCCAACACGCTGCTGATCTTCATCAACCCCATCCGTATGAAAATTGGTGTGATGTTCGGCAACCCGGAAACCACTTACCGGTGGTAACGCGCTGAAATTCTACGCCTCTGTTCGTCTCGACATCCGTTAAATCGGCGCGGTGAAAGAGGGCGAAAACGTGGTGGGTAGCGAAACCCGCGTGAAAGTGGTGAAGAACAAAATCGCTGCGCCGTTTAAACAGGCTGAATTCCAGATCCTCTACGGCGAAGGTATCAACTTCTACCCCGAACTGGTTGACCTGGGCGTAAAAGAGAAGCTGATCGAGAAAGCAGGCGCGTGGTACAGCTACAAAGGTGAGAAGATCGGTCAGGGTAAAGCGAATGCGACTGCCTGGCTGAAATTTAACCCGGAAACCGCGAAAGAGATCGAGTGAAAAGTACGTGAGTTGCTGCTGAGCAACCCGAACTCAACGCCGGATTTCTCTGTAGATGATAGCGAAGGCGTAGCAGAAACTAACGAAGATTTTTAATCGTCTTGTTTGATACACAAGGGTCGCATCTGCGGCCCTTTTGCTTTTTTAAGTTGTAAGGATATGCCATTCTAGACAGTTAACACACCAACAAAGATCGGTAGAGCGTCGTGTAGGGAAAGAGTGTGGTACC'
    m = regex.search(pattern, text, flags=regex.BESTMATCH)
    self.assertEqual(m.fuzzy_counts, (0, 1, 0))
    self.assertEqual(m.fuzzy_changes, ([], [1206], []))
    self.assertEqual(regex.search('(?e)(dogf(((oo){e<1})|((00){e<1}))d){e<2}', 'dogfood').fuzzy_counts, (0, 0, 0))
    self.assertEqual(regex.search('(?e)(dogf(((oo){e<1})|((00){e<1}))d){e<2}', 'dogfoot').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.findall('\\X', '👨\u200d👩\u200d👧\u200d👦'), ['👨\u200d👩\u200d👧\u200d👦'])
    self.assertEqual(bool(regex.search('(?=a)a', 'a')), True)
    self.assertEqual(bool(regex.search('(?!b)a', 'a')), True)
    self.assertEqual(regex.fullmatch('((\\d)*?)*?', '123').span(), (0, 3))
    self.assertEqual(regex.search('(?(DEFINE)(?<mydef>(?<wrong>THIS_SHOULD_NOT_MATCHx?)|(?<right>right))).*(?<=(?&mydef).*)', 'x right').capturesdict(), {'mydef': ['right'], 'wrong': [], 'right': ['right']})
    self.assertEqual(bool(regex.match('(?:cat){e<=1:[u]}', 'cut')), True)
    self.assertEqual(bool(regex.match('(?:cat){e<=1:u}', 'cut')), True)
    self.assertEqual(regex.search('(?be)(AGTGTTCCCCGCGCCAGCGGGGATAAACCG){s<=5,i<=5,d<=5,s+i+d<=10}', 'TTCCCCGCGCCAGCGGGGATAAACCG').fuzzy_changes, ([], [], [0, 1, 3, 5]))
    self.assertEqual(regex.match('(?:bc){e}', 'c').fuzzy_counts, (1, 0, 1))
    self.assertEqual(regex.match('(?:bc){e}', 'c').fuzzy_changes, ([0], [], [1]))
    self.assertEqual(regex.match('(?e)(?:bc){e}', 'c').fuzzy_counts, (0, 0, 1))
    self.assertEqual(regex.match('(?e)(?:bc){e}', 'c').fuzzy_changes, ([], [], [0]))
    self.assertEqual(regex.match('(?b)(?:bc){e}', 'c').fuzzy_counts, (0, 0, 1))
    self.assertEqual(regex.match('(?b)(?:bc){e}', 'c').fuzzy_changes, ([], [], [0]))
    self.assertEqual(regex.match('(?e)(?:^(\\$ )?\\d{1,3}(,\\d{3})*(\\.\\d{2})$){e}', '$ 10,112.111.12').fuzzy_counts, (6, 0, 5))
    self.assertEqual(regex.match('(?e)(?:^(\\$ )?\\d{1,3}(,\\d{3})*(\\.\\d{2})$){s<=1}', '$ 10,112.111.12').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?e)(?:^(\\$ )?\\d{1,3}(,\\d{3})*(\\.\\d{2})$){s<=1,i<=1,d<=1}', '$ 10,112.111.12').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.match('(?e)(?:^(\\$ )?\\d{1,3}(,\\d{3})*(\\.\\d{2})$){s<=3}', '$ 10,1a2.111.12').fuzzy_counts, (2, 0, 0))
    self.assertEqual(regex.match('(?e)(?:^(\\$ )?\\d{1,3}(,\\d{3})*(\\.\\d{2})$){s<=2}', '$ 10,1a2.111.12').fuzzy_counts, (2, 0, 0))
    self.assertEqual(regex.fullmatch('(?e)(?:0?,0(?:,0)?){s<=1,d<=1}', ',0;0').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.fullmatch('(?e)(?:0??,0(?:,0)?){s<=1,d<=1}', ',0;0').fuzzy_counts, (1, 0, 0))
    self.assertEqual(regex.search('\\b(?e)(?:\\d{6,20}){i<=5:[\\-\\\\\\/]}\\b', 'cat dog starting at 00:01132.000. hello world'), None)
    self.assertEqual(bool(regex.compile('(?#)')), True)
    self.assertEqual(bool(regex.compile('(?x)(?#)')), True)
    self.assertEqual(regex.findall('(\\d+){i<=2:[ab]}', '123X4Y5'), ['123', '4', '5'])
    self.assertEqual(regex.findall('(?i)(\\d+){i<=2:[ab]}', '123X4Y5'), ['123', '4', '5'])
    self.assertEqual(regex.match('^(test){e<=5}$', 'terstin', flags=regex.B).fuzzy_counts, (0, 3, 0))
    self.assertEqual(bool(regex.match('(?:(x*)\\1\\1\\1)*x$', 'x' * 5)), True)
    self.assertEqual(bool(regex.match('(?:(x*)\\1{3})*x$', 'x' * 5)), True)
    self.assertEqual(regex.match('t(?:es){s<=1:\\d}t', 'te5t').group(), 'te5t')
    self.assertEqual(regex.match('t(?:es){s<=1:\\d}t', 'tezt'), None)
    self.assertEqual(regex.match('t(?:es){i<=1:\\d}t', 'tes5t').group(), 'tes5t')
    self.assertEqual(regex.match('t(?:es){i<=1:\\d}t', 'teszt'), None)
    self.assertEqual(regex.match('t(?:es){i<=1:\\d}t', 'tes5t').fuzzy_changes, ([], [3], []))
    self.assertEqual(regex.match('t(es){i<=1,0<e<=1}t', 'tes5t').group(), 'tes5t')
    self.assertEqual(regex.match('t(?:es){i<=1,0<e<=1:\\d}t', 'tes5t').fuzzy_changes, ([], [3], []))
    self.assertEqual(regex.compile('(\\d+ week|\\d+ days)').split('7 days'), ['', '7 days', ''])
    self.assertEqual(regex.compile('(\\d+ week|\\d+ days)').split('10 days'), ['', '10 days', ''])
    self.assertEqual(regex.compile('[ ]* Name[ ]*\\* ').search('  Name *'), None)
    self.assertEqual(regex.compile('a|\\.*pb\\.py').search('.geojs'), None)
    p = regex.compile('(?<=(?:\\A|\\W|_))(\\d+ decades? ago|\\d+ minutes ago|\\d+ seconds ago|in \\d+ decades?|\\d+ months ago|in \\d+ minutes|\\d+ minute ago|in \\d+ seconds|\\d+ second ago|\\d+ years ago|in \\d+ months|\\d+ month ago|\\d+ weeks ago|\\d+ hours ago|in \\d+ minute|in \\d+ second|in \\d+ years|\\d+ year ago|in \\d+ month|in \\d+ weeks|\\d+ week ago|\\d+ days ago|in \\d+ hours|\\d+ hour ago|in \\d+ year|in \\d+ week|in \\d+ days|\\d+ day ago|in \\d+ hour|\\d+ min ago|\\d+ sec ago|\\d+ yr ago|\\d+ mo ago|\\d+ wk ago|in \\d+ day|\\d+ hr ago|in \\d+ min|in \\d+ sec|in \\d+ yr|in \\d+ mo|in \\d+ wk|in \\d+ hr)(?=(?:\\Z|\\W|_))', flags=regex.I | regex.V0)
    self.assertEqual(p.search('1 month ago').group(), '1 month ago')
    self.assertEqual(p.search('9 hours 1 minute ago').group(), '1 minute ago')
    self.assertEqual(p.search('10 months 1 hour ago').group(), '1 hour ago')
    self.assertEqual(p.search('1 month 10 hours ago').group(), '10 hours ago')
    sequence = 'TTCAGACGTGTGCTCTTCCGATCTCAATACCGACTCCTCACTGTGTGTCT'
    pattern = '(?P<insert>.*)(?P<anchor>CTTCC){e<=1}(?P<umi>([ACGT]){4,6})(?P<sid>CAATACCGACTCCTCACTGTGT){e<=2}(?P<end>([ACGT]){0,6}$)'
    m = regex.match(pattern, sequence, flags=regex.BESTMATCH)
    self.assertEqual(m.span(), (0, 50))
    self.assertEqual(m.groupdict(), {'insert': 'TTCAGACGTGTGCT', 'anchor': 'CTTCC', 'umi': 'GATCT', 'sid': 'CAATACCGACTCCTCACTGTGT', 'end': 'GTCT'})
    m = regex.match(pattern, sequence, flags=regex.ENHANCEMATCH)
    self.assertEqual(m.span(), (0, 50))
    self.assertEqual(m.groupdict(), {'insert': 'TTCAGACGTGTGCT', 'anchor': 'CTTCC', 'umi': 'GATCT', 'sid': 'CAATACCGACTCCTCACTGTGT', 'end': 'GTCT'})
    pattern = '(?P<insert>.*)(?P<anchor>AACACTGG){e<=1}(?P<umi>([AT][CG]){5}){e<=2}(?P<sid>GTAACCGAAG){e<=2}(?P<end>([ACGT]){0,6}$)'
    sequence = 'GGAAAACACTGGTCTCAGTCTCGTAACCGAAGTGGTCG'
    m = regex.match(pattern, sequence, flags=regex.BESTMATCH)
    self.assertEqual(m.fuzzy_counts, (0, 0, 0))
    self.assertEqual(m.fuzzy_changes, ([], [], []))
    sequence = 'GGAAAACACTGGTCTCAGTCTCGTCCCCGAAGTGGTCG'
    m = regex.match(pattern, sequence, flags=regex.BESTMATCH)
    self.assertEqual(m.fuzzy_counts, (2, 0, 0))
    self.assertEqual(m.fuzzy_changes, ([24, 25], [], []))
    self.assertEqual(regex.sub('(test1)|(test2)', 'matched: \\1\\2', 'test1'), 'matched: test1')
    self.assertEqual(regex.subf('(test1)|(test2)', 'matched: {1}{2}', 'test1'), 'matched: test1')
    (self.assertEqual(regex.search('(test1)|(test2)', 'matched: test1').expand('matched: \\1\\2'), 'matched: test1'),)
    self.assertEqual(regex.search('(test1)|(test2)', 'matched: test1').expandf('matched: {1}{2}'), 'matched: test1')
    self.assertEqual(regex.search('(?:\\bha\\b){i:[ ]}', 'having'), None)
    self.assertEqual(regex.search('(?:\\bha\\b){i:[ ]}', 'having', flags=regex.I), None)
    self.assertEqual(regex.match('(?a:\\w)\\w', 'dж').span(), (0, 2))
    self.assertEqual(regex.match('(?a:\\w)(?u:\\w)', 'dж').span(), (0, 2))
    self.assertEqual(regex.match('^\\p{LC}+$', '😺'), None)
    self.assertEqual(regex.match('^\\p{So}+$', '😺').span(), (0, 1))
    self.assertEqual(regex.match('(.)+', 'abc').allcaptures(), (['abc'], ['a', 'b', 'c']))
    self.assertEqual(regex.match('(.)+', 'abc').allspans(), ([(0, 3)], [(0, 1), (1, 2), (2, 3)]))
    self.assertEqual(bool(regex.fullmatch('\\p{HorizSpace}+', '\t \xa0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000')), True)
    self.assertEqual(bool(regex.fullmatch('\\p{VertSpace}+', '\n\x0b\x0c\r\x85\u2028\u2029')), True)
    self.assertEqual(regex.match('(?(?<=A)|(?(?![^B])C|D))', 'A'), None)
    self.assertEqual(regex.search('(?(?<=A)|(?(?![^B])C|D))', 'A').span(), (1, 1))
    self.assertEqual(regex.search('^a?(a?)b?c\\1$', 'abca').span(), (0, 4))
    self.assertEqual(regex.match('(?(?=a).|..)', 'ab').span(), (0, 1))
    self.assertEqual(regex.match('(?(?=b).|..)', 'ab').span(), (0, 2))
    self.assertEqual(regex.match('(?(?!a).|..)', 'ab').span(), (0, 2))
    self.assertEqual(regex.match('(?(?!b).|..)', 'ab').span(), (0, 1))