from openstack.compute.v2 import server
from openstack.tests.functional.compute import base as ft_base
from openstack.tests.functional.network.v2 import test_network
def test_server_metadata(self):
    test_server = self.conn.compute.get_server(self.server.id)
    test_server = self.conn.compute.get_server_metadata(test_server)
    self.assertFalse(test_server.metadata)
    self.conn.compute.set_server_metadata(test_server)
    test_server = self.conn.compute.get_server_metadata(test_server)
    self.assertFalse(test_server.metadata)
    self.conn.compute.set_server_metadata(test_server, k0='')
    server = self.conn.compute.get_server_metadata(test_server)
    self.assertTrue(server.metadata)
    self.conn.compute.set_server_metadata(test_server, k1='v1')
    test_server = self.conn.compute.get_server_metadata(test_server)
    self.assertTrue(test_server.metadata)
    self.assertEqual(2, len(test_server.metadata))
    self.assertIn('k0', test_server.metadata)
    self.assertEqual('', test_server.metadata['k0'])
    self.assertIn('k1', test_server.metadata)
    self.assertEqual('v1', test_server.metadata['k1'])
    self.conn.compute.set_server_metadata(test_server, k2='v2')
    test_server = self.conn.compute.get_server_metadata(test_server)
    self.assertTrue(test_server.metadata)
    self.assertEqual(3, len(test_server.metadata))
    self.assertIn('k0', test_server.metadata)
    self.assertEqual('', test_server.metadata['k0'])
    self.assertIn('k1', test_server.metadata)
    self.assertEqual('v1', test_server.metadata['k1'])
    self.assertIn('k2', test_server.metadata)
    self.assertEqual('v2', test_server.metadata['k2'])
    self.conn.compute.set_server_metadata(test_server, k1='v1.1')
    test_server = self.conn.compute.get_server_metadata(test_server)
    self.assertTrue(test_server.metadata)
    self.assertEqual(3, len(test_server.metadata))
    self.assertIn('k0', test_server.metadata)
    self.assertEqual('', test_server.metadata['k0'])
    self.assertIn('k1', test_server.metadata)
    self.assertEqual('v1.1', test_server.metadata['k1'])
    self.assertIn('k2', test_server.metadata)
    self.assertEqual('v2', test_server.metadata['k2'])
    self.conn.compute.delete_server_metadata(test_server, test_server.metadata.keys())
    test_server = self.conn.compute.get_server_metadata(test_server)
    self.assertFalse(test_server.metadata)