import itertools
import cirq
import cirq_ft
from cirq_ft import infra
import numpy as np
import pytest
from cirq_ft.deprecation import allow_deprecated_cirq_ft_use_in_tests
@allow_deprecated_cirq_ft_use_in_tests
def test_reflection_using_prepare_diagram():
    data = [1, 2, 3, 4, 5, 6]
    eps = 0.1
    prepare_gate = cirq_ft.StatePreparationAliasSampling.from_lcu_probs(data, probability_epsilon=eps)
    gate = cirq_ft.ReflectionUsingPrepare(prepare_gate, control_val=None)
    op = gate.on_registers(**infra.get_named_qubits(gate.signature))
    circuit = greedily_allocate_ancilla(cirq.Circuit(cirq.decompose_once(op)))
    cirq.testing.assert_has_diagram(circuit, '\n               ┌──────────────────────────────┐          ┌──────────────────────────────┐\nancilla_0: ─────sigma_mu───────────────────────────────────sigma_mu─────────────────────────\n                │                                          │\nancilla_1: ─────alt────────────────────────────────────────alt──────────────────────────────\n                │                                          │\nancilla_2: ─────alt────────────────────────────────────────alt──────────────────────────────\n                │                                          │\nancilla_3: ─────alt────────────────────────────────────────alt──────────────────────────────\n                │                                          │\nancilla_4: ─────keep───────────────────────────────────────keep─────────────────────────────\n                │                                          │\nancilla_5: ─────less_than_equal────────────────────────────less_than_equal──────────────────\n                │                                          │\nancilla_6: ─────┼────────────────────────────X────Z───────X┼────────────────────────────────\n                │                                 │        │\nselection0: ────StatePreparationAliasSampling─────@(0)─────StatePreparationAliasSampling────\n                │                                 │        │\nselection1: ────selection─────────────────────────@(0)─────selection────────────────────────\n                │                                 │        │\nselection2: ────selection^-1──────────────────────@(0)─────selection────────────────────────\n               └──────────────────────────────┘          └──────────────────────────────┘')
    gate = cirq_ft.ReflectionUsingPrepare(prepare_gate, control_val=1)
    op = gate.on_registers(**infra.get_named_qubits(gate.signature))
    circuit = greedily_allocate_ancilla(cirq.Circuit(cirq.decompose_once(op)))
    cirq.testing.assert_has_diagram(circuit, '\nancilla_0: ────sigma_mu───────────────────────────────sigma_mu────────────────────────\n               │                                      │\nancilla_1: ────alt────────────────────────────────────alt─────────────────────────────\n               │                                      │\nancilla_2: ────alt────────────────────────────────────alt─────────────────────────────\n               │                                      │\nancilla_3: ────alt────────────────────────────────────alt─────────────────────────────\n               │                                      │\nancilla_4: ────keep───────────────────────────────────keep────────────────────────────\n               │                                      │\nancilla_5: ────less_than_equal────────────────────────less_than_equal─────────────────\n               │                                      │\ncontrol: ──────┼───────────────────────────────Z──────┼───────────────────────────────\n               │                               │      │\nselection0: ───StatePreparationAliasSampling───@(0)───StatePreparationAliasSampling───\n               │                               │      │\nselection1: ───selection───────────────────────@(0)───selection───────────────────────\n               │                               │      │\nselection2: ───selection^-1────────────────────@(0)───selection───────────────────────\n')
    gate = cirq_ft.ReflectionUsingPrepare(prepare_gate, control_val=0)
    op = gate.on_registers(**infra.get_named_qubits(gate.signature))
    circuit = greedily_allocate_ancilla(cirq.Circuit(cirq.decompose_once(op)))
    cirq.testing.assert_has_diagram(circuit, '\n               ┌──────────────────────────────┐          ┌──────────────────────────────┐\nancilla_0: ─────sigma_mu───────────────────────────────────sigma_mu─────────────────────────\n                │                                          │\nancilla_1: ─────alt────────────────────────────────────────alt──────────────────────────────\n                │                                          │\nancilla_2: ─────alt────────────────────────────────────────alt──────────────────────────────\n                │                                          │\nancilla_3: ─────alt────────────────────────────────────────alt──────────────────────────────\n                │                                          │\nancilla_4: ─────keep───────────────────────────────────────keep─────────────────────────────\n                │                                          │\nancilla_5: ─────less_than_equal────────────────────────────less_than_equal──────────────────\n                │                                          │\ncontrol: ───────┼────────────────────────────X────Z───────X┼────────────────────────────────\n                │                                 │        │\nselection0: ────StatePreparationAliasSampling─────@(0)─────StatePreparationAliasSampling────\n                │                                 │        │\nselection1: ────selection─────────────────────────@(0)─────selection────────────────────────\n                │                                 │        │\nselection2: ────selection^-1──────────────────────@(0)─────selection────────────────────────\n               └──────────────────────────────┘          └──────────────────────────────┘\n')