import unittest
import textwrap
from collections import defaultdict
def test_instantiate_from_kv_with_child_inherit(self):
    from kivy.lang import Builder

    class TestEventsFromKVChildInherit(TrackCallbacks.get_base_class()):
        instantiated_widgets = []
    widget = Builder.load_string(textwrap.dedent("\n        <TestEventsFromKVChildInherit2@TestEventsFromKVChildInherit>:\n            on_kv_pre: self.add(3, 'pre')\n            on_kv_applied: self.add(3, 'applied')\n            on_kv_post: self.add(3, 'post')\n\n        <TestEventsFromKVChildInherit3@TestEventsFromKVChildInherit2>:\n            on_kv_pre: self.add(4, 'pre')\n            on_kv_applied: self.add(4, 'applied')\n            on_kv_post: self.add(4, 'post')\n            some_value: 'fruit'\n            TestEventsFromKVChildInherit2:\n                events_in_applied: [1, 2, 3]\n                events_in_post: [1, 2, 3, 4]\n                on_kv_pre: self.add(4, 'pre')\n                on_kv_applied: self.add(4, 'applied')\n                on_kv_post: self.add(4, 'post')\n                root_widget: root\n                base_widget: self.parent.parent\n                name: 'third child'\n                id: third_child\n                my_roots_expected_ids: {'third_child': self}\n\n        <TestEventsFromKVChildInherit>:\n            on_kv_pre: self.add(2, 'pre')\n            on_kv_applied: self.add(2, 'applied')\n            on_kv_post: self.add(2, 'post')\n            another_value: 'apple'\n\n        TestEventsFromKVChildInherit:\n            events_in_applied: [1, 2]\n            events_in_post: [1, 2, 3]\n            on_kv_pre: self.add(3, 'pre')\n            on_kv_applied: self.add(3, 'applied')\n            on_kv_post: self.add(3, 'post')\n            root_widget: self\n            base_widget: self\n            name: 'root'\n            my_roots_expected_ids:                 {'second_child': second_child, 'first_child': first_child}\n            TestEventsFromKVChildInherit:\n                events_in_applied: [1, 2]\n                events_in_post: [1, 2, 3]\n                on_kv_pre: self.add(3, 'pre')\n                on_kv_applied: self.add(3, 'applied')\n                on_kv_post: self.add(3, 'post')\n                root_widget: root\n                base_widget: root\n                name: 'first child'\n                id: first_child\n                my_roots_expected_ids:                     {'second_child': second_child, 'first_child': self}\n            TestEventsFromKVChildInherit3:\n                events_in_applied: [1, 2, 3, 4]\n                events_in_post: [1, 2, 3, 4, 5]\n                on_kv_pre: self.add(5, 'pre')\n                on_kv_applied: self.add(5, 'applied')\n                on_kv_post: self.add(5, 'post')\n                root_widget: root\n                base_widget: root\n                name: 'second child'\n                some_value: first_child.another_value\n                expected_prop_values: {'some_value': 'apple'}\n                id: second_child\n                my_roots_expected_ids:                     {'second_child': self, 'first_child': first_child}\n        "))
    widget.check(self)