import pyomo.common.unittest as unittest
from pyomo.environ import (
def test_non_negative_propagate(self):
    """Test zero sum propagation for non-negative vars."""
    m = ConcreteModel()
    m.v1 = Var(initialize=0)
    m.v2 = Var(initialize=2, domain=NonNegativeReals)
    m.v3 = Var(initialize=3, domain=NonNegativeReals)
    m.v4 = Var(initialize=4, domain=NonNegativeReals)
    m.c1 = Constraint(expr=m.v1 == m.v2 + m.v3 + m.v4)
    m.v1.fix()
    TransformationFactory('contrib.propagate_zero_sum').apply_to(m)
    self.assertTrue(m.v1.fixed)
    self.assertTrue(m.v2.fixed)
    self.assertTrue(m.v3.fixed)
    self.assertTrue(m.v4.fixed)
    del m
    m = ConcreteModel()
    m.v1 = Var(initialize=0)
    m.v2 = Var(initialize=2, domain=NonNegativeReals)
    m.v3 = Var(initialize=3, domain=NonNegativeReals)
    m.v4 = Var(initialize=4, domain=NonNegativeReals)
    m.c1 = Constraint(expr=m.v2 + m.v3 + m.v4 == m.v1)
    m.v1.fix()
    TransformationFactory('contrib.propagate_zero_sum').apply_to(m)
    self.assertTrue(m.v1.fixed)
    self.assertTrue(m.v2.fixed)
    self.assertTrue(m.v3.fixed)
    self.assertTrue(m.v4.fixed)
    del m
    m = ConcreteModel()
    m.v1 = Var(initialize=0)
    m.v2 = Var(initialize=2, domain=NonNegativeReals)
    m.v3 = Var(initialize=3, domain=NonNegativeReals)
    m.v4 = Var(initialize=4, domain=NonNegativeReals)
    m.c1 = Constraint(expr=m.v1 >= m.v2 + m.v3 + m.v4)
    m.v1.fix()
    TransformationFactory('contrib.propagate_zero_sum').apply_to(m)
    self.assertTrue(m.v1.fixed)
    self.assertTrue(m.v2.fixed)
    self.assertTrue(m.v3.fixed)
    self.assertTrue(m.v4.fixed)