import sys
import weakref
from rdkit import Chem
from rdkit.Chem import rdChemReactions as Reactions
def testUreaRxn(self):
    m = Chem.MolFromSmiles('C1CC1NC(=O)NC1OC1')
    res = RecapDecompose(m, onlyUseReactions=[0])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*NC1CC1' in ks)
    self.assertTrue('*NC1CO1' in ks)
    m = Chem.MolFromSmiles('C1CC1NC(=O)N(C)C1OC1')
    res = RecapDecompose(m, onlyUseReactions=[0])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*NC1CC1' in ks)
    self.assertTrue('*N(C)C1CO1' in ks)
    m = Chem.MolFromSmiles('C1CCNC(=O)NC1C')
    res = RecapDecompose(m, onlyUseReactions=[0])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 0)
    m = Chem.MolFromSmiles('c1cccn1C(=O)NC1OC1')
    res = RecapDecompose(m, onlyUseReactions=[0])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*n1cccc1' in ks)
    self.assertTrue('*NC1CO1' in ks)
    m = Chem.MolFromSmiles('c1cccn1C(=O)n1c(C)ccc1')
    res = RecapDecompose(m, onlyUseReactions=[0])
    self.assertTrue(res)
    self.assertTrue(len(res.GetLeaves()) == 2)
    ks = res.GetLeaves().keys()
    self.assertTrue('*n1cccc1C' in ks)