import datetime
import logging
import logging.handlers
import os
import re
import socket
import sys
import threading
import ovs.dirs
import ovs.unixctl
import ovs.util
def warn_is_enabled(self):
    return self.__is_enabled('WARN')