import pytest
import numpy as np
import cirq
import cirq_google
from cirq_google.transformers.target_gatesets import sycamore_gateset
def test_merge_swap_rzz_and_2q_unitaries():
    q = cirq.LineQubit.range(3)
    c_orig = cirq.Circuit(cirq.SWAP(*q[:2]), cirq.ZZ(*q[:2]) ** 0.5, cirq.ZZ(*q[:2]) ** 0.25, cirq.SWAP(*q[:2]), cirq.SWAP(q[0], q[2]).with_tags('ignore'), cirq.ZZ(q[0], q[2]) ** 0.75, cirq.Moment(cirq.H.on_each(*q)), cirq.CNOT(q[0], q[2]), cirq.CircuitOperation(cirq.FrozenCircuit(cirq.CNOT(*q[0:2]), cirq.H(q[0]), cirq.CZ(*q[:2]))), cirq.CNOT(*q[1:3]), cirq.X(q[0]), cirq.ZZ(*q[:2]) ** 0.15, cirq.SWAP(*q[:2]), cirq.Moment(cirq.X(q[0]).with_tags('ignore'), cirq.Y(q[1])), cirq.CNOT(*q[:2]), strategy=cirq.InsertStrategy.NEW)
    cirq.testing.assert_has_diagram(c_orig, "\n                                                                 [ 0: ───@───H───@─── ]\n0: ───×───ZZ───────ZZ────────×───×['ignore']───ZZ────────H───@───[       │       │    ]───────X───ZZ────────×───X['ignore']───@───\n      │   │        │         │   │             │             │   [ 1: ───X───────@─── ]           │         │                 │\n      │   │        │         │   │             │             │   │                                │         │                 │\n1: ───×───ZZ^0.5───ZZ^0.25───×───┼─────────────┼─────────H───┼───#2───────────────────────@───────ZZ^0.15───×───Y─────────────X───\n                                 │             │             │                            │\n2: ──────────────────────────────×─────────────ZZ^0.75───H───X────────────────────────────X───────────────────────────────────────\n")
    c_new = sycamore_gateset.merge_swap_rzz_and_2q_unitaries(c_orig, context=cirq.TransformerContext(tags_to_ignore=('ignore',)), merged_swap_rzz_tag='swap_rzz', merged_2q_component_tag='2q_component')
    cirq.testing.assert_has_diagram(c_new, "\n                                                                                                                                                                [           [ 0: ───@───H───@─── ]        ]\n      [ 0: ───×───ZZ─────── ]                   [ 0: ───ZZ────────×─── ]                                 [ 0: ───ZZ────────H───@─── ]                           [ 0: ───────[       │       │    ]───X─── ]                           [ 0: ───ZZ────────×─── ]                                 [ 0: ───────@─── ]\n0: ───[       │   │         ]───────────────────[       │         │    ]───────────────────×['ignore']───[       │             │    ]───────────────────────────[           [ 1: ───X───────@─── ]        ]───────────────────────────[       │         │    ]───────────────────X['ignore']───[           │    ]───────────────────\n      [ 1: ───×───ZZ^0.5─── ]['swap_rzz']       [ 1: ───ZZ^0.25───×─── ]['swap_rzz']       │             [ 2: ───ZZ^0.75───H───X─── ]['2q_component']           [           │                             ]                           [ 1: ───ZZ^0.15───×─── ]['swap_rzz']                     [ 1: ───Y───X─── ]['2q_component']\n      │                                         │                                          │             │                                                      [ 1: ───H───#2─────────────────────────── ]['2q_component']           │                                                        │\n      │                                         │                                          │             │                                                      │                                                                     │                                                        │\n1: ───#2────────────────────────────────────────#2─────────────────────────────────────────┼─────────────┼──────────────────────────────────────────────────────#2────────────────────────────────────────────────────────────@───────#2───────────────────────────────────────────────────────#2───────────────────────────────────\n                                                                                           │             │                                                                                                                    │\n2: ────────────────────────────────────────────────────────────────────────────────────────×─────────────#2───────────────────────────────────────────────────────────────────────────────────────────────────────────────────X─────────────────────────────────────────────────────────────────────────────────────────────────────\n")