import os
import re
import unicodedata as ud
from .. import osutils, tests
from .._termcolor import FG, color_string
from ..tests.features import UnicodeFilenameFeature
def test_ver_files_without_matches(self):
    """(ver) Ensure --files-without-match, -L works
        """
    wd = 'foobar0'
    self.make_branch_and_tree(wd)
    os.chdir(wd)
    self._mk_versioned_file('file0.txt', total_lines=2)
    self._mk_versioned_file('file1.txt', total_lines=2)
    self._mk_versioned_dir('dir0')
    self._mk_versioned_file('dir0/file00.txt', total_lines=2)
    self._mk_versioned_file('dir0/file01.txt', total_lines=2)
    self._update_file('file0.txt', 'HELLO\n')
    self._update_file('dir0/file00.txt', 'HELLO\n')
    out, err = self.run_bzr(['grep', '-r', '-1', '--files-without-match', 'HELLO'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 2)
    out, err = self.run_bzr(['grep', '-r', '-1', '--files-without-match', 'H.LLO'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 2)
    out, err = self.run_bzr(['grep', '-r', '6..7', '--files-without-match', 'HELLO'])
    self.assertContainsRe(out, '^file1.txt~6$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file00.txt~6$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~6$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 5)
    out, err = self.run_bzr(['grep', '-r', '6..7', '--files-without-match', 'H.LLO'])
    self.assertContainsRe(out, '^file1.txt~6$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file00.txt~6$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~6$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 5)
    out, err = self.run_bzr(['grep', '-r', '-1', '-L', 'HELLO'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 2)
    out, err = self.run_bzr(['grep', '-r', '-1', '-L', 'H.LLO'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 2)
    out, err = self.run_bzr(['grep', '-L', 'HELLO', '-r', '-1', 'dir0', 'file1.txt'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 2)
    out, err = self.run_bzr(['grep', '-L', 'H.LLO', '-r', '-1', 'dir0', 'file1.txt'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertContainsRe(out, '^dir0/file01.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 2)
    out, err = self.run_bzr(['grep', '-L', 'HELLO', '-r', '-2', 'file1.txt'])
    self.assertContainsRe(out, '^file1.txt~6$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 1)
    out, err = self.run_bzr(['grep', '-L', 'HE.LO', '-r', '-2', 'file1.txt'])
    self.assertContainsRe(out, '^file1.txt~6$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 1)
    out, err = self.run_bzr(['grep', '--no-recursive', '-r', '-1', '-L', 'HELLO'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 1)
    out, err = self.run_bzr(['grep', '--no-recursive', '-r', '-1', '-L', '.ELLO'])
    self.assertContainsRe(out, '^file1.txt~7$', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 1)