import shutil
import sys
from breezy import (branch, controldir, errors, info, osutils, tests, upgrade,
from breezy.bzr import bzrdir
from breezy.transport import memory
def test_info_shared_repository(self):
    format = controldir.format_registry.make_controldir('knit')
    transport = self.get_transport()
    repo = self.make_repository('repo', shared=True, format=format)
    repo.set_make_working_trees(False)
    out, err = self.run_bzr('info -v repo')
    self.assertEqualDiff('Shared repository (format: dirstate or dirstate-tags or knit)\nLocation:\n  shared repository: {}\n\nFormat:\n       control: Meta directory format 1\n    repository: {}\n\nControl directory:\n         0 branches\n\nRepository:\n         0 revisions\n'.format('repo', format.repository_format.get_format_description()), out)
    self.assertEqual('', err)
    repo.controldir.root_transport.mkdir('branch')
    branch1 = controldir.ControlDir.create_branch_convenience('repo/branch', format=format)
    out, err = self.run_bzr('info -v repo/branch')
    self.assertEqualDiff('Repository branch (format: dirstate or knit)\nLocation:\n  shared repository: repo\n  repository branch: repo/branch\n\nFormat:\n       control: Meta directory format 1\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nBranch history:\n         0 revisions\n\nRepository:\n         0 revisions\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description()), out)
    self.assertEqual('', err)
    transport.mkdir('tree')
    transport.mkdir('tree/lightcheckout')
    tree2 = branch1.create_checkout('tree/lightcheckout', lightweight=True)
    branch2 = tree2.branch
    self.assertCheckoutStatusOutput('-v tree/lightcheckout', tree2, shared_repo=repo, repo_branch=branch1, verbose=True)
    tree3 = branch1.create_checkout('tree/checkout')
    self.assertCheckoutStatusOutput('tree/checkout --verbose', tree3, verbose=True, light_checkout=False, repo_branch=branch1)
    self.build_tree(['tree/lightcheckout/a'])
    tree2.add('a')
    tree2.commit('commit one')
    rev = repo.get_revision(branch2.last_revision())
    datestring_first = osutils.format_date(rev.timestamp, rev.timezone)
    out, err = self.run_bzr('info tree/lightcheckout --verbose')
    self.assertEqualDiff('Lightweight checkout (format: {})\nLocation:\n  light checkout root: tree/lightcheckout\n   checkout of branch: repo/branch\n    shared repository: repo\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 6\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(self._repo_strings, format.get_branch_format().get_format_description(), format.repository_format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info -v tree/checkout')
    self.assertEqualDiff('Checkout (format: unnamed)\nLocation:\n       checkout root: tree/checkout\n  checkout of branch: repo/branch\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 6\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nBranch is out of date: missing 1 revision.\n\nIn the working tree:\n         0 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         0 revisions\n\nRepository:\n         0 revisions\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description()), out)
    self.assertEqual('', err)
    tree3.update()
    self.build_tree(['tree/checkout/b'])
    tree3.add('b')
    out, err = self.run_bzr('info tree/checkout --verbose')
    self.assertEqualDiff('Checkout (format: unnamed)\nLocation:\n       checkout root: tree/checkout\n  checkout of branch: repo/branch\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 6\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         1 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    tree3.commit('commit two')
    rev = repo.get_revision(branch1.last_revision())
    datestring_last = osutils.format_date(rev.timestamp, rev.timezone)
    out, err = self.run_bzr('info tree/lightcheckout --verbose')
    self.assertEqualDiff('Lightweight checkout (format: {})\nLocation:\n  light checkout root: tree/lightcheckout\n   checkout of branch: repo/branch\n    shared repository: repo\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 6\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nWorking tree is out of date: missing 1 revision.\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         2 revisions\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         2 revisions\n'.format(self._repo_strings, format.get_branch_format().get_format_description(), format.repository_format.get_format_description(), datestring_first, datestring_last), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info repo/branch --verbose')
    self.assertEqualDiff('Repository branch (format: dirstate or knit)\nLocation:\n  shared repository: repo\n  repository branch: repo/branch\n\nFormat:\n       control: Meta directory format 1\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nBranch history:\n         2 revisions\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         2 revisions\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description(), datestring_first, datestring_last), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info -v repo')
    self.assertEqualDiff('Shared repository (format: dirstate or dirstate-tags or knit)\nLocation:\n  shared repository: repo\n\nFormat:\n       control: Meta directory format 1\n    repository: {}\n\nControl directory:\n         0 branches\n\nRepository:\n         2 revisions\n'.format(format.repository_format.get_format_description()), out)
    self.assertEqual('', err)