import argparse
from unittest import mock
import testtools
from aodhclient.v2 import alarm_cli
def test_alarm_from_args(self):
    parser = self.cli_alarm_create.get_parser('aodh alarm create')
    test_parsed_args = parser.parse_args(['--type', 'event', '--name', 'alarm_from_args_test', '--project-id', '01919bbd-8b0e-451c-be28-abe250ae9b1b', '--user-id', '01919bbd-8b0e-451c-be28-abe250ae9c1c', '--description', 'For Test', '--state', 'ok', '--severity', 'critical', '--enabled', 'True', '--alarm-action', 'http://something/alarm', '--ok-action', 'http://something/ok', '--repeat-action', 'True', '--insufficient-data-action', 'http://something/insufficient', '--time-constraint', 'name=cons1;start="0 11 * * *";duration=300;description=desc1', '--evaluation-periods', '60', '--comparison-operator', 'le', '--threshold', '80', '--event-type', 'event', '--query', 'resource=fake-resource-id', '--granularity', '60', '--aggregation-method', 'last', '--metric', 'cpu', '--resource-id', '01919bbd-8b0e-451c-be28-abe250ae9c1c', '--resource-type', 'generic', '--stack-id', '0809ab348-8b0e-451c-be28-abe250ae9c1c', '--pool-id', '79832aabf-343ba-be28-abe250ae9c1c', '--autoscaling-group-id', 'abe250ae9c1c-79832aabf-343ba-be28'])
    alarm = {'name': 'alarm_from_args_test', 'project_id': '01919bbd-8b0e-451c-be28-abe250ae9b1b', 'user_id': '01919bbd-8b0e-451c-be28-abe250ae9c1c', 'description': 'For Test', 'state': 'ok', 'severity': 'critical', 'enabled': True, 'alarm_actions': ['http://something/alarm'], 'ok_actions': ['http://something/ok'], 'insufficient_data_actions': ['http://something/insufficient'], 'time_constraints': [{'description': 'desc1', 'duration': '300', 'name': 'cons1', 'start': '0 11 * * *'}], 'repeat_actions': True, 'event_rule': {'event_type': 'event', 'query': [{'field': 'resource', 'op': 'eq', 'type': '', 'value': 'fake-resource-id'}]}, 'threshold_rule': {'comparison_operator': 'le', 'evaluation_periods': 60, 'query': [{'field': 'resource', 'op': 'eq', 'type': '', 'value': 'fake-resource-id'}], 'threshold': 80.0}, 'prometheus_rule': {'comparison_operator': 'le', 'query': [{'field': 'resource', 'op': 'eq', 'type': '', 'value': 'fake-resource-id'}], 'threshold': 80.0}, 'gnocchi_resources_threshold_rule': {'granularity': '60', 'metric': 'cpu', 'aggregation_method': 'last', 'evaluation_periods': 60, 'resource_id': '01919bbd-8b0e-451c-be28-abe250ae9c1c', 'comparison_operator': 'le', 'threshold': 80.0, 'resource_type': 'generic'}, 'gnocchi_aggregation_by_metrics_threshold_rule': {'granularity': '60', 'aggregation_method': 'last', 'evaluation_periods': 60, 'comparison_operator': 'le', 'threshold': 80.0, 'metrics': ['cpu']}, 'loadbalancer_member_health_rule': {'autoscaling_group_id': 'abe250ae9c1c-79832aabf-343ba-be28', 'pool_id': '79832aabf-343ba-be28-abe250ae9c1c', 'stack_id': '0809ab348-8b0e-451c-be28-abe250ae9c1c'}, 'gnocchi_aggregation_by_resources_threshold_rule': {'granularity': '60', 'metric': 'cpu', 'aggregation_method': 'last', 'evaluation_periods': 60, 'comparison_operator': 'le', 'threshold': 80.0, 'query': [{'field': 'resource', 'op': 'eq', 'type': '', 'value': 'fake-resource-id'}], 'resource_type': 'generic'}, 'composite_rule': None, 'type': 'event'}
    alarm_rep = self.cli_alarm_create._alarm_from_args(test_parsed_args)
    self.assertEqual(alarm, alarm_rep)