from weakref import proxy
import copy
import pickle
import regex
import string
import sys
import unittest
def test_search_reverse(self):
    self.assertEqual(regex.findall('(?r).', 'abc'), ['c', 'b', 'a'])
    self.assertEqual(regex.findall('(?r).', 'abc', overlapped=True), ['c', 'b', 'a'])
    self.assertEqual(regex.findall('(?r)..', 'abcde'), ['de', 'bc'])
    self.assertEqual(regex.findall('(?r)..', 'abcde', overlapped=True), ['de', 'cd', 'bc', 'ab'])
    self.assertEqual(regex.findall('(?r)(.)(-)(.)', 'a-b-c', overlapped=True), [('b', '-', 'c'), ('a', '-', 'b')])
    self.assertEqual([m[0] for m in regex.finditer('(?r).', 'abc')], ['c', 'b', 'a'])
    self.assertEqual([m[0] for m in regex.finditer('(?r)..', 'abcde', overlapped=True)], ['de', 'cd', 'bc', 'ab'])
    self.assertEqual([m[0] for m in regex.finditer('(?r).', 'abc')], ['c', 'b', 'a'])
    self.assertEqual([m[0] for m in regex.finditer('(?r)..', 'abcde', overlapped=True)], ['de', 'cd', 'bc', 'ab'])
    self.assertEqual(regex.findall('^|\\w+', 'foo bar'), ['', 'foo', 'bar'])
    self.assertEqual(regex.findall('(?V1)^|\\w+', 'foo bar'), ['', 'foo', 'bar'])
    self.assertEqual(regex.findall('(?r)^|\\w+', 'foo bar'), ['bar', 'foo', ''])
    self.assertEqual(regex.findall('(?rV1)^|\\w+', 'foo bar'), ['bar', 'foo', ''])
    self.assertEqual([m[0] for m in regex.finditer('^|\\w+', 'foo bar')], ['', 'foo', 'bar'])
    self.assertEqual([m[0] for m in regex.finditer('(?V1)^|\\w+', 'foo bar')], ['', 'foo', 'bar'])
    self.assertEqual([m[0] for m in regex.finditer('(?r)^|\\w+', 'foo bar')], ['bar', 'foo', ''])
    self.assertEqual([m[0] for m in regex.finditer('(?rV1)^|\\w+', 'foo bar')], ['bar', 'foo', ''])
    self.assertEqual(regex.findall('\\G\\w{2}', 'abcd ef'), ['ab', 'cd'])
    self.assertEqual(regex.findall('.{2}(?<=\\G.*)', 'abcd'), ['ab', 'cd'])
    self.assertEqual(regex.findall('(?r)\\G\\w{2}', 'abcd ef'), [])
    self.assertEqual(regex.findall('(?r)\\w{2}\\G', 'abcd ef'), ['ef'])
    self.assertEqual(regex.findall('q*', 'qqwe'), ['qq', '', '', ''])
    self.assertEqual(regex.findall('(?V1)q*', 'qqwe'), ['qq', '', '', ''])
    self.assertEqual(regex.findall('(?r)q*', 'qqwe'), ['', '', 'qq', ''])
    self.assertEqual(regex.findall('(?rV1)q*', 'qqwe'), ['', '', 'qq', ''])
    self.assertEqual(regex.findall('.', 'abcd', pos=1, endpos=3), ['b', 'c'])
    self.assertEqual(regex.findall('.', 'abcd', pos=1, endpos=-1), ['b', 'c'])
    self.assertEqual([m[0] for m in regex.finditer('.', 'abcd', pos=1, endpos=3)], ['b', 'c'])
    self.assertEqual([m[0] for m in regex.finditer('.', 'abcd', pos=1, endpos=-1)], ['b', 'c'])
    self.assertEqual([m[0] for m in regex.finditer('(?r).', 'abcd', pos=1, endpos=3)], ['c', 'b'])
    self.assertEqual([m[0] for m in regex.finditer('(?r).', 'abcd', pos=1, endpos=-1)], ['c', 'b'])
    self.assertEqual(regex.findall('(?r).', 'abcd', pos=1, endpos=3), ['c', 'b'])
    self.assertEqual(regex.findall('(?r).', 'abcd', pos=1, endpos=-1), ['c', 'b'])
    self.assertEqual(regex.findall('[ab]', 'aB', regex.I), ['a', 'B'])
    self.assertEqual(regex.findall('(?r)[ab]', 'aB', regex.I), ['B', 'a'])
    self.assertEqual(regex.findall('(?r).{2}', 'abc'), ['bc'])
    self.assertEqual(regex.findall('(?r).{2}', 'abc', overlapped=True), ['bc', 'ab'])
    self.assertEqual(regex.findall('(\\w+) (\\w+)', 'first second third fourth fifth'), [('first', 'second'), ('third', 'fourth')])
    self.assertEqual(regex.findall('(?r)(\\w+) (\\w+)', 'first second third fourth fifth'), [('fourth', 'fifth'), ('second', 'third')])
    self.assertEqual([m[0] for m in regex.finditer('(?r).{2}', 'abc')], ['bc'])
    self.assertEqual([m[0] for m in regex.finditer('(?r).{2}', 'abc', overlapped=True)], ['bc', 'ab'])
    self.assertEqual([m[0] for m in regex.finditer('(\\w+) (\\w+)', 'first second third fourth fifth')], ['first second', 'third fourth'])
    self.assertEqual([m[0] for m in regex.finditer('(?r)(\\w+) (\\w+)', 'first second third fourth fifth')], ['fourth fifth', 'second third'])
    self.assertEqual(regex.search('abcdef', 'abcdef').span(), (0, 6))
    self.assertEqual(regex.search('(?r)abcdef', 'abcdef').span(), (0, 6))
    self.assertEqual(regex.search('(?i)abcdef', 'ABCDEF').span(), (0, 6))
    self.assertEqual(regex.search('(?ir)abcdef', 'ABCDEF').span(), (0, 6))
    self.assertEqual(regex.sub('(.)', '\\1', 'abc'), 'abc')
    self.assertEqual(regex.sub('(?r)(.)', '\\1', 'abc'), 'abc')