import pyomo.common.unittest as unittest
from pyomo.core.base.indexed_component import normalize_index
from pyomo.core.base.indexed_component_slice import IndexedComponent_slice
from pyomo.core.base.global_set import UnindexedComponent_set
import pyomo.environ as pyo
import pyomo.dae as dae
from pyomo.common.collections import ComponentSet, ComponentMap
from pyomo.util.slices import (
def test_dimen_none_replacement(self):
    m = self.model()
    index_set = m.b0dn.index_set()
    index = ('c', 1, 10)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet((m.d_none,))
    pred_index = (Ellipsis,)
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    sets = ComponentSet()
    pred_index = ('c', 1, 10)
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    index_set = m.b1dn.index_set()
    index = (1, 'c', 1, 10)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet((m.d_none,))
    pred_index = (1, Ellipsis)
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    sets = ComponentSet((m.d_none, m.time))
    pred_index = (slice(None), Ellipsis)
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    index_set = m.b1dnd2.index_set()
    index = (1, 'c', 1, 10, 'a', 1)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet((m.d_none, m.time, m.d_2))
    pred_index = (slice(None), Ellipsis, slice(None), slice(None))
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    sets = ComponentSet((m.time, m.d_2))
    pred_index = (slice(None), 'c', 1, 10, slice(None), slice(None))
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    sets = ComponentSet((m.d_2,))
    pred_index = (1, 'c', 1, 10, slice(None), slice(None))
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    index_set = m.b2dn.index_set()
    index = (1, 0, 'd', 3)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet()
    pred_index = (1, 0, 'd', 3)
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    sets = ComponentSet((m.d_none,))
    pred_index = (1, 0, Ellipsis)
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    index_set = m.b2dnd2.index_set()
    index = (1, 'c', 1, 10, 'b', 2, 0)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet((m.d_none, m.space))
    pred_index = (1, Ellipsis, 'b', 2, slice(None))
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    index_set = m.dnd2b1.index_set()
    index = ('d', 3, 'b', 2, 1)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet((m.d_none, m.time))
    pred_index = (Ellipsis, 'b', 2, slice(None))
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)
    index_set = m.b3dn.index_set()
    index = (1, 'a', 1, 'd', 3, 0, 'b', 2)
    location_set_map = get_location_set_map(index, index_set)
    sets = ComponentSet((m.d_none, m.d_2))
    pred_index = (1, slice(None), slice(None), Ellipsis, 0, slice(None), slice(None))
    new_index = replace_indices(index, location_set_map, sets)
    self.assertEqual(new_index, pred_index)