import pytest
import numpy as np
import numpy.ma as ma
from numpy.ma.mrecords import MaskedRecords
from numpy.ma.testutils import assert_equal
from numpy.testing import assert_, assert_raises
from numpy.lib.recfunctions import (
def test_structured_to_unstructured(self, tmp_path):
    a = np.zeros(4, dtype=[('a', 'i4'), ('b', 'f4,u2'), ('c', 'f4', 2)])
    out = structured_to_unstructured(a)
    assert_equal(out, np.zeros((4, 5), dtype='f8'))
    b = np.array([(1, 2, 5), (4, 5, 7), (7, 8, 11), (10, 11, 12)], dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])
    out = np.mean(structured_to_unstructured(b[['x', 'z']]), axis=-1)
    assert_equal(out, np.array([3.0, 5.5, 9.0, 11.0]))
    out = np.mean(structured_to_unstructured(b[['x']]), axis=-1)
    assert_equal(out, np.array([1.0, 4.0, 7.0, 10.0]))
    c = np.arange(20).reshape((4, 5))
    out = unstructured_to_structured(c, a.dtype)
    want = np.array([(0, (1.0, 2), [3.0, 4.0]), (5, (6.0, 7), [8.0, 9.0]), (10, (11.0, 12), [13.0, 14.0]), (15, (16.0, 17), [18.0, 19.0])], dtype=[('a', 'i4'), ('b', [('f0', 'f4'), ('f1', 'u2')]), ('c', 'f4', (2,))])
    assert_equal(out, want)
    d = np.array([(1, 2, 5), (4, 5, 7), (7, 8, 11), (10, 11, 12)], dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])
    assert_equal(apply_along_fields(np.mean, d), np.array([8.0 / 3, 16.0 / 3, 26.0 / 3, 11.0]))
    assert_equal(apply_along_fields(np.mean, d[['x', 'z']]), np.array([3.0, 5.5, 9.0, 11.0]))
    d = np.array([(1, 2, 5), (4, 5, 7), (7, 8, 11), (10, 11, 12)], dtype=[('x', 'i4'), ('y', 'i4'), ('z', 'i4')])
    dd = structured_to_unstructured(d)
    ddd = unstructured_to_structured(dd, d.dtype)
    assert_(np.shares_memory(dd, d))
    assert_(np.shares_memory(ddd, d))
    dd_attrib_rev = structured_to_unstructured(d[['z', 'x']])
    assert_equal(dd_attrib_rev, [[5, 1], [7, 4], [11, 7], [12, 10]])
    assert_(np.shares_memory(dd_attrib_rev, d))
    d = np.array([(1, [2, 3], [[4, 5], [6, 7]]), (8, [9, 10], [[11, 12], [13, 14]])], dtype=[('x0', 'i4'), ('x1', ('i4', 2)), ('x2', ('i4', (2, 2)))])
    dd = structured_to_unstructured(d)
    ddd = unstructured_to_structured(dd, d.dtype)
    assert_(np.shares_memory(dd, d))
    assert_(np.shares_memory(ddd, d))
    d_rev = d[::-1]
    dd_rev = structured_to_unstructured(d_rev)
    assert_equal(dd_rev, [[8, 9, 10, 11, 12, 13, 14], [1, 2, 3, 4, 5, 6, 7]])
    d_attrib_rev = d[['x2', 'x1', 'x0']]
    dd_attrib_rev = structured_to_unstructured(d_attrib_rev)
    assert_equal(dd_attrib_rev, [[4, 5, 6, 7, 2, 3, 1], [11, 12, 13, 14, 9, 10, 8]])
    d = np.array([(1, [2, 3], [[4, 5], [6, 7]], 32), (8, [9, 10], [[11, 12], [13, 14]], 64)], dtype=[('x0', 'i4'), ('x1', ('i4', 2)), ('x2', ('i4', (2, 2))), ('ignored', 'u1')])
    dd = structured_to_unstructured(d[['x0', 'x1', 'x2']])
    assert_(np.shares_memory(dd, d))
    assert_equal(dd, [[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
    point = np.dtype([('x', int), ('y', int)])
    triangle = np.dtype([('a', point), ('b', point), ('c', point)])
    arr = np.zeros(10, triangle)
    res = structured_to_unstructured(arr, dtype=int)
    assert_equal(res, np.zeros((10, 6), dtype=int))

    def subarray(dt, shape):
        return np.dtype((dt, shape))

    def structured(*dts):
        return np.dtype([('x{}'.format(i), dt) for i, dt in enumerate(dts)])

    def inspect(dt, dtype=None):
        arr = np.zeros((), dt)
        ret = structured_to_unstructured(arr, dtype=dtype)
        backarr = unstructured_to_structured(ret, dt)
        return (ret.shape, ret.dtype, backarr.dtype)
    dt = structured(subarray(structured(np.int32, np.int32), 3))
    assert_equal(inspect(dt), ((6,), np.int32, dt))
    dt = structured(subarray(subarray(np.int32, 2), 2))
    assert_equal(inspect(dt), ((4,), np.int32, dt))
    dt = structured(np.int32)
    assert_equal(inspect(dt), ((1,), np.int32, dt))
    dt = structured(np.int32, subarray(subarray(np.int32, 2), 2))
    assert_equal(inspect(dt), ((5,), np.int32, dt))
    dt = structured()
    assert_raises(ValueError, structured_to_unstructured, np.zeros(3, dt))
    assert_raises(NotImplementedError, structured_to_unstructured, np.zeros(3, dt), dtype=np.int32)
    assert_raises(NotImplementedError, unstructured_to_structured, np.zeros((3, 0), dtype=np.int32))
    d_plain = np.array([(1, 2), (3, 4)], dtype=[('a', 'i4'), ('b', 'i4')])
    dd_expected = structured_to_unstructured(d_plain, copy=True)
    d = d_plain.view(np.recarray)
    dd = structured_to_unstructured(d, copy=False)
    ddd = structured_to_unstructured(d, copy=True)
    assert_(np.shares_memory(d, dd))
    assert_(type(dd) is np.recarray)
    assert_(type(ddd) is np.recarray)
    assert_equal(dd, dd_expected)
    assert_equal(ddd, dd_expected)
    d = np.memmap(tmp_path / 'memmap', mode='w+', dtype=d_plain.dtype, shape=d_plain.shape)
    d[:] = d_plain
    dd = structured_to_unstructured(d, copy=False)
    ddd = structured_to_unstructured(d, copy=True)
    assert_(np.shares_memory(d, dd))
    assert_(type(dd) is np.memmap)
    assert_(type(ddd) is np.memmap)
    assert_equal(dd, dd_expected)
    assert_equal(ddd, dd_expected)