import numpy
import numpy as np
import datetime
import pytest
from numpy.testing import (
from numpy.compat import pickle
def test_datetime_nat_casting(self):
    a = np.array('NaT', dtype='M8[D]')
    b = np.datetime64('NaT', '[D]')
    assert_equal(a.astype('M8[s]'), np.array('NaT', dtype='M8[s]'))
    assert_equal(a.astype('M8[ms]'), np.array('NaT', dtype='M8[ms]'))
    assert_equal(a.astype('M8[M]'), np.array('NaT', dtype='M8[M]'))
    assert_equal(a.astype('M8[Y]'), np.array('NaT', dtype='M8[Y]'))
    assert_equal(a.astype('M8[W]'), np.array('NaT', dtype='M8[W]'))
    assert_equal(np.datetime64(b, '[s]'), np.datetime64('NaT', '[s]'))
    assert_equal(np.datetime64(b, '[ms]'), np.datetime64('NaT', '[ms]'))
    assert_equal(np.datetime64(b, '[M]'), np.datetime64('NaT', '[M]'))
    assert_equal(np.datetime64(b, '[Y]'), np.datetime64('NaT', '[Y]'))
    assert_equal(np.datetime64(b, '[W]'), np.datetime64('NaT', '[W]'))
    assert_equal(np.datetime64(a, '[s]'), np.datetime64('NaT', '[s]'))
    assert_equal(np.datetime64(a, '[ms]'), np.datetime64('NaT', '[ms]'))
    assert_equal(np.datetime64(a, '[M]'), np.datetime64('NaT', '[M]'))
    assert_equal(np.datetime64(a, '[Y]'), np.datetime64('NaT', '[Y]'))
    assert_equal(np.datetime64(a, '[W]'), np.datetime64('NaT', '[W]'))
    nan = np.array([np.nan] * 8)
    fnan = nan.astype('f')
    lnan = nan.astype('g')
    cnan = nan.astype('D')
    cfnan = nan.astype('F')
    clnan = nan.astype('G')
    nat = np.array([np.datetime64('NaT')] * 8)
    assert_equal(nan.astype('M8[ns]'), nat)
    assert_equal(fnan.astype('M8[ns]'), nat)
    assert_equal(lnan.astype('M8[ns]'), nat)
    assert_equal(cnan.astype('M8[ns]'), nat)
    assert_equal(cfnan.astype('M8[ns]'), nat)
    assert_equal(clnan.astype('M8[ns]'), nat)
    nat = np.array([np.timedelta64('NaT')] * 8)
    assert_equal(nan.astype('timedelta64[ns]'), nat)
    assert_equal(fnan.astype('timedelta64[ns]'), nat)
    assert_equal(lnan.astype('timedelta64[ns]'), nat)
    assert_equal(cnan.astype('timedelta64[ns]'), nat)
    assert_equal(cfnan.astype('timedelta64[ns]'), nat)
    assert_equal(clnan.astype('timedelta64[ns]'), nat)