from ipywidgets import (
from ipywidgets.widgets.trait_types import TypedTuple
from traitlets import (
from .._base.Three import ThreeWidget
from .._base.uniforms import uniforms_serialization
from ..enums import *
from ..traits import *
from .Mesh_autogen import Mesh
from ..materials.LineMaterial_autogen import LineMaterial
from ..geometries.LineGeometry_autogen import LineGeometry
import inspect
Line2

    Autogenerated by generate-wrappers.js
    This class is a custom class for pythreejs, with no
    direct corresponding class in three.js.
    