from __future__ import absolute_import
from apitools.base.protorpclite import messages as _messages
from apitools.base.py import encoding
from apitools.base.py import extra_types
class PrimaryTechniquesValueListEntryValuesEnum(_messages.Enum):
    """PrimaryTechniquesValueListEntryValuesEnum enum type.

    Values:
      TECHNIQUE_UNSPECIFIED: Unspecified value.
      MASQUERADING: T1036
      MATCH_LEGITIMATE_NAME_OR_LOCATION: T1036.005
      BOOT_OR_LOGON_INITIALIZATION_SCRIPTS: T1037
      STARTUP_ITEMS: T1037.005
      NETWORK_SERVICE_DISCOVERY: T1046
      PROCESS_DISCOVERY: T1057
      COMMAND_AND_SCRIPTING_INTERPRETER: T1059
      UNIX_SHELL: T1059.004
      PERMISSION_GROUPS_DISCOVERY: T1069
      CLOUD_GROUPS: T1069.003
      APPLICATION_LAYER_PROTOCOL: T1071
      DNS: T1071.004
      SOFTWARE_DEPLOYMENT_TOOLS: T1072
      VALID_ACCOUNTS: T1078
      DEFAULT_ACCOUNTS: T1078.001
      LOCAL_ACCOUNTS: T1078.003
      CLOUD_ACCOUNTS: T1078.004
      PROXY: T1090
      EXTERNAL_PROXY: T1090.002
      MULTI_HOP_PROXY: T1090.003
      ACCOUNT_MANIPULATION: T1098
      ADDITIONAL_CLOUD_CREDENTIALS: T1098.001
      SSH_AUTHORIZED_KEYS: T1098.004
      ADDITIONAL_CONTAINER_CLUSTER_ROLES: T1098.006
      INGRESS_TOOL_TRANSFER: T1105
      NATIVE_API: T1106
      BRUTE_FORCE: T1110
      SHARED_MODULES: T1129
      ACCESS_TOKEN_MANIPULATION: T1134
      TOKEN_IMPERSONATION_OR_THEFT: T1134.001
      EXPLOIT_PUBLIC_FACING_APPLICATION: T1190
      DOMAIN_POLICY_MODIFICATION: T1484
      DATA_DESTRUCTION: T1485
      SERVICE_STOP: T1489
      INHIBIT_SYSTEM_RECOVERY: T1490
      RESOURCE_HIJACKING: T1496
      NETWORK_DENIAL_OF_SERVICE: T1498
      CLOUD_SERVICE_DISCOVERY: T1526
      STEAL_APPLICATION_ACCESS_TOKEN: T1528
      ACCOUNT_ACCESS_REMOVAL: T1531
      STEAL_WEB_SESSION_COOKIE: T1539
      CREATE_OR_MODIFY_SYSTEM_PROCESS: T1543
      ABUSE_ELEVATION_CONTROL_MECHANISM: T1548
      UNSECURED_CREDENTIALS: T1552
      MODIFY_AUTHENTICATION_PROCESS: T1556
      IMPAIR_DEFENSES: T1562
      DISABLE_OR_MODIFY_TOOLS: T1562.001
      EXFILTRATION_OVER_WEB_SERVICE: T1567
      EXFILTRATION_TO_CLOUD_STORAGE: T1567.002
      DYNAMIC_RESOLUTION: T1568
      LATERAL_TOOL_TRANSFER: T1570
      MODIFY_CLOUD_COMPUTE_INFRASTRUCTURE: T1578
      CREATE_SNAPSHOT: T1578.001
      CLOUD_INFRASTRUCTURE_DISCOVERY: T1580
      OBTAIN_CAPABILITIES: T1588
      ACTIVE_SCANNING: T1595
      SCANNING_IP_BLOCKS: T1595.001
      CONTAINER_AND_RESOURCE_DISCOVERY: T1613
    """
    TECHNIQUE_UNSPECIFIED = 0
    MASQUERADING = 1
    MATCH_LEGITIMATE_NAME_OR_LOCATION = 2
    BOOT_OR_LOGON_INITIALIZATION_SCRIPTS = 3
    STARTUP_ITEMS = 4
    NETWORK_SERVICE_DISCOVERY = 5
    PROCESS_DISCOVERY = 6
    COMMAND_AND_SCRIPTING_INTERPRETER = 7
    UNIX_SHELL = 8
    PERMISSION_GROUPS_DISCOVERY = 9
    CLOUD_GROUPS = 10
    APPLICATION_LAYER_PROTOCOL = 11
    DNS = 12
    SOFTWARE_DEPLOYMENT_TOOLS = 13
    VALID_ACCOUNTS = 14
    DEFAULT_ACCOUNTS = 15
    LOCAL_ACCOUNTS = 16
    CLOUD_ACCOUNTS = 17
    PROXY = 18
    EXTERNAL_PROXY = 19
    MULTI_HOP_PROXY = 20
    ACCOUNT_MANIPULATION = 21
    ADDITIONAL_CLOUD_CREDENTIALS = 22
    SSH_AUTHORIZED_KEYS = 23
    ADDITIONAL_CONTAINER_CLUSTER_ROLES = 24
    INGRESS_TOOL_TRANSFER = 25
    NATIVE_API = 26
    BRUTE_FORCE = 27
    SHARED_MODULES = 28
    ACCESS_TOKEN_MANIPULATION = 29
    TOKEN_IMPERSONATION_OR_THEFT = 30
    EXPLOIT_PUBLIC_FACING_APPLICATION = 31
    DOMAIN_POLICY_MODIFICATION = 32
    DATA_DESTRUCTION = 33
    SERVICE_STOP = 34
    INHIBIT_SYSTEM_RECOVERY = 35
    RESOURCE_HIJACKING = 36
    NETWORK_DENIAL_OF_SERVICE = 37
    CLOUD_SERVICE_DISCOVERY = 38
    STEAL_APPLICATION_ACCESS_TOKEN = 39
    ACCOUNT_ACCESS_REMOVAL = 40
    STEAL_WEB_SESSION_COOKIE = 41
    CREATE_OR_MODIFY_SYSTEM_PROCESS = 42
    ABUSE_ELEVATION_CONTROL_MECHANISM = 43
    UNSECURED_CREDENTIALS = 44
    MODIFY_AUTHENTICATION_PROCESS = 45
    IMPAIR_DEFENSES = 46
    DISABLE_OR_MODIFY_TOOLS = 47
    EXFILTRATION_OVER_WEB_SERVICE = 48
    EXFILTRATION_TO_CLOUD_STORAGE = 49
    DYNAMIC_RESOLUTION = 50
    LATERAL_TOOL_TRANSFER = 51
    MODIFY_CLOUD_COMPUTE_INFRASTRUCTURE = 52
    CREATE_SNAPSHOT = 53
    CLOUD_INFRASTRUCTURE_DISCOVERY = 54
    OBTAIN_CAPABILITIES = 55
    ACTIVE_SCANNING = 56
    SCANNING_IP_BLOCKS = 57
    CONTAINER_AND_RESOURCE_DISCOVERY = 58