import os
import os.path as op
from glob import glob
import shutil
import sys
import numpy as np
from nibabel import load
from ... import logging, LooseVersion
from ...utils.filemanip import fname_presuffix, check_depends
from ..io import FreeSurferSource
from ..base import (
from .base import FSCommand, FSTraitedSpec, FSTraitedSpecOpenMP, FSCommandOpenMP, Info
from .utils import copy2subjdir
class MRIConvertInputSpec(FSTraitedSpec):
    read_only = traits.Bool(argstr='--read_only', desc='read the input volume')
    no_write = traits.Bool(argstr='--no_write', desc='do not write output')
    in_info = traits.Bool(argstr='--in_info', desc='display input info')
    out_info = traits.Bool(argstr='--out_info', desc='display output info')
    in_stats = traits.Bool(argstr='--in_stats', desc='display input stats')
    out_stats = traits.Bool(argstr='--out_stats', desc='display output stats')
    in_matrix = traits.Bool(argstr='--in_matrix', desc='display input matrix')
    out_matrix = traits.Bool(argstr='--out_matrix', desc='display output matrix')
    in_i_size = traits.Int(argstr='--in_i_size %d', desc='input i size')
    in_j_size = traits.Int(argstr='--in_j_size %d', desc='input j size')
    in_k_size = traits.Int(argstr='--in_k_size %d', desc='input k size')
    force_ras = traits.Bool(argstr='--force_ras_good', desc='use default when orientation info absent')
    in_i_dir = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--in_i_direction %f %f %f', desc='<R direction> <A direction> <S direction>')
    in_j_dir = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--in_j_direction %f %f %f', desc='<R direction> <A direction> <S direction>')
    in_k_dir = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--in_k_direction %f %f %f', desc='<R direction> <A direction> <S direction>')
    _orientations = ['LAI', 'LIA', 'ALI', 'AIL', 'ILA', 'IAL', 'LAS', 'LSA', 'ALS', 'ASL', 'SLA', 'SAL', 'LPI', 'LIP', 'PLI', 'PIL', 'ILP', 'IPL', 'LPS', 'LSP', 'PLS', 'PSL', 'SLP', 'SPL', 'RAI', 'RIA', 'ARI', 'AIR', 'IRA', 'IAR', 'RAS', 'RSA', 'ARS', 'ASR', 'SRA', 'SAR', 'RPI', 'RIP', 'PRI', 'PIR', 'IRP', 'IPR', 'RPS', 'RSP', 'PRS', 'PSR', 'SRP', 'SPR']
    in_orientation = traits.Enum(_orientations, argstr='--in_orientation %s', desc='specify the input orientation')
    in_center = traits.List(traits.Float, maxlen=3, argstr='--in_center %s', desc='<R coordinate> <A coordinate> <S coordinate>')
    sphinx = traits.Bool(argstr='--sphinx', desc='change orientation info to sphinx')
    out_i_count = traits.Int(argstr='--out_i_count %d', desc='some count ?? in i direction')
    out_j_count = traits.Int(argstr='--out_j_count %d', desc='some count ?? in j direction')
    out_k_count = traits.Int(argstr='--out_k_count %d', desc='some count ?? in k direction')
    vox_size = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='-voxsize %f %f %f', desc='<size_x> <size_y> <size_z> specify the size (mm) - useful for upsampling or downsampling')
    out_i_size = traits.Int(argstr='--out_i_size %d', desc='output i size')
    out_j_size = traits.Int(argstr='--out_j_size %d', desc='output j size')
    out_k_size = traits.Int(argstr='--out_k_size %d', desc='output k size')
    out_i_dir = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--out_i_direction %f %f %f', desc='<R direction> <A direction> <S direction>')
    out_j_dir = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--out_j_direction %f %f %f', desc='<R direction> <A direction> <S direction>')
    out_k_dir = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--out_k_direction %f %f %f', desc='<R direction> <A direction> <S direction>')
    out_orientation = traits.Enum(_orientations, argstr='--out_orientation %s', desc='specify the output orientation')
    out_center = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--out_center %f %f %f', desc='<R coordinate> <A coordinate> <S coordinate>')
    out_datatype = traits.Enum('uchar', 'short', 'int', 'float', argstr='--out_data_type %s', desc='output data type <uchar|short|int|float>')
    resample_type = traits.Enum('interpolate', 'weighted', 'nearest', 'sinc', 'cubic', argstr='--resample_type %s', desc='<interpolate|weighted|nearest|sinc|cubic> (default is interpolate)')
    no_scale = traits.Bool(argstr='--no_scale 1', desc='dont rescale values for COR')
    no_change = traits.Bool(argstr='--nochange', desc="don't change type of input to that of template")
    tr = traits.Int(argstr='-tr %d', desc='TR in msec')
    te = traits.Int(argstr='-te %d', desc='TE in msec')
    ti = traits.Int(argstr='-ti %d', desc='TI in msec (note upper case flag)')
    autoalign_matrix = File(exists=True, argstr='--autoalign %s', desc='text file with autoalign matrix')
    unwarp_gradient = traits.Bool(argstr='--unwarp_gradient_nonlinearity', desc='unwarp gradient nonlinearity')
    apply_transform = File(exists=True, argstr='--apply_transform %s', desc='apply xfm file')
    apply_inv_transform = File(exists=True, argstr='--apply_inverse_transform %s', desc='apply inverse transformation xfm file')
    devolve_transform = traits.Str(argstr='--devolvexfm %s', desc='subject id')
    crop_center = traits.Tuple(traits.Int, traits.Int, traits.Int, argstr='--crop %d %d %d', desc='<x> <y> <z> crop to 256 around center (x, y, z)')
    crop_size = traits.Tuple(traits.Int, traits.Int, traits.Int, argstr='--cropsize %d %d %d', desc='<dx> <dy> <dz> crop to size <dx, dy, dz>')
    cut_ends = traits.Int(argstr='--cutends %d', desc='remove ncut slices from the ends')
    slice_crop = traits.Tuple(traits.Int, traits.Int, argstr='--slice-crop %d %d', desc='s_start s_end : keep slices s_start to s_end')
    slice_reverse = traits.Bool(argstr='--slice-reverse', desc='reverse order of slices, update vox2ras')
    slice_bias = traits.Float(argstr='--slice-bias %f', desc='apply half-cosine bias field')
    fwhm = traits.Float(argstr='--fwhm %f', desc='smooth input volume by fwhm mm')
    _filetypes = ['cor', 'mgh', 'mgz', 'minc', 'analyze', 'analyze4d', 'spm', 'afni', 'brik', 'bshort', 'bfloat', 'sdt', 'outline', 'otl', 'gdf', 'nifti1', 'nii', 'niigz']
    _infiletypes = ['ge', 'gelx', 'lx', 'ximg', 'siemens', 'dicom', 'siemens_dicom']
    in_type = traits.Enum(_filetypes + _infiletypes, argstr='--in_type %s', desc='input file type')
    out_type = traits.Enum(_filetypes, argstr='--out_type %s', desc='output file type')
    ascii = traits.Bool(argstr='--ascii', desc='save output as ascii col>row>slice>frame')
    reorder = traits.Tuple(traits.Int, traits.Int, traits.Int, argstr='--reorder %d %d %d', desc='olddim1 olddim2 olddim3')
    invert_contrast = traits.Float(argstr='--invert_contrast %f', desc='threshold for inversting contrast')
    in_file = File(exists=True, mandatory=True, position=-2, argstr='--input_volume %s', desc='File to read/convert')
    out_file = File(argstr='--output_volume %s', position=-1, genfile=True, desc='output filename or True to generate one')
    conform = traits.Bool(argstr='--conform', desc='conform to 1mm voxel size in coronal slice direction with 256^3 or more')
    conform_min = traits.Bool(argstr='--conform_min', desc='conform to smallest size')
    conform_size = traits.Float(argstr='--conform_size %s', desc='conform to size_in_mm')
    cw256 = traits.Bool(argstr='--cw256', desc='confrom to dimensions of 256^3')
    parse_only = traits.Bool(argstr='--parse_only', desc='parse input only')
    subject_name = traits.Str(argstr='--subject_name %s', desc='subject name ???')
    reslice_like = File(exists=True, argstr='--reslice_like %s', desc='reslice output to match file')
    template_type = traits.Enum(_filetypes + _infiletypes, argstr='--template_type %s', desc='template file type')
    split = traits.Bool(argstr='--split', desc='split output frames into separate output files.')
    frame = traits.Int(argstr='--frame %d', desc='keep only 0-based frame number')
    midframe = traits.Bool(argstr='--mid-frame', desc='keep only the middle frame')
    skip_n = traits.Int(argstr='--nskip %d', desc='skip the first n frames')
    drop_n = traits.Int(argstr='--ndrop %d', desc='drop the last n frames')
    frame_subsample = traits.Tuple(traits.Int, traits.Int, traits.Int, argstr='--fsubsample %d %d %d', desc='start delta end : frame subsampling (end = -1 for end)')
    in_scale = traits.Float(argstr='--scale %f', desc='input intensity scale factor')
    out_scale = traits.Float(argstr='--out-scale %d', desc='output intensity scale factor')
    in_like = File(exists=True, argstr='--in_like %s', desc='input looks like')
    fill_parcellation = traits.Bool(argstr='--fill_parcellation', desc='fill parcellation')
    smooth_parcellation = traits.Bool(argstr='--smooth_parcellation', desc='smooth parcellation')
    zero_outlines = traits.Bool(argstr='--zero_outlines', desc='zero outlines')
    color_file = File(exists=True, argstr='--color_file %s', desc='color file')
    no_translate = traits.Bool(argstr='--no_translate', desc='???')
    status_file = File(argstr='--status %s', desc='status file for DICOM conversion')
    sdcm_list = File(exists=True, argstr='--sdcmlist %s', desc='list of DICOM files for conversion')
    template_info = traits.Bool(argstr='--template_info', desc='dump info about template')
    crop_gdf = traits.Bool(argstr='--crop_gdf', desc='apply GDF cropping')
    zero_ge_z_offset = traits.Bool(argstr='--zero_ge_z_offset', desc='zero ge z offset ???')