import os
from ..base import (
from ...external.due import BibTeX
from .base import (
class DeconvolveInputSpec(AFNICommandInputSpec):
    in_files = InputMultiPath(File(exists=True), desc="filenames of 3D+time input datasets. More than one filename can be given and the datasets will be auto-catenated in time. You can input a 1D time series file here, but the time axis should run along the ROW direction, not the COLUMN direction as in the 'input1D' option.", argstr='-input %s', copyfile=False, sep=' ', position=1)
    sat = traits.Bool(desc='check the dataset time series for initial saturation transients, which should normally have been excised before data analysis.', argstr='-sat', xor=['trans'])
    trans = traits.Bool(desc='check the dataset time series for initial saturation transients, which should normally have been excised before data analysis.', argstr='-trans', xor=['sat'])
    noblock = traits.Bool(desc="normally, if you input multiple datasets with 'input', then the separate datasets are taken to be separate image runs that get separate baseline models. Use this options if you want to have the program consider these to be all one big run.* If any of the input dataset has only 1 sub-brick, then this option is automatically invoked!* If the auto-catenation feature isn't used, then this option has no effect, no how, no way.", argstr='-noblock')
    force_TR = traits.Float(desc="use this value instead of the TR in the 'input' dataset. (It's better to fix the input using Refit.)", argstr='-force_TR %f', position=0)
    input1D = File(desc='filename of single (fMRI) .1D time series where time runs down the column.', argstr='-input1D %s', exists=True)
    TR_1D = traits.Float(desc="TR to use with 'input1D'. This option has no effect if you do not also use 'input1D'.", argstr='-TR_1D %f')
    legendre = traits.Bool(desc='use Legendre polynomials for null hypothesis (baseline model)', argstr='-legendre')
    nolegendre = traits.Bool(desc="use power polynomials for null hypotheses. Don't do this unless you are crazy!", argstr='-nolegendre')
    nodmbase = traits.Bool(desc="don't de-mean baseline time series", argstr='-nodmbase')
    dmbase = traits.Bool(desc="de-mean baseline time series (default if 'polort' >= 0)", argstr='-dmbase')
    svd = traits.Bool(desc='use SVD instead of Gaussian elimination (default)', argstr='-svd')
    nosvd = traits.Bool(desc='use Gaussian elimination instead of SVD', argstr='-nosvd')
    rmsmin = traits.Float(desc="minimum rms error to reject reduced model (default = 0; don't use this option normally!)", argstr='-rmsmin %f')
    nocond = traits.Bool(desc="DON'T calculate matrix condition number", argstr='-nocond')
    singvals = traits.Bool(desc='print out the matrix singular values', argstr='-singvals')
    goforit = traits.Int(desc='use this to proceed even if the matrix has bad problems (e.g., duplicate columns, large condition number, etc.).', argstr='-GOFORIT %i')
    allzero_OK = traits.Bool(desc="don't consider all zero matrix columns to be the type of error that 'gotforit' is needed to ignore.", argstr='-allzero_OK')
    dname = traits.Tuple(Str, Str, desc='set environmental variable to provided value', argstr='-D%s=%s')
    mask = File(desc='filename of 3D mask dataset; only data time series from within the mask will be analyzed; results for voxels outside the mask will be set to zero.', argstr='-mask %s', exists=True)
    automask = traits.Bool(desc='build a mask automatically from input data (will be slow for long time series datasets)', argstr='-automask')
    STATmask = File(desc="build a mask from provided file, and use this mask for the purpose of reporting truncation-to float issues AND for computing the FDR curves. The actual results ARE not masked with this option (only with 'mask' or 'automask' options).", argstr='-STATmask %s', exists=True)
    censor = File(desc='filename of censor .1D time series. This is a file of 1s and 0s, indicating which time points are to be included (1) and which are to be excluded (0).', argstr='-censor %s', exists=True)
    polort = traits.Int(desc='degree of polynomial corresponding to the null hypothesis [default: 1]', argstr='-polort %d')
    ortvec = traits.Tuple(File(desc='filename', exists=True), Str(desc='label'), desc='this option lets you input a rectangular array of 1 or more baseline vectors from a file. This method is a fast way to include a lot of baseline regressors in one step. ', argstr='-ortvec %s %s')
    x1D = File(desc='specify name for saved X matrix', argstr='-x1D %s')
    x1D_stop = traits.Bool(desc='stop running after writing .xmat.1D file', argstr='-x1D_stop')
    cbucket = traits.Str(desc='Name for dataset in which to save the regression coefficients (no statistics). This dataset will be used in a -xrestore run [not yet implemented] instead of the bucket dataset, if possible.', argstr='-cbucket %s')
    out_file = File(desc='output statistics file', argstr='-bucket %s')
    num_threads = traits.Int(desc='run the program with provided number of sub-processes', argstr='-jobs %d', nohash=True)
    fout = traits.Bool(desc='output F-statistic for each stimulus', argstr='-fout')
    rout = traits.Bool(desc='output the R^2 statistic for each stimulus', argstr='-rout')
    tout = traits.Bool(desc='output the T-statistic for each stimulus', argstr='-tout')
    vout = traits.Bool(desc='output the sample variance (MSE) for each stimulus', argstr='-vout')
    nofdr = traits.Bool(desc="Don't compute the statistic-vs-FDR curves for the bucket dataset.", argstr='-noFDR')
    global_times = traits.Bool(desc='use global timing for stimulus timing files', argstr='-global_times', xor=['local_times'])
    local_times = traits.Bool(desc='use local timing for stimulus timing files', argstr='-local_times', xor=['global_times'])
    num_stimts = traits.Int(desc='number of stimulus timing files', argstr='-num_stimts %d', position=-6)
    stim_times = traits.List(traits.Tuple(traits.Int(desc='k-th response model'), File(desc='stimulus timing file', exists=True), Str(desc='model')), desc='generate a response model from a set of stimulus times given in file.', argstr="-stim_times %d %s '%s'...", position=-5)
    stim_label = traits.List(traits.Tuple(traits.Int(desc='k-th input stimulus'), Str(desc='stimulus label')), desc='label for kth input stimulus (e.g., Label1)', argstr='-stim_label %d %s...', requires=['stim_times'], position=-4)
    stim_times_subtract = traits.Float(desc="this option means to subtract specified seconds from each time encountered in any 'stim_times' option. The purpose of this option is to make it simple to adjust timing files for the removal of images from the start of each imaging run.", argstr='-stim_times_subtract %f')
    num_glt = traits.Int(desc='number of general linear tests (i.e., contrasts)', argstr='-num_glt %d', position=-3)
    gltsym = traits.List(Str(desc='symbolic general linear test'), desc="general linear tests (i.e., contrasts) using symbolic conventions (e.g., '+Label1 -Label2')", argstr="-gltsym 'SYM: %s'...", position=-2)
    glt_label = traits.List(traits.Tuple(traits.Int(desc='k-th general linear test'), Str(desc='GLT label')), desc='general linear test (i.e., contrast) labels', argstr='-glt_label %d %s...', requires=['gltsym'], position=-1)