import os
from ...utils.filemanip import fname_presuffix, split_filename
from ..base import (
from .base import FSCommand, FSTraitedSpec
from .utils import copy2subjdir
class GLMFitInputSpec(FSTraitedSpec):
    glm_dir = traits.Str(argstr='--glmdir %s', desc='save outputs to dir', genfile=True)
    in_file = File(desc='input 4D file', argstr='--y %s', mandatory=True, copyfile=False)
    _design_xor = ('fsgd', 'design', 'one_sample')
    fsgd = traits.Tuple(File(exists=True), traits.Enum('doss', 'dods'), argstr='--fsgd %s %s', xor=_design_xor, desc='freesurfer descriptor file')
    design = File(exists=True, argstr='--X %s', xor=_design_xor, desc='design matrix file')
    contrast = InputMultiPath(File(exists=True), argstr='--C %s...', desc='contrast file')
    one_sample = traits.Bool(argstr='--osgm', xor=('one_sample', 'fsgd', 'design', 'contrast'), desc='construct X and C as a one-sample group mean')
    no_contrast_ok = traits.Bool(argstr='--no-contrasts-ok', desc='do not fail if no contrasts specified')
    per_voxel_reg = InputMultiPath(File(exists=True), argstr='--pvr %s...', desc='per-voxel regressors')
    self_reg = traits.Tuple(traits.Int, traits.Int, traits.Int, argstr='--selfreg %d %d %d', desc='self-regressor from index col row slice')
    weighted_ls = File(exists=True, argstr='--wls %s', xor=('weight_file', 'weight_inv', 'weight_sqrt'), desc='weighted least squares')
    fixed_fx_var = File(exists=True, argstr='--yffxvar %s', desc='for fixed effects analysis')
    fixed_fx_dof = traits.Int(argstr='--ffxdof %d', xor=['fixed_fx_dof_file'], desc='dof for fixed effects analysis')
    fixed_fx_dof_file = File(argstr='--ffxdofdat %d', xor=['fixed_fx_dof'], desc='text file with dof for fixed effects analysis')
    weight_file = File(exists=True, xor=['weighted_ls'], desc='weight for each input at each voxel')
    weight_inv = traits.Bool(argstr='--w-inv', desc='invert weights', xor=['weighted_ls'])
    weight_sqrt = traits.Bool(argstr='--w-sqrt', desc='sqrt of weights', xor=['weighted_ls'])
    fwhm = traits.Range(low=0.0, argstr='--fwhm %f', desc='smooth input by fwhm')
    var_fwhm = traits.Range(low=0.0, argstr='--var-fwhm %f', desc='smooth variance by fwhm')
    no_mask_smooth = traits.Bool(argstr='--no-mask-smooth', desc='do not mask when smoothing')
    no_est_fwhm = traits.Bool(argstr='--no-est-fwhm', desc='turn off FWHM output estimation')
    mask_file = File(exists=True, argstr='--mask %s', desc='binary mask')
    label_file = File(exists=True, argstr='--label %s', xor=['cortex'], desc='use label as mask, surfaces only')
    cortex = traits.Bool(argstr='--cortex', xor=['label_file'], desc='use subjects ?h.cortex.label as label')
    invert_mask = traits.Bool(argstr='--mask-inv', desc='invert mask')
    prune = traits.Bool(argstr='--prune', desc='remove voxels that do not have a non-zero value at each frame (def)')
    no_prune = traits.Bool(argstr='--no-prune', xor=['prunethresh'], desc='do not prune')
    prune_thresh = traits.Float(argstr='--prune_thr %f', xor=['noprune'], desc='prune threshold. Default is FLT_MIN')
    compute_log_y = traits.Bool(argstr='--logy', desc='compute natural log of y prior to analysis')
    save_estimate = traits.Bool(argstr='--yhat-save', desc='save signal estimate (yhat)')
    save_residual = traits.Bool(argstr='--eres-save', desc='save residual error (eres)')
    save_res_corr_mtx = traits.Bool(argstr='--eres-scm', desc='save residual error spatial correlation matrix (eres.scm). Big!')
    surf = traits.Bool(argstr='--surf %s %s %s', requires=['subject_id', 'hemi'], desc='analysis is on a surface mesh')
    subject_id = traits.Str(desc='subject id for surface geometry')
    hemi = traits.Enum('lh', 'rh', desc='surface hemisphere')
    surf_geo = traits.Str('white', usedefault=True, desc='surface geometry name (e.g. white, pial)')
    simulation = traits.Tuple(traits.Enum('perm', 'mc-full', 'mc-z'), traits.Int(min=1), traits.Float, traits.Str, argstr='--sim %s %d %f %s', desc='nulltype nsim thresh csdbasename')
    sim_sign = traits.Enum('abs', 'pos', 'neg', argstr='--sim-sign %s', desc='abs, pos, or neg')
    uniform = traits.Tuple(traits.Float, traits.Float, argstr='--uniform %f %f', desc='use uniform distribution instead of gaussian')
    pca = traits.Bool(argstr='--pca', desc='perform pca/svd analysis on residual')
    calc_AR1 = traits.Bool(argstr='--tar1', desc='compute and save temporal AR1 of residual')
    save_cond = traits.Bool(argstr='--save-cond', desc='flag to save design matrix condition at each voxel')
    vox_dump = traits.Tuple(traits.Int, traits.Int, traits.Int, argstr='--voxdump %d %d %d', desc='dump voxel GLM and exit')
    seed = traits.Int(argstr='--seed %d', desc='used for synthesizing noise')
    synth = traits.Bool(argstr='--synth', desc='replace input with gaussian')
    resynth_test = traits.Int(argstr='--resynthtest %d', desc='test GLM by resynthsis')
    profile = traits.Int(argstr='--profile %d', desc='niters : test speed')
    mrtm1 = traits.Tuple(File(exists=True), File(exists=True), argstr='--mrtm1 %s %s', desc='RefTac TimeSec : perform MRTM1 kinetic modeling')
    mrtm2 = traits.Tuple(File(exists=True), File(exists=True), traits.Float, argstr='--mrtm2 %s %s %f', desc='RefTac TimeSec k2prime : perform MRTM2 kinetic modeling')
    logan = traits.Tuple(File(exists=True), File(exists=True), traits.Float, argstr='--logan %s %s %f', desc='RefTac TimeSec tstar   : perform Logan kinetic modeling')
    force_perm = traits.Bool(argstr='--perm-force', desc='force perumtation test, even when design matrix is not orthog')
    diag = traits.Int(argstr='--diag %d', desc='Gdiag_no : set diagnostic level')
    diag_cluster = traits.Bool(argstr='--diag-cluster', desc='save sig volume and exit from first sim loop')
    debug = traits.Bool(argstr='--debug', desc='turn on debugging')
    check_opts = traits.Bool(argstr='--checkopts', desc="don't run anything, just check options and exit")
    allow_repeated_subjects = traits.Bool(argstr='--allowsubjrep', desc='allow subject names to repeat in the fsgd file (must appear before --fsgd')
    allow_ill_cond = traits.Bool(argstr='--illcond', desc='allow ill-conditioned design matrices')
    sim_done_file = File(argstr='--sim-done %s', desc='create file when simulation finished')
    _ext_xor = ['nii', 'nii_gz']
    nii = traits.Bool(argstr='--nii', desc='save outputs as nii', xor=_ext_xor)
    nii_gz = traits.Bool(argstr='--nii.gz', desc='save outputs as nii.gz', xor=_ext_xor)