import grpc
from . import core_worker_pb2 as src_dot_ray_dot_protobuf_dot_core__worker__pb2
from . import pubsub_pb2 as src_dot_ray_dot_protobuf_dot_pubsub__pb2
class CoreWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RayletNotifyGCSRestart = channel.unary_unary('/ray.rpc.CoreWorkerService/RayletNotifyGCSRestart', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.RayletNotifyGCSRestartRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.RayletNotifyGCSRestartReply.FromString)
        self.PushTask = channel.unary_unary('/ray.rpc.CoreWorkerService/PushTask', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.PushTaskRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.PushTaskReply.FromString)
        self.DirectActorCallArgWaitComplete = channel.unary_unary('/ray.rpc.CoreWorkerService/DirectActorCallArgWaitComplete', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.DirectActorCallArgWaitCompleteRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.DirectActorCallArgWaitCompleteReply.FromString)
        self.GetObjectStatus = channel.unary_unary('/ray.rpc.CoreWorkerService/GetObjectStatus', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.GetObjectStatusRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.GetObjectStatusReply.FromString)
        self.WaitForActorOutOfScope = channel.unary_unary('/ray.rpc.CoreWorkerService/WaitForActorOutOfScope', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.WaitForActorOutOfScopeRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.WaitForActorOutOfScopeReply.FromString)
        self.PubsubLongPolling = channel.unary_unary('/ray.rpc.CoreWorkerService/PubsubLongPolling', request_serializer=src_dot_ray_dot_protobuf_dot_pubsub__pb2.PubsubLongPollingRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_pubsub__pb2.PubsubLongPollingReply.FromString)
        self.ReportGeneratorItemReturns = channel.unary_unary('/ray.rpc.CoreWorkerService/ReportGeneratorItemReturns', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.ReportGeneratorItemReturnsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.ReportGeneratorItemReturnsReply.FromString)
        self.PubsubCommandBatch = channel.unary_unary('/ray.rpc.CoreWorkerService/PubsubCommandBatch', request_serializer=src_dot_ray_dot_protobuf_dot_pubsub__pb2.PubsubCommandBatchRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_pubsub__pb2.PubsubCommandBatchReply.FromString)
        self.UpdateObjectLocationBatch = channel.unary_unary('/ray.rpc.CoreWorkerService/UpdateObjectLocationBatch', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.UpdateObjectLocationBatchRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.UpdateObjectLocationBatchReply.FromString)
        self.GetObjectLocationsOwner = channel.unary_unary('/ray.rpc.CoreWorkerService/GetObjectLocationsOwner', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.GetObjectLocationsOwnerRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.GetObjectLocationsOwnerReply.FromString)
        self.KillActor = channel.unary_unary('/ray.rpc.CoreWorkerService/KillActor', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.KillActorRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.KillActorReply.FromString)
        self.CancelTask = channel.unary_unary('/ray.rpc.CoreWorkerService/CancelTask', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.CancelTaskRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.CancelTaskReply.FromString)
        self.RemoteCancelTask = channel.unary_unary('/ray.rpc.CoreWorkerService/RemoteCancelTask', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.RemoteCancelTaskRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.RemoteCancelTaskReply.FromString)
        self.GetCoreWorkerStats = channel.unary_unary('/ray.rpc.CoreWorkerService/GetCoreWorkerStats', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.GetCoreWorkerStatsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.GetCoreWorkerStatsReply.FromString)
        self.LocalGC = channel.unary_unary('/ray.rpc.CoreWorkerService/LocalGC', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.LocalGCRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.LocalGCReply.FromString)
        self.DeleteObjects = channel.unary_unary('/ray.rpc.CoreWorkerService/DeleteObjects', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.DeleteObjectsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.DeleteObjectsReply.FromString)
        self.SpillObjects = channel.unary_unary('/ray.rpc.CoreWorkerService/SpillObjects', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.SpillObjectsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.SpillObjectsReply.FromString)
        self.RestoreSpilledObjects = channel.unary_unary('/ray.rpc.CoreWorkerService/RestoreSpilledObjects', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.RestoreSpilledObjectsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.RestoreSpilledObjectsReply.FromString)
        self.DeleteSpilledObjects = channel.unary_unary('/ray.rpc.CoreWorkerService/DeleteSpilledObjects', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.DeleteSpilledObjectsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.DeleteSpilledObjectsReply.FromString)
        self.PlasmaObjectReady = channel.unary_unary('/ray.rpc.CoreWorkerService/PlasmaObjectReady', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.PlasmaObjectReadyRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.PlasmaObjectReadyReply.FromString)
        self.Exit = channel.unary_unary('/ray.rpc.CoreWorkerService/Exit', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.ExitRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.ExitReply.FromString)
        self.AssignObjectOwner = channel.unary_unary('/ray.rpc.CoreWorkerService/AssignObjectOwner', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.AssignObjectOwnerRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.AssignObjectOwnerReply.FromString)
        self.NumPendingTasks = channel.unary_unary('/ray.rpc.CoreWorkerService/NumPendingTasks', request_serializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.NumPendingTasksRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_core__worker__pb2.NumPendingTasksReply.FromString)