import os
from ..base import (
class MedicAlgorithmLesionToadsInputSpec(CommandLineInputSpec):
    inT1_MPRAGE = File(desc='T1_MPRAGE Image', exists=True, argstr='--inT1_MPRAGE %s')
    inT1_SPGR = File(desc='T1_SPGR Image', exists=True, argstr='--inT1_SPGR %s')
    inFLAIR = File(desc='FLAIR Image', exists=True, argstr='--inFLAIR %s')
    inAtlas = traits.Enum('With Lesion', 'No Lesion', desc='Atlas to Use', argstr='--inAtlas %s')
    inOutput = traits.Enum('hard segmentation', 'hard segmentation+memberships', 'cruise inputs', 'dura removal inputs', desc='Output images', argstr='--inOutput %s')
    inOutput2 = traits.Enum('true', 'false', desc='Output the hard classification using maximum membership (not neceesarily topologically correct)', argstr='--inOutput2 %s')
    inCorrect = traits.Enum('true', 'false', desc='Correct MR field inhomogeneity.', argstr='--inCorrect %s')
    inOutput3 = traits.Enum('true', 'false', desc='Output the estimated inhomogeneity field', argstr='--inOutput3 %s')
    inAtlas2 = File(desc='Atlas File - With Lesions', exists=True, argstr='--inAtlas2 %s')
    inAtlas3 = File(desc='Atlas File - No Lesion - T1 and FLAIR', exists=True, argstr='--inAtlas3 %s')
    inAtlas4 = File(desc='Atlas File - No Lesion - T1 Only', exists=True, argstr='--inAtlas4 %s')
    inMaximum = traits.Int(desc='Maximum distance from the interventricular WM boundary to downweight the lesion membership to avoid false positives', argstr='--inMaximum %d')
    inMaximum2 = traits.Int(desc='Maximum Ventircle Distance', argstr='--inMaximum2 %d')
    inMaximum3 = traits.Int(desc='Maximum InterVentricular Distance', argstr='--inMaximum3 %d')
    inInclude = traits.Enum('true', 'false', desc='Include lesion in WM class in hard classification', argstr='--inInclude %s')
    inAtlas5 = traits.Float(desc='Controls the effect of the statistical atlas on the segmentation', argstr='--inAtlas5 %f')
    inSmooting = traits.Float(desc='Controls the effect of neighborhood voxels on the membership', argstr='--inSmooting %f')
    inMaximum4 = traits.Float(desc='Maximum amount of relative change in the energy function considered as the convergence criteria', argstr='--inMaximum4 %f')
    inMaximum5 = traits.Int(desc='Maximum iterations', argstr='--inMaximum5 %d')
    inAtlas6 = traits.Enum('rigid', 'multi_fully_affine', desc='Atlas alignment', argstr='--inAtlas6 %s')
    inConnectivity = traits.Enum('(26,6)', '(6,26)', '(6,18)', '(18,6)', desc='Connectivity (foreground,background)', argstr='--inConnectivity %s')
    xPrefExt = traits.Enum('nrrd', desc='Output File Type', argstr='--xPrefExt %s')
    outHard = traits.Either(traits.Bool, File(), hash_files=False, desc='Hard segmentation', argstr='--outHard %s')
    outHard2 = traits.Either(traits.Bool, File(), hash_files=False, desc='Hard segmentationfrom memberships', argstr='--outHard2 %s')
    outInhomogeneity = traits.Either(traits.Bool, File(), hash_files=False, desc='Inhomogeneity Field', argstr='--outInhomogeneity %s')
    outMembership = traits.Either(traits.Bool, File(), hash_files=False, desc='Membership Functions', argstr='--outMembership %s')
    outLesion = traits.Either(traits.Bool, File(), hash_files=False, desc='Lesion Segmentation', argstr='--outLesion %s')
    outSulcal = traits.Either(traits.Bool, File(), hash_files=False, desc='Sulcal CSF Membership', argstr='--outSulcal %s')
    outCortical = traits.Either(traits.Bool, File(), hash_files=False, desc='Cortical GM Membership', argstr='--outCortical %s')
    outFilled = traits.Either(traits.Bool, File(), hash_files=False, desc='Filled WM Membership', argstr='--outFilled %s')
    outWM = traits.Either(traits.Bool, File(), hash_files=False, desc='WM Mask', argstr='--outWM %s')
    null = traits.Str(desc='Execution Time', argstr='--null %s')
    xDefaultMem = traits.Int(desc='Set default maximum heap size', argstr='-xDefaultMem %d')
    xMaxProcess = traits.Int(1, desc='Set default maximum number of processes.', argstr='-xMaxProcess %d', usedefault=True)