from pygments.lexer import RegexLexer, words, include, bygroups, inherit
from pygments.token import Comment, Name, Number, Operator, Punctuation, \
class KLexer(RegexLexer):
    """
    For `K <https://code.kx.com/>`_ source code.

    .. versionadded:: 2.12
    """
    name = 'K'
    aliases = ['k']
    filenames = ['*.k']
    tokens = {'whitespace': [('^#!.*', Comment.Hashbang), ('^/\\s*\\n', Comment.Multiline, 'comments'), ('(?<!\\S)/.*', Comment.Single), ('\\s+', Whitespace), ('\\"', String.Double, 'strings')], 'root': [include('whitespace'), include('keywords'), include('declarations')], 'keywords': [(words(('abs', 'acos', 'asin', 'atan', 'avg', 'bin', 'binr', 'by', 'cor', 'cos', 'cov', 'dev', 'delete', 'div', 'do', 'enlist', 'exec', 'exit', 'exp', 'from', 'getenv', 'hopen', 'if', 'in', 'insert', 'last', 'like', 'log', 'max', 'min', 'prd', 'select', 'setenv', 'sin', 'sqrt', 'ss', 'sum', 'tan', 'update', 'var', 'wavg', 'while', 'within', 'wsum', 'xexp'), suffix='\\b'), Operator.Word)], 'declarations': [('^\\\\ts?', Comment.Preproc), ('^(\\\\\\w\\s+[^/\\n]*?)(/.*)', bygroups(Comment.Preproc, Comment.Single)), ('^\\\\\\w.*', Comment.Preproc), ('^[a-zA-Z]\\)', Generic.Prompt), ("([.]?[a-zA-Z][\\w.]*)(\\s*)([-.~=!@#$%^&*_+|,<>?/\\\\:']?:)(\\s*)(\\{)", bygroups(Name.Function, Whitespace, Operator, Whitespace, Punctuation), 'functions'), ("([.]?[a-zA-Z][\\w.]*)(\\s*)([-.~=!@#$%^&*_+|,<>?/\\\\:']?:)", bygroups(Name.Variable, Whitespace, Operator)), ('\\{', Punctuation, 'functions'), ('\\(', Punctuation, 'parentheses'), ('\\[', Punctuation, 'brackets'), ("'`([a-zA-Z][\\w.]*)?", Name.Exception), ('`:([a-zA-Z/][\\w./]*)?', String.Symbol), ('`([a-zA-Z][\\w.]*)?', String.Symbol), include('numbers'), ('[a-zA-Z][\\w.]*', Name), ("[-=+*#$%@!~^&:.,<>'\\\\|/?_]", Operator), (';', Punctuation)], 'functions': [include('root'), ('\\}', Punctuation, '#pop')], 'parentheses': [include('root'), ('\\)', Punctuation, '#pop')], 'brackets': [include('root'), ('\\]', Punctuation, '#pop')], 'numbers': [('[01]+b', Number.Bin), ('0[nNwW][cefghijmndzuvtp]?', Number), ('(?:[0-9]{4}[.][0-9]{2}[.][0-9]{2}|[0-9]+)D(?:[0-9](?:[0-9](?::[0-9]{2}(?::[0-9]{2}(?:[.][0-9]*)?)?)?)?)?', Literal.Date), ('[0-9]{4}[.][0-9]{2}(?:m|[.][0-9]{2}(?:T(?:[0-9]{2}:[0-9]{2}(?::[0-9]{2}(?:[.][0-9]*)?)?)?)?)', Literal.Date), ('[0-9]{2}:[0-9]{2}(?::[0-9]{2}(?:[.][0-9]{1,3})?)?', Literal.Date), ('[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', Number.Hex), ('0x[0-9a-fA-F]+', Number.Hex), ('([0-9]*[.]?[0-9]+|[0-9]+[.]?[0-9]*)[eE][+-]?[0-9]+[ef]?', Number.Float), ('([0-9]*[.][0-9]+|[0-9]+[.][0-9]*)[ef]?', Number.Float), ('[0-9]+[ef]', Number.Float), ('[0-9]+c', Number), ('[0-9]+[ihtuv]', Number.Integer), ('[0-9]+[jnp]?', Number.Integer.Long)], 'comments': [('[^\\\\]+', Comment.Multiline), ('^\\\\', Comment.Multiline, '#pop'), ('\\\\', Comment.Multiline)], 'strings': [('[^"\\\\]+', String.Double), ('\\\\.', String.Escape), ('"', String.Double, '#pop')]}