from nipype.interfaces.base import (
import os
class EMSegmentCommandLineInputSpec(CommandLineInputSpec):
    mrmlSceneFileName = File(desc='Active MRML scene that contains EMSegment algorithm parameters.', exists=True, argstr='--mrmlSceneFileName %s')
    resultVolumeFileName = traits.Either(traits.Bool, File(), hash_files=False, desc='The file name that the segmentation result volume will be written to.', argstr='--resultVolumeFileName %s')
    targetVolumeFileNames = InputMultiPath(File(exists=True), desc='File names of target volumes (to be segmented).  The number of target images must be equal to the number of target images specified in the parameter set, and these images must be spatially aligned.', argstr='--targetVolumeFileNames %s...')
    intermediateResultsDirectory = Directory(desc='Directory where EMSegmenter will write intermediate data (e.g., aligned atlas data).', exists=True, argstr='--intermediateResultsDirectory %s')
    parametersMRMLNodeName = traits.Str(desc='The name of the EMSegment parameters node within the active MRML scene.  Leave blank for default.', argstr='--parametersMRMLNodeName %s')
    disableMultithreading = traits.Int(desc='Disable multithreading for the EMSegmenter algorithm only! Preprocessing might still run in multi-threaded mode. -1: Do not overwrite default value. 0: Disable. 1: Enable.', argstr='--disableMultithreading %d')
    dontUpdateIntermediateData = traits.Int(desc='Disable update of intermediate results.  -1: Do not overwrite default value. 0: Disable. 1: Enable.', argstr='--dontUpdateIntermediateData %d')
    verbose = traits.Bool(desc='Enable verbose output.', argstr='--verbose ')
    loadTargetCentered = traits.Bool(desc='Read target files centered.', argstr='--loadTargetCentered ')
    loadAtlasNonCentered = traits.Bool(desc='Read atlas files non-centered.', argstr='--loadAtlasNonCentered ')
    taskPreProcessingSetting = traits.Str(desc='Specifies the different task parameter. Leave blank for default.', argstr='--taskPreProcessingSetting %s')
    keepTempFiles = traits.Bool(desc='If flag is set then at the end of command the temporary files are not removed', argstr='--keepTempFiles ')
    resultStandardVolumeFileName = File(desc='Used for testing.  Compare segmentation results to this image and return EXIT_FAILURE if they do not match.', exists=True, argstr='--resultStandardVolumeFileName %s')
    dontWriteResults = traits.Bool(desc="Used for testing.  Don't actually write the resulting labelmap to disk.", argstr='--dontWriteResults ')
    generateEmptyMRMLSceneAndQuit = traits.Either(traits.Bool, File(), hash_files=False, desc='Used for testing.  Only write a scene with default mrml parameters.', argstr='--generateEmptyMRMLSceneAndQuit %s')
    resultMRMLSceneFileName = traits.Either(traits.Bool, File(), hash_files=False, desc='Write out the MRML scene after command line substitutions have been made.', argstr='--resultMRMLSceneFileName %s')
    disableCompression = traits.Bool(desc="Don't use compression when writing result image to disk.", argstr='--disableCompression ')
    atlasVolumeFileNames = InputMultiPath(File(exists=True), desc='Use an alternative atlas to the one that is specified by the mrml file - note the order matters ! ', argstr='--atlasVolumeFileNames %s...')
    registrationPackage = traits.Str(desc='specify the registration package for preprocessing (CMTK or BRAINS or PLASTIMATCH or DEMONS)', argstr='--registrationPackage %s')
    registrationAffineType = traits.Int(desc='specify the accuracy of the affine registration. -2: Do not overwrite default, -1: Test, 0: Disable, 1: Fast, 2: Accurate', argstr='--registrationAffineType %d')
    registrationDeformableType = traits.Int(desc='specify the accuracy of the deformable registration. -2: Do not overwrite default, -1: Test, 0: Disable, 1: Fast, 2: Accurate', argstr='--registrationDeformableType %d')