import grpc
from . import node_manager_pb2 as src_dot_ray_dot_protobuf_dot_node__manager__pb2
class NodeManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyGCSRestart = channel.unary_unary('/ray.rpc.NodeManagerService/NotifyGCSRestart', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.NotifyGCSRestartRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.NotifyGCSRestartReply.FromString)
        self.GetResourceLoad = channel.unary_unary('/ray.rpc.NodeManagerService/GetResourceLoad', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetResourceLoadRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetResourceLoadReply.FromString)
        self.RequestWorkerLease = channel.unary_unary('/ray.rpc.NodeManagerService/RequestWorkerLease', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.RequestWorkerLeaseRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.RequestWorkerLeaseReply.FromString)
        self.ReportWorkerBacklog = channel.unary_unary('/ray.rpc.NodeManagerService/ReportWorkerBacklog', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReportWorkerBacklogRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReportWorkerBacklogReply.FromString)
        self.ReturnWorker = channel.unary_unary('/ray.rpc.NodeManagerService/ReturnWorker', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReturnWorkerRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReturnWorkerReply.FromString)
        self.ReleaseUnusedWorkers = channel.unary_unary('/ray.rpc.NodeManagerService/ReleaseUnusedWorkers', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReleaseUnusedWorkersRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReleaseUnusedWorkersReply.FromString)
        self.ShutdownRaylet = channel.unary_unary('/ray.rpc.NodeManagerService/ShutdownRaylet', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ShutdownRayletRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ShutdownRayletReply.FromString)
        self.DrainRaylet = channel.unary_unary('/ray.rpc.NodeManagerService/DrainRaylet', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.DrainRayletRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.DrainRayletReply.FromString)
        self.PrepareBundleResources = channel.unary_unary('/ray.rpc.NodeManagerService/PrepareBundleResources', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.PrepareBundleResourcesRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.PrepareBundleResourcesReply.FromString)
        self.CommitBundleResources = channel.unary_unary('/ray.rpc.NodeManagerService/CommitBundleResources', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.CommitBundleResourcesRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.CommitBundleResourcesReply.FromString)
        self.CancelResourceReserve = channel.unary_unary('/ray.rpc.NodeManagerService/CancelResourceReserve', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.CancelResourceReserveRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.CancelResourceReserveReply.FromString)
        self.CancelWorkerLease = channel.unary_unary('/ray.rpc.NodeManagerService/CancelWorkerLease', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.CancelWorkerLeaseRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.CancelWorkerLeaseReply.FromString)
        self.PinObjectIDs = channel.unary_unary('/ray.rpc.NodeManagerService/PinObjectIDs', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.PinObjectIDsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.PinObjectIDsReply.FromString)
        self.GetNodeStats = channel.unary_unary('/ray.rpc.NodeManagerService/GetNodeStats', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetNodeStatsRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetNodeStatsReply.FromString)
        self.GlobalGC = channel.unary_unary('/ray.rpc.NodeManagerService/GlobalGC', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GlobalGCRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GlobalGCReply.FromString)
        self.FormatGlobalMemoryInfo = channel.unary_unary('/ray.rpc.NodeManagerService/FormatGlobalMemoryInfo', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.FormatGlobalMemoryInfoRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.FormatGlobalMemoryInfoReply.FromString)
        self.RequestObjectSpillage = channel.unary_unary('/ray.rpc.NodeManagerService/RequestObjectSpillage', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.RequestObjectSpillageRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.RequestObjectSpillageReply.FromString)
        self.ReleaseUnusedBundles = channel.unary_unary('/ray.rpc.NodeManagerService/ReleaseUnusedBundles', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReleaseUnusedBundlesRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.ReleaseUnusedBundlesReply.FromString)
        self.GetSystemConfig = channel.unary_unary('/ray.rpc.NodeManagerService/GetSystemConfig', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetSystemConfigRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetSystemConfigReply.FromString)
        self.GetTasksInfo = channel.unary_unary('/ray.rpc.NodeManagerService/GetTasksInfo', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetTasksInfoRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetTasksInfoReply.FromString)
        self.GetObjectsInfo = channel.unary_unary('/ray.rpc.NodeManagerService/GetObjectsInfo', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetObjectsInfoRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetObjectsInfoReply.FromString)
        self.GetTaskFailureCause = channel.unary_unary('/ray.rpc.NodeManagerService/GetTaskFailureCause', request_serializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetTaskFailureCauseRequest.SerializeToString, response_deserializer=src_dot_ray_dot_protobuf_dot_node__manager__pb2.GetTaskFailureCauseReply.FromString)