import random
from PySide2 import QtCore, QtGui, QtWidgets
class TetrixWindow(QtWidgets.QWidget):

    def __init__(self):
        super(TetrixWindow, self).__init__()
        self.board = TetrixBoard()
        nextPieceLabel = QtWidgets.QLabel()
        nextPieceLabel.setFrameStyle(QtWidgets.QFrame.Box | QtWidgets.QFrame.Raised)
        nextPieceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.board.setNextPieceLabel(nextPieceLabel)
        scoreLcd = QtWidgets.QLCDNumber(5)
        scoreLcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        levelLcd = QtWidgets.QLCDNumber(2)
        levelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        linesLcd = QtWidgets.QLCDNumber(5)
        linesLcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        startButton = QtWidgets.QPushButton('&Start')
        startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        quitButton = QtWidgets.QPushButton('&Quit')
        quitButton.setFocusPolicy(QtCore.Qt.NoFocus)
        pauseButton = QtWidgets.QPushButton('&Pause')
        pauseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        startButton.clicked.connect(self.board.start)
        pauseButton.clicked.connect(self.board.pause)
        quitButton.clicked.connect(QtWidgets.qApp.quit)
        self.board.scoreChanged.connect(scoreLcd.display)
        self.board.levelChanged.connect(levelLcd.display)
        self.board.linesRemovedChanged.connect(linesLcd.display)
        layout = QtWidgets.QGridLayout()
        layout.addWidget(self.createLabel('NEXT'), 0, 0)
        layout.addWidget(nextPieceLabel, 1, 0)
        layout.addWidget(self.createLabel('LEVEL'), 2, 0)
        layout.addWidget(levelLcd, 3, 0)
        layout.addWidget(startButton, 4, 0)
        layout.addWidget(self.board, 0, 1, 6, 1)
        layout.addWidget(self.createLabel('SCORE'), 0, 2)
        layout.addWidget(scoreLcd, 1, 2)
        layout.addWidget(self.createLabel('LINES REMOVED'), 2, 2)
        layout.addWidget(linesLcd, 3, 2)
        layout.addWidget(quitButton, 4, 2)
        layout.addWidget(pauseButton, 5, 2)
        self.setLayout(layout)
        self.setWindowTitle('Tetrix')
        self.resize(550, 370)

    def createLabel(self, text):
        lbl = QtWidgets.QLabel(text)
        lbl.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        return lbl