import re
from pygments.lexer import RegexLexer, DelegatingLexer, bygroups, include, \
from pygments.token import Punctuation, Text, Comment, Operator, Keyword, \
from pygments.util import get_choice_opt
from pygments import unistring as uni
from pygments.lexers.html import XmlLexer
class XppLexer(RegexLexer):
    """
    For X++ source code. This is based loosely on the CSharpLexer

    .. versionadded:: 2.15
    """
    name = 'X++'
    url = 'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-language-reference'
    aliases = ['xpp', 'x++']
    filenames = ['*.xpp']
    flags = re.MULTILINE
    XPP_CHARS = '@?(?:_|[^' + uni.allexcept('Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Nl') + '])' + '[^' + uni.allexcept('Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Nl', 'Nd', 'Pc', 'Cf', 'Mn', 'Mc') + ']*'
    XPP_CHARS = XPP_CHARS.replace('\x00', '\x01')
    OPERATORS = ('<=', '>=', '+=', '-=', '*=', '/=', '!=', '==', '&&', '||', '>>', '<<', '++', '--', '+', '-', '*', '/', '%', '&', '|', '^', '<', '>', '?', '!', '~', '=')
    KEYWORDS = ('abstract', 'anytype', 'as', 'async', 'asc', 'at', 'avg', 'break', 'breakpoint', 'by', 'byref', 'case', 'catch', 'changecompany', 'client', 'container', 'continue', 'count', 'crosscompany', 'default', 'delegate', 'delete_from', 'desc', 'display', 'div', 'do', 'edit', 'else', 'element', 'eventhandler', 'exists', 'false', 'final', 'firstfast', 'firstonly', 'firstonly10', 'firstonly100', 'firstonly1000', 'flush', 'for', 'forceliterals', 'forcenestedloop', 'forceplaceholders', 'forceselectorder', 'forupdate', 'from', 'group', 'if', 'insert_recordset', 'interface', 'is', 'join', 'like', 'maxof', 'minof', 'mod', 'new', 'next', 'nofetch', 'notexists', 'null', 'optimisticlock', 'order', 'outer', 'pause', 'pessimisticlock', 'print', 'private', 'protected', 'public', 'repeatableread', 'retry', 'return', 'reverse', 'select', 'server', 'setting', 'static', 'sum', 'super', 'switch', 'tablelock', 'this', 'throw', 'true', 'try', 'ttsabort', 'ttsbegin', 'ttscommit', 'update_recordset', 'validtimestate', 'void', 'where', 'while', 'window')
    RUNTIME_FUNCTIONS = ('_duration', 'abs', 'acos', 'any2Date', 'any2Enum', 'any2Guid', 'any2Int', 'any2Int64', 'any2Real', 'any2Str', 'anytodate', 'anytoenum', 'anytoguid', 'anytoint', 'anytoint64', 'anytoreal', 'anytostr', 'asin', 'atan', 'beep', 'cTerm', 'char2Num', 'classIdGet', 'corrFlagGet', 'corrFlagSet', 'cos', 'cosh', 'curExt', 'curUserId', 'date2Num', 'date2Str', 'datetime2Str', 'dayName', 'dayOfMth', 'dayOfWk', 'dayOfYr', 'ddb', 'decRound', 'dg', 'dimOf', 'endMth', 'enum2str', 'exp', 'exp10', 'fV', 'fieldId2Name', 'fieldId2PName', 'fieldName2Id', 'frac', 'funcName', 'getCurrentPartition', 'getCurrentPartitionRecId', 'getPrefix', 'guid2Str', 'idg', 'indexId2Name', 'indexName2Id', 'int2Str', 'int642Str', 'intvMax', 'intvName', 'intvNo', 'intvNorm', 'log10', 'logN', 'match', 'max', 'min', 'mkDate', 'mthName', 'mthOfYr', 'newGuid', 'nextMth', 'nextQtr', 'nextYr', 'num2Char', 'num2Date', 'num2Str', 'pmt', 'power', 'prevMth', 'prevQtr', 'prevYr', 'prmIsDefault', 'pt', 'pv', 'rate', 'refPrintAll', 'round', 'runAs', 'sessionId', 'setPrefix', 'sin', 'sinh', 'sleep', 'sln', 'str2Date', 'str2Datetime', 'str2Enum', 'str2Guid', 'str2Int', 'str2Int64', 'str2Num', 'str2Time', 'strAlpha', 'strCmp', 'strColSeq', 'strDel', 'strFind', 'strFmt', 'strIns', 'strKeep', 'strLTrim', 'strLen', 'strLine', 'strLwr', 'strNFind', 'strPoke', 'strPrompt', 'strRTrim', 'strRem', 'strRep', 'strScan', 'strUpr', 'subStr', 'syd', 'systemDateGet', 'systemDateSet', 'tableId2Name', 'tableId2PName', 'tableName2Id', 'tan', 'tanh', 'term', 'time2Str', 'timeNow', 'today', 'trunc', 'typeOf', 'uint2Str', 'wkOfYr', 'year')
    COMPILE_FUNCTIONS = ('attributeStr', 'classNum', 'classStr', 'configurationKeyNum', 'configurationKeyStr', 'dataEntityDataSourceStr', 'delegateStr', 'dimensionHierarchyLevelStr', 'dimensionHierarchyStr', 'dimensionReferenceStr', 'dutyStr', 'enumCnt', 'enumLiteralStr', 'enumNum', 'enumStr', 'extendedTypeNum', 'extendedTypeStr', 'fieldNum', 'fieldPName', 'fieldStr', 'formControlStr', 'formDataFieldStr', 'formDataSourceStr', 'formMethodStr', 'formStr', 'identifierStr', 'indexNum', 'indexStr', 'licenseCodeNum', 'licenseCodeStr', 'literalStr', 'maxDate', 'maxInt', 'measureStr', 'measurementStr', 'menuItemActionStr', 'menuItemDisplayStr', 'menuItemOutputStr', 'menuStr', 'methodStr', 'minInt', 'privilegeStr', 'queryDatasourceStr', 'queryMethodStr', 'queryStr', 'reportStr', 'resourceStr', 'roleStr', 'ssrsReportStr', 'staticDelegateStr', 'staticMethodStr', 'tableCollectionStr', 'tableFieldGroupStr', 'tableMethodStr', 'tableNum', 'tablePName', 'tableStaticMethodStr', 'tableStr', 'tileStr', 'varStr', 'webActionItemStr', 'webDisplayContentItemStr', 'webFormStr', 'webMenuStr', 'webOutputContentItemStr', 'webReportStr', 'webSiteTempStr', 'webStaticFileStr', 'webUrlItemStr', 'webWebPartStr', 'webletItemStr', 'webpageDefStr', 'websiteDefStr', 'workflowApprovalStr', 'workflowCategoryStr', 'workflowTaskStr', 'workflowTypeStr')
    tokens = {}
    tokens = {'root': [('(\\s*)\\b(else|if)\\b([^\\n])', bygroups(Whitespace, Keyword, using(this))), ('^([ \\t]*)((?:' + XPP_CHARS + '(?:\\[\\])?\\s+)+?)(' + XPP_CHARS + ')(\\s*)(\\()', bygroups(Whitespace, using(this), Name.Function, Whitespace, Punctuation)), ('^(\\s*)(\\[)([^\\n]*?)(\\])', bygroups(Whitespace, Name.Attribute, Name.Variable.Class, Name.Attribute)), ('[^\\S\\n]+', Whitespace), ('(\\\\)(\\n)', bygroups(Text, Whitespace)), ('//[^\\n]*?\\n', Comment.Single), ('/[*][^\\n]*?[*]/', Comment.Multiline), ('\\n', Whitespace), (words(OPERATORS), Operator), ('=~|!=|==|<<|>>|[-+/*%=<>&^|]', Operator), ('[()\\[\\];:,.#@]', Punctuation), ('[{}]', Punctuation), ('@"(""|[^"])*"', String), ('\\$?"(\\\\\\\\|\\\\[^\\\\]|[^"\\\\\\n])*["\\n]', String), ("'\\\\.'|'[^\\\\]'", String.Char), ('[0-9]+(\\.[0-9]*)?([eE][+-][0-9]+)?[flFLdD]?|0[xX][0-9a-fA-F]+[Ll]?', Number), (words(KEYWORDS, suffix='\\b'), Keyword), ('(boolean|int|int64|str|real|guid|date)\\b\\??', Keyword.Type), ('(class|struct|extends|implements)(\\s+)', bygroups(Keyword, Whitespace), 'class'), ('(' + XPP_CHARS + ')(::)', bygroups(Name.Variable.Class, Punctuation)), ('(\\s*)(\\w+)(\\s+\\w+(,|=)?[^\\n]*;)', bygroups(Whitespace, Name.Variable.Class, using(this))), ('(fieldNum\\()(' + XPP_CHARS + ')(\\s*,\\s*)(' + XPP_CHARS + ')(\\s*\\))', bygroups(using(this), Name.Variable.Class, using(this), Name.Property, using(this))), ('(tableNum\\()(' + XPP_CHARS + ')(\\s*\\))', bygroups(using(this), Name.Variable.Class, using(this))), (words(RUNTIME_FUNCTIONS, suffix='(?=\\()'), Name.Function.Magic), (words(COMPILE_FUNCTIONS, suffix='(?=\\()'), Name.Function.Magic), (XPP_CHARS, Name)], 'class': [(XPP_CHARS, Name.Class, '#pop'), default('#pop')], 'namespace': [('(?=\\()', Text, '#pop'), ('(' + XPP_CHARS + '|\\.)+', Name.Namespace, '#pop')]}