from breezy.tests.per_workingtree import TestCaseWithWorkingTree
class TestAnnotateIter(TestCaseWithWorkingTree):

    def make_single_rev_tree(self):
        builder = self.make_branch_builder('branch')
        revid = builder.build_snapshot(None, [('add', ('', None, 'directory', None)), ('add', ('file', None, 'file', b'initial content\n'))])
        b = builder.get_branch()
        tree = b.create_checkout('tree', lightweight=True)
        tree.lock_read()
        self.addCleanup(tree.unlock)
        return (tree, revid)

    def test_annotate_same_as_parent(self):
        tree, revid = self.make_single_rev_tree()
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid, b'initial content\n')], annotations)

    def test_annotate_mod_from_parent(self):
        tree, revid = self.make_single_rev_tree()
        self.build_tree_contents([('tree/file', b'initial content\nnew content\n')])
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid, b'initial content\n'), (b'current:', b'new content\n')], annotations)

    def test_annotate_merge_parents(self):
        builder = self.make_branch_builder('branch')
        builder.start_series()
        revid1 = builder.build_snapshot(None, [('add', ('', None, 'directory', None)), ('add', ('file', None, 'file', b'initial content\n'))])
        revid2 = builder.build_snapshot([revid1], [('modify', ('file', b'initial content\ncontent in 2\n'))])
        revid3 = builder.build_snapshot([revid1], [('modify', ('file', b'initial content\ncontent in 3\n'))])
        builder.finish_series()
        b = builder.get_branch()
        tree = b.create_checkout('tree', revision_id=revid2, lightweight=True)
        tree.lock_write()
        self.addCleanup(tree.unlock)
        tree.set_parent_ids([revid2, revid3])
        self.build_tree_contents([('tree/file', b'initial content\ncontent in 2\ncontent in 3\nnew content\n')])
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid1, b'initial content\n'), (revid2, b'content in 2\n'), (revid3, b'content in 3\n'), (b'current:', b'new content\n')], annotations)

    def test_annotate_merge_parent_no_file(self):
        builder = self.make_branch_builder('branch')
        builder.start_series()
        revid1 = builder.build_snapshot(None, [('add', ('', None, 'directory', None))])
        revid2 = builder.build_snapshot([revid1], [('add', ('file', None, 'file', b'initial content\n'))])
        revid3 = builder.build_snapshot([revid1], [])
        builder.finish_series()
        b = builder.get_branch()
        tree = b.create_checkout('tree', revision_id=revid2, lightweight=True)
        tree.lock_write()
        self.addCleanup(tree.unlock)
        tree.set_parent_ids([revid2, revid3])
        self.build_tree_contents([('tree/file', b'initial content\nnew content\n')])
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid2, b'initial content\n'), (b'current:', b'new content\n')], annotations)

    def test_annotate_merge_parent_was_directory(self):
        builder = self.make_branch_builder('branch')
        builder.start_series()
        revid1 = builder.build_snapshot(None, [('add', ('', None, 'directory', None))])
        revid2 = builder.build_snapshot([revid1], [('add', ('file', None, 'file', b'initial content\n'))])
        revid3 = builder.build_snapshot([revid1], [('add', ('a_dir', None, 'directory', None))])
        builder.finish_series()
        b = builder.get_branch()
        tree = b.create_checkout('tree', revision_id=revid2, lightweight=True)
        tree.lock_write()
        self.addCleanup(tree.unlock)
        tree.set_parent_ids([revid2, revid3])
        self.build_tree_contents([('tree/file', b'initial content\nnew content\n')])
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid2, b'initial content\n'), (b'current:', b'new content\n')], annotations)

    def test_annotate_same_as_merge_parent(self):
        builder = self.make_branch_builder('branch')
        builder.start_series()
        revid1 = builder.build_snapshot(None, [('add', ('', None, 'directory', None)), ('add', ('file', None, 'file', b'initial content\n'))])
        revid2 = builder.build_snapshot([revid1], [])
        revid3 = builder.build_snapshot([revid1], [('modify', ('file', b'initial content\ncontent in 3\n'))])
        builder.finish_series()
        b = builder.get_branch()
        tree = b.create_checkout('tree', revision_id=revid2, lightweight=True)
        tree.lock_write()
        self.addCleanup(tree.unlock)
        tree.set_parent_ids([revid2, revid3])
        self.build_tree_contents([('tree/file', b'initial content\ncontent in 3\n')])
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid1, b'initial content\n'), (revid3, b'content in 3\n')], annotations)

    def test_annotate_same_as_merge_parent_supersedes(self):
        builder = self.make_branch_builder('branch')
        builder.start_series()
        revid1 = builder.build_snapshot(None, [('add', ('', None, 'directory', None)), ('add', ('file', None, 'file', b'initial content\n'))])
        revid2 = builder.build_snapshot([revid1], [('modify', ('file', b'initial content\nnew content\n'))])
        revid3 = builder.build_snapshot([revid2], [('modify', ('file', b'initial content\ncontent in 3\n'))])
        revid4 = builder.build_snapshot([revid3], [('modify', ('file', b'initial content\nnew content\n'))])
        builder.finish_series()
        b = builder.get_branch()
        tree = b.create_checkout('tree', revision_id=revid2, lightweight=True)
        tree.lock_write()
        self.addCleanup(tree.unlock)
        tree.set_parent_ids([revid2, revid4])
        annotations = tree.annotate_iter('file')
        self.assertEqual([(revid1, b'initial content\n'), (revid4, b'new content\n')], annotations)