import a new buffer interface.
import pygame
import pygame.newbuffer
from pygame.newbuffer import (
import unittest
import ctypes
import operator
from functools import reduce
class ExporterTest(unittest.TestCase):
    """Class Exporter unit tests"""

    def test_formats(self):
        char_sz = ctypes.sizeof(ctypes.c_char)
        short_sz = ctypes.sizeof(ctypes.c_short)
        int_sz = ctypes.sizeof(ctypes.c_int)
        long_sz = ctypes.sizeof(ctypes.c_long)
        longlong_sz = ctypes.sizeof(ctypes.c_longlong)
        float_sz = ctypes.sizeof(ctypes.c_float)
        double_sz = ctypes.sizeof(ctypes.c_double)
        voidp_sz = ctypes.sizeof(ctypes.c_void_p)
        bool_sz = ctypes.sizeof(ctypes.c_bool)
        self.check_args(0, (1,), 'B', (1,), 1, 1, 1)
        self.check_args(1, (1,), 'b', (1,), 1, 1, 1)
        self.check_args(1, (1,), 'B', (1,), 1, 1, 1)
        self.check_args(1, (1,), 'c', (char_sz,), char_sz, char_sz, char_sz)
        self.check_args(1, (1,), 'h', (short_sz,), short_sz, short_sz, short_sz)
        self.check_args(1, (1,), 'H', (short_sz,), short_sz, short_sz, short_sz)
        self.check_args(1, (1,), 'i', (int_sz,), int_sz, int_sz, int_sz)
        self.check_args(1, (1,), 'I', (int_sz,), int_sz, int_sz, int_sz)
        self.check_args(1, (1,), 'l', (long_sz,), long_sz, long_sz, long_sz)
        self.check_args(1, (1,), 'L', (long_sz,), long_sz, long_sz, long_sz)
        self.check_args(1, (1,), 'q', (longlong_sz,), longlong_sz, longlong_sz, longlong_sz)
        self.check_args(1, (1,), 'Q', (longlong_sz,), longlong_sz, longlong_sz, longlong_sz)
        self.check_args(1, (1,), 'f', (float_sz,), float_sz, float_sz, float_sz)
        self.check_args(1, (1,), 'd', (double_sz,), double_sz, double_sz, double_sz)
        self.check_args(1, (1,), 'x', (1,), 1, 1, 1)
        self.check_args(1, (1,), 'P', (voidp_sz,), voidp_sz, voidp_sz, voidp_sz)
        self.check_args(1, (1,), '?', (bool_sz,), bool_sz, bool_sz, bool_sz)
        self.check_args(1, (1,), '@b', (1,), 1, 1, 1)
        self.check_args(1, (1,), '@B', (1,), 1, 1, 1)
        self.check_args(1, (1,), '@c', (char_sz,), char_sz, char_sz, char_sz)
        self.check_args(1, (1,), '@h', (short_sz,), short_sz, short_sz, short_sz)
        self.check_args(1, (1,), '@H', (short_sz,), short_sz, short_sz, short_sz)
        self.check_args(1, (1,), '@i', (int_sz,), int_sz, int_sz, int_sz)
        self.check_args(1, (1,), '@I', (int_sz,), int_sz, int_sz, int_sz)
        self.check_args(1, (1,), '@l', (long_sz,), long_sz, long_sz, long_sz)
        self.check_args(1, (1,), '@L', (long_sz,), long_sz, long_sz, long_sz)
        self.check_args(1, (1,), '@q', (longlong_sz,), longlong_sz, longlong_sz, longlong_sz)
        self.check_args(1, (1,), '@Q', (longlong_sz,), longlong_sz, longlong_sz, longlong_sz)
        self.check_args(1, (1,), '@f', (float_sz,), float_sz, float_sz, float_sz)
        self.check_args(1, (1,), '@d', (double_sz,), double_sz, double_sz, double_sz)
        self.check_args(1, (1,), '@?', (bool_sz,), bool_sz, bool_sz, bool_sz)
        self.check_args(1, (1,), '=b', (1,), 1, 1, 1)
        self.check_args(1, (1,), '=B', (1,), 1, 1, 1)
        self.check_args(1, (1,), '=c', (1,), 1, 1, 1)
        self.check_args(1, (1,), '=h', (2,), 2, 2, 2)
        self.check_args(1, (1,), '=H', (2,), 2, 2, 2)
        self.check_args(1, (1,), '=i', (4,), 4, 4, 4)
        self.check_args(1, (1,), '=I', (4,), 4, 4, 4)
        self.check_args(1, (1,), '=l', (4,), 4, 4, 4)
        self.check_args(1, (1,), '=L', (4,), 4, 4, 4)
        self.check_args(1, (1,), '=q', (8,), 8, 8, 8)
        self.check_args(1, (1,), '=Q', (8,), 8, 8, 8)
        self.check_args(1, (1,), '=?', (1,), 1, 1, 1)
        self.check_args(1, (1,), '<h', (2,), 2, 2, 2)
        self.check_args(1, (1,), '>h', (2,), 2, 2, 2)
        self.check_args(1, (1,), '!h', (2,), 2, 2, 2)
        self.check_args(1, (1,), '<q', (8,), 8, 8, 8)
        self.check_args(1, (1,), '>q', (8,), 8, 8, 8)
        self.check_args(1, (1,), '!q', (8,), 8, 8, 8)
        self.check_args(1, (1,), '1x', (1,), 1, 1, 1)
        self.check_args(1, (1,), '2x', (2,), 2, 2, 2)
        self.check_args(1, (1,), '3x', (3,), 3, 3, 3)
        self.check_args(1, (1,), '4x', (4,), 4, 4, 4)
        self.check_args(1, (1,), '5x', (5,), 5, 5, 5)
        self.check_args(1, (1,), '6x', (6,), 6, 6, 6)
        self.check_args(1, (1,), '7x', (7,), 7, 7, 7)
        self.check_args(1, (1,), '8x', (8,), 8, 8, 8)
        self.check_args(1, (1,), '9x', (9,), 9, 9, 9)
        self.check_args(1, (1,), '1h', (2,), 2, 2, 2)
        self.check_args(1, (1,), '=1h', (2,), 2, 2, 2)
        self.assertRaises(ValueError, Exporter, (2, 1), '')
        self.assertRaises(ValueError, Exporter, (2, 1), 'W')
        self.assertRaises(ValueError, Exporter, (2, 1), '^Q')
        self.assertRaises(ValueError, Exporter, (2, 1), '=W')
        self.assertRaises(ValueError, Exporter, (2, 1), '=f')
        self.assertRaises(ValueError, Exporter, (2, 1), '=d')
        self.assertRaises(ValueError, Exporter, (2, 1), '<f')
        self.assertRaises(ValueError, Exporter, (2, 1), '<d')
        self.assertRaises(ValueError, Exporter, (2, 1), '>f')
        self.assertRaises(ValueError, Exporter, (2, 1), '>d')
        self.assertRaises(ValueError, Exporter, (2, 1), '!f')
        self.assertRaises(ValueError, Exporter, (2, 1), '!d')
        self.assertRaises(ValueError, Exporter, (2, 1), '0x')
        self.assertRaises(ValueError, Exporter, (2, 1), '11x')
        self.assertRaises(ValueError, Exporter, (2, 1), 'BB')

    def test_strides(self):
        self.check_args(1, (10,), '=h', (2,), 20, 20, 2)
        self.check_args(1, (5, 3), '=h', (6, 2), 30, 30, 2)
        self.check_args(1, (7, 3, 5), '=h', (30, 10, 2), 210, 210, 2)
        self.check_args(1, (13, 5, 11, 3), '=h', (330, 66, 6, 2), 4290, 4290, 2)
        self.check_args(3, (7, 3, 5), '=h', (2, 14, 42), 210, 210, 2)
        self.check_args(3, (7, 3, 5), '=h', (2, 16, 48), 210, 240, 2)
        self.check_args(3, (13, 5, 11, 3), '=h', (440, 88, 8, 2), 4290, 5720, 2)
        self.check_args(3, (7, 5), '3x', (15, 3), 105, 105, 3)
        self.check_args(3, (7, 5), '3x', (3, 21), 105, 105, 3)
        self.check_args(3, (7, 5), '3x', (3, 24), 105, 120, 3)

    def test_readonly(self):
        a = Exporter((2,), 'h', readonly=True)
        self.assertTrue(a.readonly)
        b = Importer(a, PyBUF_STRIDED_RO)
        self.assertRaises(BufferError, Importer, a, PyBUF_STRIDED)
        b = Importer(a, PyBUF_STRIDED_RO)

    def test_is_contiguous(self):
        a = Exporter((10,), '=h')
        self.assertTrue(a.is_contiguous('C'))
        self.assertTrue(a.is_contiguous('F'))
        self.assertTrue(a.is_contiguous('A'))
        a = Exporter((10, 4), '=h')
        self.assertTrue(a.is_contiguous('C'))
        self.assertTrue(a.is_contiguous('A'))
        self.assertFalse(a.is_contiguous('F'))
        a = Exporter((13, 5, 11, 3), '=h', (330, 66, 6, 2))
        self.assertTrue(a.is_contiguous('C'))
        self.assertTrue(a.is_contiguous('A'))
        self.assertFalse(a.is_contiguous('F'))
        a = Exporter((10, 4), '=h', (2, 20))
        self.assertTrue(a.is_contiguous('F'))
        self.assertTrue(a.is_contiguous('A'))
        self.assertFalse(a.is_contiguous('C'))
        a = Exporter((13, 5, 11, 3), '=h', (2, 26, 130, 1430))
        self.assertTrue(a.is_contiguous('F'))
        self.assertTrue(a.is_contiguous('A'))
        self.assertFalse(a.is_contiguous('C'))
        a = Exporter((2, 11, 6, 4), '=h', (576, 48, 8, 2))
        self.assertFalse(a.is_contiguous('A'))
        a = Exporter((2, 11, 6, 4), '=h', (2, 4, 48, 288))
        self.assertFalse(a.is_contiguous('A'))
        a = Exporter((3, 2, 2), '=h', (16, 8, 4))
        self.assertFalse(a.is_contiguous('A'))
        a = Exporter((3, 2, 2), '=h', (4, 12, 24))
        self.assertFalse(a.is_contiguous('A'))

    def test_PyBUF_flags(self):
        a = Exporter((10, 2), 'd')
        b = Importer(a, PyBUF_SIMPLE)
        self.assertTrue(b.obj is a)
        self.assertTrue(b.format is None)
        self.assertEqual(b.len, a.len)
        self.assertEqual(b.itemsize, a.itemsize)
        self.assertTrue(b.shape is None)
        self.assertTrue(b.strides is None)
        self.assertTrue(b.suboffsets is None)
        self.assertTrue(b.internal is None)
        self.assertFalse(b.readonly)
        b = Importer(a, PyBUF_WRITABLE)
        self.assertTrue(b.obj is a)
        self.assertTrue(b.format is None)
        self.assertEqual(b.len, a.len)
        self.assertEqual(b.itemsize, a.itemsize)
        self.assertTrue(b.shape is None)
        self.assertTrue(b.strides is None)
        self.assertTrue(b.suboffsets is None)
        self.assertTrue(b.internal is None)
        self.assertFalse(b.readonly)
        b = Importer(a, PyBUF_ND)
        self.assertTrue(b.obj is a)
        self.assertTrue(b.format is None)
        self.assertEqual(b.len, a.len)
        self.assertEqual(b.itemsize, a.itemsize)
        self.assertEqual(b.shape, a.shape)
        self.assertTrue(b.strides is None)
        self.assertTrue(b.suboffsets is None)
        self.assertTrue(b.internal is None)
        self.assertFalse(b.readonly)
        a = Exporter((5, 10), '=h', (24, 2))
        b = Importer(a, PyBUF_STRIDES)
        self.assertTrue(b.obj is a)
        self.assertTrue(b.format is None)
        self.assertEqual(b.len, a.len)
        self.assertEqual(b.itemsize, a.itemsize)
        self.assertEqual(b.shape, a.shape)
        self.assertEqual(b.strides, a.strides)
        self.assertTrue(b.suboffsets is None)
        self.assertTrue(b.internal is None)
        self.assertFalse(b.readonly)
        b = Importer(a, PyBUF_FULL)
        self.assertTrue(b.obj is a)
        self.assertEqual(b.format, '=h')
        self.assertEqual(b.len, a.len)
        self.assertEqual(b.itemsize, a.itemsize)
        self.assertEqual(b.shape, a.shape)
        self.assertEqual(b.strides, a.strides)
        self.assertTrue(b.suboffsets is None)
        self.assertTrue(b.internal is None)
        self.assertFalse(b.readonly)
        self.assertRaises(BufferError, Importer, a, PyBUF_SIMPLE)
        self.assertRaises(BufferError, Importer, a, PyBUF_WRITABLE)
        self.assertRaises(BufferError, Importer, a, PyBUF_ND)
        self.assertRaises(BufferError, Importer, a, PyBUF_C_CONTIGUOUS)
        self.assertRaises(BufferError, Importer, a, PyBUF_F_CONTIGUOUS)
        self.assertRaises(BufferError, Importer, a, PyBUF_ANY_CONTIGUOUS)
        self.assertRaises(BufferError, Importer, a, PyBUF_CONTIG)

    def test_negative_strides(self):
        self.check_args(3, (3, 5, 4), 'B', (20, 4, -1), 60, 60, 1, 3)
        self.check_args(3, (3, 5, 3), 'B', (20, 4, -1), 45, 60, 1, 2)
        self.check_args(3, (3, 5, 4), 'B', (20, -4, 1), 60, 60, 1, 16)
        self.check_args(3, (3, 5, 4), 'B', (-20, -4, -1), 60, 60, 1, 59)
        self.check_args(3, (3, 5, 3), 'B', (-20, -4, -1), 45, 60, 1, 58)

    def test_attributes(self):
        a = Exporter((13, 5, 11, 3), '=h', (440, 88, 8, 2))
        self.assertEqual(a.ndim, 4)
        self.assertEqual(a.itemsize, 2)
        self.assertFalse(a.readonly)
        self.assertEqual(a.shape, (13, 5, 11, 3))
        self.assertEqual(a.format, '=h')
        self.assertEqual(a.strides, (440, 88, 8, 2))
        self.assertEqual(a.len, 4290)
        self.assertEqual(a.buflen, 5720)
        self.assertEqual(a.buf, ctypes.addressof(a._buf))
        a = Exporter((8,))
        self.assertEqual(a.ndim, 1)
        self.assertEqual(a.itemsize, 1)
        self.assertFalse(a.readonly)
        self.assertEqual(a.shape, (8,))
        self.assertEqual(a.format, 'B')
        self.assertTrue(isinstance(a.strides, tuple))
        self.assertEqual(a.strides, (1,))
        self.assertEqual(a.len, 8)
        self.assertEqual(a.buflen, 8)
        a = Exporter([13, 5, 11, 3], '=h', [440, 88, 8, 2])
        self.assertTrue(isinstance(a.shape, tuple))
        self.assertTrue(isinstance(a.strides, tuple))
        self.assertEqual(a.shape, (13, 5, 11, 3))
        self.assertEqual(a.strides, (440, 88, 8, 2))

    def test_itemsize(self):
        exp = Exporter((4, 5), format='B', itemsize=8)
        imp = Importer(exp, PyBUF_RECORDS)
        self.assertEqual(imp.itemsize, 8)
        self.assertEqual(imp.format, 'B')
        self.assertEqual(imp.strides, (40, 8))
        exp = Exporter((4, 5), format='weird', itemsize=5)
        imp = Importer(exp, PyBUF_RECORDS)
        self.assertEqual(imp.itemsize, 5)
        self.assertEqual(imp.format, 'weird')
        self.assertEqual(imp.strides, (25, 5))

    def check_args(self, call_flags, shape, format, strides, length, bufsize, itemsize, offset=0):
        format_arg = format if call_flags & 1 else None
        strides_arg = strides if call_flags & 2 else None
        a = Exporter(shape, format_arg, strides_arg)
        self.assertEqual(a.buflen, bufsize)
        self.assertEqual(a.buf, ctypes.addressof(a._buf) + offset)
        m = Importer(a, PyBUF_RECORDS_RO)
        self.assertEqual(m.buf, a.buf)
        self.assertEqual(m.len, length)
        self.assertEqual(m.format, format)
        self.assertEqual(m.itemsize, itemsize)
        self.assertEqual(m.shape, shape)
        self.assertEqual(m.strides, strides)