import functools
import warnings
import numpy as np
from numba import jit, typeof
from numba.core import cgutils, types, serialize, sigutils, errors
from numba.core.extending import (is_jitted, overload_attribute,
from numba.core.typing import npydecl
from numba.core.typing.templates import AbstractTemplate, signature
from numba.cpython.unsafe.tuple import tuple_setitem
from numba.np.ufunc import _internal
from numba.parfors import array_analysis
from numba.np.ufunc import ufuncbuilder
from numba.np import numpy_support
from typing import Callable
from llvmlite import ir
class DUFuncKernel(npyimpl._Kernel):
    """
        npyimpl._Kernel subclass responsible for lowering a DUFunc kernel
        (element-wise function) inside a broadcast loop (which is
        generated by npyimpl.numpy_ufunc_kernel()).
        """
    dufunc = _dufunc

    def __init__(self, context, builder, outer_sig):
        super(DUFuncKernel, self).__init__(context, builder, outer_sig)
        self.inner_sig, self.cres = self.dufunc.find_ewise_function(outer_sig.args)

    def generate(self, *args):
        isig = self.inner_sig
        osig = self.outer_sig
        cast_args = [self.cast(val, inty, outty) for val, inty, outty in zip(args, osig.args, isig.args)]
        if self.cres.objectmode:
            func_type = self.context.call_conv.get_function_type(types.pyobject, [types.pyobject] * len(isig.args))
        else:
            func_type = self.context.call_conv.get_function_type(isig.return_type, isig.args)
        module = self.builder.block.function.module
        entry_point = cgutils.get_or_insert_function(module, func_type, self.cres.fndesc.llvm_func_name)
        entry_point.attributes.add('alwaysinline')
        _, res = self.context.call_conv.call_function(self.builder, entry_point, isig.return_type, isig.args, cast_args)
        return self.cast(res, isig.return_type, osig.return_type)