import sys
from typing import Any
import pytorch_lightning as pl
class HPUAccelerator:
    auto_device_count = ...
    get_parallel_devices = ...
    is_available = ...
    parse_devices = ...
    setup_device = ...
    teardown = ...

    def __init__(self, *_: Any, **__: Any) -> None:
        raise NotImplementedError('The `HPUAccelerator` class has been moved to an external package. Install the extension package as `pip install lightning-habana` and import with `from lightning_habana import HPUAccelerator`. Please see: https://github.com/Lightning-AI/lightning-Habana for more details.')