import os
from ... import logging
from ..base import (
from .base import FSCommand, FSTraitedSpec
from .model import GLMFitInputSpec, GLMFit
class GTMPVCInputSpec(FSTraitedSpec):
    in_file = File(exists=True, argstr='--i %s', mandatory=True, copyfile=False, desc='input volume - source data to pvc')
    frame = traits.Int(argstr='--frame %i', desc='only process 0-based frame F from inputvol')
    psf = traits.Float(argstr='--psf %f', desc='scanner PSF FWHM in mm')
    segmentation = File(argstr='--seg %s', exists=True, mandatory=True, desc='segfile : anatomical segmentation to define regions for GTM')
    _reg_xor = ['reg_file', 'regheader', 'reg_identity']
    reg_file = File(exists=True, argstr='--reg %s', mandatory=True, desc='LTA registration file that maps PET to anatomical', xor=_reg_xor)
    regheader = traits.Bool(argstr='--regheader', mandatory=True, desc='assume input and seg share scanner space', xor=_reg_xor)
    reg_identity = traits.Bool(argstr='--reg-identity', mandatory=True, desc='assume that input is in anatomical space', xor=_reg_xor)
    pvc_dir = traits.Str(argstr='--o %s', desc='save outputs to dir', genfile=True)
    mask_file = File(exists=True, argstr='--mask %s', desc='ignore areas outside of the mask (in input vol space)')
    auto_mask = traits.Tuple(traits.Float, traits.Float, argstr='--auto-mask %f %f', desc='FWHM thresh : automatically compute mask')
    no_reduce_fov = traits.Bool(argstr='--no-reduce-fov', desc='do not reduce FoV to encompass mask')
    reduce_fox_eqodd = traits.Bool(argstr='--reduce-fox-eqodd', desc='reduce FoV to encompass mask but force nc=nr and ns to be odd')
    contrast = InputMultiPath(File(exists=True), argstr='--C %s...', desc='contrast file')
    default_seg_merge = traits.Bool(argstr='--default-seg-merge', desc='default schema for merging ROIs')
    merge_hypos = traits.Bool(argstr='--merge-hypos', desc='merge left and right hypointensites into to ROI')
    merge_cblum_wm_gyri = traits.Bool(argstr='--merge-cblum-wm-gyri', desc='cerebellum WM gyri back into cerebellum WM')
    tt_reduce = traits.Bool(argstr='--tt-reduce', desc='reduce segmentation to that of a tissue type')
    replace = traits.Tuple(traits.Int, traits.Int, argstr='--replace %i %i', desc='Id1 Id2 : replace seg Id1 with seg Id2')
    rescale = traits.List(argstr='--rescale %s...', desc='Id1 <Id2...>  : specify reference region(s) used to rescale (default is pons)')
    no_rescale = traits.Bool(argstr='--no-rescale', desc='do not global rescale such that mean of reference region is scaleref')
    scale_refval = traits.Float(argstr='--scale-refval %f', desc='refval : scale such that mean in reference region is refval')
    _ctab_inputs = ('color_table_file', 'default_color_table')
    color_table_file = File(exists=True, argstr='--ctab %s', xor=_ctab_inputs, desc='color table file with seg id names')
    default_color_table = traits.Bool(argstr='--ctab-default', xor=_ctab_inputs, desc='use $FREESURFER_HOME/FreeSurferColorLUT.txt')
    tt_update = traits.Bool(argstr='--tt-update', desc='changes tissue type of VentralDC, BrainStem, and Pons to be SubcortGM')
    lat = traits.Bool(argstr='--lat', desc='lateralize tissue types')
    no_tfe = traits.Bool(argstr='--no-tfe', desc='do not correct for tissue fraction effect (with --psf 0 turns off PVC entirely)')
    no_pvc = traits.Bool(argstr='--no-pvc', desc='turns off PVC entirely (both PSF and TFE)')
    tissue_fraction_resolution = traits.Float(argstr='--segpvfres %f', desc='set the tissue fraction resolution parameter (def is 0.5)')
    rbv = traits.Bool(argstr='--rbv', requires=['subjects_dir'], desc='perform Region-based Voxelwise (RBV) PVC')
    rbv_res = traits.Float(argstr='--rbv-res %f', desc='voxsize : set RBV voxel resolution (good for when standard res takes too much memory)')
    mg = traits.Tuple(traits.Float, traits.List(traits.String), argstr='--mg %g %s', desc='gmthresh RefId1 RefId2 ...: perform Mueller-Gaertner PVC, gmthresh is min gm pvf bet 0 and 1')
    mg_ref_cerebral_wm = traits.Bool(argstr='--mg-ref-cerebral-wm', desc=' set MG RefIds to 2 and 41')
    mg_ref_lobes_wm = traits.Bool(argstr='--mg-ref-lobes-wm', desc='set MG RefIds to those for lobes when using wm subseg')
    mgx = traits.Float(argstr='--mgx %f', desc='gmxthresh : GLM-based Mueller-Gaertner PVC, gmxthresh is min gm pvf bet 0 and 1')
    km_ref = traits.List(argstr='--km-ref %s...', desc='RefId1 RefId2 ... : compute reference TAC for KM as mean of given RefIds')
    km_hb = traits.List(argstr='--km-hb %s...', desc='RefId1 RefId2 ... : compute HiBinding TAC for KM as mean of given RefIds')
    steady_state_params = traits.Tuple(traits.Float, traits.Float, traits.Float, argstr='--ss %f %f %f', desc='bpc scale dcf : steady-state analysis spec blood plasma concentration, unit scale and decay correction factor. You must also spec --km-ref. Turns off rescaling')
    X = traits.Bool(argstr='--X', desc='save X matrix in matlab4 format as X.mat (it will be big)')
    y = traits.Bool(argstr='--y', desc='save y matrix in matlab4 format as y.mat')
    beta = traits.Bool(argstr='--beta', desc='save beta matrix in matlab4 format as beta.mat')
    X0 = traits.Bool(argstr='--X0', desc='save X0 matrix in matlab4 format as X0.mat (it will be big)')
    save_input = traits.Bool(argstr='--save-input', desc='saves rescaled input as input.rescaled.nii.gz')
    save_eres = traits.Bool(argstr='--save-eres', desc='saves residual error')
    save_yhat = traits.Bool(argstr='--save-yhat', xor=['save_yhat_with_noise'], desc='save signal estimate (yhat) smoothed with the PSF')
    save_yhat_with_noise = traits.Tuple(traits.Int, traits.Int, argstr='--save-yhat-with-noise %i %i', xor=['save_yhat'], desc='seed nreps : save signal estimate (yhat) with noise')
    save_yhat_full_fov = traits.Bool(argstr='--save-yhat-full-fov', desc='save signal estimate (yhat)')
    save_yhat0 = traits.Bool(argstr='--save-yhat0', desc='save signal estimate (yhat)')
    optimization_schema = traits.Enum('3D', '2D', '1D', '3D_MB', '2D_MB', '1D_MB', 'MBZ', 'MB3', argstr='--opt %s', desc='opt : optimization schema for applying adaptive GTM')
    opt_tol = traits.Tuple(traits.Int, traits.Float, traits.Float, argstr='--opt-tol %i %f %f', desc='n_iters_max ftol lin_min_tol : optimization parameters for adaptive gtm using fminsearch')
    opt_brain = traits.Bool(argstr='--opt-brain', desc='apply adaptive GTM')
    opt_seg_merge = traits.Bool(argstr='--opt-seg-merge', desc='optimal schema for merging ROIs when applying adaptive GTM')
    num_threads = traits.Int(argstr='--threads %i', desc='threads : number of threads to use')
    psf_col = traits.Float(argstr='--psf-col %f', desc='xFWHM : full-width-half-maximum in the x-direction')
    psf_row = traits.Float(argstr='--psf-row %f', desc='yFWHM : full-width-half-maximum in the y-direction')
    psf_slice = traits.Float(argstr='--psf-slice %f', desc='zFWHM : full-width-half-maximum in the z-direction')