import copy
import itertools
import logging
import pickle
from io import StringIO
from collections import namedtuple as NamedTuple
import pyomo.common.unittest as unittest
from pyomo.common import DeveloperError
from pyomo.common.dependencies import numpy as np, numpy_available
from pyomo.common.dependencies import pandas as pd, pandas_available
from pyomo.common.log import LoggingIntercept
from pyomo.core.expr import native_numeric_types, native_types
import pyomo.core.base.set as SetModule
from pyomo.core.base.indexed_component import normalize_index
from pyomo.core.base.initializer import (
from pyomo.core.base.set import (
from pyomo.environ import (
class Test_SetInitializer(unittest.TestCase):

    def test_single_set(self):
        tmp = Set()
        a = SetInitializer(None)
        self.assertIs(type(a), SetInitializer)
        self.assertIsNone(a._set)
        self.assertIs(a(None, None, tmp), Any)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        a = SetInitializer(Reals)
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), ConstantInitializer)
        self.assertIs(a(None, None, tmp), Reals)
        self.assertIs(a._set.val, Reals)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        a = SetInitializer({1: Reals})
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), ItemInitializer)
        self.assertIs(a(None, 1, tmp), Reals)
        self.assertFalse(a.constant())
        self.assertFalse(a.verified)

    def test_intersect(self):
        tmp = Set()
        a = SetInitializer(None)
        a.intersect(SetInitializer(None))
        self.assertIs(type(a), SetInitializer)
        self.assertIsNone(a._set)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        self.assertIs(a(None, None, tmp), Any)
        a = SetInitializer(None)
        a.intersect(SetInitializer(Reals))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), ConstantInitializer)
        self.assertIs(a._set.val, Reals)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        self.assertIs(a(None, None, tmp), Reals)
        a = SetInitializer(None)
        a.intersect(BoundsInitializer(5, default_step=1))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), BoundsInitializer)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        self.assertEqual(a(None, None, tmp), RangeSet(5))
        a = SetInitializer(Reals)
        a.intersect(SetInitializer(None))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), ConstantInitializer)
        self.assertIs(a._set.val, Reals)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        self.assertIs(a(None, None, tmp), Reals)
        a = SetInitializer(Reals)
        a.intersect(SetInitializer(Integers))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), SetIntersectInitializer)
        self.assertIs(type(a._set._A), ConstantInitializer)
        self.assertIs(type(a._set._B), ConstantInitializer)
        self.assertIs(a._set._A.val, Reals)
        self.assertIs(a._set._B.val, Integers)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None, tmp)
        self.assertIs(type(s), SetIntersection_InfiniteSet)
        self.assertIs(s._sets[0], Reals)
        self.assertIs(s._sets[1], Integers)
        a = SetInitializer(Reals)
        a.intersect(SetInitializer(Integers))
        a.intersect(BoundsInitializer(3, default_step=1))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), SetIntersectInitializer)
        self.assertIs(type(a._set._A), SetIntersectInitializer)
        self.assertIs(type(a._set._B), BoundsInitializer)
        self.assertIs(a._set._A._A.val, Reals)
        self.assertIs(a._set._A._B.val, Integers)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None, tmp)
        self.assertIs(type(s), SetIntersection_OrderedSet)
        self.assertIs(type(s._sets[0]), SetIntersection_InfiniteSet)
        self.assertIsInstance(s._sets[1], RangeSet)
        p = Param(initialize=3)
        a = SetInitializer(Reals)
        a.intersect(SetInitializer(Integers))
        a.intersect(BoundsInitializer(p, default_step=0))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), SetIntersectInitializer)
        self.assertIs(type(a._set._A), SetIntersectInitializer)
        self.assertIs(type(a._set._B), BoundsInitializer)
        self.assertIs(a._set._A._A.val, Reals)
        self.assertIs(a._set._A._B.val, Integers)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None, tmp)
        self.assertIs(type(s), SetIntersection_InfiniteSet)
        p.construct()
        s.construct()
        self.assertIs(type(s), SetIntersection_OrderedSet)
        self.assertIs(type(s._sets[0]), SetIntersection_InfiniteSet)
        self.assertIsInstance(s._sets[1], RangeSet)
        self.assertFalse(s._sets[0].isfinite())
        self.assertFalse(s._sets[1].isfinite())
        self.assertTrue(s.isfinite())
        p = Param(initialize=3)
        a = SetInitializer(Reals)
        a.intersect(SetInitializer({1: Integers}))
        a.intersect(BoundsInitializer(p, default_step=0))
        self.assertIs(type(a), SetInitializer)
        self.assertIs(type(a._set), SetIntersectInitializer)
        self.assertIs(type(a._set._A), SetIntersectInitializer)
        self.assertIs(type(a._set._B), BoundsInitializer)
        self.assertIs(a._set._A._A.val, Reals)
        self.assertIs(type(a._set._A._B), ItemInitializer)
        self.assertFalse(a.constant())
        self.assertFalse(a.verified)
        with self.assertRaises(KeyError):
            a(None, None, tmp)
        s = a(None, 1, tmp)
        self.assertIs(type(s), SetIntersection_InfiniteSet)
        p.construct()
        s.construct()
        self.assertIs(type(s), SetIntersection_OrderedSet)
        self.assertIs(type(s._sets[0]), SetIntersection_InfiniteSet)
        self.assertIsInstance(s._sets[1], RangeSet)
        self.assertFalse(s._sets[0].isfinite())
        self.assertFalse(s._sets[1].isfinite())
        self.assertTrue(s.isfinite())

    def test_boundsinit(self):
        a = BoundsInitializer(5, default_step=1)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(5))
        a = BoundsInitializer((0, 5), default_step=1)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(0, 5))
        a = BoundsInitializer((0, 5, 2))
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(0, 5, 2))
        a = BoundsInitializer(())
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(None, None, 0))
        a = BoundsInitializer(5)
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(1, 5, 0))
        a = BoundsInitializer((0, 5))
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(0, 5, 0))
        a = BoundsInitializer((0, 5, 2))
        self.assertTrue(a.constant())
        self.assertFalse(a.verified)
        s = a(None, None)
        self.assertEqual(s, RangeSet(0, 5, 2))
        a = BoundsInitializer({1: 5}, default_step=1)
        self.assertFalse(a.constant())
        self.assertFalse(a.verified)
        s = a(None, 1)
        self.assertEqual(s, RangeSet(5))
        a = BoundsInitializer({1: (0, 5)}, default_step=1)
        self.assertFalse(a.constant())
        self.assertFalse(a.verified)
        s = a(None, 1)
        self.assertEqual(s, RangeSet(0, 5))

    def test_setdefault(self):
        tmp = Set()
        a = SetInitializer(None)
        self.assertIs(a(None, None, tmp), Any)
        a.setdefault(Reals)
        self.assertIs(a(None, None, tmp), Reals)
        a = SetInitializer(Integers)
        self.assertIs(a(None, None, tmp), Integers)
        a.setdefault(Reals)
        self.assertIs(a(None, None, tmp), Integers)
        a = BoundsInitializer(5, default_step=1)
        self.assertEqual(a(None, None), RangeSet(5))
        a.setdefault(Reals)
        self.assertEqual(a(None, None), RangeSet(5))
        a = SetInitializer(Reals)
        a.intersect(SetInitializer(Integers))
        self.assertIs(type(a(None, None, tmp)), SetIntersection_InfiniteSet)
        a.setdefault(RangeSet(5))
        self.assertIs(type(a(None, None, tmp)), SetIntersection_InfiniteSet)

    def test_indices(self):
        a = SetInitializer(None)
        self.assertFalse(a.contains_indices())
        with self.assertRaisesRegex(RuntimeError, 'does not contain embedded indices'):
            a.indices()
        a = SetInitializer([1, 2, 3])
        self.assertFalse(a.contains_indices())
        with self.assertRaisesRegex(RuntimeError, 'does not contain embedded indices'):
            a.indices()
        a = SetInitializer({1: [1, 2, 3], 2: [4]})
        self.assertTrue(a.contains_indices())
        self.assertEqual(list(a.indices()), [1, 2])
        a.intersect(SetInitializer({1: [4], 2: [1, 2]}))
        self.assertTrue(a.contains_indices())
        self.assertEqual(list(a.indices()), [1, 2])
        a = SetInitializer({1: [1, 2, 3], 2: [4]})
        self.assertTrue(a.contains_indices())
        self.assertEqual(list(a.indices()), [1, 2])
        a.intersect(SetInitializer({1: [4], 3: [1, 2]}))
        self.assertTrue(a.contains_indices())
        with self.assertRaisesRegex(ValueError, 'contains two sub-initializers with inconsistent'):
            a.indices()
        a = SetInitializer([1, 2])
        self.assertFalse(a.contains_indices())
        a.intersect(SetInitializer([1, 2]))
        self.assertFalse(a.contains_indices())
        with self.assertRaisesRegex(RuntimeError, 'does not contain embedded indices'):
            a.indices()