from __future__ import annotations
import logging # isort:skip
from ...core.enums import CalendarPosition
from ...core.has_props import HasProps, abstract
from ...core.properties import (
from .inputs import InputWidget
@abstract
class DateCommon(HasProps):
    """ Common properties for date-like picker widgets. """

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
    disabled_dates = Nullable(List(Either(Date, Tuple(Date, Date))), default=None, help='\n    A list of dates of ``(start, end)`` date ranges to make unavailable for\n    selection. All other dates will be avalable.\n\n    .. note::\n        Only one of ``disabled_dates`` and ``enabled_dates`` should be specified.\n    ')
    enabled_dates = Nullable(List(Either(Date, Tuple(Date, Date))), default=None, help='\n    A list of dates of ``(start, end)`` date ranges to make available for\n    selection. All other dates will be unavailable.\n\n    .. note::\n        Only one of ``disabled_dates`` and ``enabled_dates`` should be specified.\n    ')
    date_format = String(default='Y-m-d', help='\n    Formatting specification for the display of the picked date.\n\n    +---+-----------------------------------------------------------+-----------------------------------------+\n    | d | Day of the month, 2 digits with leading zeros             | 01 to 31                                |\n    | D | A textual representation of a day                         | Mon through Sun                         |\n    | l | A full textual representation of the day of the week      | Sunday through Saturday                 |\n    | j | Day of the month without leading zeros                    | 1 to 31                                 |\n    | J | Day of the month without leading zeros and ordinal suffix | 1st, 2nd, to 31st                       |\n    | w | Numeric representation of the day of the week             | 0 (for Sunday) through 6 (for Saturday) |\n    | W | Numeric representation of the week                        | 0 through 52                            |\n    | F | A full textual representation of a month                  | January through December                |\n    | m | Numeric representation of a month, with leading zero      | 01 through 12                           |\n    | n | Numeric representation of a month, without leading zeros  | 1 through 12                            |\n    | M | A short textual representation of a month                 | Jan through Dec                         |\n    | U | The number of seconds since the Unix Epoch                | 1413704993                              |\n    | y | A two digit representation of a year                      | 99 or 03                                |\n    | Y | A full numeric representation of a year, 4 digits         | 1999 or 2003                            |\n    | Z | ISO Date format                                           | 2017-03-04T01:23:43.000Z                |\n    +---+-----------------------------------------------------------+-----------------------------------------+\n\n    See also https://flatpickr.js.org/formatting/#date-formatting-tokens.\n    ')