from __future__ import absolute_import, division, print_function
import re
 to reduce commands generated by an edgeswitch module
        we take interfaces one by one and we try to merge them with neighbors if everyone has same commands to run
    