from ipywidgets import (
from ipywidgets.widgets.trait_types import TypedTuple
from traitlets import (
from .._base.Three import ThreeWidget
from .._base.uniforms import uniforms_serialization
from ..enums import *
from ..traits import *
from .._base.Three import ThreeWidget
import inspect
FogExp2

    Autogenerated by generate-wrappers.js
    See https://threejs.org/docs/#api/scenes/FogExp2
    