from prov.model import ProvDocument, Namespace, Literal, PROV, Identifier
import datetime
def primer_example():
    g = ProvDocument()
    ex = Namespace('ex', 'http://example/')
    g.add_namespace('dcterms', 'http://purl.org/dc/terms/')
    g.add_namespace('foaf', 'http://xmlns.com/foaf/0.1/')
    g.entity(ex['article'], {'dcterms:title': 'Crime rises in cities'})
    g.entity(ex['articleV1'])
    g.entity(ex['articleV2'])
    g.entity(ex['dataSet1'])
    g.entity(ex['dataSet2'])
    g.entity(ex['regionList'])
    g.entity(ex['composition'])
    g.entity(ex['chart1'])
    g.entity(ex['chart2'])
    g.entity(ex['blogEntry'])
    g.activity('ex:compile')
    g.activity('ex:compile2')
    g.activity('ex:compose')
    g.activity('ex:correct', '2012-03-31T09:21:00', '2012-04-01T15:21:00')
    g.activity('ex:illustrate')
    g.used('ex:compose', 'ex:dataSet1', other_attributes={'prov:role': 'ex:dataToCompose'})
    g.used('ex:compose', 'ex:regionList', other_attributes={'prov:role': 'ex:regionsToAggregateBy'})
    g.wasGeneratedBy('ex:composition', 'ex:compose')
    g.used('ex:illustrate', 'ex:composition')
    g.wasGeneratedBy('ex:chart1', 'ex:illustrate')
    g.wasGeneratedBy('ex:chart1', 'ex:compile', '2012-03-02T10:30:00')
    g.agent('ex:derek', {'prov:type': PROV['Person'], 'foaf:givenName': 'Derek', 'foaf:mbox': '<mailto:derek@example.org>'})
    g.wasAssociatedWith('ex:compose', 'ex:derek')
    g.wasAssociatedWith('ex:illustrate', 'ex:derek')
    g.agent('ex:chartgen', {'prov:type': PROV['Organization'], 'foaf:name': 'Chart Generators Inc'})
    g.actedOnBehalfOf('ex:derek', 'ex:chartgen', 'ex:compose')
    g.wasAttributedTo('ex:chart1', 'ex:derek')
    g.wasGeneratedBy('ex:dataSet2', 'ex:correct')
    g.used('ex:correct', 'ex:dataSet1')
    g.wasDerivedFrom('ex:dataSet2', 'ex:dataSet1', other_attributes={'prov:type': PROV['Revision']})
    g.wasDerivedFrom('ex:chart2', 'ex:dataSet2')
    g.wasDerivedFrom('ex:blogEntry', 'ex:article', other_attributes={'prov:type': PROV['Quotation']})
    g.specializationOf('ex:articleV1', 'ex:article')
    g.wasDerivedFrom('ex:articleV1', 'ex:dataSet1')
    g.specializationOf('ex:articleV2', 'ex:article')
    g.wasDerivedFrom('ex:articleV2', 'ex:dataSet2')
    g.alternateOf('ex:articleV2', 'ex:articleV1')
    return g