import sys
from breezy import tests
from breezy.tests import features
def test__resize(self):
    obj = self.module.SimpleSet()
    k1 = _Hashable(501)
    k2 = _Hashable(591)
    k3 = _Hashable(2051)
    obj.add(k1)
    obj.add(k2)
    obj.add(k3)
    obj.discard(k2)
    self.assertFillState(2, 3, 1023, obj)
    self.assertEqual(1024, obj._py_resize(500))
    self.assertFillState(2, 2, 1023, obj)
    obj.add(k2)
    obj.discard(k3)
    self.assertFillState(2, 3, 1023, obj)
    self.assertEqual(4096, obj._py_resize(4095))
    self.assertFillState(2, 2, 4095, obj)
    self.assertIn(k1, obj)
    self.assertIn(k2, obj)
    self.assertNotIn(k3, obj)
    obj.add(k2)
    self.assertIn(k2, obj)
    obj.discard(k2)
    self.assertEqual((591, '<dummy>'), obj._test_lookup(k2))
    self.assertFillState(1, 2, 4095, obj)
    self.assertEqual(2048, obj._py_resize(1024))
    self.assertFillState(1, 1, 2047, obj)
    self.assertEqual((591, '<null>'), obj._test_lookup(k2))