from pyparsing import (
import pydot
def graph_definition():
    global graphparser
    if not graphparser:
        colon = Literal(':')
        lbrace = Literal('{')
        rbrace = Literal('}')
        lbrack = Literal('[')
        rbrack = Literal(']')
        lparen = Literal('(')
        rparen = Literal(')')
        equals = Literal('=')
        comma = Literal(',')
        semi = Literal(';')
        at = Literal('@')
        minus = Literal('-')
        strict_ = CaselessLiteral('strict')
        graph_ = CaselessLiteral('graph')
        digraph_ = CaselessLiteral('digraph')
        subgraph_ = CaselessLiteral('subgraph')
        node_ = CaselessLiteral('node')
        edge_ = CaselessLiteral('edge')
        identifier = Word(pyparsing_unicode.BasicMultilingualPlane.alphanums + '_.').setName('identifier')
        double_quoted_string = QuotedString('"', multiline=True, unquoteResults=False, escChar='\\')
        html_text = Forward()
        inner_html = OneOrMore(CharsNotIn('<>') | html_text)
        html_text << '<' + inner_html + '>'
        html_text.setParseAction(lambda arr: ''.join(arr))
        ID = (identifier | html_text | double_quoted_string).setName('ID')
        float_number = Combine(Optional(minus) + OneOrMore(Word(nums + '.'))).setName('float_number')
        righthand_id = (float_number | ID).setName('righthand_id')
        port_angle = (at + ID).setName('port_angle')
        port_location = (OneOrMore(Group(colon + ID)) | Group(colon + lparen + ID + comma + ID + rparen)).setName('port_location')
        port = (Group(port_location + Optional(port_angle)) | Group(port_angle + Optional(port_location))).setName('port')
        node_id = ID + Optional(port)
        a_list = OneOrMore(ID + Optional(equals + righthand_id) + Optional(comma.suppress())).setName('a_list')
        attr_list = OneOrMore(lbrack.suppress() + Optional(a_list) + rbrack.suppress()).setName('attr_list')
        attr_stmt = (Group(graph_ | node_ | edge_) + attr_list).setName('attr_stmt')
        edgeop = (Literal('--') | Literal('->')).setName('edgeop')
        stmt_list = Forward()
        graph_stmt = Group(lbrace.suppress() + Optional(stmt_list) + rbrace.suppress() + Optional(semi.suppress())).setName('graph_stmt')
        edge_point = Forward()
        edgeRHS = OneOrMore(edgeop + edge_point)
        edge_stmt = edge_point + edgeRHS + Optional(attr_list)
        subgraph = Group(subgraph_ + Optional(ID) + graph_stmt).setName('subgraph')
        edge_point << Group(subgraph | graph_stmt | node_id).setName('edge_point')
        node_stmt = (node_id + Optional(attr_list) + Optional(semi.suppress())).setName('node_stmt')
        assignment = (ID + equals + righthand_id).setName('assignment')
        stmt = (assignment | edge_stmt | attr_stmt | subgraph | graph_stmt | node_stmt).setName('stmt')
        stmt_list << OneOrMore(stmt + Optional(semi.suppress()))
        graphparser = OneOrMore((Optional(strict_) + Group(graph_ | digraph_) + Optional(ID) + graph_stmt).setResultsName('graph'))
        singleLineComment = Group('//' + restOfLine) | Group('#' + restOfLine)
        graphparser.ignore(singleLineComment)
        graphparser.ignore(cStyleComment)
        assignment.setParseAction(push_attr_list)
        a_list.setParseAction(push_attr_list)
        edge_stmt.setParseAction(push_edge_stmt)
        node_stmt.setParseAction(push_node_stmt)
        attr_stmt.setParseAction(push_default_stmt)
        subgraph.setParseAction(push_subgraph_stmt)
        graph_stmt.setParseAction(push_graph_stmt)
        graphparser.setParseAction(push_top_graph_stmt)
    return graphparser