from sys import version_info
from pyflakes import messages as m
from pyflakes.test.harness import TestCase, skipIf
def test_variable_annotations(self):
    self.flakes('\n        name: str\n        age: int\n        ')
    self.flakes("\n        name: str = 'Bob'\n        age: int = 18\n        ")
    self.flakes('\n        class C:\n            name: str\n            age: int\n        ')
    self.flakes("\n        class C:\n            name: str = 'Bob'\n            age: int = 18\n        ")
    self.flakes('\n        def f():\n            name: str\n            age: int\n        ', m.UnusedAnnotation, m.UnusedAnnotation)
    self.flakes("\n        def f():\n            name: str = 'Bob'\n            age: int = 18\n            foo: not_a_real_type = None\n        ", m.UnusedVariable, m.UnusedVariable, m.UnusedVariable, m.UndefinedName)
    self.flakes('\n        def f():\n            name: str\n            print(name)\n        ', m.UndefinedName)
    self.flakes('\n        from typing import Any\n        def f():\n            a: Any\n        ', m.UnusedAnnotation)
    self.flakes('\n        foo: not_a_real_type\n        ', m.UndefinedName)
    self.flakes('\n        foo: not_a_real_type = None\n        ', m.UndefinedName)
    self.flakes('\n        class C:\n            foo: not_a_real_type\n        ', m.UndefinedName)
    self.flakes('\n        class C:\n            foo: not_a_real_type = None\n        ', m.UndefinedName)
    self.flakes('\n        def f():\n            class C:\n                foo: not_a_real_type\n        ', m.UndefinedName)
    self.flakes('\n        def f():\n            class C:\n                foo: not_a_real_type = None\n        ', m.UndefinedName)
    self.flakes('\n        from foo import Bar\n        bar: Bar\n        ')
    self.flakes("\n        from foo import Bar\n        bar: 'Bar'\n        ")
    self.flakes('\n        import foo\n        bar: foo.Bar\n        ')
    self.flakes("\n        import foo\n        bar: 'foo.Bar'\n        ")
    self.flakes('\n        from foo import Bar\n        def f(bar: Bar): pass\n        ')
    self.flakes("\n        from foo import Bar\n        def f(bar: 'Bar'): pass\n        ")
    self.flakes('\n        from foo import Bar\n        def f(bar) -> Bar: return bar\n        ')
    self.flakes("\n        from foo import Bar\n        def f(bar) -> 'Bar': return bar\n        ")
    self.flakes("\n        bar: 'Bar'\n        ", m.UndefinedName)
    self.flakes("\n        bar: 'foo.Bar'\n        ", m.UndefinedName)
    self.flakes('\n        from foo import Bar\n        bar: str\n        ', m.UnusedImport)
    self.flakes('\n        from foo import Bar\n        def f(bar: str): pass\n        ', m.UnusedImport)
    self.flakes('\n        def f(a: A) -> A: pass\n        class A: pass\n        ', m.UndefinedName, m.UndefinedName)
    self.flakes("\n        def f(a: 'A') -> 'A': return a\n        class A: pass\n        ")
    self.flakes('\n        a: A\n        class A: pass\n        ', m.UndefinedName)
    self.flakes("\n        a: 'A'\n        class A: pass\n        ")
    self.flakes('\n        T: object\n        def f(t: T): pass\n        ', m.UndefinedName)
    self.flakes("\n        T: object\n        def g(t: 'T'): pass\n        ")
    self.flakes("\n        a: 'A B'\n        ", m.ForwardAnnotationSyntaxError)
    self.flakes("\n        a: 'A; B'\n        ", m.ForwardAnnotationSyntaxError)
    self.flakes("\n        a: '1 + 2'\n        ")
    self.flakes('\n        a: \'a: "A"\'\n        ', m.ForwardAnnotationSyntaxError)