import shutil
import sys
from breezy import (branch, controldir, errors, info, osutils, tests, upgrade,
from breezy.bzr import bzrdir
from breezy.transport import memory
def test_info_shared_repository_with_trees(self):
    format = controldir.format_registry.make_controldir('knit')
    transport = self.get_transport()
    repo = self.make_repository('repo', shared=True, format=format)
    repo.set_make_working_trees(True)
    out, err = self.run_bzr('info -v repo')
    self.assertEqualDiff('Shared repository with trees (format: dirstate or dirstate-tags or knit)\nLocation:\n  shared repository: repo\n\nFormat:\n       control: Meta directory format 1\n    repository: {}\n\nControl directory:\n         0 branches\n\nCreate working tree for new branches inside the repository.\n\nRepository:\n         0 revisions\n'.format(format.repository_format.get_format_description()), out)
    self.assertEqual('', err)
    repo.controldir.root_transport.mkdir('branch1')
    branch1 = controldir.ControlDir.create_branch_convenience('repo/branch1', format=format)
    branch2 = branch1.controldir.sprout('repo/branch2').open_branch()
    out, err = self.run_bzr('info repo/branch1 --verbose')
    self.assertEqualDiff('Repository tree (format: knit)\nLocation:\n  shared repository: repo\n  repository branch: repo/branch1\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         0 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         0 revisions\n\nRepository:\n         0 revisions\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description()), out)
    self.assertEqual('', err)
    self.build_tree(['repo/branch1/a'])
    tree1 = branch1.controldir.open_workingtree()
    tree1.add('a')
    tree1.commit('commit one')
    rev = repo.get_revision(branch1.last_revision())
    datestring_first = osutils.format_date(rev.timestamp, rev.timezone)
    out, err = self.run_bzr('info -v repo/branch1')
    self.assertEqualDiff('Repository tree (format: knit)\nLocation:\n  shared repository: repo\n  repository branch: repo/branch1\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info repo/branch2 --verbose')
    self.assertEqualDiff('Repository tree (format: knit)\nLocation:\n  shared repository: repo\n  repository branch: repo/branch2\n\nRelated branches:\n  parent branch: repo/branch1\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         0 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         0 revisions\n\nRepository:\n         1 revision\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description()), out)
    self.assertEqual('', err)
    tree2 = branch2.controldir.open_workingtree()
    tree2.pull(branch1)
    out, err = self.run_bzr('info -v repo/branch2')
    self.assertEqualDiff('Repository tree (format: knit)\nLocation:\n  shared repository: repo\n  repository branch: repo/branch2\n\nRelated branches:\n  parent branch: repo/branch1\n\nFormat:\n       control: Meta directory format 1\n  working tree: Working tree format 3\n        branch: {}\n    repository: {}\n\nControl directory:\n         1 branches\n\nIn the working tree:\n         1 unchanged\n         0 modified\n         0 added\n         0 removed\n         0 renamed\n         0 copied\n         0 unknown\n         0 ignored\n         0 versioned subdirectories\n\nBranch history:\n         1 revision\n         0 days old\n   first revision: {}\n  latest revision: {}\n\nRepository:\n         1 revision\n'.format(format.get_branch_format().get_format_description(), format.repository_format.get_format_description(), datestring_first, datestring_first), out)
    self.assertEqual('', err)
    out, err = self.run_bzr('info -v repo')
    self.assertEqualDiff('Shared repository with trees (format: dirstate or dirstate-tags or knit)\nLocation:\n  shared repository: repo\n\nFormat:\n       control: Meta directory format 1\n    repository: {}\n\nControl directory:\n         0 branches\n\nCreate working tree for new branches inside the repository.\n\nRepository:\n         1 revision\n'.format(format.repository_format.get_format_description()), out)
    self.assertEqual('', err)