import os
import re
import unicodedata as ud
from .. import osutils, tests
from .._termcolor import FG, color_string
from ..tests.features import UnicodeFilenameFeature
def test_revno_range_basic_history_grep(self):
    """Search for pattern in revision range for file.
        """
    wd = 'foobar0'
    fname = 'file0.txt'
    self.make_branch_and_tree(wd)
    os.chdir(wd)
    self._mk_versioned_file(fname, total_lines=0)
    self._mk_versioned_file('file1.txt')
    self._update_file(fname, text='v3 text\n')
    self._update_file(fname, text='v4 text\n')
    self._update_file(fname, text='v5 text\n')
    self._update_file(fname, text='v6 text\n')
    out, err = self.run_bzr(['grep', '-r', '1..', 'v3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 4)
    out, err = self.run_bzr(['grep', '-r', '..1', 'v3'])
    self.assertEqual(len(out.splitlines()), 0)
    out, err = self.run_bzr(['grep', '-r', '..6', 'v3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 4)
    out, err = self.run_bzr(['grep', '-r', '..', 'v3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 4)
    out, err = self.run_bzr(['grep', '-r', '1..5', 'v3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertNotContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 3)
    out, err = self.run_bzr(['grep', '-r', '5..1', 'v3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertNotContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 3)
    out, err = self.run_bzr(['grep', '-r', '1..', '[tuv]3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 4)
    out, err = self.run_bzr(['grep', '-r', '1..5', '[tuv]3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertNotContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 3)
    out, err = self.run_bzr(['grep', '-r', '5..1', '[tuv]3'])
    self.assertContainsRe(out, 'file0.txt~3:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~4:v3', flags=TestGrep._reflags)
    self.assertContainsRe(out, 'file0.txt~5:v3', flags=TestGrep._reflags)
    self.assertNotContainsRe(out, 'file0.txt~6:v3', flags=TestGrep._reflags)
    self.assertEqual(len(out.splitlines()), 3)