import sys
import unittest
import platform
import pygame
@unittest.skipIf(not pygame.HAVE_NEWBUF, 'newbuf not implemented')
@unittest.skipIf(IS_PYPY, 'fails on pypy')
def test_PgDict_AsBuffer_PyBUF_flags(self):
    from pygame.bufferproxy import BufferProxy
    is_lil_endian = pygame.get_sdl_byteorder() == pygame.LIL_ENDIAN
    fsys, frev = ('<', '>') if is_lil_endian else ('>', '<')
    buftools = self.buftools
    Importer = buftools.Importer
    a = BufferProxy({'typestr': '|u4', 'shape': (10, 2), 'data': (9, False)})
    b = Importer(a, buftools.PyBUF_SIMPLE)
    self.assertEqual(b.ndim, 0)
    self.assertTrue(b.format is None)
    self.assertEqual(b.len, a.length)
    self.assertEqual(b.itemsize, 4)
    self.assertTrue(b.shape is None)
    self.assertTrue(b.strides is None)
    self.assertTrue(b.suboffsets is None)
    self.assertFalse(b.readonly)
    self.assertEqual(b.buf, 9)
    b = Importer(a, buftools.PyBUF_WRITABLE)
    self.assertEqual(b.ndim, 0)
    self.assertTrue(b.format is None)
    self.assertEqual(b.len, a.length)
    self.assertEqual(b.itemsize, 4)
    self.assertTrue(b.shape is None)
    self.assertTrue(b.strides is None)
    self.assertTrue(b.suboffsets is None)
    self.assertFalse(b.readonly)
    self.assertEqual(b.buf, 9)
    b = Importer(a, buftools.PyBUF_ND)
    self.assertEqual(b.ndim, 2)
    self.assertTrue(b.format is None)
    self.assertEqual(b.len, a.length)
    self.assertEqual(b.itemsize, 4)
    self.assertEqual(b.shape, (10, 2))
    self.assertTrue(b.strides is None)
    self.assertTrue(b.suboffsets is None)
    self.assertFalse(b.readonly)
    self.assertEqual(b.buf, 9)
    a = BufferProxy({'typestr': fsys + 'i2', 'shape': (5, 10), 'strides': (24, 2), 'data': (42, False)})
    b = Importer(a, buftools.PyBUF_STRIDES)
    self.assertEqual(b.ndim, 2)
    self.assertTrue(b.format is None)
    self.assertEqual(b.len, 100)
    self.assertEqual(b.itemsize, 2)
    self.assertEqual(b.shape, (5, 10))
    self.assertEqual(b.strides, (24, 2))
    self.assertTrue(b.suboffsets is None)
    self.assertFalse(b.readonly)
    self.assertEqual(b.buf, 42)
    b = Importer(a, buftools.PyBUF_FULL_RO)
    self.assertEqual(b.ndim, 2)
    self.assertEqual(b.format, '=h')
    self.assertEqual(b.len, 100)
    self.assertEqual(b.itemsize, 2)
    self.assertEqual(b.shape, (5, 10))
    self.assertEqual(b.strides, (24, 2))
    self.assertTrue(b.suboffsets is None)
    self.assertFalse(b.readonly)
    self.assertEqual(b.buf, 42)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_SIMPLE)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_ND)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_C_CONTIGUOUS)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_F_CONTIGUOUS)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_ANY_CONTIGUOUS)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_CONTIG)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_SIMPLE)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_ND)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_C_CONTIGUOUS)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_F_CONTIGUOUS)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_ANY_CONTIGUOUS)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_CONTIG)
    a = BufferProxy({'typestr': frev + 'i2', 'shape': (3, 5, 10), 'strides': (120, 24, 2), 'data': (1000000, True)})
    b = Importer(a, buftools.PyBUF_FULL_RO)
    self.assertEqual(b.ndim, 3)
    self.assertEqual(b.format, frev + 'h')
    self.assertEqual(b.len, 300)
    self.assertEqual(b.itemsize, 2)
    self.assertEqual(b.shape, (3, 5, 10))
    self.assertEqual(b.strides, (120, 24, 2))
    self.assertTrue(b.suboffsets is None)
    self.assertTrue(b.readonly)
    self.assertEqual(b.buf, 1000000)
    self.assertRaises(BufferError, Importer, a, buftools.PyBUF_FULL)