from breezy import bedding, ignores, tests
from breezy.tests.per_workingtree import TestCaseWithWorkingTree
def test_global_ignored(self):
    tree = self.make_branch_and_tree('.')
    bedding.ensure_config_dir_exists()
    user_ignore_file = bedding.user_ignore_config_path()
    self._set_user_ignore_content(b'*.py[co]\n./.shelf\n# comment line\n\n\r\n * \ncrlf\r\n*\xc3\xa5*\n')
    self.assertEqual('./.shelf', tree.is_ignored('.shelf'))
    self.assertEqual(None, tree.is_ignored('foo/.shelf'))
    self.assertEqual('*.py[co]', tree.is_ignored('foo.pyc'))
    self.assertEqual('*.py[co]', tree.is_ignored('foo.pyo'))
    self.assertEqual(None, tree.is_ignored('foo.py'))
    self.assertEqual('*.py[co]', tree.is_ignored('bar/foo.pyc'))
    self.assertEqual('*.py[co]', tree.is_ignored('bar/foo.pyo'))
    self.assertEqual(None, tree.is_ignored('bar/foo.py'))
    self.assertEqual('*å*', tree.is_ignored('bågfors'))
    self.assertEqual('*å*', tree.is_ignored('ågfors'))
    self.assertEqual('*å*', tree.is_ignored('å'))
    self.assertEqual('*å*', tree.is_ignored('bå'))
    self.assertEqual('*å*', tree.is_ignored('b/å'))
    self.assertEqual(' * ', tree.is_ignored(' bbb '))
    self.assertEqual(' * ', tree.is_ignored('subdir/ bbb '))
    self.assertEqual(None, tree.is_ignored('bbb '))
    self.assertEqual(None, tree.is_ignored(' bbb'))
    self.assertEqual('crlf', tree.is_ignored('crlf'))
    self.assertEqual('crlf', tree.is_ignored('subdir/crlf'))
    self.assertEqual(None, tree.is_ignored('# comment line'))
    self.assertEqual(None, tree.is_ignored(''))
    self.assertEqual(None, tree.is_ignored('baz/'))