import numpy as np
import unittest
from numba import jit, from_dtype
from numba.core import types
from numba.typed import Dict
from numba.tests.support import (TestCase, skip_ppc64le_issue4563)
def test_setitem2(self):
    pyfunc = setitem2
    cfunc = jit(nopython=True)(pyfunc)
    x1 = np.array(['123', 'ABC'])
    x2 = np.array(['123', 'ABC'])
    y1 = pyfunc(x1, 0, x1, 1)
    y2 = cfunc(x2, 0, x2, 1)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array([b'123', b'ABC'])
    x2 = np.array([b'123', b'ABC'])
    y1 = pyfunc(x1, 0, x1, 1)
    y2 = cfunc(x2, 0, x2, 1)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array('123')
    x2 = np.array('123')
    z1 = np.array('ABC')
    z2 = np.array('ABC')
    y1 = pyfunc(x1, (), z1, ())
    y2 = cfunc(x2, (), z2, ())
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array(123)
    x2 = np.array(123)
    z1 = (456,)
    z2 = (456,)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array(b'123')
    x2 = np.array(b'123')
    z1 = (b'ABC',)
    z2 = (b'ABC',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array('123')
    x2 = np.array('123')
    z1 = ('ABC',)
    z2 = ('ABC',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array('123')
    x2 = np.array('123')
    z1 = ('ABǩ',)
    z2 = ('ABǩ',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array('123')
    x2 = np.array('123')
    z1 = ('AB\U00108a0e',)
    z2 = ('AB\U00108a0e',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array('123')
    x2 = np.array('123')
    z1 = ('ABCD',)
    z2 = ('ABCD',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array('123')
    x2 = np.array('123')
    z1 = ('AB',)
    z2 = ('AB',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array(b'123')
    x2 = np.array(b'123')
    z1 = (b'ABCD',)
    z2 = (b'ABCD',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)
    x1 = np.array(b'123')
    x2 = np.array(b'123')
    z1 = (b'AB',)
    z2 = (b'AB',)
    y1 = pyfunc(x1, (), z1, 0)
    y2 = cfunc(x2, (), z2, 0)
    self.assertPreciseEqual(x1, x2)
    self.assertPreciseEqual(y1, y2)