from heat_integrationtests.functional import functional_base
def deployment_crud(self, template):
    stack_identifier = self.stack_create(template=template, enable_cleanup=self.enable_cleanup, expected_status='CREATE_IN_PROGRESS')
    self._wait_for_resource_status(stack_identifier, 'deployment', 'CREATE_IN_PROGRESS')
    nested_identifier = self.assert_resource_is_a_stack(stack_identifier, 'deployment')
    self._wait_for_stack_status(nested_identifier, 'CREATE_IN_PROGRESS')
    self._wait_for_all_resource_status(nested_identifier, 'CREATE_IN_PROGRESS')
    group_resources = self.list_group_resources(stack_identifier, 'deployment', minimal=False)
    self.assertEqual(4, len(group_resources))
    self._wait_for_stack_status(stack_identifier, 'CREATE_COMPLETE', signal_required=True, resources_to_signal=group_resources)
    created_group_resources = self.list_group_resources(stack_identifier, 'deployment', minimal=False)
    self.assertEqual(4, len(created_group_resources))
    self.check_input_values(created_group_resources, 'foo', 'foo_input')
    self.update_stack(stack_identifier, template=template, environment={'parameters': {'input': 'input2'}}, expected_status='UPDATE_IN_PROGRESS')
    nested_identifier = self.assert_resource_is_a_stack(stack_identifier, 'deployment')
    self._wait_for_stack_status(stack_identifier, 'UPDATE_COMPLETE', signal_required=True, resources_to_signal=group_resources)
    self.check_input_values(created_group_resources, 'foo', 'input2')
    self._stack_delete(stack_identifier)
    self._wait_for_stack_status(nested_identifier, 'DELETE_COMPLETE', success_on_not_found=True)