import platform
import pytest
import numpy as np
from numpy import uint16, float16, float32, float64
from numpy.testing import assert_, assert_equal, _OLD_PROMOTION, IS_WASM
def test_half_ufuncs(self):
    """Test the various ufuncs"""
    a = np.array([0, 1, 2, 4, 2], dtype=float16)
    b = np.array([-2, 5, 1, 4, 3], dtype=float16)
    c = np.array([0, -1, -np.inf, np.nan, 6], dtype=float16)
    assert_equal(np.add(a, b), [-2, 6, 3, 8, 5])
    assert_equal(np.subtract(a, b), [2, -4, 1, 0, -1])
    assert_equal(np.multiply(a, b), [0, 5, 2, 16, 6])
    assert_equal(np.divide(a, b), [0, 0.199951171875, 2, 1, 0.66650390625])
    assert_equal(np.equal(a, b), [False, False, False, True, False])
    assert_equal(np.not_equal(a, b), [True, True, True, False, True])
    assert_equal(np.less(a, b), [False, True, False, False, True])
    assert_equal(np.less_equal(a, b), [False, True, False, True, True])
    assert_equal(np.greater(a, b), [True, False, True, False, False])
    assert_equal(np.greater_equal(a, b), [True, False, True, True, False])
    assert_equal(np.logical_and(a, b), [False, True, True, True, True])
    assert_equal(np.logical_or(a, b), [True, True, True, True, True])
    assert_equal(np.logical_xor(a, b), [True, False, False, False, False])
    assert_equal(np.logical_not(a), [True, False, False, False, False])
    assert_equal(np.isnan(c), [False, False, False, True, False])
    assert_equal(np.isinf(c), [False, False, True, False, False])
    assert_equal(np.isfinite(c), [True, True, False, False, True])
    assert_equal(np.signbit(b), [True, False, False, False, False])
    assert_equal(np.copysign(b, a), [2, 5, 1, 4, 3])
    assert_equal(np.maximum(a, b), [0, 5, 2, 4, 3])
    x = np.maximum(b, c)
    assert_(np.isnan(x[3]))
    x[3] = 0
    assert_equal(x, [0, 5, 1, 0, 6])
    assert_equal(np.minimum(a, b), [-2, 1, 1, 4, 2])
    x = np.minimum(b, c)
    assert_(np.isnan(x[3]))
    x[3] = 0
    assert_equal(x, [-2, -1, -np.inf, 0, 3])
    assert_equal(np.fmax(a, b), [0, 5, 2, 4, 3])
    assert_equal(np.fmax(b, c), [0, 5, 1, 4, 6])
    assert_equal(np.fmin(a, b), [-2, 1, 1, 4, 2])
    assert_equal(np.fmin(b, c), [-2, -1, -np.inf, 4, 3])
    assert_equal(np.floor_divide(a, b), [0, 0, 2, 1, 0])
    assert_equal(np.remainder(a, b), [0, 1, 0, 0, 2])
    assert_equal(np.divmod(a, b), ([0, 0, 2, 1, 0], [0, 1, 0, 0, 2]))
    assert_equal(np.square(b), [4, 25, 1, 16, 9])
    assert_equal(np.reciprocal(b), [-0.5, 0.199951171875, 1, 0.25, 0.333251953125])
    assert_equal(np.ones_like(b), [1, 1, 1, 1, 1])
    assert_equal(np.conjugate(b), b)
    assert_equal(np.absolute(b), [2, 5, 1, 4, 3])
    assert_equal(np.negative(b), [2, -5, -1, -4, -3])
    assert_equal(np.positive(b), b)
    assert_equal(np.sign(b), [-1, 1, 1, 1, 1])
    assert_equal(np.modf(b), ([0, 0, 0, 0, 0], b))
    assert_equal(np.frexp(b), ([-0.5, 0.625, 0.5, 0.5, 0.75], [2, 3, 1, 3, 2]))
    assert_equal(np.ldexp(b, [0, 1, 2, 4, 2]), [-2, 10, 4, 64, 12])