from tests.unit import unittest
from tests.unit import AWSMockServiceTestCase
from boto.vpc import VPCConnection, RouteTable
def test_get_all_route_tables(self):
    self.set_http_response(status_code=200)
    api_response = self.service_connection.get_all_route_tables(['rtb-13ad487a', 'rtb-f9ad4890'], filters=[('route.state', 'active')])
    self.assert_request_parameters({'Action': 'DescribeRouteTables', 'RouteTableId.1': 'rtb-13ad487a', 'RouteTableId.2': 'rtb-f9ad4890', 'Filter.1.Name': 'route.state', 'Filter.1.Value.1': 'active'}, ignore_params_values=['AWSAccessKeyId', 'SignatureMethod', 'SignatureVersion', 'Timestamp', 'Version'])
    self.assertEquals(len(api_response), 2)
    self.assertIsInstance(api_response[0], RouteTable)
    self.assertEquals(api_response[0].id, 'rtb-13ad487a')
    self.assertEquals(len(api_response[0].routes), 1)
    self.assertEquals(api_response[0].routes[0].destination_cidr_block, '10.0.0.0/22')
    self.assertEquals(api_response[0].routes[0].gateway_id, 'local')
    self.assertEquals(api_response[0].routes[0].state, 'active')
    self.assertEquals(api_response[0].routes[0].origin, 'CreateRouteTable')
    self.assertEquals(len(api_response[0].associations), 1)
    self.assertEquals(api_response[0].associations[0].id, 'rtbassoc-12ad487b')
    self.assertEquals(api_response[0].associations[0].route_table_id, 'rtb-13ad487a')
    self.assertIsNone(api_response[0].associations[0].subnet_id)
    self.assertEquals(api_response[0].associations[0].main, True)
    self.assertEquals(api_response[1].id, 'rtb-f9ad4890')
    self.assertEquals(len(api_response[1].routes), 4)
    self.assertEquals(api_response[1].routes[0].destination_cidr_block, '10.0.0.0/22')
    self.assertEquals(api_response[1].routes[0].gateway_id, 'local')
    self.assertEquals(api_response[1].routes[0].state, 'active')
    self.assertEquals(api_response[1].routes[0].origin, 'CreateRouteTable')
    self.assertEquals(api_response[1].routes[1].destination_cidr_block, '0.0.0.0/0')
    self.assertEquals(api_response[1].routes[1].gateway_id, 'igw-eaad4883')
    self.assertEquals(api_response[1].routes[1].state, 'active')
    self.assertEquals(api_response[1].routes[1].origin, 'CreateRoute')
    self.assertEquals(api_response[1].routes[2].destination_cidr_block, '10.0.0.0/21')
    self.assertEquals(api_response[1].routes[2].interface_id, 'eni-884ec1d1')
    self.assertEquals(api_response[1].routes[2].state, 'blackhole')
    self.assertEquals(api_response[1].routes[2].origin, 'CreateRoute')
    self.assertEquals(api_response[1].routes[3].destination_cidr_block, '11.0.0.0/22')
    self.assertEquals(api_response[1].routes[3].vpc_peering_connection_id, 'pcx-efc52b86')
    self.assertEquals(api_response[1].routes[3].state, 'blackhole')
    self.assertEquals(api_response[1].routes[3].origin, 'CreateRoute')
    self.assertEquals(len(api_response[1].associations), 1)
    self.assertEquals(api_response[1].associations[0].id, 'rtbassoc-faad4893')
    self.assertEquals(api_response[1].associations[0].route_table_id, 'rtb-f9ad4890')
    self.assertEquals(api_response[1].associations[0].subnet_id, 'subnet-15ad487c')
    self.assertEquals(api_response[1].associations[0].main, False)