import os
import re
import sys
import breezy
from breezy import osutils
from breezy.branch import Branch
from breezy.errors import CommandError
from breezy.tests import TestCaseWithTransport
from breezy.tests.http_utils import TestCaseWithWebserver
from breezy.tests.test_sftp_transport import TestCaseWithSFTPServer
from breezy.workingtree import WorkingTree
def test_bzr(self):
    from os import chdir, mkdir
    from os.path import exists
    progress = self.log
    progress('basic branch creation')
    mkdir('branch1')
    chdir('branch1')
    self.run_bzr('init')
    self.assertIsSameRealPath(self.run_bzr('root')[0].rstrip(), osutils.pathjoin(self.test_dir, 'branch1'))
    progress('status of new file')
    with open('test.txt', 'w') as f:
        f.write('hello world!\n')
    self.assertEqual(self.run_bzr('unknowns')[0], 'test.txt\n')
    out = self.run_bzr('status')[0]
    self.assertEqual(out, 'unknown:\n  test.txt\n')
    with open('test2.txt', 'w') as f:
        f.write('goodbye cruel world...\n')
    out = self.run_bzr('status test.txt')[0]
    self.assertEqual(out, 'unknown:\n  test.txt\n')
    out = self.run_bzr('status')[0]
    self.assertEqual(out, 'unknown:\n  test.txt\n  test2.txt\n')
    os.unlink('test2.txt')
    progress('command aliases')
    out = self.run_bzr('st')[0]
    self.assertEqual(out, 'unknown:\n  test.txt\n')
    out = self.run_bzr('stat')[0]
    self.assertEqual(out, 'unknown:\n  test.txt\n')
    progress('command help')
    self.run_bzr('help st')
    self.run_bzr('help')
    self.run_bzr('help commands')
    self.run_bzr('help slartibartfast', retcode=3)
    out = self.run_bzr('help ci')[0]
    out.index('Aliases:  ci, checkin\n')
    with open('hello.txt', 'w') as f:
        f.write('some nice new content\n')
    self.run_bzr('add hello.txt')
    with open('msg.tmp', 'w') as f:
        f.write('this is my new commit\nand it has multiple lines, for fun')
    self.run_bzr('commit -F msg.tmp')
    self.assertEqual(self.run_bzr('revno')[0], '1\n')
    self.run_bzr('export -r 1 export-1.tmp')
    self.run_bzr('export export.tmp')
    self.run_bzr('log')
    self.run_bzr('log -v')
    self.run_bzr('log -v --forward')
    self.run_bzr('log -m', retcode=3)
    log_out = self.run_bzr('log -m commit')[0]
    self.assertTrue('this is my new commit\n  and' in log_out)
    self.assertTrue('rename nested' not in log_out)
    self.assertTrue('revision-id' not in log_out)
    self.assertTrue('revision-id' in self.run_bzr('log --show-ids -m commit')[0])
    log_out = self.run_bzr('log --line')[0]
    max_width = osutils.terminal_width()
    if max_width is not None:
        for line in log_out.splitlines():
            self.assertTrue(len(line) <= max_width - 1, len(line))
    self.assertTrue('this is my new commit and' not in log_out)
    self.assertTrue('this is my new commit' in log_out)
    progress('file with spaces in name')
    mkdir('sub directory')
    with open('sub directory/file with spaces ', 'w') as f:
        f.write('see how this works\n')
    self.run_bzr('add .')
    self.run_bzr('diff', retcode=1)
    self.run_bzr('commit -m add-spaces')
    self.run_bzr('check')
    self.run_bzr('log')
    self.run_bzr('log --forward')
    self.run_bzr('info')
    if osutils.supports_symlinks(self.test_dir):
        progress('symlinks')
        mkdir('symlinks')
        chdir('symlinks')
        self.run_bzr('init')
        os.symlink('NOWHERE1', 'link1')
        self.run_bzr('add link1')
        self.assertEqual(self.run_bzr('unknowns')[0], '')
        self.run_bzr(['commit', '-m', '1: added symlink link1'])
        mkdir('d1')
        self.run_bzr('add d1')
        self.assertEqual(self.run_bzr('unknowns')[0], '')
        os.symlink('NOWHERE2', 'd1/link2')
        self.assertEqual(self.run_bzr('unknowns')[0], 'd1/link2\n')
        self.run_bzr('add d1')
        self.assertEqual(self.run_bzr('unknowns')[0], '')
        os.symlink('NOWHERE3', 'd1/link3')
        self.assertEqual(self.run_bzr('unknowns')[0], 'd1/link3\n')
        self.run_bzr(['commit', '-m', '2: added dir, symlink'])
        self.run_bzr('rename d1 d2')
        self.run_bzr('move d2/link2 .')
        self.run_bzr('move link1 d2')
        self.assertEqual(os.readlink('./link2'), 'NOWHERE2')
        self.assertEqual(os.readlink('d2/link1'), 'NOWHERE1')
        self.run_bzr('add d2/link3')
        self.run_bzr('diff', retcode=1)
        self.run_bzr(['commit', '-m', '3: rename of dir, move symlinks, add link3'])
        os.unlink('link2')
        os.symlink('TARGET 2', 'link2')
        os.unlink('d2/link1')
        os.symlink('TARGET 1', 'd2/link1')
        self.run_bzr('diff', retcode=1)
        self.assertEqual(self.run_bzr('relpath d2/link1')[0], 'd2/link1\n')
        self.run_bzr(['commit', '-m', '4: retarget of two links'])
        self.run_bzr('remove --keep d2/link1')
        self.assertEqual(self.run_bzr('unknowns')[0], 'd2/link1\n')
        self.run_bzr(['commit', '-m', '5: remove d2/link1'])
        self.run_bzr('add d2/link1')
        self.run_bzr(['commit', '-m', '6: add d2/link1'])
        self.run_bzr('rm --keep d2/link1')
        self.assertEqual(self.run_bzr('unknowns')[0], 'd2/link1\n')
        self.run_bzr(['commit', '-m', '7: remove d2/link1'])
        os.mkdir('d1')
        self.run_bzr('add d1')
        self.run_bzr('rename d2/link3 d1/link3new')
        self.assertEqual(self.run_bzr('unknowns')[0], 'd2/link1\n')
        self.run_bzr(['commit', '-m', '8: remove d2/link1, move/rename link3'])
        self.run_bzr('check')
        self.run_bzr('export -r 1 exp1.tmp')
        chdir('exp1.tmp')
        self.assertEqual(listdir_sorted('.'), ['link1'])
        self.assertEqual(os.readlink('link1'), 'NOWHERE1')
        chdir('..')
        self.run_bzr('export -r 2 exp2.tmp')
        chdir('exp2.tmp')
        self.assertEqual(listdir_sorted('.'), ['d1', 'link1'])
        chdir('..')
        self.run_bzr('export -r 3 exp3.tmp')
        chdir('exp3.tmp')
        self.assertEqual(listdir_sorted('.'), ['d2', 'link2'])
        self.assertEqual(listdir_sorted('d2'), ['link1', 'link3'])
        self.assertEqual(os.readlink('d2/link1'), 'NOWHERE1')
        self.assertEqual(os.readlink('link2'), 'NOWHERE2')
        chdir('..')
        self.run_bzr('export -r 4 exp4.tmp')
        chdir('exp4.tmp')
        self.assertEqual(listdir_sorted('.'), ['d2', 'link2'])
        self.assertEqual(os.readlink('d2/link1'), 'TARGET 1')
        self.assertEqual(os.readlink('link2'), 'TARGET 2')
        self.assertEqual(listdir_sorted('d2'), ['link1', 'link3'])
        chdir('..')
        self.run_bzr('export -r 5 exp5.tmp')
        chdir('exp5.tmp')
        self.assertEqual(listdir_sorted('.'), ['d2', 'link2'])
        self.assertTrue(os.path.islink('link2'))
        self.assertTrue(listdir_sorted('d2') == ['link3'])
        chdir('..')
        self.run_bzr('export -r 8 exp6.tmp')
        chdir('exp6.tmp')
        self.assertEqual(listdir_sorted('.'), ['d1', 'd2', 'link2'])
        self.assertEqual(listdir_sorted('d1'), ['link3new'])
        self.assertEqual(listdir_sorted('d2'), [])
        self.assertEqual(os.readlink('d1/link3new'), 'NOWHERE3')
        chdir('..')
    else:
        progress('skipping symlink tests')