import os
import sys
from .gui import *
from .app_menus import ListedWindow
def build_font_pane(self, master):
    current_font = self.settings.current_font_dict()
    groupBG = self.style.groupBG
    self.font_frame = font_frame = ttk.Frame(master)
    font_frame.columnconfigure(2, weight=1)
    font_frame.columnconfigure(0, weight=1)
    self.list_frame = list_frame = ttk.Frame(font_frame)
    self.font_list = font_list = Tk_.Listbox(list_frame, selectmode=Tk_.SINGLE)
    self.families = families = [f for f in font_families() if f[0] != '@']
    families.sort()
    for family in families:
        font_list.insert(Tk_.END, family)
    self.current_family = families.index(current_font['family'])
    font_list.selection_set(self.current_family)
    font_list.see(self.current_family)
    font_list.grid(row=0, column=0, pady=(20, 30))
    font_scroller = ttk.Scrollbar(list_frame, command=font_list.yview)
    font_list.config(yscrollcommand=font_scroller.set)
    font_scroller.grid(row=0, column=1, sticky=Tk_.N + Tk_.S, pady=(20, 30))
    list_frame.grid(rowspan=6, column=0)
    label = ttk.Label(self.font_frame, text='Size: ')
    label.grid(row=0, column=1, sticky=Tk_.E, pady=(20, 0))
    self.font_sizer = sizer = Spinbox(font_frame, from_=10, to_=36, width=4, command=self.set_font_sample)
    sizer.delete(0, 2)
    sizer.insert(0, current_font['size'])
    sizer.bind('<Return>', self.set_font_sample)
    sizer.bind('<Tab>', self.set_font_sample)
    self.current_size = current_font['size']
    sizer.grid(row=0, column=2, sticky=Tk_.W, pady=(20, 0))
    label = ttk.Label(font_frame, text='Weight: ')
    label.grid(row=1, column=1, sticky=Tk_.E)
    self.font_weight = weight = Tk_.StringVar(value=current_font['weight'])
    radio = ttk.Radiobutton(font_frame, text='normal', variable=weight, value='normal', command=self.set_font_sample)
    radio.grid(row=1, column=2, sticky=Tk_.W)
    radio = ttk.Radiobutton(font_frame, text='bold', variable=weight, value='bold', command=self.set_font_sample)
    radio.grid(row=2, column=2, sticky=Tk_.W)
    label = ttk.Label(font_frame, text='Slant: ')
    label.grid(row=3, column=1, sticky=Tk_.E)
    self.font_slant = slant = Tk_.StringVar(value=current_font['slant'])
    radio = ttk.Radiobutton(font_frame, text='roman', variable=slant, value='roman', command=self.set_font_sample)
    radio.grid(row=3, column=2, sticky=Tk_.W)
    radio = ttk.Radiobutton(font_frame, text='italic', variable=slant, value='italic', command=self.set_font_sample)
    radio.grid(row=4, column=2, sticky=Tk_.W)
    self.sample = sample = Tk_.Text(self.font_frame, width=40, height=6, highlightthickness=0, relief=Tk_.FLAT, font=self.settings['font'])
    self.sample.bind('<Button-1>', lambda event: 'break')
    self.sample.insert(Tk_.INSERT, '\nABCDEFGHIJKLMNOPQRSTUVWXYZ\nabcdefghijklmnopqrstuvwxyz')
    sample.tag_add('all', '1.0', Tk_.END)
    self.set_font_sample()
    font_list.bind('<ButtonRelease-1>', self.set_font_sample)
    self.sample.grid(row=6, columnspan=4, padx=10, pady=10, sticky=Tk_.E + Tk_.W)