from io import StringIO
import os
import sys
import types
import json
from copy import deepcopy
from os.path import abspath, dirname, join
import pyomo.common.unittest as unittest
from pyomo.environ import (
from pyomo.common.log import LoggingIntercept
from pyomo.common.tempfiles import TempfileManager
from pyomo.core.base.block import (
import pyomo.core.expr as EXPR
from pyomo.opt import check_available_solvers
from pyomo.gdp import Disjunct
def test_pseudomap_getitem(self):
    m = Block()
    m.a = a = Constraint()
    m.b = b = Constraint()
    m.c = c = Constraint()
    m.s = s = Set()
    m.t = t = Suffix()
    m.z = z = Objective()
    m.x = x = Objective()
    m.b.deactivate()
    m.z.deactivate()

    def assertWorks(self, key, pm):
        self.assertIs(pm[key.local_name], key)

    def assertFails(self, key, pm):
        if not isinstance(key, str):
            key = key.local_name
        self.assertRaises(KeyError, pm.__getitem__, key)
    pm = m.component_map()
    assertWorks(self, a, pm)
    assertWorks(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertWorks(self, s, pm)
    assertWorks(self, t, pm)
    assertWorks(self, x, pm)
    assertWorks(self, z, pm)
    pm = m.component_map(active=True)
    assertWorks(self, a, pm)
    assertFails(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertWorks(self, s, pm)
    assertWorks(self, t, pm)
    assertWorks(self, x, pm)
    assertFails(self, z, pm)
    pm = m.component_map(active=False)
    assertFails(self, a, pm)
    assertWorks(self, b, pm)
    assertFails(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertFails(self, x, pm)
    assertWorks(self, z, pm)
    pm = m.component_map(Constraint)
    assertWorks(self, a, pm)
    assertWorks(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertFails(self, x, pm)
    assertFails(self, z, pm)
    pm = m.component_map(Constraint, active=True)
    assertWorks(self, a, pm)
    assertFails(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertFails(self, x, pm)
    assertFails(self, z, pm)
    pm = m.component_map(Constraint, active=False)
    assertFails(self, a, pm)
    assertWorks(self, b, pm)
    assertFails(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertFails(self, x, pm)
    assertFails(self, z, pm)
    pm = m.component_map([Constraint, Objective])
    assertWorks(self, a, pm)
    assertWorks(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertWorks(self, x, pm)
    assertWorks(self, z, pm)
    pm = m.component_map([Constraint, Objective], active=True)
    assertWorks(self, a, pm)
    assertFails(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertWorks(self, x, pm)
    assertFails(self, z, pm)
    pm = m.component_map([Constraint, Objective], active=False)
    assertFails(self, a, pm)
    assertWorks(self, b, pm)
    assertFails(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertFails(self, x, pm)
    assertWorks(self, z, pm)
    pm = m.component_map(set([Constraint, Objective]))
    assertWorks(self, a, pm)
    assertWorks(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertWorks(self, x, pm)
    assertWorks(self, z, pm)
    pm = m.component_map(set([Constraint, Objective]), active=True)
    assertWorks(self, a, pm)
    assertFails(self, b, pm)
    assertWorks(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertWorks(self, x, pm)
    assertFails(self, z, pm)
    pm = m.component_map(set([Constraint, Objective]), active=False)
    assertFails(self, a, pm)
    assertWorks(self, b, pm)
    assertFails(self, c, pm)
    assertFails(self, 'd', pm)
    assertFails(self, s, pm)
    assertFails(self, t, pm)
    assertFails(self, x, pm)
    assertWorks(self, z, pm)