from ... import errors, multiparent, tests
from .. import groupcompress, versionedfile
def test_process_contents(self):
    vf = self.make_three_vf()
    gen = versionedfile._MPDiffGenerator(vf, [(b'two',), (b'three',)])
    gen._find_needed_keys()
    self.assertEqual({(b'two',): ((b'one',),), (b'three',): ((b'one',), (b'two',))}, gen.parent_map)
    self.assertEqual({(b'one',): 2, (b'two',): 1}, gen.refcounts)
    self.assertEqual(sorted([(b'one',), (b'two',), (b'three',)]), sorted(gen.needed_keys))
    stream = vf.get_record_stream(gen.needed_keys, 'topological', True)
    record = next(stream)
    self.assertEqual((b'one',), record.key)
    gen._process_one_record(record.key, record.get_bytes_as('chunked'))
    self.assertEqual({(b'one',)}, set(gen.chunks))
    self.assertEqual({(b'one',): 2, (b'two',): 1}, gen.refcounts)
    self.assertEqual(set(), set(gen.diffs))
    record = next(stream)
    self.assertEqual((b'two',), record.key)
    gen._process_one_record(record.key, record.get_bytes_as('chunked'))
    self.assertEqual({(b'one',), (b'two',)}, set(gen.chunks))
    self.assertEqual({(b'one',): 1, (b'two',): 1}, gen.refcounts)
    self.assertEqual({(b'two',)}, set(gen.diffs))
    self.assertEqual({(b'three',): ((b'one',), (b'two',))}, gen.parent_map)
    record = next(stream)
    self.assertEqual((b'three',), record.key)
    gen._process_one_record(record.key, record.get_bytes_as('chunked'))
    self.assertEqual(set(), set(gen.chunks))
    self.assertEqual({}, gen.refcounts)
    self.assertEqual({(b'two',), (b'three',)}, set(gen.diffs))