from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from googlecloudsdk.calliope import arg_parsers
from googlecloudsdk.calliope import base
from googlecloudsdk.command_lib.compute import flags as compute_flags
def _AddAddEndpoint(endpoint_group, endpoint_spec, support_ipv6, support_port_mapping_neg):
    """Adds add endpoint argument for updating network endpoint groups."""
    help_text = '          The network endpoint to add to the network endpoint group. Keys used\n          depend on the endpoint type of the NEG.\n\n          `gce-vm-ip-port`\n\n              *instance* - Name of instance in same zone as the network endpoint\n              group.\n\n              The VM instance must belong to the network / subnetwork\n              associated with the network endpoint group. If the VM instance\n              is deleted, then any network endpoint group that has a reference\n              to it is updated.\n\n              *ip* - Optional IP address of the network endpoint. The IP address\n              must belong to a VM in compute engine (either the primary IP or\n              as part of an aliased IP range). If the IP address is not\n              specified, then the primary IP address for the VM instance in\n              the network that the network endpoint group belongs to is\n              used.\n              '
    if support_ipv6:
        help_text += '\n              *ipv6* - Optional IPv6 address of the network endpoint. The IPv6\n              address must belong to a VM in compute engine (either the internal\n              or external IPv6 address).\n\n              At least one of the ip and ipv6 must be specified.\n                 '
    help_text += '\n              *port* - Required endpoint port unless NEG default port is set.\n               '
    if support_port_mapping_neg:
        help_text += '\n              *client-port* - Required endpoint client port only for the port\n              mapping NEG.\n               '
    help_text += '\n          `internet-ip-port`\n               '
    if support_ipv6:
        help_text += '\n              *ip* - Optional IPv4 address of the endpoint to attach. Must be\n              publicly routable.\n\n              *ipv6* - Optional IPv6 address of the endpoint to attach. Must be\n              publicly routable.\n\n              At least one of the ip and ipv6 must be specified.\n            '
    else:
        help_text += '\n              *ip* - Required IPv4 address of the endpoint to attach. Must be\n              publicly routable.\n            '
    help_text += '\n              *port* - Optional port of the endpoint to attach. If unspecified,\n              the NEG default port is set. If no default port is set, the\n              well-known port for the backend protocol is used instead\n              (80 for HTTP, 443 for HTTPS).\n\n          `internet-fqdn-port`\n\n              *fqdn* - Required fully qualified domain name to use to look up an\n              external endpoint. Must be resolvable to a public IP address via\n              public DNS.\n\n              *port* - Optional port of the endpoint to attach. If unspecified,\n              the NEG default port is set. If no default port is set, the\n              well-known port for the backend protocol is used instead\n              (80 for HTTP, 443 for HTTPS or HTTP2).\n\n              Example: `--add-endpoint="fqdn=backend.example.com,port=443"`\n\n          `non-gcp-private-ip-port`\n\n    '
    if support_ipv6:
        help_text += '\n              *ip* - Optional IPv4 address of the network endpoint to attach.\n              The IP address must belong to a VM not in Compute Engine and must\n              be routable using a Cloud Router over VPN or an Interconnect\n              connection.\n\n              *ipv6* - Optional IPv6 address of the network endpoint to attach.\n              The IP address must belong to a VM not in Compute Engine and must\n              be routable using a Cloud Router over VPN or an Interconnect\n              connection.\n\n              At least one of the ip and ipv6 must be specified.\n      '
    else:
        help_text += '\n              *ip* - Required IPv4 address of the network endpoint to attach.\n              The IP address must belong to a VM not in Compute Engine and must\n              be routable using a Cloud Router over VPN or an Interconnect\n              connection.\n      '
    help_text += "\n              *port* - Required port of the network endpoint to attach unless\n              the NEG default port is set.\n\n          `gce-vm-ip`\n\n              *instance* - Required instance name in same zone as the network\n              endpoint group.\n\n              The VM instance must belong to the network / subnetwork\n              associated with the network endpoint group. If the VM instance\n              is deleted, then any network endpoint group that has a reference\n              to it is updated.\n\n              *ip* - Optional IP address of the network endpoint to attach. The\n              IP address must be the VM's network interface address. If not\n              specified, the primary NIC address is used.\n    "
    endpoint_group.add_argument('--add-endpoint', action='append', type=arg_parsers.ArgDict(spec=endpoint_spec), help=help_text)