import math
from PySide2 import QtCore, QtGui, QtWidgets
import diagramscene_rc
def createToolBox(self):
    self.buttonGroup = QtWidgets.QButtonGroup()
    self.buttonGroup.setExclusive(False)
    self.buttonGroup.buttonClicked[int].connect(self.buttonGroupClicked)
    layout = QtWidgets.QGridLayout()
    layout.addWidget(self.createCellWidget('Conditional', DiagramItem.Conditional), 0, 0)
    layout.addWidget(self.createCellWidget('Process', DiagramItem.Step), 0, 1)
    layout.addWidget(self.createCellWidget('Input/Output', DiagramItem.Io), 1, 0)
    textButton = QtWidgets.QToolButton()
    textButton.setCheckable(True)
    self.buttonGroup.addButton(textButton, self.InsertTextButton)
    textButton.setIcon(QtGui.QIcon(QtGui.QPixmap(':/images/textpointer.png').scaled(30, 30)))
    textButton.setIconSize(QtCore.QSize(50, 50))
    textLayout = QtWidgets.QGridLayout()
    textLayout.addWidget(textButton, 0, 0, QtCore.Qt.AlignHCenter)
    textLayout.addWidget(QtWidgets.QLabel('Text'), 1, 0, QtCore.Qt.AlignCenter)
    textWidget = QtWidgets.QWidget()
    textWidget.setLayout(textLayout)
    layout.addWidget(textWidget, 1, 1)
    layout.setRowStretch(3, 10)
    layout.setColumnStretch(2, 10)
    itemWidget = QtWidgets.QWidget()
    itemWidget.setLayout(layout)
    self.backgroundButtonGroup = QtWidgets.QButtonGroup()
    self.backgroundButtonGroup.buttonClicked.connect(self.backgroundButtonGroupClicked)
    backgroundLayout = QtWidgets.QGridLayout()
    backgroundLayout.addWidget(self.createBackgroundCellWidget('Blue Grid', ':/images/background1.png'), 0, 0)
    backgroundLayout.addWidget(self.createBackgroundCellWidget('White Grid', ':/images/background2.png'), 0, 1)
    backgroundLayout.addWidget(self.createBackgroundCellWidget('Gray Grid', ':/images/background3.png'), 1, 0)
    backgroundLayout.addWidget(self.createBackgroundCellWidget('No Grid', ':/images/background4.png'), 1, 1)
    backgroundLayout.setRowStretch(2, 10)
    backgroundLayout.setColumnStretch(2, 10)
    backgroundWidget = QtWidgets.QWidget()
    backgroundWidget.setLayout(backgroundLayout)
    self.toolBox = QtWidgets.QToolBox()
    self.toolBox.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored))
    self.toolBox.setMinimumWidth(itemWidget.sizeHint().width())
    self.toolBox.addItem(itemWidget, 'Basic Flowchart Shapes')
    self.toolBox.addItem(backgroundWidget, 'Backgrounds')