import pyomo.common.unittest as unittest
from io import StringIO
from pyomo.environ import (
from pyomo.network import Port, Arc
def test_arc_lists(self):
    m = ConcreteModel()
    m.x = Var()
    m.p1 = Port()
    m.p2 = Port()
    m.p3 = Port()
    m.p4 = Port()
    m.p5 = Port()
    m.p1.add(m.x)
    m.p2.add(m.x)
    m.p3.add(m.x)
    m.p4.add(m.x)
    m.p5.add(m.x)
    m.a1 = Arc(source=m.p1, destination=m.p2)
    m.a2 = Arc(source=m.p1, destination=m.p3)
    m.a3 = Arc(source=m.p4, destination=m.p1)
    m.a4 = Arc(source=m.p5, destination=m.p1)
    self.assertEqual(len(m.p1.dests()), 2)
    self.assertEqual(len(m.p1.sources()), 2)
    self.assertEqual(len(m.p1.arcs()), 4)
    self.assertEqual(len(m.p2.dests()), 0)
    self.assertEqual(len(m.p2.sources()), 1)
    self.assertEqual(len(m.p2.arcs()), 1)
    self.assertIn(m.a1, m.p1.dests())
    self.assertIn(m.a1, m.p2.sources())
    self.assertNotIn(m.a1, m.p1.sources())
    self.assertNotIn(m.a1, m.p2.dests())
    self.assertEqual(len(m.p1.dests(active=True)), 2)
    self.assertEqual(len(m.p1.sources(active=True)), 2)
    self.assertEqual(len(m.p1.arcs(active=True)), 4)
    self.assertEqual(len(m.p2.dests(active=True)), 0)
    self.assertEqual(len(m.p2.sources(active=True)), 1)
    self.assertEqual(len(m.p2.arcs(active=True)), 1)
    self.assertIn(m.a1, m.p1.dests(active=True))
    self.assertIn(m.a1, m.p2.sources(active=True))
    self.assertNotIn(m.a1, m.p1.sources(active=True))
    self.assertNotIn(m.a1, m.p2.dests(active=True))
    m.a2.deactivate()
    self.assertNotIn(m.a2, m.p1.dests(active=True))
    self.assertNotIn(m.a2, m.p3.sources(active=True))
    self.assertIn(m.a2, m.p1.dests(active=False))
    self.assertIn(m.a2, m.p3.sources(active=False))
    self.assertIn(m.a2, m.p1.arcs(active=False))
    self.assertIn(m.a2, m.p3.arcs(active=False))
    self.assertIn(m.a2, m.p1.dests())
    self.assertIn(m.a2, m.p3.sources())
    self.assertIn(m.a2, m.p1.arcs())
    self.assertIn(m.a2, m.p3.arcs())