import platform
import warnings
import fnmatch
import itertools
import pytest
import sys
import os
import operator
from fractions import Fraction
from functools import reduce
from collections import namedtuple
import numpy.core.umath as ncu
from numpy.core import _umath_tests as ncu_tests
import numpy as np
from numpy.testing import (
from numpy.testing._private.utils import _glibc_older_than
def test_ufunc_override_methods(self):

    class A:

        def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
            return (self, ufunc, method, inputs, kwargs)
    a = A()
    with assert_raises(TypeError):
        np.multiply.__call__(1, a, foo='bar', answer=42)
    res = np.multiply.__call__(1, a, subok='bar', where=42)
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], '__call__')
    assert_equal(res[3], (1, a))
    assert_equal(res[4], {'subok': 'bar', 'where': 42})
    assert_raises(TypeError, np.multiply, a)
    assert_raises(TypeError, np.multiply, a, a, a, a)
    assert_raises(TypeError, np.multiply, a, a, sig='a', signature='a')
    assert_raises(TypeError, ncu_tests.inner1d, a, a, axis=0, axes=[0, 0])
    res = np.multiply.reduce(a, 'axis0', 'dtype0', 'out0', 'keep0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'reduce')
    assert_equal(res[3], (a,))
    assert_equal(res[4], {'dtype': 'dtype0', 'out': ('out0',), 'keepdims': 'keep0', 'axis': 'axis0'})
    res = np.multiply.reduce(a, axis='axis0', dtype='dtype0', out='out0', keepdims='keep0', initial='init0', where='where0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'reduce')
    assert_equal(res[3], (a,))
    assert_equal(res[4], {'dtype': 'dtype0', 'out': ('out0',), 'keepdims': 'keep0', 'axis': 'axis0', 'initial': 'init0', 'where': 'where0'})
    res = np.multiply.reduce(a, 0, None, None, False)
    assert_equal(res[4], {'axis': 0, 'dtype': None, 'keepdims': False})
    res = np.multiply.reduce(a, out=None, axis=0, keepdims=True)
    assert_equal(res[4], {'axis': 0, 'keepdims': True})
    res = np.multiply.reduce(a, None, out=(None,), dtype=None)
    assert_equal(res[4], {'axis': None, 'dtype': None})
    res = np.multiply.reduce(a, 0, None, None, False, 2, True)
    assert_equal(res[4], {'axis': 0, 'dtype': None, 'keepdims': False, 'initial': 2, 'where': True})
    res = np.multiply.reduce(a, 0, None, None, False, np._NoValue, True)
    assert_equal(res[4], {'axis': 0, 'dtype': None, 'keepdims': False, 'where': True})
    res = np.multiply.reduce(a, 0, None, None, False, None, True)
    assert_equal(res[4], {'axis': 0, 'dtype': None, 'keepdims': False, 'initial': None, 'where': True})
    assert_raises(ValueError, np.multiply.reduce, a, out=())
    assert_raises(ValueError, np.multiply.reduce, a, out=('out0', 'out1'))
    assert_raises(TypeError, np.multiply.reduce, a, 'axis0', axis='axis0')
    res = np.multiply.accumulate(a, 'axis0', 'dtype0', 'out0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'accumulate')
    assert_equal(res[3], (a,))
    assert_equal(res[4], {'dtype': 'dtype0', 'out': ('out0',), 'axis': 'axis0'})
    res = np.multiply.accumulate(a, axis='axis0', dtype='dtype0', out='out0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'accumulate')
    assert_equal(res[3], (a,))
    assert_equal(res[4], {'dtype': 'dtype0', 'out': ('out0',), 'axis': 'axis0'})
    res = np.multiply.accumulate(a, 0, None, None)
    assert_equal(res[4], {'axis': 0, 'dtype': None})
    res = np.multiply.accumulate(a, out=None, axis=0, dtype='dtype1')
    assert_equal(res[4], {'axis': 0, 'dtype': 'dtype1'})
    res = np.multiply.accumulate(a, None, out=(None,), dtype=None)
    assert_equal(res[4], {'axis': None, 'dtype': None})
    assert_raises(ValueError, np.multiply.accumulate, a, out=())
    assert_raises(ValueError, np.multiply.accumulate, a, out=('out0', 'out1'))
    assert_raises(TypeError, np.multiply.accumulate, a, 'axis0', axis='axis0')
    res = np.multiply.reduceat(a, [4, 2], 'axis0', 'dtype0', 'out0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'reduceat')
    assert_equal(res[3], (a, [4, 2]))
    assert_equal(res[4], {'dtype': 'dtype0', 'out': ('out0',), 'axis': 'axis0'})
    res = np.multiply.reduceat(a, [4, 2], axis='axis0', dtype='dtype0', out='out0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'reduceat')
    assert_equal(res[3], (a, [4, 2]))
    assert_equal(res[4], {'dtype': 'dtype0', 'out': ('out0',), 'axis': 'axis0'})
    res = np.multiply.reduceat(a, [4, 2], 0, None, None)
    assert_equal(res[4], {'axis': 0, 'dtype': None})
    res = np.multiply.reduceat(a, [4, 2], axis=None, out=None, dtype='dt')
    assert_equal(res[4], {'axis': None, 'dtype': 'dt'})
    res = np.multiply.reduceat(a, [4, 2], None, None, out=(None,))
    assert_equal(res[4], {'axis': None, 'dtype': None})
    assert_raises(ValueError, np.multiply.reduce, a, [4, 2], out=())
    assert_raises(ValueError, np.multiply.reduce, a, [4, 2], out=('out0', 'out1'))
    assert_raises(TypeError, np.multiply.reduce, a, [4, 2], 'axis0', axis='axis0')
    res = np.multiply.outer(a, 42)
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'outer')
    assert_equal(res[3], (a, 42))
    assert_equal(res[4], {})
    assert_raises(TypeError, np.multiply.outer, a)
    assert_raises(TypeError, np.multiply.outer, a, a, a, a)
    assert_raises(TypeError, np.multiply.outer, a, a, sig='a', signature='a')
    res = np.multiply.at(a, [4, 2], 'b0')
    assert_equal(res[0], a)
    assert_equal(res[1], np.multiply)
    assert_equal(res[2], 'at')
    assert_equal(res[3], (a, [4, 2], 'b0'))
    assert_raises(TypeError, np.multiply.at, a)
    assert_raises(TypeError, np.multiply.at, a, a, a, a)