import re
import unittest
import jsbeautifier
import six
import copy
def test_beautifier_unconverted(self):
    test_fragment = self.decodesto
    bt = self.bt
    self.reset_options()
    bt(None, '')
    self.reset_options()
    setattr(self.options, 'end-with-newline', True)
    test_fragment(None, '\n')
    self.reset_options()
    self.options = {'end_with_newline': True, 'eol': '\r\n'}
    test_fragment(None, '\r\n')
    self.options = {'end-with-newline': True}
    test_fragment(None, '\n')
    self.options = {'end-with-newline': False}
    test_fragment(None, '')
    self.options = (('end-with-newline', True), ('eol', '\r'))
    test_fragment(None, '\r')
    self.reset_options()
    self.options.indent_size = 1
    self.options.indent_char = ' '
    bt('{ one_char() }', '{\n one_char()\n}')
    bt('var a,b=1,c=2', 'var a, b = 1,\n c = 2')
    self.options.indent_size = 4
    self.options.indent_char = ' '
    bt('{ one_char() }', '{\n    one_char()\n}')
    self.options.indent_size = 1
    self.options.indent_char = '\t'
    bt('{ one_char() }', '{\n\tone_char()\n}')
    bt('x = a ? b : c; x;', 'x = a ? b : c;\nx;')
    self.options.indent_size = 5
    self.options.indent_char = ' '
    self.options.indent_with_tabs = True
    bt('{ one_char() }', '{\n\tone_char()\n}')
    bt('x = a ? b : c; x;', 'x = a ? b : c;\nx;')
    self.reset_options()
    self.options.preserve_newlines = False
    bt('var\na=dont_preserve_newlines;', 'var a = dont_preserve_newlines;')
    bt('function foo() {\n    return 1;\n}\n\nfunction foo() {\n    return 1;\n}')
    bt('function foo() {\n    return 1;\n}\nfunction foo() {\n    return 1;\n}', 'function foo() {\n    return 1;\n}\n\nfunction foo() {\n    return 1;\n}')
    bt('function foo() {\n    return 1;\n}\n\n\nfunction foo() {\n    return 1;\n}', 'function foo() {\n    return 1;\n}\n\nfunction foo() {\n    return 1;\n}')
    self.options.preserve_newlines = True
    bt('var\na=do_preserve_newlines;', 'var\n    a = do_preserve_newlines;')
    bt('if (foo) //  comment\n{\n    bar();\n}')
    self.reset_options()
    self.options.brace_style = 'expand'
    bt('//case 1\nif (a == 1)\n{}\n//case 2\nelse if (a == 2)\n{}')
    bt('if(1){2}else{3}', 'if (1)\n{\n    2\n}\nelse\n{\n    3\n}')
    bt('try{a();}catch(b){c();}catch(d){}finally{e();}', 'try\n{\n    a();\n}\ncatch (b)\n{\n    c();\n}\ncatch (d)\n{}\nfinally\n{\n    e();\n}')
    bt('if(a){b();}else if(c) foo();', 'if (a)\n{\n    b();\n}\nelse if (c) foo();')
    bt('if (a) {\n// comment\n}else{\n// comment\n}', 'if (a)\n{\n    // comment\n}\nelse\n{\n    // comment\n}')
    bt('if (x) {y} else { if (x) {y}}', 'if (x)\n{\n    y\n}\nelse\n{\n    if (x)\n    {\n        y\n    }\n}')
    bt('if (a)\n{\nb;\n}\nelse\n{\nc;\n}', 'if (a)\n{\n    b;\n}\nelse\n{\n    c;\n}')
    test_fragment('    /*\n* xx\n*/\n// xx\nif (foo) {\n    bar();\n}', '    /*\n     * xx\n     */\n    // xx\n    if (foo)\n    {\n        bar();\n    }')
    bt('if (foo)\n{}\nelse /regex/.test();')
    test_fragment('if (foo) {', 'if (foo)\n{')
    test_fragment('foo {', 'foo\n{')
    test_fragment('return {', 'return {')
    test_fragment('return /* inline */ {', 'return /* inline */ {')
    test_fragment('return;\n{', 'return;\n{')
    bt('throw {}')
    bt('throw {\n    foo;\n}')
    bt('var foo = {}')
    bt('function x() {\n    foo();\n}zzz', 'function x()\n{\n    foo();\n}\nzzz')
    test_fragment('a: do {} while (); xxx', 'a: do {} while ();\nxxx')
    bt('{a: do {} while (); xxx}', '{\n    a: do {} while ();xxx\n}')
    bt('var a = new function() {};')
    bt('var a = new function a() {};', 'var a = new function a()\n{};')
    bt('var a = new function()\n{};', 'var a = new function() {};')
    bt('var a = new function a()\n{};')
    bt('var a = new function a()\n    {},\n    b = new function b()\n    {};')
    bt("foo({\n    'a': 1\n},\n10);", "foo(\n    {\n        'a': 1\n    },\n    10);")
    bt('(["foo","bar"]).each(function(i) {return i;});', '(["foo", "bar"]).each(function(i)\n{\n    return i;\n});')
    bt('(function(i) {return i;})();', '(function(i)\n{\n    return i;\n})();')
    bt('test( /*Argument 1*/ {\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test(\n' + '/*Argument 1*/ {\n' + "    'Value1': '1'\n" + '},\n' + '/*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test(\n' + '    /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test( /*Argument 1*/\n' + '{\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */\n' + '{\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    self.options.brace_style = 'collapse'
    bt('//case 1\nif (a == 1) {}\n//case 2\nelse if (a == 2) {}')
    bt('if(1){2}else{3}', 'if (1) {\n    2\n} else {\n    3\n}')
    bt('try{a();}catch(b){c();}catch(d){}finally{e();}', 'try {\n    a();\n} catch (b) {\n    c();\n} catch (d) {} finally {\n    e();\n}')
    bt('if(a){b();}else if(c) foo();', 'if (a) {\n    b();\n} else if (c) foo();')
    bt('if (a) {\n// comment\n}else{\n// comment\n}', 'if (a) {\n    // comment\n} else {\n    // comment\n}')
    bt('if (x) {y} else { if (x) {y}}', 'if (x) {\n    y\n} else {\n    if (x) {\n        y\n    }\n}')
    bt('if (a)\n{\nb;\n}\nelse\n{\nc;\n}', 'if (a) {\n    b;\n} else {\n    c;\n}')
    test_fragment('    /*\n* xx\n*/\n// xx\nif (foo) {\n    bar();\n}', '    /*\n     * xx\n     */\n    // xx\n    if (foo) {\n        bar();\n    }')
    bt('if (foo) {} else /regex/.test();')
    test_fragment('if (foo) {', 'if (foo) {')
    test_fragment('foo {', 'foo {')
    test_fragment('return {', 'return {')
    test_fragment('return /* inline */ {', 'return /* inline */ {')
    test_fragment('return;\n{', 'return;\n{')
    bt('throw {}')
    bt('throw {\n    foo;\n}')
    bt('var foo = {}')
    bt('function x() {\n    foo();\n}zzz', 'function x() {\n    foo();\n}\nzzz')
    test_fragment('a: do {} while (); xxx', 'a: do {} while ();\nxxx')
    bt('{a: do {} while (); xxx}', '{\n    a: do {} while ();xxx\n}')
    bt('var a = new function() {};')
    bt('var a = new function a() {};')
    bt('var a = new function()\n{};', 'var a = new function() {};')
    bt('var a = new function a()\n{};', 'var a = new function a() {};')
    bt('var a = new function a()\n    {},\n    b = new function b()\n    {};', 'var a = new function a() {},\n    b = new function b() {};')
    bt("foo({\n    'a': 1\n},\n10);", "foo({\n        'a': 1\n    },\n    10);")
    bt('(["foo","bar"]).each(function(i) {return i;});', '(["foo", "bar"]).each(function(i) {\n    return i;\n});')
    bt('(function(i) {return i;})();', '(function(i) {\n    return i;\n})();')
    bt('test( /*Argument 1*/ {\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/ {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test(\n' + '/*Argument 1*/ {\n' + "    'Value1': '1'\n" + '},\n' + '/*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test(\n' + '    /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test( /*Argument 1*/\n' + '{\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */\n' + '{\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/ {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    self.options.brace_style = 'end-expand'
    bt('//case 1\nif (a == 1) {}\n//case 2\nelse if (a == 2) {}')
    bt('if(1){2}else{3}', 'if (1) {\n    2\n}\nelse {\n    3\n}')
    bt('try{a();}catch(b){c();}catch(d){}finally{e();}', 'try {\n    a();\n}\ncatch (b) {\n    c();\n}\ncatch (d) {}\nfinally {\n    e();\n}')
    bt('if(a){b();}else if(c) foo();', 'if (a) {\n    b();\n}\nelse if (c) foo();')
    bt('if (a) {\n// comment\n}else{\n// comment\n}', 'if (a) {\n    // comment\n}\nelse {\n    // comment\n}')
    bt('if (x) {y} else { if (x) {y}}', 'if (x) {\n    y\n}\nelse {\n    if (x) {\n        y\n    }\n}')
    bt('if (a)\n{\nb;\n}\nelse\n{\nc;\n}', 'if (a) {\n    b;\n}\nelse {\n    c;\n}')
    test_fragment('    /*\n* xx\n*/\n// xx\nif (foo) {\n    bar();\n}', '    /*\n     * xx\n     */\n    // xx\n    if (foo) {\n        bar();\n    }')
    bt('if (foo) {}\nelse /regex/.test();')
    test_fragment('if (foo) {', 'if (foo) {')
    test_fragment('foo {', 'foo {')
    test_fragment('return {', 'return {')
    test_fragment('return /* inline */ {', 'return /* inline */ {')
    test_fragment('return;\n{', 'return;\n{')
    bt('throw {}')
    bt('throw {\n    foo;\n}')
    bt('var foo = {}')
    bt('function x() {\n    foo();\n}zzz', 'function x() {\n    foo();\n}\nzzz')
    test_fragment('a: do {} while (); xxx', 'a: do {} while ();\nxxx')
    bt('{a: do {} while (); xxx}', '{\n    a: do {} while ();xxx\n}')
    bt('var a = new function() {};')
    bt('var a = new function a() {};')
    bt('var a = new function()\n{};', 'var a = new function() {};')
    bt('var a = new function a()\n{};', 'var a = new function a() {};')
    bt('var a = new function a()\n    {},\n    b = new function b()\n    {};', 'var a = new function a() {},\n    b = new function b() {};')
    bt("foo({\n    'a': 1\n},\n10);", "foo({\n        'a': 1\n    },\n    10);")
    bt('(["foo","bar"]).each(function(i) {return i;});', '(["foo", "bar"]).each(function(i) {\n    return i;\n});')
    bt('(function(i) {return i;})();', '(function(i) {\n    return i;\n})();')
    bt('test( /*Argument 1*/ {\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/ {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test(\n' + '/*Argument 1*/ {\n' + "    'Value1': '1'\n" + '},\n' + '/*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test(\n' + '    /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test( /*Argument 1*/\n' + '{\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */\n' + '{\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/ {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    self.options.brace_style = 'none'
    bt('//case 1\nif (a == 1)\n{}\n//case 2\nelse if (a == 2)\n{}')
    bt('if(1){2}else{3}', 'if (1) {\n    2\n} else {\n    3\n}')
    bt('try{a();}catch(b){c();}catch(d){}finally{e();}', 'try {\n    a();\n} catch (b) {\n    c();\n} catch (d) {} finally {\n    e();\n}')
    bt('if(a){b();}else if(c) foo();', 'if (a) {\n    b();\n} else if (c) foo();')
    bt('if (a) {\n// comment\n}else{\n// comment\n}', 'if (a) {\n    // comment\n} else {\n    // comment\n}')
    bt('if (x) {y} else { if (x) {y}}', 'if (x) {\n    y\n} else {\n    if (x) {\n        y\n    }\n}')
    bt('if (a)\n{\nb;\n}\nelse\n{\nc;\n}', 'if (a)\n{\n    b;\n}\nelse\n{\n    c;\n}')
    test_fragment('    /*\n* xx\n*/\n// xx\nif (foo) {\n    bar();\n}', '    /*\n     * xx\n     */\n    // xx\n    if (foo) {\n        bar();\n    }')
    bt('if (foo)\n{}\nelse /regex/.test();')
    test_fragment('if (foo) {')
    test_fragment('foo {')
    test_fragment('return {')
    test_fragment('return /* inline */ {')
    test_fragment('return;\n{')
    bt('throw {}')
    bt('throw {\n    foo;\n}')
    bt('var foo = {}')
    bt('function x() {\n    foo();\n}zzz', 'function x() {\n    foo();\n}\nzzz')
    test_fragment('a: do {} while (); xxx', 'a: do {} while ();\nxxx')
    bt('{a: do {} while (); xxx}', '{\n    a: do {} while ();xxx\n}')
    bt('var a = new function() {};')
    bt('var a = new function a() {};')
    bt('var a = new function()\n{};', 'var a = new function() {};')
    bt('var a = new function a()\n{};')
    bt('var a = new function a()\n    {},\n    b = new function b()\n    {};')
    bt("foo({\n    'a': 1\n},\n10);", "foo({\n        'a': 1\n    },\n    10);")
    bt('(["foo","bar"]).each(function(i) {return i;});', '(["foo", "bar"]).each(function(i) {\n    return i;\n});')
    bt('(function(i) {return i;})();', '(function(i) {\n    return i;\n})();')
    bt('test( /*Argument 1*/ {\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/ {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test(\n' + '/*Argument 1*/ {\n' + "    'Value1': '1'\n" + '},\n' + '/*Argument 2\n' + ' */ {\n' + "    'Value2': '2'\n" + '});', 'test(\n' + '    /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    bt('test( /*Argument 1*/\n' + '{\n' + "    'Value1': '1'\n" + '}, /*Argument 2\n' + ' */\n' + '{\n' + "    'Value2': '2'\n" + '});', 'test( /*Argument 1*/\n' + '    {\n' + "        'Value1': '1'\n" + '    },\n' + '    /*Argument 2\n' + '     */\n' + '    {\n' + "        'Value2': '2'\n" + '    });')
    self.reset_options()
    self.options.preserve_newlines = True
    bt("var a = 'foo' +\n    'bar';")
    bt('"foo""bar""baz"', '"foo"\n"bar"\n"baz"')
    bt("'foo''bar''baz'", "'foo'\n'bar'\n'baz'")
    bt('{\n    get foo() {}\n}')
    bt('{\n    var a = get\n    foo();\n}')
    bt('{\n    set foo() {}\n}')
    bt('{\n    var a = set\n    foo();\n}')
    bt('var x = {\n    get function()\n}')
    bt('var x = {\n    set function()\n}')
    bt('var x = set\n\na() {}', 'var x = set\n\na() {}')
    bt('var x = set\n\nfunction() {}', 'var x = set\n\nfunction() {}')
    bt('for () /abc/.test()')
    bt('if (k) /aaa/m.test(v) && l();')
    bt('switch (true) {\n    case /swf/i.test(foo):\n        bar();\n}')
    bt('createdAt = {\n    type: Date,\n    default: Date.now\n}')
    bt('switch (createdAt) {\n    case a:\n        Date,\n    default:\n        Date.now\n}')
    self.reset_options()