import copy
from osc_lib.tests import utils as oscutils
from ironicclient.osc.v1 import baremetal_driver
from ironicclient.tests.unit.osc.v1 import fakes as baremetal_fakes
def test_baremetal_driver_show(self):
    arglist = ['fakedrivername']
    verifylist = []
    parsed_args = self.check_parser(self.cmd, arglist, verifylist)
    columns, data = self.cmd.take_action(parsed_args)
    args = ['fakedrivername']
    self.baremetal_mock.driver.get.assert_called_with(*args, fields=None)
    self.assertFalse(self.baremetal_mock.driver.properties.called)
    collist = ('default_bios_interface', 'default_boot_interface', 'default_console_interface', 'default_deploy_interface', 'default_firmware_interface', 'default_inspect_interface', 'default_management_interface', 'default_network_interface', 'default_power_interface', 'default_raid_interface', 'default_rescue_interface', 'default_storage_interface', 'default_vendor_interface', 'enabled_bios_interfaces', 'enabled_boot_interfaces', 'enabled_console_interfaces', 'enabled_deploy_interfaces', 'enabled_firmware_interfaces', 'enabled_inspect_interfaces', 'enabled_management_interfaces', 'enabled_network_interfaces', 'enabled_power_interfaces', 'enabled_raid_interfaces', 'enabled_rescue_interfaces', 'enabled_storage_interfaces', 'enabled_vendor_interfaces', 'hosts', 'name', 'type')
    self.assertEqual(collist, columns)
    datalist = (baremetal_fakes.baremetal_driver_default_bios_if, baremetal_fakes.baremetal_driver_default_boot_if, baremetal_fakes.baremetal_driver_default_console_if, baremetal_fakes.baremetal_driver_default_deploy_if, baremetal_fakes.baremetal_driver_default_firmware_if, baremetal_fakes.baremetal_driver_default_inspect_if, baremetal_fakes.baremetal_driver_default_management_if, baremetal_fakes.baremetal_driver_default_network_if, baremetal_fakes.baremetal_driver_default_power_if, baremetal_fakes.baremetal_driver_default_raid_if, baremetal_fakes.baremetal_driver_default_rescue_if, baremetal_fakes.baremetal_driver_default_storage_if, baremetal_fakes.baremetal_driver_default_vendor_if, ', '.join(baremetal_fakes.baremetal_driver_enabled_bios_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_boot_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_console_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_deploy_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_firmware_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_inspect_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_management_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_network_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_power_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_raid_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_rescue_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_storage_ifs), ', '.join(baremetal_fakes.baremetal_driver_enabled_vendor_ifs), ', '.join(baremetal_fakes.baremetal_driver_hosts), baremetal_fakes.baremetal_driver_name, baremetal_fakes.baremetal_driver_type)
    self.assertEqual(datalist, tuple(data))