import abc
import operator
import textwrap
import six
from apitools.base.protorpclite import descriptor as protorpc_descriptor
from apitools.base.protorpclite import message_types
from apitools.base.protorpclite import messages
from apitools.base.py import extra_types
def PrintPreamble(self, package, version, file_descriptor):
    self.__printer('"""Generated message classes for %s version %s.', package, version)
    self.__printer()
    for line in textwrap.wrap(file_descriptor.description, 78):
        self.__printer(line)
    self.__printer('"""')
    self.__printer('# NOTE: This file is autogenerated and should not be edited by hand.')
    self.__printer()
    self.__printer('from __future__ import absolute_import')
    self.__printer()
    self.__PrintAdditionalImports(file_descriptor.additional_imports)
    self.__printer()
    self.__printer("package = '%s'", file_descriptor.package)
    self.__printer()
    self.__printer()