import numpy as np
import onnx
from onnx.backend.test.case.base import Base
from onnx.backend.test.case.node import expect
@staticmethod
def export_types() -> None:
    node = onnx.helper.make_node('Pow', inputs=['x', 'y'], outputs=['z'])
    x = np.array([1, 2, 3]).astype(np.float32)
    y = np.array([4, 5, 6]).astype(np.int64)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_float32_int64')
    x = np.array([1, 2, 3]).astype(np.int64)
    y = np.array([4, 5, 6]).astype(np.float32)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_int64_float32')
    x = np.array([1, 2, 3]).astype(np.float32)
    y = np.array([4, 5, 6]).astype(np.int32)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_float32_int32')
    x = np.array([1, 2, 3]).astype(np.int32)
    y = np.array([4, 5, 6]).astype(np.float32)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_int32_float32')
    x = np.array([1, 2, 3]).astype(np.float32)
    y = np.array([4, 5, 6]).astype(np.uint64)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_float32_uint64')
    x = np.array([1, 2, 3]).astype(np.float32)
    y = np.array([4, 5, 6]).astype(np.uint32)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_float32_uint32')
    x = np.array([1, 2, 3]).astype(np.int64)
    y = np.array([4, 5, 6]).astype(np.int64)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_int64_int64')
    x = np.array([1, 2, 3]).astype(np.int32)
    y = np.array([4, 5, 6]).astype(np.int32)
    z = pow(x, y)
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_types_int32_int32')