from functools import reduce
from pyparsing import Word, OneOrMore, Optional, Literal, NotAny, MatchFirst
from pyparsing import Group, oneOf, Suppress, ZeroOrMore, Combine, FollowedBy
from pyparsing import srange, CharsNotIn, StringEnd, LineEnd, White, Regex
from pyparsing import nums, alphas, alphanums, ParseException, Forward
import types, sys, os, re, datetime
def abc_grammar():
    b1 = Word(u"-,'<>’#", exact=1)
    b2 = Regex('[^H-Wh-w~=]*')
    b3 = Regex('[^=]*')
    number = Word(nums).setParseAction(lambda t: int(t[0]))
    field_str = Regex('[^]]*')
    field_str.setParseAction(lambda t: t[0].strip())
    userdef_symbol = Word(srange('[H-Wh-w~]'), exact=1)
    fieldId = oneOf('K L M Q P I T C O A Z N G H R B D F S E r Y')
    X_field = Literal('X') + Suppress(':') + field_str
    U_field = Literal('U') + Suppress(':') + b2 + Optional(userdef_symbol, 'H') + b3 + Suppress('=') + field_str
    V_field = Literal('V') + Suppress(':') + Word(alphanums + '_') + field_str
    inf_fld = fieldId + Suppress(':') + field_str
    ifield = Suppress('[') + (X_field | U_field | V_field | inf_fld) + Suppress(']')
    abc_header = OneOrMore(ifield) + StringEnd()
    voiceId = Suppress(Optional('*')) + Word(alphanums + '_')
    voice_gr = Suppress('(') + OneOrMore(voiceId | Suppress('|')) + Suppress(')')
    simple_part = voiceId | voice_gr | Suppress('|')
    grand_staff = oneOf('{* {') + OneOrMore(simple_part) + Suppress('}')
    part = Forward()
    part_seq = OneOrMore(part | Suppress('|'))
    brace_gr = Suppress('{') + part_seq + Suppress('}')
    bracket_gr = Suppress('[') + part_seq + Suppress(']')
    part <<= MatchFirst(simple_part | grand_staff | brace_gr | bracket_gr | Suppress('|'))
    abc_scoredef = Suppress(oneOf('staves score')) + OneOrMore(part)
    skip_note = oneOf('* - ~')
    extend_note = Literal('_')
    measure_end = Literal('|')
    syl_str = CharsNotIn('*~-_| \t\n\\]')
    syl_chars = Combine(OneOrMore(syl_str | Regex('\\\\.')))
    white = Word(' \t')
    syllable = Combine(Optional('~') + syl_chars + ZeroOrMore(Literal('~') + syl_chars)) + Optional('-')
    lyr_elem = (syllable | skip_note | extend_note | measure_end) + Optional(white).suppress()
    lyr_line = Optional(white).suppress() + ZeroOrMore(lyr_elem)
    syllable.setParseAction(lambda t: pObj('syl', t))
    skip_note.setParseAction(lambda t: pObj('skip', t))
    extend_note.setParseAction(lambda t: pObj('ext', t))
    measure_end.setParseAction(lambda t: pObj('sbar', t))
    lyr_line_wsp = lyr_line.leaveWhitespace()
    inline_field = Suppress('[') + (inf_fld | U_field | V_field) + Suppress(']')
    lyr_fld = Suppress('[') + Suppress('w') + Suppress(':') + lyr_line_wsp + Suppress(']')
    lyr_blk = OneOrMore(lyr_fld)
    fld_or_lyr = inline_field | lyr_blk
    note_length = Optional(number, 1) + Group(ZeroOrMore('/')) + Optional(number, 2)
    octaveHigh = OneOrMore("'").setParseAction(lambda t: len(t))
    octaveLow = OneOrMore(',').setParseAction(lambda t: -len(t))
    octave = octaveHigh | octaveLow
    basenote = oneOf('C D E F G A B c d e f g a b y')
    accidental = oneOf('^^ __ ^ _ =')
    rest_sym = oneOf('x X z Z')
    slur_beg = oneOf("( (, (' .( .(, .('") + ~Word(nums)
    slur_ends = OneOrMore(oneOf(') .)'))
    long_decoration = Combine(oneOf('! +') + CharsNotIn('!+ \n') + oneOf('! +'))
    staccato = Literal('.') + ~Literal('|')
    pizzicato = Literal('!+!')
    decoration = slur_beg | staccato | userdef_symbol | long_decoration | pizzicato
    decorations = OneOrMore(decoration)
    tie = oneOf('.- -')
    rest = Optional(accidental) + rest_sym + note_length
    pitch = Optional(accidental) + basenote + Optional(octave, 0)
    note = pitch + note_length + Optional(tie) + Optional(slur_ends)
    dec_note = Optional(decorations) + pitch + note_length + Optional(tie) + Optional(slur_ends)
    chord_note = dec_note | rest | b1
    grace_notes = Forward()
    chord = Suppress('[') + OneOrMore(chord_note | grace_notes) + Suppress(']') + note_length + Optional(tie) + Optional(slur_ends)
    stem = note | chord | rest
    broken = Combine(OneOrMore('<') | OneOrMore('>'))
    tuplet_num = Suppress('(') + number
    tuplet_into = Suppress(':') + Optional(number, 0)
    tuplet_notes = Suppress(':') + Optional(number, 0)
    tuplet_start = tuplet_num + Optional(tuplet_into + Optional(tuplet_notes))
    acciaccatura = Literal('/')
    grace_stem = Optional(decorations) + stem
    grace_notes <<= Group(Suppress('{') + Optional(acciaccatura) + OneOrMore(grace_stem) + Suppress('}'))
    text_expression = Optional(oneOf('^ _ < > @'), '^') + Optional(CharsNotIn('"'), '')
    chord_accidental = oneOf('# b =')
    triad = oneOf('ma Maj maj M mi min m aug dim o + -')
    seventh = oneOf('7 ma7 Maj7 M7 maj7 mi7 min7 m7 dim7 o7 -7 aug7 +7 m7b5 mi7b5')
    sixth = oneOf('6 ma6 M6 mi6 min6 m6')
    ninth = oneOf('9 ma9 M9 maj9 Maj9 mi9 min9 m9')
    elevn = oneOf('11 ma11 M11 maj11 Maj11 mi11 min11 m11')
    thirt = oneOf('13 ma13 M13 maj13 Maj13 mi13 min13 m13')
    suspended = oneOf('sus sus2 sus4')
    chord_degree = Combine(Optional(chord_accidental) + oneOf('2 4 5 6 7 9 11 13'))
    chord_kind = Optional(seventh | sixth | ninth | elevn | thirt | triad) + Optional(suspended)
    chord_root = oneOf('C D E F G A B') + Optional(chord_accidental)
    chord_bass = oneOf('C D E F G A B') + Optional(chord_accidental)
    chordsym = chord_root + chord_kind + ZeroOrMore(chord_degree) + Optional(Suppress('/') + chord_bass)
    chord_sym = chordsym + Optional(Literal('(') + CharsNotIn(')') + Literal(')')).suppress()
    chord_or_text = Suppress('"') + (chord_sym ^ text_expression) + Suppress('"')
    volta_nums = Optional('[').suppress() + Combine(Word(nums) + ZeroOrMore(oneOf(', -') + Word(nums)))
    volta_text = Literal('[').suppress() + Regex('"[^"]+"')
    volta = volta_nums | volta_text
    invisible_barline = oneOf('[|] []')
    dashed_barline = oneOf(': .|')
    double_rep = Literal(':') + FollowedBy(':')
    voice_overlay = Combine(OneOrMore('&'))
    bare_volta = FollowedBy(Literal('[') + Word(nums))
    bar_left = oneOf('[|: |: [: :') + Optional(volta) | Optional('|').suppress() + volta | oneOf('| [|')
    bars = ZeroOrMore(':') + ZeroOrMore('[') + OneOrMore(oneOf('| ]'))
    bar_right = invisible_barline | double_rep | Combine(bars) | dashed_barline | voice_overlay | bare_volta
    errors = ~bar_right + Optional(Word(' \n')) + CharsNotIn(':&|', exact=1)
    linebreak = Literal('$') | ~decorations + Literal('!')
    element = fld_or_lyr | broken | decorations | stem | chord_or_text | grace_notes | tuplet_start | linebreak | errors
    measure = Group(ZeroOrMore(inline_field) + Optional(bar_left) + ZeroOrMore(element) + bar_right + Optional(linebreak) + Optional(lyr_blk))
    noBarMeasure = Group(ZeroOrMore(inline_field) + Optional(bar_left) + OneOrMore(element) + Optional(linebreak) + Optional(lyr_blk))
    abc_voice = ZeroOrMore(measure) + Optional(noBarMeasure | Group(bar_left)) + ZeroOrMore(inline_field).suppress() + StringEnd()
    white2 = (white | StringEnd()).suppress()
    w3 = Optional(white2)
    percid = Word(alphanums + '-')
    step = basenote + Optional(octave, 0)
    pitchg = Group(Optional(accidental, '') + step + FollowedBy(white2))
    stepg = Group(step + FollowedBy(white2)) | Literal('*')
    midi = Literal('*') | number | pitchg | percid
    nhd = Optional(Combine(percid + Optional('+')), '')
    perc_wsp = Literal('percmap') + w3 + pitchg + w3 + Optional(stepg, '*') + w3 + Optional(midi, '*') + w3 + nhd
    abc_percmap = perc_wsp.leaveWhitespace()
    ifield.setParseAction(lambda t: pObj('field', t))
    grand_staff.setParseAction(lambda t: pObj('grand', t, 1))
    brace_gr.setParseAction(lambda t: pObj('bracegr', t, 1))
    bracket_gr.setParseAction(lambda t: pObj('bracketgr', t, 1))
    voice_gr.setParseAction(lambda t: pObj('voicegr', t, 1))
    voiceId.setParseAction(lambda t: pObj('vid', t, 1))
    abc_scoredef.setParseAction(lambda t: pObj('score', t, 1))
    note_length.setParseAction(lambda t: pObj('dur', (t[0], t[2] << len(t[1]) >> 1)))
    chordsym.setParseAction(lambda t: pObj('chordsym', t))
    chord_root.setParseAction(lambda t: pObj('root', t))
    chord_kind.setParseAction(lambda t: pObj('kind', t))
    chord_degree.setParseAction(lambda t: pObj('degree', t))
    chord_bass.setParseAction(lambda t: pObj('bass', t))
    text_expression.setParseAction(lambda t: pObj('text', t))
    inline_field.setParseAction(lambda t: pObj('inline', t))
    lyr_fld.setParseAction(lambda t: pObj('lyr_fld', t, 1))
    lyr_blk.setParseAction(lambda t: pObj('lyr_blk', t, 1))
    grace_notes.setParseAction(doGrace)
    acciaccatura.setParseAction(lambda t: pObj('accia', t))
    note.setParseAction(noteActn)
    rest.setParseAction(restActn)
    decorations.setParseAction(lambda t: pObj('deco', t))
    pizzicato.setParseAction(lambda t: ['!plus!'])
    slur_ends.setParseAction(lambda t: pObj('slurs', t))
    chord.setParseAction(lambda t: pObj('chord', t, 1))
    dec_note.setParseAction(noteActn)
    tie.setParseAction(lambda t: pObj('tie', t))
    pitch.setParseAction(lambda t: pObj('pitch', t))
    bare_volta.setParseAction(lambda t: ['|'])
    dashed_barline.setParseAction(lambda t: ['.|'])
    bar_right.setParseAction(lambda t: pObj('rbar', t))
    bar_left.setParseAction(lambda t: pObj('lbar', t))
    broken.setParseAction(lambda t: pObj('broken', t))
    tuplet_start.setParseAction(lambda t: pObj('tup', t))
    linebreak.setParseAction(lambda t: pObj('linebrk', t))
    measure.setParseAction(doMaat)
    noBarMeasure.setParseAction(doMaat)
    b1.setParseAction(errorWarn)
    b2.setParseAction(errorWarn)
    b3.setParseAction(errorWarn)
    errors.setParseAction(errorWarn)
    return (abc_header, abc_voice, abc_scoredef, abc_percmap)