from kivy.tests.common import GraphicUnitTest
def test_multitouch_appear(self):
    eventloop, win, mouse, wid = self.mouse_init()
    mouse.start()
    eventloop.add_input_provider(mouse)
    self.assertEqual(mouse.counter, 0)
    self.assertEqual(mouse.touches, {})
    win.dispatch('on_mouse_down', 10, self.correct_y(win, 10), 'right', {})
    event_id = next(iter(mouse.touches))
    self.assertEqual(mouse.counter, 1)
    self.assertIsNotNone(mouse.touches[event_id].ud.get('_drawelement'))
    ellipse = mouse.touches[event_id].ud.get('_drawelement')[1].proxy_ref
    self.assertAlmostEqual(ellipse.pos[0], 0, delta=0.0001)
    self.assertAlmostEqual(ellipse.pos[1], 0, delta=0.0001)
    win.dispatch('on_mouse_move', 11, self.correct_y(win, 11), {})
    self.assertEqual(ellipse.pos, (1, 1))
    win.dispatch('on_mouse_up', 10, self.correct_y(win, 10), 'right', {})
    self.assertEqual(ellipse.pos, (1, 1))
    self.assertEqual(mouse.counter, 1)
    self.assertIn(event_id, mouse.touches)
    self.assertIsNotNone(mouse.touches[event_id].ud.get('_drawelement'))
    self.render(wid)
    mouse.stop()
    eventloop.remove_input_provider(mouse)