import os
import unittest
from pygame.tests import test_utils
from pygame.tests.test_utils import (
import pygame
from pygame.locals import *
from pygame.bufferproxy import BufferProxy
import platform
import gc
import weakref
import ctypes
def test_get_view(self):
    """Ensure a buffer view of the surface's pixels can be retrieved."""
    Error = ValueError
    s = pygame.Surface((5, 7), 0, 8)
    v2 = s.get_view('2')
    self.assertRaises(Error, s.get_view, '0')
    self.assertRaises(Error, s.get_view, '1')
    self.assertIsInstance(v2, BufferProxy)
    self.assertRaises(Error, s.get_view, '3')
    s = pygame.Surface((8, 7), 0, 8)
    length = s.get_bytesize() * s.get_width() * s.get_height()
    v0 = s.get_view('0')
    v1 = s.get_view('1')
    self.assertIsInstance(v0, BufferProxy)
    self.assertEqual(v0.length, length)
    self.assertIsInstance(v1, BufferProxy)
    self.assertEqual(v1.length, length)
    s = pygame.Surface((5, 7), 0, 16)
    v2 = s.get_view('2')
    self.assertRaises(Error, s.get_view, '0')
    self.assertRaises(Error, s.get_view, '1')
    self.assertIsInstance(v2, BufferProxy)
    self.assertRaises(Error, s.get_view, '3')
    s = pygame.Surface((8, 7), 0, 16)
    length = s.get_bytesize() * s.get_width() * s.get_height()
    v0 = s.get_view('0')
    v1 = s.get_view('1')
    self.assertIsInstance(v0, BufferProxy)
    self.assertEqual(v0.length, length)
    self.assertIsInstance(v1, BufferProxy)
    self.assertEqual(v1.length, length)
    s = pygame.Surface((5, 7), pygame.SRCALPHA, 16)
    v2 = s.get_view('2')
    self.assertIsInstance(v2, BufferProxy)
    self.assertRaises(Error, s.get_view, '3')
    s = pygame.Surface((5, 7), 0, 24)
    v2 = s.get_view('2')
    v3 = s.get_view('3')
    self.assertRaises(Error, s.get_view, '0')
    self.assertRaises(Error, s.get_view, '1')
    self.assertIsInstance(v2, BufferProxy)
    self.assertIsInstance(v3, BufferProxy)
    s = pygame.Surface((8, 7), 0, 24)
    length = s.get_bytesize() * s.get_width() * s.get_height()
    v0 = s.get_view('0')
    v1 = s.get_view('1')
    self.assertIsInstance(v0, BufferProxy)
    self.assertEqual(v0.length, length)
    self.assertIsInstance(v1, BufferProxy)
    self.assertEqual(v1.length, length)
    s = pygame.Surface((5, 7), 0, 32)
    length = s.get_bytesize() * s.get_width() * s.get_height()
    v0 = s.get_view('0')
    v1 = s.get_view('1')
    v2 = s.get_view('2')
    v3 = s.get_view('3')
    self.assertIsInstance(v0, BufferProxy)
    self.assertEqual(v0.length, length)
    self.assertIsInstance(v1, BufferProxy)
    self.assertEqual(v1.length, length)
    self.assertIsInstance(v2, BufferProxy)
    self.assertIsInstance(v3, BufferProxy)
    s2 = s.subsurface((0, 0, 4, 7))
    self.assertRaises(Error, s2.get_view, '0')
    self.assertRaises(Error, s2.get_view, '1')
    s2 = None
    s = pygame.Surface((5, 7), pygame.SRCALPHA, 32)
    for kind in ('2', '3', 'a', 'A', 'r', 'R', 'g', 'G', 'b', 'B'):
        self.assertIsInstance(s.get_view(kind), BufferProxy)
    s = pygame.Surface((2, 4), 0, 32)
    v = s.get_view()
    if not IS_PYPY:
        ai = ArrayInterface(v)
        self.assertEqual(ai.nd, 2)
    s = pygame.Surface((2, 4), 0, 32)
    self.assertFalse(s.get_locked())
    v = s.get_view('2')
    self.assertFalse(s.get_locked())
    c = v.__array_interface__
    self.assertTrue(s.get_locked())
    c = None
    gc.collect()
    self.assertTrue(s.get_locked())
    v = None
    gc.collect()
    self.assertFalse(s.get_locked())
    s = pygame.Surface((2, 4), pygame.SRCALPHA, 32)
    self.assertRaises(TypeError, s.get_view, '')
    self.assertRaises(TypeError, s.get_view, '9')
    self.assertRaises(TypeError, s.get_view, 'RGBA')
    self.assertRaises(TypeError, s.get_view, 2)
    s = pygame.Surface((2, 4), 0, 32)
    s.get_view('2')
    s.get_view(b'2')
    s = pygame.Surface((2, 4), 0, 32)
    weak_s = weakref.ref(s)
    v = s.get_view('3')
    weak_v = weakref.ref(v)
    gc.collect()
    self.assertTrue(weak_s() is s)
    self.assertTrue(weak_v() is v)
    del v
    gc.collect()
    self.assertTrue(weak_s() is s)
    self.assertTrue(weak_v() is None)
    del s
    gc.collect()
    self.assertTrue(weak_s() is None)