from openstack.object_store.v1 import container as _container
from openstack.tests.functional import base
def test_system_metadata(self):
    container = self.conn.object_store.get_container_metadata(self.NAME)
    self.assertEqual(0, container.object_count)
    self.assertEqual(0, container.bytes_used)
    container = self.conn.object_store.get_container_metadata(self.NAME)
    self.assertIsNone(container.read_ACL)
    self.assertIsNone(container.write_ACL)
    self.conn.object_store.set_container_metadata(container, read_ACL='.r:*', write_ACL='demo:demo')
    container = self.conn.object_store.get_container_metadata(self.NAME)
    self.assertEqual('.r:*', container.read_ACL)
    self.assertEqual('demo:demo', container.write_ACL)
    self.conn.object_store.set_container_metadata(container, read_ACL='.r:demo')
    container = self.conn.object_store.get_container_metadata(self.NAME)
    self.assertEqual('.r:demo', container.read_ACL)
    self.assertEqual('demo:demo', container.write_ACL)
    self.conn.object_store.set_container_metadata(container, k0='v0', sync_key='1234')
    container = self.conn.object_store.get_container_metadata(self.NAME)
    self.assertTrue(container.metadata)
    self.assertIn('k0', container.metadata)
    self.assertEqual('v0', container.metadata['k0'])
    self.assertEqual('.r:demo', container.read_ACL)
    self.assertEqual('demo:demo', container.write_ACL)
    self.assertEqual('1234', container.sync_key)
    self.conn.object_store.delete_container_metadata(container, ['sync_key'])
    container = self.conn.object_store.get_container_metadata(self.NAME)
    self.assertTrue(container.metadata)
    self.assertIn('k0', container.metadata)
    self.assertEqual('v0', container.metadata['k0'])
    self.assertEqual('.r:demo', container.read_ACL)
    self.assertEqual('demo:demo', container.write_ACL)
    self.assertIsNone(container.sync_key)