import pyomo.common.unittest as unittest
from io import StringIO
import logging
from pyomo.environ import (
from pyomo.network import Arc, Port
from pyomo.core.expr.visitor import identify_variables
from pyomo.common.collections.component_set import ComponentSet
def test_with_scalar_ports(self):

    def rule(m):
        return dict(source=m.prt1, destination=m.prt2)
    m = ConcreteModel()
    m.prt1 = Port()
    m.prt2 = Port()
    m.c1 = Arc(rule=rule)
    self.assertEqual(len(m.c1), 1)
    self.assertTrue(m.c1.directed)
    self.assertIs(m.c1.source, m.prt1)
    self.assertIs(m.c1.destination, m.prt2)
    self.assertIs(m.c1.ports[0], m.prt1)
    self.assertIs(m.c1.ports[1], m.prt2)
    m.c2 = Arc(ports=(m.prt1, m.prt2))
    self.assertEqual(len(m.c2), 1)
    self.assertFalse(m.c2.directed)
    self.assertIsInstance(m.c2.ports, tuple)
    self.assertEqual(len(m.c2.ports), 2)
    self.assertIs(m.c2.ports[0], m.prt1)
    self.assertIs(m.c2.ports[1], m.prt2)
    self.assertIsNone(m.c2.source)
    self.assertIsNone(m.c2.destination)
    m = AbstractModel()
    m.prt1 = Port()
    m.prt2 = Port()
    m.c1 = Arc(source=m.prt1, destination=m.prt2)
    self.assertEqual(len(m.c1), 0)
    self.assertIsNone(m.c1.directed)
    self.assertIsNone(m.c1.ports)
    self.assertIsNone(m.c1.source)
    self.assertIsNone(m.c1.destination)
    m.c2 = Arc(ports=(m.prt1, m.prt2))
    self.assertEqual(len(m.c2), 0)
    self.assertIsNone(m.c2.directed)
    self.assertIsNone(m.c2.ports)
    self.assertIsNone(m.c2.source)
    self.assertIsNone(m.c2.destination)
    inst = m.create_instance()
    self.assertEqual(len(inst.c1), 1)
    self.assertTrue(inst.c1.directed)
    self.assertIs(inst.c1.source, inst.prt1)
    self.assertIs(inst.c1.destination, inst.prt2)
    self.assertIs(inst.c1.ports[0], inst.prt1)
    self.assertIs(inst.c1.ports[1], inst.prt2)
    self.assertEqual(len(inst.c2), 1)
    self.assertFalse(inst.c2.directed)
    self.assertIsInstance(inst.c2.ports, tuple)
    self.assertEqual(len(inst.c2.ports), 2)
    self.assertIs(inst.c2.ports[0], inst.prt1)
    self.assertIs(inst.c2.ports[1], inst.prt2)
    self.assertIsNone(inst.c2.source)
    self.assertIsNone(inst.c2.destination)